### ISSUE TITLE
Not possible to draw a perfect cone using cylinderElliptic

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#1005]
## Expected Behavior

Since cylinder doesn't take two sets of arguments to render a cone, cylinderElliptic becomes an option to render a cone.

## Actual Behavior

cylinderElliptic() doesn't accept [0, 0] as a valid value for radius. This seems acceptable in OpenSCAD.

```
const jscad = require('@jscad/modeling');
const CssColor = jscad.colors.cssColors;
const Colors = jscad.colors;
const Primitive = jscad.primitives;

function main() {
  return Colors.colorize(CssColor.red, Primitive.cylinderElliptic({
    center: [0, 0, 0],
    height: 3,
    startRadius: [1, 1],
    endRadius: [0, 0]
  }));
}

module.exports = { main }
```

## Steps to Reproduce the Problem

  1. use the code snippet provided in codemirror in the UI
  2. SHIFT+ENTER
  3. Uncaught Error: bad output from script: expected geom3/geom2/path2 objects

## Specifications

  - Version: production
  - Platform: all
  - Environment: browser

**Comment by z3dev** [comment]
True, but the radius can of on cap can be any floating above zero, like 0.0001

**Comment by samuelwang48** [comment]
@z3dev thanks yes that's what I am using for now. Not sure this is an issue or not. If not please close the issue.

**Comment by platypii** [comment]
Is there a reason that constraint is in place? When I change [cylinderElliptic.js:43](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/modeling/src/primitives/cylinderElliptic.js#L43) to allow zero, things appear to still work.

```diff
-  if (!endRadius.every((n) => n > 0)) throw new Error('endRadius values must be greater than zero')
+  if (!endRadius.every((n) => n >= 0)) throw new Error('endRadius values must be greater than zero')
```

![Screenshot at 2022-02-19 18-25-50](https://user-images.githubusercontent.com/1766297/154825974-b0cf897b-4889-4d31-bf4e-763d80bbbc73.png)

**Comment by paulftw** [comment]
> Is there a reason that constraint is in place?
Doesn't make sense to me either. If it passes the tests why don't we change to `>=`? both end and start radius would need this change.

**Comment by platypii** [comment]
Although the code does seem to work if one of the ends is `[0, 0]` there are still some issues. It is not as simple as relaxing the strict equality to greater-than-or-equals. For example, `cylinderElliptic({ endRadius: [0, 1] })` gives the following invalid geometry:

![cone](https://user-images.githubusercontent.com/1766297/160021674-fe42768e-d719-40dc-9496-86d406d25158.png)

I'm still investigating to see if either that case could be fixed, or if there should be a more precise set of input checks to allow a perfect cone, but not a "squished cylinder"

**Comment by hrgdavor** [comment]
It is interesting to explore, but looks like to support it, alg needs to be changed in some way. Likely special handling for the case.

**Comment by z3dev** [comment]
> Although the code does seem to work if one of the ends is `[0, 0]` there are still some issues. It is not as simple as relaxing the strict equality to greater-than-or-equals. For example, `cylinderElliptic({ endRadius: [0, 1] })` gives the following invalid geometry:

Yeah. Since the calculations are based on ellipse, a perfect cone is probably not possible.

An alternative is creating another primitive for cones.
