### ISSUE TITLE
the orientation option of polyhedron is incorrectly typed in the documentation

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#1011]
## Expected Behavior

In primitives/polyhedron API, the `orientation` option is incorrectly typed in the documentation. It should be String.

## Actual Behavior

It is now documented as Array.

## Steps to Reproduce the Problem

  1. goto https://www.openjscad.xyz/docs/module-modeling_primitives.html#.polyhedron

## Specifications

  - Version: Production
  - Platform: all
  - Environment: all

**Comment by platypii** [comment]
Fixed now in master. Thanks @samuelwang48 !
