### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by udif** [jscad/OpenJSCAD.org#1023]
## Expected Behavior
Following the instructions in `CONTRIBUTING.md` should lead to a successfull installation

## Actual Behavior
`npm test` fails with missing packages

## Steps to Reproduce the Problem

  1. `git clone https://github.com/jscad/OpenJSCAD.org.git`
  2. `cd OpenJSCAD.org`
  3. `npm install`
  4. `npm test`

Each time this is run, `npm test` fails due to missing packages. I had to gradually install all the following:
```
npm install @jscad/array-utils
npm install @jscad/modeling
npm install @jscad/io
npm install @jscad/core
```
Each time I installed one package, got a new missing package error, and installed the next one.

I am not a front-end web developer. I know some JS, but lack any knowledge about modern web development flow, so I have to follow the guidelines from `CONTRIBUTING.md` to the letter.

## Specifications

  - Version: [Release : 2022 MAR 03](https://github.com/jscad/OpenJSCAD.org/commit/317c2ada65f7fb5d4e0b579feb1e45c5f1c79b51)
  - Platform: Windows 10
  - Environment: Chrome (Version 98.0.4758.102 (Official Build) (64-bit)), Latest NodsJS LTS (16.14.0), npm 8.3.1

**Comment by udif** [comment]
Following on:
```
C:\Sync\Sync\git\OpenJSCAD.org\packages\web>npm run dev

> @jscad/web@2.5.5 dev
> budo demo.js --port=8081 --css ./css/demo.css --live -- -b

[0001] info  Server running at http://10.10.20.177:8081/ (connect)
[0001] info  LiveReload running
Error: Can't walk dependency graph: Cannot find module '../../../examples/examples.json' from 'c:\Sync\Sync\git\OpenJSCAD.org\packages\web\src\ui\views'
    required by c:\Sync\Sync\git\OpenJSCAD.org\packages\web\src\ui\views\examples.js
    at c:\Sync\Sync\git\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (c:\Sync\Sync\git\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (c:\Sync\Sync\git\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at c:\Sync\Sync\git\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (node:fs:198:21) {
  stream: [Labeled]
}
```

**Comment by z3dev** [comment]
Windows? Please see #777

**Comment by udif** [comment]
OK, going by the path of least resistance, I'm now cloning OpenJACSD.org on my WSL2 environment instead.

**Comment by z3dev** [comment]
Thanks @udif 

Let us know if there are any more problems.
