### ISSUE TITLE
openjscad.xyz / Browsereditor line numbers overlapping

### ISSUE THREAD

**Issue by NilsKrause** [jscad/OpenJSCAD.org#1030]
## Expected Behavior
![Screenshot 2022-03-16 at 21 27 53](https://user-images.githubusercontent.com/15922517/158684941-8165898b-94f2-4bbd-8f4c-5c3a646f3571.png)

## Actual Behavior
![Screenshot 2022-03-16 at 21 19 58](https://user-images.githubusercontent.com/15922517/158683554-7fcdeaa0-c708-4fce-8374-eb2229d9bef2.png)

## Steps to Reproduce the Problem

  1. Goto https://openjscad.xyz/
  2. Open Editor
  3. Input code

## Specifications

  - Version: Current running website
  - Platform: MacOS
  - Environment: browser (Brave, Safari)

I am pretty sure that  this also happens in other browsers. I have a fix on my local setup and would submit a PR. Just wanted to be sure that this is not just an issue I have.

**Comment by z3dev** [comment]
@NilsKrause welcome

this is present in all browsers. A fix would be very nice.

**Comment by NilsKrause** [comment]
Thanks, just found jscad and am already a big fan of it.

Will submit the PR tomorrow.

**Comment by hrgdavor** [comment]
If you can also fix, why editor content is not visible before clicking would be perfect.
openin jscad and choosing an example, then opening editor, it looks like code is not loaded, but it is, just not shown

**Comment by NilsKrause** [comment]
Both issued should be fixed in #1031, take a look if you got the time. It's only a very minor change.
