### ISSUE TITLE
Incorrect order of arguments in enclosedEdge (modling/src/operations/modifiers/edges.js)

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1032]
## Expected Behavior
This template doesn't really cover this issue.
I'm in process of translating jscad to C#.... the type checking caused me to find a clear problem in enclosedEdge.

The line3 method closestPoint has a signature of closestPoint(line, point).
In enclosedEdge (edges.js, lines 116 and 117) the calls to closestPoint clearly have the point and line arguments reversed.

Here are the relevant incorrect lines:
        const closest0 = vec3.snap(vec3.create(), eps, line3.closestPoint(openedge[0], line3d))
        const closest1 = vec3.snap(vec3.create(), eps, line3.closestPoint(openedge[1], line3d))
        
Tracing through the usage of enclosedEdges, only the generalize..."repair" unit test would exercise this code, and in this case, didn't
catch the problem.

Amazingly, this is the only problem I've found during the translation... and I'm more than halfway through!

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: Current
  - Platform: N/A
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment]
@briansturgill C#!!! Wow! That's pretty cool. I know that someone translated this to C++ once, long long ago.

We will look at this little 'mistake' in more detail, test, and fix.

**Comment by platypii** [comment]
Steps to reproduce the problem:
```js
generalize({ repair: true }, union(cube({ size: 8 }), cube({ center: [0, 0, 4] })))
```

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.subtract (blob:https://openjscad.xyz/3d865e0e-a752-47e3-945a-f1ae9718dce7:2438:32)
    at Object.fromPoints (blob:https://openjscad.xyz/3d865e0e-a752-47e3-945a-f1ae9718dce7:2090:122)
    at enclosedEdge (blob:https://openjscad.xyz/3d865e0e-a752-47e3-945a-f1ae9718dce7:2774:1492)
```

**Comment by z3dev** [comment]
Probably anything "repair" will die. It was a ambitious idea...

**Comment by platypii** [comment]
> Probably anything "repair" will die.

Should I change #1042 to just delete all the generalize repair code? Happy to delete lines of code :fire:
