### ISSUE TITLE
cutByPlane function of old openJSCAD not implemented

### ISSUE THREAD

**Issue by Oisangui** [jscad/OpenJSCAD.org#1054]
## Expected Behavior
Expected ```cutByPlane``` to be implemented

## Actual Behavior
It is not implemented, at least not with a similar name and it is not obvious.

**Comment by z3dev** [comment]
@Oisangui welcome

this function was considered broken in V1, and better implemented by users or special libraries.

https://github.com/jscad/csg.js/blob/master/src/api/ops-cuts.js

This function is fairly simple to duplicate in V2. Let us know if you need a few pointers.

**Comment by Oisangui** [comment]
It would be nice to get some help with that. The thing is I became used to V1 and implemented a solution for a problem that uses the aforementioned function, but I'm having trouble connecting that with node and that's why I'm trying to do the same in V2 (better node integration for what I have read). What I was doing in V1 is running a script and within the script I do a console log which  prints the result of some calculations to standard output. I need to get those results in nodeJS but the node package for V1 doesn't seem to support getting that.

**Comment by Oisangui** [comment]
I solved it with the following: Create a big 2D square, the extrude it really high, rotate it so that the normal of the plane is the one specified, and finally translate it. Then you can subtract your shape with this plane.
