### ISSUE TITLE
Possible flaw in poly3.validate

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1059]
## Expected Behavior
Perhaps, poly3.validate should check to see that the vertices are coplanar?

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment]
I guess that for more than 3 points this makes sense.
