### ISSUE TITLE
Problem with JSCAD measureBoundingBox/measureBoundingSphere caching.

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1094]
1. Because Geom2/Geom3/Path2 geometries are NOT immutable, any transformation on a Geometry after the first call to measureBoundingX will in most cases return an invalid result from the cache.

2. The caching of values makes the performance testing numbers very skewed. In real life the cache would be very seldom used as new geometries are usually created for each position in which they are used. One questions if the cache should be there at all.

3. The major measuring of bounding spheres is done by poly3.measureBoundingSphere (which calls poly3.measureBoundingBox), which is not included at all in the performance testing. It is also not cached... if caches actually are useful, this should likely be cached as poly3.measureBoundingSphere is VERY critical path in boolean operations.

You might want to look at the attached screen capture from my running profiling on the CSharp version I'm working on. The profiling you see was run on the union portion of the performance testing translated from JSCAD.
The need for absolute speed in the measurement of bounding boxes and spheres is amazing.
I used profiling via nodejs on JSCAD and got similar results, but the profiling is harder to read/understand there.

Brian
![Capture](https://user-images.githubusercontent.com/7350143/170785044-54f695a4-5188-44b3-86d3-ea8ba205d0d6.PNG)

**Comment by hrgdavor** [comment]
I would not disregard caching of bounding boxes as easily. The bounding box can be safely recalculated for transforms that only translate and scale (no rotation). One of reasons I wanted to introduce caching is to allow for shape generators to prefill the cache. For example it is trivial to precalculate bounding box of a sphere, but is exponentialy more expensive wirh increasing segment count.

One more thing, if cache is to removed, It should not be because of geometries that are mutable. The direction of making geometries immutable is already a chosen path and I would not like to revert it.

**Comment by briansturgill** [comment]
...
> One more thing, if cache is to removed, It should not be because of geometries that are mutable. The direction of making geometries immutable is already a chosen path and I would not like to revert it.

I think you misunderstand... all geometries ARE mutable. That is how Transform/ApplyTransforms works.
The "measurement.measureBounding... routines INCORRECTLY do the caching. They will return incorrect values
if the routine is called before a Transform, and then called again. The current caching simply is incorrect.
If you want caching, the the cached bounds should be on the geometry object and the transform/applyTransform
methods must invalidate the cached values. The current situation is simply broken.

Further, caching isn't really doing anything at all w.r.t. to usage by JSCAD internals.
Currently, the only caching of BoundingBox/BoundingSphere is in the "measurement" routines, which are not even used by the runtime. (The runtime uses poly3.measureBounding... which is NOT cached). So it's unclear why the measure routines do this at all. I mean if the user whats the values cached, why don't they cached them themselves?
If you really do want caching, then it is the poly3 routines that need to be caching as those are what are used by the runtime.

**Comment by briansturgill** [comment]
BTW. if you want to speed up your boolean operations, one should study the screenshot I gave you above.
I renamed a few things in my CS version, so here is a translation:
JSCAD poly3.measureBoundingBox is CSCAD Poly3.BoundingBox
JSCAD poly3.measureBoundingSphrere is CSCAD Poly3.BoundingSphere
JSCAD (really Nodejs) Math.hypot is Vec3.Hypot.

The column you want to look at is Self CPU... this is the % of CPU the given routine is using inside itself (not in things it calls).
The profile is from running the "union" performance tests and as you can see, BoundingBox/BoundingSphere/Hypot need to be as optimized as possible. With some hard work, one might be able to speed up the boolean operations by 25% or more.

My implementation of hypot that matches the new IEEE spec.
```C#
    /// <summary>Returns the hypotenuse of the three points, avoiding unnecessary underflow/overflow.</summary>
    public static double Hypot(double _x, double _y, double _z)
    {
        var x = _x < 0.0 ? -_x : _x;
        var y = _y < 0.0 ? -_y : _y;
        var z = _z < 0.0 ? -_z : _z;
        var m = x > y ? x : y;
        m = m > z ? m : z;
        if (m == 0.0)
        {
            return 0.0;
        }
        x /= m;
        y /= m;
        z /= m;
        return m * Math.Sqrt(x * x + y * y + z * z);
    }
```
In accordance with the issue I raise in #1095 I will be changing this to:
```C#
    /// <summary>Returns the hypotenuse of the three points.</summary>
    public static double Hypot(double x, double y, double z)
    {
        return Math.Sqrt(x * x + y * y + z * z);
    }
```

**Comment by hrgdavor** [comment]
> I think you misunderstand... all geometries ARE mutable. That is how Transform/ApplyTransforms works.

That is not the intention, and if true will be fixed. 

Transform creates new geometry by keeping keeping reference to same vertex data but generating a new transform that is a combination of existing transform and newly applied transform. Intention is not the "absolute immutability" but the "effective immutability" and the is the direction I am lobbying for internally.

ApplyTransforms is allowed to mutate the internal data of geometry but it is intended to be done in such way that it remains in the same bounding box.

Your input is sincerely appreciated. I am simply perceiving issues that arise from mutable geometry data as a bug in the fact that data is mutated and my intent is not to remove caching but ensure proper effective immutability is implemented internally so caching can work properly.

**Comment by briansturgill** [comment]
Wow... OK, I tried to make a test case that failed and it didn't fail.
I see what you mean about what Transform does, and you're right, at least for caching it works.
I will close this issue.
I'm going to move the Profile png to a new issue as that is still valid.

**Comment by hrgdavor** [comment]
Cool. I am, glad it actually works. Thanks for the feedback. Yor feedback is welcomw, and I hope we can work together towards more speed improvements.
