### ISSUE TITLE
Output profiling from C# that might prove useful to JSCAD development.

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1096]
Below is an image of a profile of my translation of JSCAD "union" performance tests to C#.
In particular what it shows is that unions (and it will be true for all booleans) are dominated by the seemingly simple
routines poly3.measureBoundingBox, poly3.measureBoundingSphere and Math.hypot.
I renamed a few things in my CS version, so here is a translation:
JSCAD poly3.measureBoundingBox is CSCAD Poly3.BoundingBox
JSCAD poly3.measureBoundingSphrere is CSCAD Poly3.BoundingSphere
JSCAD (really Nodejs) Math.hypot is Vec3.Hypot.

The column you want to look at is Self CPU... this is the % of CPU the given routine is using inside itself (not in things it calls).
The profile is from running the "union" performance tests and as you can see, BoundingBox/BoundingSphere/Hypot need to be as optimized as possible. With some hard work, one might be able to speed up the boolean operations by 25% or more.

My implementation of hypot that matches the new IEEE spec.
```C#
    /// <summary>Returns the hypotenuse of the three points, avoiding unnecessary underflow/overflow.</summary>
    public static double Hypot(double _x, double _y, double _z)
    {
        var x = _x < 0.0 ? -_x : _x;
        var y = _y < 0.0 ? -_y : _y;
        var z = _z < 0.0 ? -_z : _z;
        var m = x > y ? x : y;
        m = m > z ? m : z;
        if (m == 0.0)
        {
            return 0.0;
        }
        x /= m;
        y /= m;
        z /= m;
        return m * Math.Sqrt(x * x + y * y + z * z);
    }
```
In accordance with the issue I raise in #1095 I will be changing this to:
```C#
    /// <summary>Returns the hypotenuse of the three points.</summary>
    public static double Hypot(double x, double y, double z)
    {
        return Math.Sqrt(x * x + y * y + z * z);
    }
```
![image](https://user-images.githubusercontent.com/7350143/170848037-7f20e7b5-b337-4e48-af92-10b7622e2880.png)

**Comment by z3dev** [comment]
@briansturgill 

i've been trying to understand the reasoning behind the IEEE-like implementations. it seems that the scaling (by largest value) makes an assumption that ALL values are of the same 'scale'. i that isn't true then there's not much value in scaling to eliminate loss of precision errors.

did i understand correctly?

and yeah. i think JSCAD doesn't benefit from the use of Math.hypot()

**Comment by briansturgill** [comment]
It isn't entirely unreasonable to believe they are likely to be of the same scale... How many triangles do you have that have two sides a light-year long and and the third a nano-meter long? The problem is that hypot if you deal with very large or very small numbers, hypot done with Sqrt fails. Fortunately that doesn't apply to CAD. I'm assuming that the IEEE people made the assumption that people that didn't need the scaling would just do it the traditional way. I don't really know, I derived the code above by reverse engineering what G++ did with inlined code. It does what IEEE intended, but under C# runs about 5x slower.

**Comment by z3dev** [comment]
@briansturgill thanks for the nice performance hints.

The change from hypot() to sqrt() has been released. As well as, the improvements to measureBoundingSphere(). Performance of the BSP trees has been boosted by 40 to 50%.

I think this issue could be closed now. Please let us know if you find any more areas for improvement.

**Comment by briansturgill** [comment]
Yeah, it's looking good, I'll try to run a full performance test on it tonight.
I reran profiling on CSharpCAD after making similar changes and believe what's left is just indicative of what it takes to do the job.
I also looked at many other places and it looks like most things are fine.
One exception, extrudes... but I'm just now looking into why. I'll post more if I decide there's potential significant gains.
If you're curious, for ExtrudeLinear and ExtrudeRotate, 48%/40% are spent in Extrude Walls, plays an 11% role in Extrude Rectangular.
Also big in ELinear,ERotate: Plane.FromPoints (17%/26%) and Slice.Transform(8%, 9%).
The percentages reflect the amount of CPU time running the named functions called, but without the time of functions that function calls.
The total CPU time is the time (running individually) the Performance Test for the 3 Extrudes.

**Comment by briansturgill** [comment]
OK, generally nothing wrong in extrudes. I found a few problems in my translation, but I think it unlikely any of it applies to JSCAD.
It might be worth someone's time to take a look at extrudeWalls as it is very critcal path and moves a lot of data around.

**Comment by hrgdavor** [comment]
the extrude alg probably needs revisiting. Maybe splitting into few variants. I am sure there is subset of use-cases (that are actually likely very common) that can be superfast.

**Comment by briansturgill** [comment]
> the extrude alg probably needs revisiting. Maybe splitting into few variants. I am sure there is subset of use-cases (that are actually likely very common) that can be superfast.

Interesting... as you know I'm review the primitives to finalize CSCAD API. One thing I've been doing is rewriting (actually massively refactoring) the primitives (for example circle to circle (full) and semicircle).
One thing I've found is that there is quite a bit of unnecessary work done. For example "center" always gets added, even though that wouldn't be the usual case. (I mean, does one really want to be adding zero to EVERY point, EVERY time)?

Anyway, the other thing that became clear to me is that all of the 3D's that are essentially extruded Geom2's are doing their own linearExtrude... and that linearExtrude really is taking much too much CPU in its current form.
I'm working on a rewrite of that now.

**Comment by platypii** [comment]
An optimization I've been meaning to implement on `extrudeLinear` is a check for convexity. Right now it runs the ear cut algorithm, cutting off triangles "ears" recursively, until everything is triangles. But there is no need to do that if the polygon is convex.

First of all, if the poly is convex, then triangulation is trivial, no need for complicated earcut algorithm. But also, JSCAD allows faces to be any convex polygon, not just triangles. So we can save time and memory be returning early from earcut. Furthermore, `extrudeLinear` is already tracking the convexity of each corner, so it should be easy to determine when a polygon is convex.

**Comment by z3dev** [comment]
The extrude functions were created using the same functionality to make the process exactly the same. There are cases where the number of points are not the same, and therefore triangles are required to create the walls.

I'm sure optimizations are possible but don't forget that the extrude functionality is very powerful.

**Comment by hrgdavor** [comment]
I am in favor of having a different extrude for cases that can benefit in performance. I would welcome even going to a next level general aproach of adding more performance hints similar to HasOnlyOnePath .

**Comment by briansturgill** [comment]
Oh, I'd appreciate if those of you that understand sides (likely better than I do) check that the HasOnlyOnePath property checks  what it says it checks.

**Comment by briansturgill** [comment]
@z3dev 
> The extrude functions were created using the same functionality to make the process exactly the same. There are cases where the number of points are not the same, and therefore triangles are required to create the walls.
Could you elaborate on the cases where there number of points are not the same?
At least in extrudeLinear, I expect it is always the same.
