### ISSUE TITLE
Fault in documentation of circular/elliptical primitives.

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1105]
In numerous of these primitives you document:
"number of segments to create per full rotation"

That implies to me that the number of segments is per a whole (360 degree, "full" rotation) object.
However, I've reading the code a lot and clearly it is the segments per the potentially partial object from startAngle to endAngle.
Perhaps it should say instead of "per full rotation", "for the defined rotation"? Or even "for the rotation from startAngle to endAngle"

**Comment by hrgdavor** [comment]
I think that was intended as a goal, but not implemented properly everywhere. 
Having same number of segments for 360 deg and then also same for 50 deg is incosistent. I prefer if effort is made to go towards something consistent like:
 -  actually obeying: "number of segments is per a whole (360 degree, full rotation)" 
 - or something similar to OCCT

**Comment by briansturgill** [comment]
...
>     * actually obeying: "number of segments is per a whole (360 degree, full rotation)"

Interestingly, when I was trying to decide whether or not to keep the startAngle:, endAngle: features in CSharpCAD, the main (really only) pro reason was that you could control the number of segments in a partial circle. (In my head I was considering what it would take to make a pool table "rack" (i.e. rounded triangle). I decided I'd be better off making a Path object that drew it directly and then dumped out a Geom2, then extrude...

**Comment by hrgdavor** [comment]
to me it is more about precision of curves when converted to mesh, and it looks like 2 separate concepts that can not be handled by single param.
Sometimes I want direct control over number of segments, sometimes I need a kind of concept of smoothness.

**Comment by briansturgill** [comment]
This turns out to not be wrong in circle/ellipse, so I going to close this.
