### ISSUE TITLE
replace lerna with yarn(?) and lerna-lite(?)

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#1114]
## Expected Behavior

Using a new mono-repo management tool; build, version, and publish packages to NPM

## Actual Behavior

Lerna has been going through some major disappointments. First, it was deprecated, end-of-life. Then, it was given to over to Nrwl to maintain.

It's probably time to try a few other options, as technology around mono-repositories has been improving.

- pnpm
- yarn
- lerna-lite

**Comment by hrgdavor** [comment]
I vote for pnpm :) ... 
I have limited experience with it, and my main reason to use it because it reuses packages via symlinks and hardlinks, thus conserving space.

**Comment by z3dev** [comment]
V3 is now using PNPM and LERNA-LITE. This will be closed when V3 is released.
