### ISSUE TITLE
geom2.reverse creates an invalid geometry.

### ISSUE THREAD

**Issue by briansturgill** [jscad/OpenJSCAD.org#1134]
## Expected Behavior
That's the really odd part, if you think about what reverse would do, that is what you would get.
It's a really bad idea to have such a function as a geom2 "method".
It is used only in extrudeRotate.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment]
@briansturgill possibly but then there are folks creating geom2 from points in various orientation, and reverse can come in handy. see #1192
