### ISSUE TITLE
Packaging : drop NODE 12 support

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#1137]
Node 12 is no longer supported. The supported versions should as of 2022-08 should be 14, 16, 18

See https://nodejs.org/en/about/releases/

**Comment by briansturgill** [comment]
The version of node that comes with the current Ubuntu (22.04.1) LTS is 12.22.9, its end-of-life is April 2027.
To be clear, a large portion of the Linux world won't normally get an upgrade of node for quite some time.
Not a problem for me, but most people don't upgrade outside of their distributions.
I find it weird that Ubuntu lags so badly, but it's reality.  Any idea if other distributions are better about this?
Ubuntu hasn't been all that stable this time around.

Note, not a big deal on the Mac, brew is installing 18.7.0

**Comment by z3dev** [comment]
Basically, dropping support means no more testing with that version, and if people drop by and say they use an older version then the first answer would be "please try a tested version".

A while back, someone was using an older version of NODE  on windows, but was able to get the test suites to run. So, who knows.

Not sure what happens when we move to pnmp/yarn and lerna-lite. Hopefully, the world will be stable no matter the choice.

**Comment by briansturgill** [comment]
OK, some additional feedback. It looks like non-Debian versions are pretty much upto date.
OpenSuse lags a bit at node 14 (though 16 is in the latest).
Centos/Redhat/Fedora, Arch, Gentoo are all at 16 or 18.

Under Ubuntu you can install a snap with version 16. But all Debian variants seem to default to 12.
No idea what is going on here. I point it out to you only because Debian-based variant probably have more than half the Linux
user base. I understand your desire to move on.

**Comment by platypii** [comment]
Node 12 is still widely deployed, so I would vote to not intentionally break compatibility.

But when we do decide to move forward, there are some polyfills which won't be needed anymore. For example, the [Blob](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/io/io-utils/Blob.js) polyfill won't be needed in Node 15+. See #1006

**Comment by hrgdavor** [comment]
@briansturgill @briansturgill we will not intentionally break node 12 but will be less inclined to fix node 12 specific issues.

One of the steps forward will likely be ES6 and that works in node 12 https://stackoverflow.com/questions/56744272/specifying-es6-modules-in-node-12

**Comment by z3dev** [comment]
There's no choice really, as this project will be using PNPM soon. PNPM requires 14+ versions of Node.js.

**Comment by z3dev** [comment]
Notice has been given to the user group. The next release will add Node 18 and drop Node 12.

**Comment by z3dev** [comment]
The workflow settings for the CI has been adjust to include NODE 14 and 16. Closing this issue.
