### ISSUE TITLE
Failed to import stl file in jscad

### ISSUE THREAD

**Issue by miao-liu** [jscad/OpenJSCAD.org#1144]
## Expected Behavior
The imported file is displayed in the scenario

## Actual Behavior
The console reported an error. Cannot find the file

## Steps to Reproduce the Problem

Based on JSCAD V2.6.0 -> web
  ```
// test.js
const jscad = require('@jscad/modeling')
const { translateX } = jscad.transforms

const sculpture = require('./test.dxf')

const main = () => {
  return translateX(10, sculpture);
}

module.exports = { main }
```
<img width="879" alt="Screen Shot 2022-09-20 at 5 58 52 AM" src="https://user-images.githubusercontent.com/36464497/191127028-99d8f0e8-5063-47a2-9869-d9d5c0b7542b.png">
<img width="1371" alt="Screen Shot 2022-09-20 at 5 59 11 AM" src="https://user-images.githubusercontent.com/36464497/191127082-a4f7b999-43e8-4a2e-ba01-7468631110e4.png">

## Specifications

  - Version:JSCAD V2.6.0
  - Platform: mac 
  - Environment: browser

**Comment by hrgdavor** [comment]
I only see you mentioning test.js

what file did you drag and drop into the browser ?

import only works if you drag drop a folder with multiple files.

**Comment by z3dev** [comment]
@miao-liu the 'project' folder seems correct. Please drag and drop the folder to the website.

**Comment by miao-liu** [comment]
I use it in combination with three + Vue. If you need to drag the relevant JS into the browser, this is obviously not the way the client wants to proceed. However, I found the code associated with Vue-Components to implement the functionality.

**Comment by z3dev** [comment]
@miao-liu if satisfied then please close this issue
