### ISSUE TITLE
Is jscad have raycaster like Three?

### ISSUE THREAD

**Issue by miao-liu** [jscad/OpenJSCAD.org#1156]
## Expected Behavior
Click on a graphic to select it  for move and scaling related operations.

## Actual Behavior
Click on a graphic to select it, trying to move it, it's dons't work

**Comment by hrgdavor** [comment]
@miao-liu jscad is using libraries similar to Three.js to display the results. But there is no UI interface to manipulate shapes with mouse. All manipulations to the shapes (moving scaling rotating) are done inside the script with code.

**Comment by miao-liu** [comment]
> @miao-liu jscad is using libraries similar to Three.js to display the results. But there is no UI interface to manipulate shapes with mouse. All manipulations to the shapes (moving scaling rotating) are done inside the script with code.

ok
