### ISSUE TITLE
Missing opening curly brace in cuboid example

### ISSUE THREAD

**Issue by Jamesgt** [jscad/OpenJSCAD.org#1161]
See the code example here https://openjscad.xyz/docs/module-modeling_primitives.html#.cuboid , it should be:

```js
let myshape = cuboid({size: [5, 10, 5]})
```

**Comment by hrgdavor** [comment]
could you make a PR ? it is nice to get ppl involved :)

**Comment by Jamesgt** [comment]
of course and you've got also another language match free :)
