### ISSUE TITLE
Helix extrude

### ISSUE THREAD

**Issue by Loosetooth** [jscad/OpenJSCAD.org#1162]
I was unable to find a function to help me extrude a helix. Currently, both the `extrudeRotate` and `extrudeLinear` functions are not suitable for this task.

Would it be interesting to add this functionality to JSCAD?
I think it's a pretty basic function, for example if you want to model something like a bolt or a nut.

Here is my current naive implementation:
```js
const helicalExtrude = (base, pitch, numberOfSlices, totalRotation) => {

    if (geom2.isA(base)) baseSlice = slice.fromSides(geom2.toSides(base))
    if (poly3.isA(base)) baseSlice = slice.fromPoints(poly3.toPoints(base))

    const sliceCallback = (progress, index, base) => {
        const zRotation = totalRotation / numberOfSlices * index
        const zOffset = zRotation / (2 * Math.PI) * pitch

        // create rotation matrix
        const matrix = mat4.multiply(
            // then rotate around Z axis
            mat4.fromZRotation(zRotation),
            // first rotate "flat" 2D shape from XY plane to XZ plane
            mat4.fromXRotation(Math.PI / 2)
        )

        const completeMatrix = mat4.multiply(
            // add translation
            mat4.fromTranslation([0, 0, zOffset]),
            matrix
        )

        return slice.transform(completeMatrix, base)
    }

    return extrudeFromSlices(
        {
            numberOfSlices: numberOfSlices,
            capStart: false,
            capEnd: false,
            close: false,
            callback: sliceCallback
        },
        baseSlice
    )
}
```

Which you can then use as:
```js
const pitch = 10
const totalRotation = 4 * Math.PI
const totalSlices = 2 * 32

const myCircle = translate([5, 0, 0], circle({ radius: 2.5 }))
return helicalExtrude(myCircle, pitch, totalSlices, totalRotation)
```

With the following result:
![image](https://user-images.githubusercontent.com/66420755/200348499-810fa12f-e545-450b-b60c-f0c5312cfdef.png)

This feature would improve user experience, as users do not have to 'dig' into the code any more and learn how to use `extrudeFromSlices` in order to create a helix. It would also then be possible to improve the "nuts and bolts" code example in the web UI.

The implementation could be done either as a separate function like `extrudeHelical`, or it would be possible to implement an optional `pitch` parameter for the existing `extrudeRotate` function.

What do you think?
I'm willing to work on a pull request in the coming days.

**Comment by z3dev** [comment]
@Loosetooth Welcome to JSCAD.

Absolutely, we are always looking to expand the API, especially if the functionality adds to the user experience.

For 'helix', there are several existing implementations out there. I know that AutoCad and OpenSCAD both have 'helix' shapes, so please review those. It would be great if the JSCAD helix can mock those implementations.

Also, the API should follow other implementations for parameter position.

Looking forward to the PR.

**Comment by Loosetooth** [comment]
Thanks for the quick reply and warm welcome.

As for the existing implementations, I did a quick search, I'll list a few of them here:
* [Autodesk HELIX](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/AutoCAD-Core/files/GUID-C6FE985E-8978-4D11-8490-D81CFB323CDD-htm.html)
* [Fusion360 Coil](https://help.autodesk.com/view/fusion360/ENU/?guid=SFC-REF-COIL)
* [OpenSCAD Helix library](https://www.thingiverse.com/thing:1958354)

If we would like to generate spirals and tapered "helix" cones as well, we would need at least these parameters if I'm correct:
```js
const extrudeHelical = ({
    revolutions, // in radians, positive for right-hand rotation, negative for left-hand
    radius, // start radius, this one can be omitted if we expect the user to move the shape in advance
    height, // the total height of the helix
    pitch, // elevation gain for each turn
    endRadius = radius, // to create tapered helix, or '2D' extruded spiral.
                        // this could also be "endRadiusOffset" in the case that the 'radius' parameter is omitted.
}) => {
...
}
```

> Also, the API should follow other implementations for parameter position.

Sure, I will have a look at those while I implement it. Using JS object destructuring.

I still have a few questions before I start. I'll try to look at:
* implementation including spirals and tapered cones
* tests
* documentation

In what branch do I start? V2 or V3?

**Comment by z3dev** [comment]
@Loosetooth nice investigation. It seems that there's some consistency, which is good.

please work with the V2 API, and branch from master branch. This is the stable version of the API.

**Comment by hrgdavor** [comment]
@Loosetooth if u ever feel chatty, there is a discord channel https://discord.gg/AaqGskur93 there is not many of jscad ppl active there, but if you already use discord might be interesting.

**Comment by Loosetooth** [comment]
Thanks for the invitation @hrgdavor 

I currently don't use discord. Perhaps I'll look into it in the future, depending how much development I'll do for JSCAD.
