### ISSUE TITLE
CLI halts.

### ISSUE THREAD

**Issue by cptclvtch** [jscad/OpenJSCAD.org#1180]
## Expected Behavior
jscad.exe outputting an .stl file.

## Actual Behavior
jscad.exe "freezes". The only error message that appears is: "[12164:1226/235730.692:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is"

## Steps to Reproduce the Problem

  1. Use ```jscad myfile.js``` in project directory

## Specifications

  - Version: LTS
  - Platform: Windows 11 x64
  - Environment: node.js

**Comment by cptclvtch** [comment]
How do I add labels?

**Comment by z3dev** [comment]
@cptclvtch welcome.

please take a look at the README for the CLI. hopefully, this will give you some answers on how to use the CLI. if you still have some issues then post a few more examples.

https://github.com/jscad/OpenJSCAD.org/blob/master/packages/cli/README.md

**Comment by platypii** [comment]
It looks like a node.js error with accessing the GPU, but it's not clear to me why the GPU would be needed for CLI operation.

Can you give a bit more details? How did you install jscad? Can you give the exact version using `jscad -v`

What version of node? `node -v`

Is there a GPU installed in the machine you're on?

**Comment by cptclvtch** [comment]
> @cptclvtch welcome.
> 
> please take a look at the README for the CLI. hopefully, this will give you some answers on how to use the CLI. if you still have some issues then post a few more examples.
> 
> https://github.com/jscad/OpenJSCAD.org/blob/master/packages/cli/README.md

Well, I did look at the README. Thats why created the issue. jscad launches and does some things but never returns a result. Also, Im not sure what examples to post.

**Comment by z3dev** [comment]
@cptclvtch OK.

i suspect something is wrong with the NODE installation. Can you provide the version of NODE?

**Comment by cptclvtch** [comment]
Ok, Turns out I was launching VSCode this whole time because my javascript file was called jscad.js. So even though I wrote ```jscad jscad.js```, it would like I typed in ```jscad.js```.
