### ISSUE TITLE
linear extrusion of 2d arc shape not solid

### ISSUE THREAD

**Issue by ahdinosaur** [jscad/OpenJSCAD.org#1192]
Hi :smiley_cat: 

I'm pretty sure this is a bug. Or maybe I'm being dumb about my code, if so I'm sorry for the bother.

(This is a simplified example taken from a larger model where this is causing an issue.)

Thanks !

## Expected Behavior

Linear extrusion of this 2d arc shape should be solid.

![Screenshot from 2023-01-13 12-13-00](https://user-images.githubusercontent.com/719605/212201018-639d7354-ac4c-4979-8a3d-4b82436c7066.png)

## Actual Behavior

![Screenshot from 2023-01-13 12-12-29](https://user-images.githubusercontent.com/719605/212200956-a2d1684d-9d9e-4eab-9d50-1fa61ebc8026.png)

## Steps to Reproduce the Problem

```js
const { primitives, geometries, extrusions, maths } = require('@jscad/modeling')

const ROT = 2 * Math.PI

const insideRadius = 10
const materialThickness = 5
const height = 1

function main() {
  const insideArc = primitives.arc({
    radius: insideRadius,
    startAngle: 0,
    endAngle: (1/4) * ROT,
  })

  const outsideArc = primitives.arc({
    radius: insideRadius + materialThickness,
    startAngle: 0,
    endAngle: (1/4) * ROT,
  })

  const profile = geometries.path2.fromPoints(
    {
      closed: true,
    },
    [
      ...insideArc.points.map(maths.vec2.clone),
      ...outsideArc.points.map(maths.vec2.clone).reverse(),
    ],
  )

  return extrusions.extrudeLinear(
    {
      height,
    },
    profile
  )
}

module.exports = { main }
```

## Specifications

  - Version: 2.6.3
  - Platform: https://openjscad.xyz/
  - Environment: browser

**Comment by hrgdavor** [comment]
just reverse it. you have the 2d shape for extrusion in wrong direction CW/CCW

**Comment by ahdinosaur** [comment]
Okay thanks @hrgdavor !

```js
const { primitives, geometries, extrusions, maths } = require('@jscad/modeling')

const ROT = 2 * Math.PI

const insideRadius = 10
const materialThickness = 5
const height = 1

function main() {
  const insideArc = primitives.arc({
    radius: insideRadius,
    startAngle: 0,
    endAngle: (1/4) * ROT,
  })

  const outsideArc = primitives.arc({
    radius: insideRadius + materialThickness,
    startAngle: 0,
    endAngle: (1/4) * ROT,
  })

  const profile = geometries.path2.fromPoints(
    {
      closed: true,
    },
    [
      ...insideArc.points.map(maths.vec2.clone).reverse(),
      ...outsideArc.points.map(maths.vec2.clone),
    ],
  )

  return extrusions.extrudeLinear(
    {
      height,
    },
    profile
  )
}

module.exports = { main }
```

Is there documentation about the requirement for paths to be a specific CW/CCW direction?

I didn't realize this was necessary.

**Comment by z3dev** [comment]
@ahdinosaur thanks for posting this issue.

the extrusions are sensitive to orientation of the 2D geometry. for upward extrusions, the 2D geometry should have a positive area, i.e. the orientation is CCW about Z axis.
