### ISSUE TITLE
Union of mirrored path2 geometries don't work

### ISSUE THREAD

**Issue by nothingnesses** [jscad/OpenJSCAD.org#1207]
## Expected Behavior
A union of the geometries (a rectangle) is produced from the original shape (a square).

## Actual Behavior
Only the original geometry is produced.

## Steps to Reproduce the Problem

```js
const jscad = require("@jscad/modeling"),
	{ union } = jscad.booleans,
	{ fromPoints } = jscad.geometries.path2,
	{ mirrorX } = jscad.transforms,
	coordinates_generator = (coordinates) => {
		switch (coordinates.length) {
			case 0:
				return [];
			case 1:
				return coordinates;
			default:
				return coordinates
					.reduce(
						(accumulator, current) =>
							accumulator.concat([
								current.map(
									(value, index) =>
										value + accumulator[accumulator.length - 1][index]
								),
							]),
						[Array(coordinates[0].length).fill(0)]
					)
					.slice(1);
		}
	},
	points = [
		[10, 0],
		[0, 10],
		[-10, 0],
		[0, -10],
	],
	main = () => {
		// A square.
		const half = fromPoints({ closed: !0 }, coordinates_generator(points));
		// Should return a rectangle, but only returns the original square.
		return union(half, mirrorX(half));
	};
module.exports = { main };

```

## Specifications

  - Version: V2.6.3
  - Platform: https://openjscad.xyz/
  - Environment: Firefox v108.0.1 (64-bit)

**Comment by z3dev** [comment]
Union currently works with geom2 and geom3 geometers . Please try using geom2.fromPoints()

**Comment by nothingnesses** [comment]
Thanks. I tried replacing:
* `{ fromPoints } = jscad.geometries.path2,` from line 3 with `{ fromPoints } = jscad.geometries.geom2,`
* `const half = fromPoints({ closed: !0 }, coordinates_generator(points));` from line 36 with `const half = fromPoints(coordinates_generator(points));`

But this didn't fix the issue for me. It instead resulted in a different issue where the mirrored square is produced but the original isn't, and so no rectangle is produced either.

One hacky work around that kind of seems to work though is to use `extrusions.extrudeLinear` to extrude a "3D" geometry from the original code, but with a height of `0`.

**Comment by z3dev** [comment]
So... mirrorX() creates the shape mirrored about the X axis, but the points are ending up going clockwise about Z. The incorrect orientation is not handled by the booleans operations.

Here's my fix...
```

	main = () => {
		// A square.
		const half = fromPoints(coordinates_generator(points));
		// Should return a rectangle, but only returns the original square.
                const opposite = reverse(mirrorX(half))
                return union(half, opposite);
	};
```

**Comment by nothingnesses** [comment]
Ah thanks, yeah that solution works. I wasn't aware that the direction of lines mattered with the boolean operations.
