### ISSUE TITLE
`getBounds` in docs should read `measureBoundingBox`

### ISSUE THREAD

**Issue by NodeGuy** [jscad/OpenJSCAD.org#1221]
## Expected Behavior

[The documentation](https://openjscad.xyz/dokuwiki/doku.php?id=en:design_guide_measurements#bounding_box) reads:

> The getBounds function can be used to retrieve the bounding box of an object, returning an array with two points specifying the minimum and maximum coordinates, i.e. X, Y, Z values.

I expect `measurements.getBounds(shape)` to return a bounding box.

## Actual Behavior

I had to dig around the code to figure out that `measurements.measureBoundingBox(shape)` (or `measureAggregateBoundingBox`) returns a bounding box.

## Specifications

  - Version: 2.11.0
  - Platform: macOS
  - Environment: jscad-now

**Comment by z3dev** [comment]
@NodeGuy Thanks for the new issue. Sadly, the User Guide is slightly out of date in regards to the 'measurements'.

FYI, anyone with a valid GitHub account can log into the User Guide website and change the documentation. Please feel free to update documentation as you find errors or missing information. We hope that anyone can contribute.

**Comment by z3dev** [comment]
Updated the User Guide.
