### ISSUE TITLE
Remove OpenSCAD translation from docs / mark as deprecated

### ISSUE THREAD

**Issue by khusmann** [jscad/OpenJSCAD.org#1230]
FYI Looks like OpenSCAD translation isn't really supported right now (#1024 #901) but is still listed in the docs:

> An OpenSCAD to OpenJSCAD translator is included, however the following features aren't working yet:
> ...
> You can edit OpenSCAD source in the built-in editor, just make sure the first line says:
> `//!OpenSCAD`
> then the source-code is shown with OpenSCAD syntax.

(At least, I can't get `//!OpenSCAD` working, even with just a simple primitive)

Thanks!

**Comment by z3dev** [comment]
@khusmann just a quick question... which documentation are you referring to?

the new documentation is available here:
- https://openjscad.xyz/dokuwiki/doku.php
- https://openjscad.xyz/docs/

you may have stumbled upon some old documentation.

**Comment by khusmann** [comment]
Ah, I see, sorry about that -- I guess I was looking at V1 docs?

https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide

Also was confused by https://openjscad.azurewebsites.net/

Unfortunately it seems they have pretty high rankings on google.
