### ISSUE TITLE
Windows 10 Desktop 

### ISSUE THREAD

**Issue by ejlmljt** [jscad/OpenJSCAD.org#1233]
## Expected Behavior
Jscad  included on desktop app 

## Actual Behavior
Error in line 15: 'require' is not defined

## Steps to Reproduce the Problem

  1.Create  .js file  with  line  const  jscad  = require('@jscad/modeling') OR  const { jscad } = require('@jscad/modeling')
  2.Drag .js  jscad to openjscad  desktop on Windows   10
  3.Error in line 15: 'require' is not defined

## Specifications

  - Version: Desktop   by   Michael S. Scherotter
  - Platform:  Windows  10 
  - Environment: (Desktop)

**Comment by z3dev** [comment]
@ejlmljt Welcome.

Just a quick question... did you setup the JSCAD desktop application? did you down load it from somewhere?

I'm asking because V2 (main version) does not have a working version of the JSCAD desktop application.

**Comment by ejlmljt** [comment]
Thanks for your reply
Yes, I did  download it from Microsoft Store app  store  at
https://apps.microsoft.com/store/detail/openjscad/9NBLGGH6J6J9?hl=en-ca&gl=ca&rtc=1

When  app  started it displays "OpenJSCAD.org 0.3.3 (2015/12/04),"   at the
bottom left of screen.
Do I havean old , early version?

**Comment by z3dev** [comment]
@ejlmljt Sorry to say but that app was never part of JSCAD. Someone put that up in the Microsoft store long long ago (2015?)

I have requested the removal but of course Microsoft does not do anything.

If anyone has a suggestion then let us know...

@microsoft HOW ABOUT HELPING FOR ONCE!

**Comment by z3dev** [comment]
WOW. Microsoft removed the old old application. Closing this issue.
