### ISSUE TITLE
2D Scene 

### ISSUE THREAD

**Issue by kamildul** [jscad/OpenJSCAD.org#1246]
Hello,
i have a problem. I don't now how i can switch 3d scene to 2d scene, it is posible? If yes how i can do it?
I have online/web version without node.js - only apache + web browser.
Thanks!

**Comment by z3dev** [comment]
@kamildul welcome!

the website (and renderer) show 2D shapes laying on the Z plane, flat.

what version of JSCAD are you using?

**Comment by kamildul** [comment]
Hello z3dev,
i'm use Version 1.6.1. I want to get the 2d mesh effect without 3d planes and display imported dxf on it

**Comment by z3dev** [comment]
@kamildul there are probably several options.

first, you could use JSCAD to import DXF, and then export to SVG. Any browser can display the SVG, which can be imbedded into HTML as well.

second, you could use this library to convert DXF to SVG. it's probably the best DXF library available. https://github.com/skymakerolof/dxf
