### ISSUE TITLE
V1 User guide missing documentation for o.rotate() and o.rotateEulerAngles()

### ISSUE THREAD

**Issue by hovissimo** [jscad/OpenJSCAD.org#125]
Per https://github.com/Spiritdude/OpenJSCAD.org/wiki/Contributing-to-OpenJSCAD.org-Documentation I'm raising this issue because of an omission in the User Guide wiki.

I ended up implementing my own "rotate about arbitrary point" method because I thought it was missing.  After reviewing CSG.js:5409-5422 I realized that there are two functions which I could have used, but I didn't know about them because they're not in the docs.

The User Guide currently reads:

> rotate([90,15,30],obj);       // openscad like
> rotate(90,[1,0.25,0.5],obj);  //    ''
> 
> obj.rotateX(90);              // object-oriented
> obj.rotateY(45);
> obj.rotateZ(30);

**Comment by z3dev** [comment]
There are quite a few undocumented functions in the CSG library. It would be best if the examples also showed and explained how to use the functions.

Can you supply some examples that use the undocumented CSG.rotate() functions?
