### ISSUE TITLE
Enhancement: save viewer state in min.html

### ISSUE THREAD

**Issue by biscuitlad** [jscad/OpenJSCAD.org#128]
Hi

I'm working on a web interface for generating 3D shapes and I'm using cloud9's IDE with openjscad.

min.html is a great lightweight interface for openjscad, but I'd really like it if I could set it up to _keep the previous view_, in the way that index.html does when you're using the editor in the browser.  That way each time I change the script, I don't have to go through the hassle of rotating and zooming in to see if that bit I changed has moved the required number of pixels to the left!

I've tried having a look at doing this, and I can't find out how to do it?  Are there some easy pointers on where to start?  I understand that index.html just re-renders the code, whereas min.html has to be refreshed, but maybe there's some way of keeping the state of the viewer between refreshes?

**Comment by z3dev** [comment]
min.html was created to only display one (static) design. of course, all the controls for viewing the design are there, even the (hidden) parameters.

index.html is able to load any number of designs via drag and drop, shift-return, url parameters. the viewer also maintains the same position when rendering.

if i understand, you want to be able to save the state of the viewer. the saved state is then used to reset the viewer if the HTML page is reloaded.

this might be possible but would take some development work.

**Comment by biscuitlad** [comment]
Yes, it's maintaining the same position when rendering that I want, so that you don't have to rotate and zoom in each time you want to view your jscad file. 

I think it would nice if min.html was essentially a very lightweight viewer for rapidly developing jscad files, whereas index.html is the all singing, all dancing, kitchen sink demonstration of openjscad!

**Comment by z3dev** [comment]
Interesting thought about the rapid development tool. What are you using to edit the JSCAD files?

FYI, files drag and dropped to index.html are tracked for changes, and reloaded if a file changes. That allows a serious designer to use the editor of choice on all the various files of a "project". And the viewer simply reloads and processes the changes.

**Comment by biscuitlad** [comment]
Hi

I'm using the freebie cloud 9 IDE, it's basically a Ubuntu instance hosted
somewhere, but comes with your stack of choice already sorted out for you.

It's handy for testing out different configs and mashing stuff together, as
you can just delete the instance and do another GitHub clone with a
different stack.

Good for node and npm try outs.

Didn't realise index.html tracked the file, might try stripping it down and
use that.

**Comment by z3dev** [comment]
You can probably start with min.html, and add the drag/drop to that. This would allow you to drag and drop any file to the viewer, and the contents of the file would be tracked/reloaded/rendered automatically.

Might be cool.
