### ISSUE TITLE
Balloons appear to be regenerating after toggling dropdown menu on jscad.app

### ISSUE THREAD

**Issue by lorr1** [jscad/OpenJSCAD.org#1290]
## Expected Behavior
When I toggle the show/hide `Balloons` or `Friend` parameter menus (hit the triangle dropdown), the balloons should not move or change positions.

## Actual Behavior
Instead, they regenerate and change positions. Only hitting rerun or changing an actual parameter should impact their positions.

## Steps to Reproduce the Problem

  1. Go to https://jscad.app/ and the balloon example
  2. Hit the triangle dropdown triangle next to the `Balloons` or `Friend` parameter menus in the bottom left
  3. Observer the balloons moving

## Specifications
Chrome browser.

**Comment by hrgdavor** [comment]
@lorr1 jscad.app is not yet part of jscad officially. We were quick to emulate official jscad app (https://openjscad.xyz) and put the wrong link for github:  https://github.com/hrgdavor/jscadui/issues/55 . 

I moved the issue to https://github.com/hrgdavor/jscadui/issues/56
