### ISSUE TITLE
Ideas, Issues, Progress on OpenJSCAD.org

### ISSUE THREAD

**Issue by Spiritdude** [jscad/OpenJSCAD.org#13]
See https://trello.com/board/openjscad-org/51611714f75ec5da390077f5

We use this as test and see how things go.

**Comment by jtoy** [comment]
should this ticket still be open?

**Comment by z3dev** [comment]
@jtoy not really.

If you have any ideas, issues, etc then please open a new issue. We accept all suggestions.

**Comment by kaosat-dev** [comment]
I will write down some of the things that are not duplicates of the issues here on github, then we can close this issue I think.

**Comment by jtoy** [comment]
Great, I just added this: https://github.com/jscad/OpenJSCAD.org/issues/314

**Comment by kaosat-dev** [comment]
thanks @jtoy ! We added a few others, closing this now
