### ISSUE TITLE
subtracting extrudeHelical object (like threads) from a cube does not work as expected

### ISSUE THREAD

**Issue by tsdexter** [jscad/OpenJSCAD.org#1309]
## Expected Behavior
Extracting the thread shape from the cube should make a clean cut

## Actual Behavior
The cut is very messy and missing faces all over the cube 
<img width="646" alt="image" src="https://github.com/jscad/OpenJSCAD.org/assets/4126987/95a396c1-0a7d-4062-9b63-ad9013ea2cd4">

## Steps to Reproduce the Problem

```js
const jscad = require('@jscad/modeling')
const { cube, cuboid, cylinder, triangle } = jscad.primitives
const { translate, rotate } = jscad.transforms
const { extrudeHelical } = jscad.extrusions
const { subtract, union } = jscad.booleans
const { degToRad } = jscad.utils

console.log(jscad);

const main = () => {
  const thread = union(
        cylinder({height: 55, radius: 10, center: [0,0,27.5], segments: 64}),
        translate(
          [0,0,0],
          extrudeHelical(
            {
              angle: degToRad(3600),
              pitch: 5,
              segmentsPerRotation: 64,
              startAngle: 0,
            },
            translate([10,0,0],
              rotate(
                [degToRad(0),degToRad(0),degToRad(270)],
                triangle({
                  type: 'SSS',
                  values: [5*Math.sqrt(2), 5, 5]
                })
              )
            )
          )
        )
      )
  const allPrimitives = [
    subtract(
      cuboid({size: [40,40,20], center: [0,0,20]}),
      thread
    ),
    translate([0,40,0], thread)
  ]
  console.log({allPrimitives})
  return allPrimitives
}

module.exports = { main }
```

## Specifications

  https://openjscad.xyz/#

**Comment by tsdexter** [comment]
@hrgdavor any ideas as to why this isn't working or tips for creating/working with threads?

**Comment by hrgdavor** [comment]
@tsdexter I think main issue is in the extruded helical. It is likely messed up, but does not look like messed up upon visual inspection.

@platypii has a nice bolts nuts example on https://jscad.app
![image](https://github.com/jscad/OpenJSCAD.org/assets/2480762/9700b5dd-0c00-4179-86cd-30cb9c966275)


I also have a long standing project creating procedural screw, that can make bolts and nuts without booleans...
that one is not that relevant to you, but I just am using this opportunity to share it :D :D http://3d.hrg.hr/jscad/three/threejscad2.html?uri=#model.screw.js

![image](https://github.com/jscad/OpenJSCAD.org/assets/2480762/06392bc8-66e5-4fd9-88d4-899e2e3b8723)

**Comment by tsdexter** [comment]
thanks a lot, just the info I was looking for. I'll take a closer look at the links provided and have another go at it.

**Comment by z3dev** [comment]
@tsdexter theres a Bolts and Nuts example example in V2, as part of the website. You can probably look at that.
