### ISSUE TITLE
https issue and/or openjscad.xyz domain expired? 

### ISSUE THREAD

**Issue by tsdexter** [jscad/OpenJSCAD.org#1334]
## Expected Behavior
docs website works 

## Actual Behavior
HTTPS behaviour:
![image](https://github.com/jscad/OpenJSCAD.org/assets/4126987/2284528b-d4dc-4411-9564-8e353b6c495a)

HTTP behaviour:
![image](https://github.com/jscad/OpenJSCAD.org/assets/4126987/7e7de59f-d3d1-4000-878d-05709ee10844)

Oddly, the app on the root works
![image](https://github.com/jscad/OpenJSCAD.org/assets/4126987/f9bea93c-87b6-4a27-ba02-d07c6bea768c)

**Comment by jimpudar** [comment]
The root app is also down now too. It does not appear to be in danger of a domain squatter holding it hostage, but whoever is in charge of this should probably get it on auto-renew 😛

**Comment by lorr1** [comment]
Could try https://jscad.app/

**Comment by z3dev** [comment]
@tsdexter sorry much. the hosting service has been restored but it may take a few hours before the website is back.

**Comment by jimpudar** [comment]
@z3dev - FWIW, it appears to be completely down for me still.

**Comment by tsdexter** [comment]
docs are still down for me as well

**Comment by z3dev** [comment]
UG... Although Hostinger said that the payment was complete... it seems not... i added another payment method, and all seems fine. Should be working soon.

**Comment by z3dev** [comment]
@tsdexter it seems that the website is back. Please try again.

**Comment by jimpudar** [comment]
Works for me now, thanks!

**Comment by tsdexter** [comment]
all good, thx 🙏
