### ISSUE TITLE
OBJ Deserializer Example Incorrect

### ISSUE THREAD

**Issue by abetusk** [jscad/OpenJSCAD.org#1352]
## Expected Behavior

Example code as located in [packages/io/obj-deserializer](https://github.com/jscad/OpenJSCAD.org/tree/master/packages/io/obj-deserializer) should create an appropriate `geometries` data structure from an `OBJ` file.

## Actual Behavior

Example code creates an empty `geometries` data structure.

## Steps to Reproduce the Problem

  1. Download example OBJ file (attached as [gap.txt](https://github.com/user-attachments/files/16203629/gap.txt) but rename to `gap.obj` as GH doesn't allow a text file with extension `.obj` to be attached)
  2. Create example script by copying nearly verbatim from the example located [here](https://github.com/jscad/OpenJSCAD.org/tree/master/packages/io/obj-deserializer#usage):
```javascript
const fs = require("fs");
const objDeserializer = require('@jscad/obj-deserializer');
const rawData = fs.readFileSync('gap.obj');
const geometries = objDeserializer.deserialize(rawData, 'gap.obj', {output: 'geometry'});
console.log(geometries);
```
  3. Observe that `geomtries` is effectively empty:
```
//
// Produced by JSCAD IO Library : OBJ Deserializer (2.0.27)
// date: Sat Jul 13 2024 16:35:38 GMT-0400 (Eastern Daylight Time)
// source: obj
//
  const {primitives} = require('@jscad/modeling')

// groups: 0
// points: 0
const main = () => {
  // points are common to all geometries
  let points = [
  ]

  let geometries = [
  ]
  return geometries
}


module.exports = {main}
```

I believe this is an issue with input incorrectly specified to the `deserialize` method (maybe a vestige of an older version of the deserializer?). The following works:

```javascript
const fs = require("fs");
const objDeserializer = require('@jscad/obj-deserializer');
const rawData = fs.readFileSync('gap.obj');
const geometries = objDeserializer.deserialize({output: 'geometry'}, rawData.toString());
console.log(geometries);
```

With output looking more appropriate:

```
[
  {
    polygons: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object]
    ],
    transforms: [
      1, 0, 0, 0, 0, 1,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 1
    ]
  },
  {
    polygons: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object]
    ],
    transforms: [
      1, 0, 0, 0, 0, 1,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 1
    ]
  }
]
```

Further note that without the `.toString()` conversion, node complains with:

```
.../node_modules/@jscad/obj-deserializer/index.js:94
  const lines = data.split(/\n/)
                     ^
...
```

Attachment:

[gap.txt](https://github.com/user-attachments/files/16203629/gap.txt)

## Specifications

  - Version: npm package 2.0.27 ([src](https://github.com/jscad/OpenJSCAD.org/tree/master/packages/io/obj-deserializer))
  - Platform: Ubuntu 22.04.4 LTS
  - Environment: node.js (`v12.22.9`)

**Comment by z3dev** [comment]
@abetusk thanks for the detailed explanation.

definitely, the example is incorrect in the documentation. All serializers / deserializers have options as the first argument. So the documentation needs a fix.

feel free to make a change, and create a merge request.

**Comment by abetusk** [comment]
PR #1353 submitted.
