### ISSUE TITLE
smooth lighting

### ISSUE THREAD

**Issue by makc** [jscad/OpenJSCAD.org#137]
I am sure [you are aware](https://github.com/Spiritdude/OpenJSCAD.org/blob/adc37e44a6df1074581983a22be9f21cdc072ade/openjscad.js#L507) of smooth lighting problems. Well, I have been fixing them in the project that is basically private fork of your code. Although I cannot just copy the code over here, I can describe what I did. 1st, you have the bug [here](https://github.com/Spiritdude/OpenJSCAD.org/blob/adc37e44a6df1074581983a22be9f21cdc072ade/openjscad.js#L527) - it should check the color against colors[vertexindex], or else colors are interpolated. 2nd, you want to add different colors to CSG primitives' surfaces (such as cylinder top, bottom and side), and 3rd you want to make sure these colors are never the same, e g [here](https://github.com/Spiritdude/OpenJSCAD.org/blob/adc37e44a6df1074581983a22be9f21cdc072ade/openscad.js#L344) you set the same color for the whole surface, and that effectively merges all cut surfaces. I hacked around it by re-using existing "shared"-s on polygons, but you need to think of better solution to all this, and then you will have this kind of shading:

![screen shot 2016-02-24 at 23 54 20](https://cloud.githubusercontent.com/assets/242577/13330765/a37436ee-dbfa-11e5-9761-b778ede3629b.png)

**Comment by z3dev** [comment]
I wasn't aware of this as all. Interesting... The choice to use smoothing or not should be an Viewer.option as well.

We would love to have the bug fixes at least. Can you create a pull request for your changes? Please use the DEV branch when creating the pull request.

**Comment by kaosat-dev** [comment]
this is going to be added to the new version of the 3d viewer , coming soon

**Comment by z3dev** [comment]
Smooth lighting is the default for V2 rendering. Closing this issue.
