### ISSUE TITLE
AngularJs 1.x integration

### ISSUE THREAD

**Issue by themaniac** [jscad/OpenJSCAD.org#149]
Hello all,

someone tried to integrate openjscad with an angularjs project? i need to know if there's some documentation/plunkr example for this...

thanks in advance!

**Comment by z3dev** [comment]
Nope. Nothing.

**Comment by kaosat-dev** [comment]
Hi @themaniac there is nothing specific to the integration with various frameworks, and as far as I know there has not been anything going on on that end. 
The project has been using common.js modules for a while now, so you can pick & choose what you need these days from the npm modules (mostly :) ande will soon-ish have a simpler way to embed openjscad in browser only environments.
