### ISSUE TITLE
Uncaught TypeError: cag._toCSGWall is not a function

### ISSUE THREAD

**Issue by paddelkraft** [jscad/OpenJSCAD.org#158]
i get Error in line 5855: Uncaught TypeError: cag._toCSGWall is not a function

when i do

```
function main() {
   var c = circle(10).translate([-10,-10]);
   var cutOut = circle(1).translate([-1,-1]);//.translate([11,0]);
   return c.subtract(linear_extrude({ height: 20,twist: 720,  slices: 50}, cutOut.translate([10,0])));
}
```

**Comment by z3dev** [comment]
It looks like there's a mix of 2D (CAG) and 3D (CSG) objects. Work in 2D, then "extrude" to make 3D.

**Comment by z3dev** [comment]
Did that help?
I hope that you have enough information to continue.

**Comment by jeromew** [comment]
I got this error today after npm install and running the example on https://github.com/jscad/OpenJSCAD.org

```
const jscad = require('@jscad/openjscad')
const fs = require('fs')

var script = `function main() {
   return [
      torus()
  ]
}`

// generate compiled version
var params = {}
var compiled = jscad.compile(script, params)
// generate final output data, choosing your prefered format
var outputData = jscad.generateOutput('stlb', compiled)

// hurray ,we can now write an stl file from our OpenJsCad script!
fs.writeFileSync('torus.stl', outputData.asBuffer())

```

I don't know if this is a bug or a problem with the given example.

**Comment by jeromew** [comment]
It seems the example is broken because compiled is a Promise, so it cannot be used directly in generateOutput

**Comment by kaosat-dev** [comment]
@jeromew my bad, the example was from a previous API and I forgot to update it! 
Thanks for reporting this!
Could you please open a specific PR for this ? (as it is not related to the issue above)

**Comment by jeromew** [comment]
ok. done with https://github.com/jscad/OpenJSCAD.org/pull/278

**Comment by kaosat-dev** [comment]
thanks ! Merged

**Comment by kaosat-dev** [comment]
closing this as the original issue was specific to the script, feel free to reopen if needed
