### ISSUE TITLE
Does OpenJSCAD support the surface() in OpenSCAD?

### ISSUE THREAD

**Issue by michaeledi** [jscad/OpenJSCAD.org#164]
Just wondering, cuz image processing is a bright spot in OpenSCAD, I wonder if it's possible to transplant it into the OpenJSCAD too?

**Comment by z3dev** [comment]
@michaeledi thanks for the information

OpenSCAD.org allows raster image (PNG) import for surfaces. Is this what you mean?

OpenJSCAD supports the import of SVG images. You can try it, just drag and drop an SVG file to the webpage. You might find that some imports don't work. If you want to convert raster images to an SVG images then you will have to use another applications. www.z3d.jp has a tool for tracing the outlines of images, which is on-line.

**Comment by jtoy** [comment]
is this still an issue? if not, we should close it.

**Comment by z3dev** [comment]
It’s an issue until fixed.

**Comment by z3dev** [comment]
@michaeledi Here's the fix.

https://github.com/jscad-community/jscad-surface
