### ISSUE TITLE
Union speed and result depend on order of operands

### ISSUE THREAD

**Issue by szivgy** [jscad/OpenJSCAD.org#181]
Hi!
I run my script on openjscad.org and I got different results and speed if I change order of operands.
It is a bug?

Best Regards,
SzivGy

function radian(degree)
{
    return (Math.PI/180)_degree;
}
function full_thread(ttn,st,sn,zt,lfxy,or,ir)
{
  var o=[];
    for(var i=0;i<ttn;i++)
    {
        for(var j=0;j<sn;j++)
        {  
        o.push( polyhedron({points:
         [  [0,                  0,                  i_st-st            ],
                        [ir_Math.cos(j_lfxy),     ir_Math.sin(j_lfxy),     i_st+j_zt-st       ],
                        [ir_Math.cos((j+1)_lfxy), ir_Math.sin((j+1)_lfxy), i_st+(j+1)_zt-st   ],
                                [0,0,i_st],
                        [or_Math.cos(j_lfxy),     or_Math.sin(j_lfxy),     i_st+j_zt-st/2     ],
                        [or_Math.cos((j+1)_lfxy), or_Math.sin((j+1)_lfxy), i_st+(j+1)_zt-st/2 ],
                        [ir_Math.cos(j_lfxy),     ir_Math.sin(j_lfxy),     i_st+j_zt          ],
                        [ir_Math.cos((j+1)_lfxy), ir_Math.sin((j+1)_lfxy), i_st+(j+1)_zt      ],
                        [0,                  0,                  i_st+st            ]]  ,

```
                  triangles:[   [1,0,3],[1,3,6],[6,3,8],[1,6,4], //changed triangles to faces (to be deprecated)
                                        [0,1,2],[1,4,2],[2,4,5],[5,4,6],[5,6,7],[7,6,8],
                                        [7,8,3],[0,2,3],[3,2,7],[7,2,5] ]})
    );
    }

}
```

return o;
}
//correct result
function main()
{
var od=8;
var st=2;
var lf0=45;
var lt=5;
var rs=0.5;
var cs=2;

var or=od/2;
var ir=or-st/2_Math.cos(radian(lf0))/Math.sin(radian(lf0));
var pf=2_Math.PI*or;
var sn=floor(pf/rs);
var lfxy= radian(360/sn);
var ttn=round(lt/st+1);
var zt=st/sn;
return union(

cylinder({r: 10, h: 5, center: false}),
full_thread(ttn,st,sn,zt,lfxy,or,ir)
);
}

//bad result
function main()
{
var od=8;
var st=2;
var lf0=45;
var lt=5;
var rs=0.5;
var cs=2;

var or=od/2;
var ir=or-st/2_Math.cos(radian(lf0))/Math.sin(radian(lf0));
var pf=2_Math.PI*or;
var sn=floor(pf/rs);
var lfxy= radian(360/sn);
var ttn=round(lt/st+1);
var zt=st/sn;
return union(
full_thread(ttn,st,sn,zt,lfxy,or,ir),
cylinder({r: 10, h: 5, center: false})
);
}

**Comment by z3dev** [comment]
@szivgy thanks for the details of this issue.

OpenJSCAD is based on Javascript so the performance is dependent on the browser. I'm certain that 3D operations will take computing resources, and certain that the order of operations is important.

I'd like to use this for performance testing but I'm not sure improvements are possible.

**Comment by z3dev** [comment]
@szivgy Closing this issue as various performance improvements have been made as part of V2. Please try the latest, and open a new issue if there are still performance issues.
