### ISSUE TITLE
Offline browser version

### ISSUE THREAD

**Issue by Perrazoo** [jscad/OpenJSCAD.org#196]
Hi, I've made installation steps in order to get offline version working, with no success.

`% git clone https://github.com/Spiritdude/OpenJSCAD.org`
`% cd OpenJSCAD.org`
`% make install`

When I try to drag&drop come jscad file to the browser, I'm getting always `File Error: [EncodingError] Please check permissions` error. 

I've tried to give all possible permissions to whole folder but not working. Any ideas?

Thanks in advance.

**Comment by z3dev** [comment]
@Perrazoo Welcome!

That's a issue with Chrome. Correct?

**Comment by Perrazoo** [comment]
Hi! Thanks for quick reply!

Yes! It happens with Chrome, I haven't notice till you said. Any idea?

Congrats for great development!

**Comment by z3dev** [comment]
I'm going to re-open this as there is some missing documentation about this option on the User Guide.

Thanks for the feed back.

**Comment by TommyK82** [comment]
Hi,

I am very new to all this and openjSCAD is really interesting ...

But I dont really understand how to install it offline ....  is this supposed to be written in node.js command line?

Many thanks


% git clone https://github.com/Spiritdude/OpenJSCAD.org
% cd OpenJSCAD.org
% make install

**Comment by jtoy** [comment]
is this still an issue?

**Comment by z3dev** [comment]
Yes. Until Google fixes the bug.
