### ISSUE TITLE
OpenJSCAD command line hangs 

### ISSUE THREAD

**Issue by mrsimicsak** [jscad/OpenJSCAD.org#197]
When running OpenJSCAD from the command line, either with or without a .jscad file to process, it hangs with no output until terminated.

Remove the the `--log_all` at the end of line 1 of `openjscad` and OpenJSCAD behaves as expected.

OpenJSCAD version:
`~/OpenJSCAD.org$ git show`
commit ea91305cf486c88553e03962514c996a9c1c39ef
Merge: 8269eff 1b94f54
Author: Z3 Development <z3-dev@gfnews.net>
Date:   Sun Sep 11 11:08:52 2016 +0900

    Merge pull request #171 from fischman/patch-1
    
    Unbreak intersection() & difference() for CAGs.

node version:
`~/OpenJSCAD.org$ node -v
v7.0.0
`

ubuntu version:
`~/OpenJSCAD.org$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty`

**Comment by z3dev** [comment]
@mrsimicsak I believe there are issues when running with NODEJS 7+

We are coming out with a new release, which has awesome support for NODEJS. It would be good to have some feedback on this. Stay tuned...

**Comment by kaosat-dev** [comment]
@mrsimicsak could you please try it again with our latest release from npm ? This should have been fixed (at least 100% in node.js 7.x.x, need to check in node.js 8.x.x)

**Comment by kaosat-dev** [comment]
assuming this works, based on our recent tests, and no reply, please re-open if needed  @mrsimicsak
