### ISSUE TITLE
Enhancement: Fallback rendering for older devices

### ISSUE THREAD

**Issue by jallwine** [jscad/OpenJSCAD.org#206]
Older devices can't run WebGL so it'd be nice to be able to fallback to software rendering. three.js has this, so using it instead of lightgl could be one way of achieving this.

**Comment by z3dev** [comment]
Possibly. But why go back? It takes a lot of effort to develop and test anything, so why make this harder with devices that cannot run WebGL, which has been around since 2013.

How far back should support go?

**Comment by kaosat-dev** [comment]
I have to agree with @z3dev , webgl support is really widespread these days (including on mobile).
Also having worked a fair bit with the THREE.js canvasRenderer (the fallback renderer), it can be quite annoying to get right for some edge cases.
That said, I think with some of the code reorganization going on, you could potentially make custom versions of OpenJscad with custom renderers etc

**Comment by z3dev** [comment]
FYI, a three.js based viewer is coming. So, we can revisit this with that developer. ;)

**Comment by kaosat-dev** [comment]
I am going to close this , as this is not planned as part of the officially supported features. But of course a custom pure software renderer without webgl is entirely possible (geometric data structures are simple enough), but not worth the time sorry !
