### ISSUE TITLE
Move repostitories(Openjscad, CSG.js , openscad translator) to a Github Organization

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#213]
**Problem**
Right now we are facing a few headaches because of the dependencies between packages, forks of forks , outdated or not maintained repos that we depend upon , lack of node.js packaging for some of them etc

**Proposal**

1.  Move / ask the authors to move these repostories to a common Organization : https://github.com/jscad
   The list of packages should be : 
       - OpenJSCAD.org (this package, which itself uses a number of other packages in the list)
       - CSG.js (currently up to date version maintained by @joostn resides at https://github.com/joostn/OpenJsCad/blob/gh-pages/src/csg.js 
       - openscad-openjscad-translator by @garyhodgson 

2. Make sure that all of these modules are useable in all these environments:
     - browser 
     - node.js (+ Browserify for the above)

All of this would reduce headaches, make common work easier , PR's easier, avoid 'dead forks', and allow all these projects to move forward faster & better .

Would love to hear what everybody (especially @spiritdude, @z3dev, @dav-m85, @mtippett)  thinks, and if I have missed something, please post here !

**Comment by joostn** [comment]
I think this would be great. We also have the OpenJsCad organization (https://github.com/OpenJsCad) set up by Stefan (@bebbi) a while ago. @z3dev you asked a while ago to be transfered ownership, apologies for not replying - you can use this organization name if you want. (I think @bebbi you would agree too?)

Whatever the name, I'd be happy to transfer joostn-csg.js to the organization, there are no active maintainers currently and I don't have the time.

**Comment by kaosat-dev** [comment]
Thanks for chiming in @joostn ! Glad you like the idea !
We ( @z3dev  & I ) actually wondered who had registered that org :)

joostn-csg.js: that would be this one right ? https://github.com/evanw/csg.js
I just split out the more up to date version of csg.js from your openjscad repo to https://github.com/jscad/csg.js, does that make more sense (from the list of commits /contribs etc) ?

Personally, either org name is fine, even if favor the shorter one (as it seems it was already used by some people publishing openjscad extensions on NPM under scad-utils , scad-xx names, but that is another topic)

**Comment by dav-m85** [comment]
Proposal +1. I p. prefer the shorter jscad org name, faster to type when
npm requiring.

**Comment by bebbi** [comment]
yes of course, if that's still required.
btw for a project starting afresh I'd go with webpack.

**Comment by joostn** [comment]
@kaosat-dev: no, not evanw's, this is the one:
https://github.com/joostn/OpenJsCad/blob/gh-pages/src/csg.js

This was forked in 2012 from evanw's version, beacause he wanted to keep his version clean and simple (see: https://github.com/evanw/csg.js/pull/6)

@Spiritdude then forked my version of csg.js a few years ago, he built the nice gui and added the global namespace operators. The two forks ran out of sync (partly my fault because I kept committing to my own repo) but they were synchronized later by bebbi and others.

Looks like they are running out of sync again which is bad, so please go ahead and host the master copy of CSG.js and formats.js in your organization. When I find the time I'll change http://joostn.github.io/OpenJsCad/ to use your copy as a subrepository. Spiritdude/OpenJSCAD.org should do the same.

**Comment by kaosat-dev** [comment]
@dav-m85 you read my mind :)

@bebbi thanks !

@joostn whoops ! my bad, I copy pasted the wrong link (blame it on my excess of tabs & lack of coffee).
I of course used yours as a basis since that is the one with the most recent set of commits , and also contributions by @z3dev  etc :)

I agree with your points, keeping things in sync is good ! This would also be a good occasion to  add unit tests (a few are already on it ) etc, and avoid the general confusions around the forks.

(btw I have following things for a while since I also forked your version of OpenJscad a few years ago to create CoffeeScad ;)

**Comment by joostn** [comment]
Ah yes of course, you know all history. Sorry for missing that!

**Comment by kaosat-dev** [comment]
@joostn  no worries !

**Comment by mtippett** [comment]
@kaosat-dev That works for me, arguably I am more interested in formats, blobs and csg than openscad/openjscad.

My quick and dirty dependency diagram would look something like...

![mtp-test](https://cloud.githubusercontent.com/assets/3933678/21744753/a5f2ad7c-d4d0-11e6-8163-2a222ae9525f.png)

**Comment by mtippett** [comment]
An update.  I moved my personal code to https://github.com/jscad/csg.js, and it worked fine.  I'll try to see what to do about the format output.

**Comment by kaosat-dev** [comment]
Also pinging you @garyhodgson for the translator, this is the 'move I mentioned' : would you be ok with transfering it ? :)

**Comment by garyhodgson** [comment]
Hi.  Sure no problem. I thought it was no longer necessary as you have a fork in the jscad org already.  

I just tried to transfer the project and got the following message: "jscad/openscad-openjscad-translator already exists and You don’t have the permission to create repositories on jscad"  

Open to suggestions 😺

**Comment by kaosat-dev** [comment]
@garyhodgson you can now transfer it, I removed the fork :)
thanks for merging the PR too !

**Comment by kaosat-dev** [comment]
thanks @garyhodgson  :)

**Comment by apla** [comment]
I'm the current maintainer of the [atom-scad-preview](https://github.com/matiasinsaurralde/atom-scad-preview) package which is really handy to edit and preview models side by side. I would like to see somewhere repository with already created basic models such as nuts, bearings and so on. Seems like jscad github org is a perfect place for that repo.

**Comment by kaosat-dev** [comment]
@apla that would be a good idea, for the most 'standard' of parts , I think it would be a very good idea we could reuse / collaborate with http://www.bolts-library.org/en/index.html since there are a TON of standardized measurements (I used to use those regularly with CoffeeScad)

**Comment by jonnor** [comment]
I see the that https://www.npmjs.com/package/@jscad/csg was moved out. However no PR to make OpenJSCAD use this yet? Will this work happen in this repo?

**Comment by jonnor** [comment]
Another piece I one could consider splitting out (probably after the initial pieces here are done) is the 3d-view widget. I think that would be useful in other places that use CSG.js also

**Comment by dav-m85** [comment]
Hi @jonnor, you may want to check the [dev branch](https://github.com/Spiritdude/OpenJSCAD.org/blob/dev/package.json) where the csg move out is actually happening. I don't know when it is planned to be merged into master, it is however under active development.

Totally agree on the 3d-view widget.

**Comment by kaosat-dev** [comment]
@jonnor & @dav-m85 as @dav-m85  said, most of the work is done in the dev branch, the main thing remaning before master is 
- dealing with the messy drag & drop code : I am currently working on it although a bit slow, because day job:)
- spliting out all the formats handling (https://github.com/Spiritdude/OpenJSCAD.org/tree/dev/src/io) , although that might have to wait until after the next release of Openjscad / merge into master

As far as the 3D view widget goes : I will be honest, while it makes sense to have it 'swappable' /split out,  the quality of the code there is really not up to the level of the rest (Ie, no seperation of concerns between view/ camera controls/event handling),  messy structure etc :)

**Comment by kaosat-dev** [comment]
This is all done, closing !
