### ISSUE TITLE
Reporting OpenGL library files when it fails to load

### ISSUE THREAD

**Issue by ghpenguin** [jscad/OpenJSCAD.org#225]
Hi, 

It shows WebGL error and empty 3D window. 
I had to spend few hours to reinstall the missing OpenGL shared library files in Devuan Linux. :(

**Comment by z3dev** [comment]
@ghpenguin  Welcome! You may be the only Devian Linux user in the group. :)

We have a couple of other "installation" notes to add to the documentation. Can you provide details on what steps were taken?
