### ISSUE TITLE
implement 3d convex hull

### ISSUE THREAD

**Issue by jallwine** [jscad/OpenJSCAD.org#226]
I needed hull to do OpenSCAD's full 3D convex hull so I integrated [quickhull3d](https://github.com/maurizzzio/quickhull3d) into my [fork of OpenJSCAD](https://github.com/AllwineDesigns/OpenJSCAD.org/commit/2757a87c4baca2348cdb7112421aefdea9e03946). I'm jammed for time right now, but I'll try to loop back and get a decent pull request together. 

Here's briefly what I did:

- I used browserify to package up quickhull3d and included it as hull3d.js
- I added hull3d.js to the list of included libraries when running the jscad worker
- I modified the hull function to check if any arguments aren't CAG objects and, if so, do a 3D hull operation

**Comment by nbrookins** [comment]
I'd be interested in helping here if possible, or at least getting my hands on what you've done so far.  I'm rewriting a big project (finger prosthetic) to openjscad and lack of hull has become a blocker.

**Comment by jallwine** [comment]
It's been a while since I looked at where OpenJSCAD development is. It shouldn't be too difficult to integrate what I've done, but I haven't had a chance to look into all the changes that have been made since I forked the project, so I haven't done it myself. The info above should get you going, and my fork is there for you to look at and test. It would be a huge help if you could get that quickhull implementation into the main branch!

**Comment by z3dev** [comment]
With V2, the API will move to a functional approach, so please refrain from adding functions to CSG prototypes. Thanks for the help.

**Comment by nbrookins** [comment]
@z3dev , what is your suggestion on where to start and how to approach integrating this (3d hull)?  I know javascript and functional methodology but haven't yet looked much at this codebase.  A quick pointer could go a long way.  Thanks!

**Comment by kaosat-dev** [comment]
@nbrookins the premises (still VERY early wip ) of V2 can be found here 
https://github.com/jscad/csg.js/tree/V2
to get a better grasp of what we are shooting for you can take a look  for example  at 
- https://github.com/jscad/csg.js/tree/V2/src/core/math/vec3 (or vec2 , mat4) 
- https://github.com/jscad/csg.js/tree/V2/src/core/geometry/shape2 etc
- https://github.com/jscad/csg.js/blob/V2/BREAKING-CHANGES.md for an overview of concrete changes
- https://github.com/jscad/csg.js/blob/V2/V2Brainstorm.md for more wild ones

a short version is : each operation (like hull as well) should be 
- a small specific module doing one thing only but do it "well " :)
- api should follow the params first, data (shapes) second (for future curry-ability like Ramda)
all other things we more than gladly respond to specific questions the best we can

**Comment by hg42** [comment]
LOL, shape3/hull.js is the place for V2 (I accidently checked out V2 instead of master).
In V1 it is still in op-transformations.
Perhaps I should switch to V2 now?

**Comment by z3dev** [comment]
Hulling of 3D geometries is now available in V2. Please try V2.

**Comment by positron96** [comment]
Good to know that, I just stumbled upon lack of 3D hull when manually converting scad to jscad (got kinda disappointed). When is V2 expected to hit openjscad.org?

**Comment by z3dev** [comment]
We are asking for some early adopters now. So, if you really want to contribute then please try V2.

https://openjscad.org/dokuwiki/doku.php?id=early_v2
https://openjscad.org/dokuwiki/doku.php?id=changes_v2

**Comment by z3dev** [comment]
@jallwine V2 now has hull for 3D geometry. Can I close this issue?

**Comment by jallwine** [comment]
Sure, sounds great. I haven't had a chance to try it out, but I'll try to sometime soon.

**Comment by z3dev** [comment]
@jallwine thanks

**Comment by hg42** [comment]
thanks
