### ISSUE TITLE
Makefile has hardcoded sudo install locations conflicting with Homebrew, etc.

### ISSUE THREAD

**Issue by andrewgho** [jscad/OpenJSCAD.org#227]
The `make install` command from the Makefile has a couple idiosyncrasies:

* The `openjscad` program is installed into hardcoded `/usr/local/bin`, which, on OS X boxes using Homebrew, is controlled by Homebrew; and is also a common directory for other managed systems (including corporate managed boxes).
* The `install` and `deinstall` commands have `sudo` hardcoded into them. This is highly irregular and somewhat dangerous (users should `sudo make install` or `sudo make deinstall` if they want to run with elevated privileges, like they would most other open source distributions—the Makefile shouldn't do it for them).

I'll submit a pull request with fixes for these.

**Comment by kaosat-dev** [comment]
@andrewgho  thanks for the input! the makefile will actually not be useful much longer: install & uninstall will be done like any other npm package via npm install xxx etc (no need for sudo anymore), please see the changes in the dev branch for more clarity on this : the makefile is still there but is more or less obsolete except for a few edge cases.

https://github.com/Spiritdude/OpenJSCAD.org/blob/dev/package.json

**Comment by kaosat-dev** [comment]
I am closing this , as the makefile is fully obsolete and those paths are not used anymore, thanks for the PR back then @andrewgho :)
