### ISSUE TITLE
Does color()  work on 3D primitives only?

### ISSUE THREAD

**Issue by ghpenguin** [jscad/OpenJSCAD.org#233]
Hi, 

https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide#Colors 

I experienced run-time error when I applied color() or setColor() on a square object. After I change square object to cube, the error disappeared.  I think the documentation should explain which objects work.

**Comment by z3dev** [comment]
@ghpenguin That's correct. 2D colors are not supported today. Colors are only supported for 3D objects.

**Comment by z3dev** [comment]
@ghpenguin this is available in V2. Colors are supported for all,geometries, including 2D geometries and 2D paths. Please try V2.
