### ISSUE TITLE
Where are the basic view alignment functions? 

### ISSUE THREAD

**Issue by ghpenguin** [jscad/OpenJSCAD.org#235]
Hi, 

I'm in transition to OpenJSCAD. 
OpenSCAD has basic view alignment functions: Right, Top, Bottom, Front, and Back. I use these features whenever I design mechanical parts that require precise positioning.

I found OpenJSCAD doesn't have them or are there built-in hotkeys already?

**Comment by z3dev** [comment]
@ghpenguin Those hot keys (function keys) do not exist. The only key stroke that adjusts the view is the RESET-VIEW key.

We would welcome any suggestions on implementation, but remember that there are various browsers, etc.

**Comment by kaosat-dev** [comment]
this really would be a good addition, I think we can tackle it once the 3D viewer & its controls have has been updated @ghpenguin

**Comment by z3dev** [comment]
A general review of the "hot" keys would be good. Some of the key strokes need to change based on the browser, due to menu hot keys, etc.

**Comment by kaosat-dev** [comment]
a basic version of this will be present in the new 3D viewer, to be integrated very soon

**Comment by z3dev** [comment]
@ghpenguin this functionality is not available on the www.jscad.xyz website. please try this out, and close this issue if satisfied.

**Comment by z3dev** [comment]
No reply from @ghpenguin 

Closing
