### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by mdelmans** [jscad/OpenJSCAD.org#251]
Hi guys,
Nice product.

I have problems with reload on Mac 10.12 + Safari 10.0. I can load a file by drag n drop, but auto reload nor reload works: when I modify and save the file, nothing happens (even when I press reload). So I have to drag n drop file every time I save. I tried Google Chrome / Chromium, there drag n drop doesn't load the file at all.

Any thoughts ? Which browser do you fully support at the moment ?

**Comment by z3dev** [comment]
@mdelmans I test with OSX using Chrome, Firefox, Safari, and Opera.

It depends if you load index.html from a web server, or load from a file. The behavior is very different.

**Comment by mdelmans** [comment]
Ok, pardon my ignorance. I've been just loading index.html in browser.

How do I start local web server that would serve OpenJSCAD.org ?

Btw. Reload doesn't work for me at https://openjscad.org as well. Is that expected ?

**Comment by z3dev** [comment]
PHP and Python have built in web servers, which can serve the contents of the current directory.

Here's how for PHP:
  http://php.net/manual/en/features.commandline.webserver.php

I'll check the OpenJSCAD.org website. It's should be reloading...

Thanks again

**Comment by mdelmans** [comment]
Ok. Got it. Thanks.

**Comment by kaosat-dev** [comment]
closing as this seems to be solved. Please reopen if needed.
