### ISSUE TITLE
Remaining items for 1.0.0 release

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#252]
- [x] ditch cli & module build (i.e. move relevant code to common.js modules, remove rollup ) to avoid confusion and issues
- [x] do the same for scad-api
-  [x] merge fix for master
-  [x] tag OpenJSCAD master
- [x] move open IO issues to jscad/IO
- [x] final manual checks & fixes if needed 
-  [x] increase version numbers of ALL packages (IO not included, sub packages are already updated)
-  [x] move OpenJSCAD repo (this one) to jscad organization (Github supports redirects so there will be no breaking issues normally)
- [x] release !

**Comment by z3dev** [comment]
Please add "move open IO issues" to jscad/IO

**Comment by kaosat-dev** [comment]
All done, closing
