### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by berserk82** [jscad/OpenJSCAD.org#256]
Does OpenJsCad require anything but a webserver to run or does it rely on something? (eg node, frameworks, etc.)
And I also wish to know, which of these features are supported?
drawing units
draw lines/ellipses/elliptical arc/rectangles/polygon/polyline/spline/donuts/points
erasing objects
layers
translate/rotate/scale objects
adding text
filling with hatches/patterns/gradients/textures
referencing objects
printing and plotting
importing and exporting geometry

Thanks in advance for any help.

Bye, Ivano.

**Comment by z3dev** [comment]
@berserk82 Welcome

OpenJSCAD.org is the website UI, which runs in browsers such as Safari, Firefox, Chrome. You can run online at www.openjscad.org or use your own webserver to host the pages.

You can also open index.html directly. However, there are limitations when opening files, which come from browser security "features".

I suggest that you try some of the examples that come with OpenJSCAD.org. That should provide some idea as to what is and what is not available.

These are not available
- drawing units
- erasing or referencing objects
- text rendering
- textures/gradients/textures/etc
- printing / plotting (but browsers can print what's being viewed)

**Comment by berserk82** [comment]
Thanks a lot.

**Comment by z3dev** [comment]
Full text rendering is being talked about now. This may be implemented in the next couple of releases.

**Comment by berserk82** [comment]
Ok, what about the rest?

**Comment by kaosat-dev** [comment]
@berserk82 there is no 'official' list of planned features : this is an open source project, everyone contributes to the best of their time/ability/needs :) 
If you want to contribute the features you need the most, please do , a lot of people are grateful for any new features & improvements
