### ISSUE TITLE
Multi-path polygons not supported

### ISSUE THREAD

**Issue by stuartpb** [jscad/OpenJSCAD.org#26]
(according to the [User Guide](https://github.com/Spiritdude/OpenJSCAD.org/wiki/User-Guide))

I would greatly appreciate this feature, as it would allow drawing text using the same method as [Spiff.scad](https://github.com/stuartpb/Spiff.scad).

**Comment by kaosat-dev** [comment]
hi @stuartpb  I know this has been years, but could you explain what you mean by multi-path polygons ?

**Comment by stuartpb** [comment]
See https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide#Polygon:

```js
polygon({ points: [ [0,0],[3,0],[3,3],[0,6] ], paths: [ [0,1,2],[1,2,3] ] }); // multiple paths not yet implemented
```

A two-dimensional vector for paths specifies shapes to _subtract_ from the initial path. See [the documentation for OpenSCAD's polygon function](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_the_2D_Subsystem#polygon).

**Comment by kaosat-dev** [comment]
ok thanks for clarifying !

**Comment by z3dev** [comment]
@stuartpb sorry but this functionality will not be part of V2. We are breaking from SCAD for many reasons. I think this functionality can be reproduced by simple boolean operations.

If you still want this functionality then you will need to write a special ‘polygon’ function.

**Comment by stuartpb** [comment]
That's reasonable: the documentation notes that successive polygons are just difference()d, and I've never seen a case where OpenSCAD's "lists of indexes into a flat list of points" model makes more sense for 2D polygons than multiple lists of points would.

**Comment by z3dev** [comment]
Thanks.
