### ISSUE TITLE
Export not solid

### ISSUE THREAD

**Issue by Jip-Hop** [jscad/OpenJSCAD.org#265]
When converting a working OpenSCAD file like so: `openjscad working_openscad.scad -o broken_jscad.jscad` the STL export from OpenJSCAD is not solid.

Inspecting in Blender shows `non-manifold edges: 11947` and `bad contig. edges: 2`. The original OpenSCAD model exports correctly to STL and is solid.

OpenSCAD and OpenJSCAD files in zip, together with output STL files: [conversion_test.zip](https://github.com/jscad/OpenJSCAD.org/files/1011666/conversion_test.zip).

**Comment by z3dev** [comment]
@Jip-Hop Thanks for the files. All examples will help us to eliminate this pesky bug.

For reference, there are similar issues raised here; https://github.com/jscad/io/issues

**Comment by kaosat-dev** [comment]
hi @Jip-Hop 
very likely the same issue as this one : jscad/csg.js#47
Perhaps try the fix mentionned there :

> So I simply called the fixTJunctions() method just before the STL generation and it fixed my problem in slic3r.

**Comment by kaosat-dev** [comment]
this should now be fixed from version 1.0.4 onward.
If you still have issues, please reopen.
