### ISSUE TITLE
Open File Button?

### ISSUE THREAD

**Issue by hurzl** [jscad/OpenJSCAD.org#271]
I have no drag-and-drop. I need an Open File Button.

**Comment by z3dev** [comment]
@hobofan Thanks for the very terse information.

Is this on a mobile device or tablet?

**Comment by hurzl** [comment]
> @hobofan 
 
other issue?

**Comment by z3dev** [comment]
Sorry. That question was meant for you, @hurzl 

What device are you using?

**Comment by hurzl** [comment]
Why, I use seamonkey

**Comment by z3dev** [comment]
Very interesting indeed. On what OS?

I'll give this a try on my MAC.

**Comment by hurzl** [comment]
> I'll give this a try on my MAC.

So do you have an Open File button?

**Comment by z3dev** [comment]
Actually, yes. But the button is "shown" when there the browser does not have the standard drag and drop functionality.

**Comment by hurzl** [comment]
Ok but I don't want to open a file browser just for loading a file

**Comment by deckar01** [comment]
Although I am using Chrome on a Mac, I prefer opening the browser's file dialog. Would the fix for this be to remove the drag/drop functionality check and always show the button?

**Comment by kaosat-dev** [comment]
@deckar01 the main problem is, it is a lot less trivial and more constrained than drag & drop:
I just added the file dialog in addition to drag & drop (both always on) for the upcoming V2 version, and the file dialog is seriously horrid:
- you can either set the file button to load files OR folders not both (I do not even know how to work around that one)
- you cannot re-read the contents of a file once opened unlike drag & drop so it is not possible to poll for changes, which makes it very limited
- some browsers do not give correct list of files

we can still add it , but honestly that is so limited that it borders on unuseable ... if you have other solutions, please let us know I would love to have it more feature rich

**Comment by deckar01** [comment]
I did not realize how powerful the drag and drop API was. I didn't see any documentation about dropped files syncing or how multiple jscad files are supposed to be structured. I understand the desire to hide the button since it might seem like the primary UX and lead users away from those nicer features.

Explaining these features in the documentation might help "sell" users on the slightly more inconvenient UX. The link in the drop area doesn't seem to lead to any information about the feature it is referencing.

https://openjscad.org/dokuwiki/doku.php

**Comment by z3dev** [comment]
@deckar01 thanks for the good discussion thread. 

FYI, you (as a member of GitHub) can login and update the documentation. :)

**Comment by deckar01** [comment]
> Self-Registration is currently disabled or conf/users.auth.php is not writable. Please ask your DokuWiki administrator to create your account manually.

**Comment by z3dev** [comment]
:) Login with other Services has a button for GitHub. Please try. We would appreciate an updates to the documentation.

**Comment by deckar01** [comment]
That was the message I get when I tried to use the "Login with other Services" "GitHub" button. Sorry for not being specific. Happy to help once I get registered. I couldn't find a "DokuWiki administrator" point of contact, so I came back here, sorry to hijack the thread.

**Comment by z3dev** [comment]
I just tried with Chrome, and entered user name and password. No issues.

Try this then... Login into GitHub. Follow the link to the User Guide again. Click on Log in. Click on black GitHub button. You should be logged in now.

**Comment by deckar01** [comment]
I followed those steps on a different device/browser/connection and got the same error message I originally posted. Is there contact info for the wiki admin I am missing?

**Comment by kaosat-dev** [comment]
@hurzl you can also simple create a PR here and add the information to the docs :) (less hassle, universal ;) )

**Comment by z3dev** [comment]
Hmmm... I will try with a new GitHub account.

(I’m the administrator.)

**Comment by z3dev** [comment]
The V2 JSCAD WEB UI now has a 'Load JSCAD project' button, which allows the selection of a project folder from the native file manager. Although, this does not allow a single file to be selected, the single file can be placed inside a folder, just be sure the name is 'index.js' or 'index.jscad'.

www.jscad.xyz

**Comment by z3dev** [comment]
The V2 WEB UI has the ability to load projects from a selected directory, so I’m closing this issue. Please open new issues against after trying the V2 WEB UI at www.jscad.xyz
