### ISSUE TITLE
Is Blocks coding mode in the programe? I found a similar windows App appstore with Blocks coding

### ISSUE THREAD

**Issue by shytears** [jscad/OpenJSCAD.org#273]
![image](https://cloud.githubusercontent.com/assets/23303695/26450933/5c15f622-418c-11e7-9b2e-29112b7ec0b3.png)

**Comment by kaosat-dev** [comment]
Hello @shytears , no, OpenJSCAD does not currently support blocks coding, but I have seen multiple projects adding it on top of the current system.
Out of curiosity do you have a link to the app above in the windows app store please ?

**Comment by z3dev** [comment]
See https://github.com/EinsteinsWorkshop/BlocksCAD

**Comment by shytears** [comment]
@kaosat-dev here is the website of the app.
https://www.microsoft.com/en-us/store/p/openjscad/9nblggh6j6j9
totally it is based on visiting of the www.openjscad.org, and adding blocks coding mode in the interface. 
@z3dev the app i mentioned, is different to blockscad. First it has blocks with all commands,including 2d curve command. Second its based on www.openjscad.org

**Comment by z3dev** [comment]
Michael is a member of the User group. You can contact him there.

I don't think the APP is maintained anymore, but you can ask him.

**Comment by z3dev** [comment]
Here's website that hosts BlocksCAD.

https://blockscad.einsteinsworkshop.com/
