### ISSUE TITLE
V1: Auto reload of SCAD files does not work

### ISSUE THREAD

**Issue by Kenzu** [jscad/OpenJSCAD.org#279]
Hey

When I use auto reload in chrome or firefox it reloads every 2 seconds or something like that.
Why does it not reload on file change only?

Thanks

**Comment by z3dev** [comment]
@Kenzu welcome

The auto load should occur when the file changes.
Does your editor save periodically?

**Comment by Kenzu** [comment]
It happens even before I open the file in my editor. I use Gedit on Debian Stretch.


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.4.59&pv=7.0&source=email_footer_2] On Sun, Jun 25, 2017 at 12:40am, Z3 Development < notifications@github.com [notifications@github.com] > wrote:
@Kenzu [https://github.com/kenzu] welcome

The auto load should occur when the file changes.
Does your editor save periodically?

**Comment by Kenzu** [comment]
Firefox ESR 52.2.0 and Chrome 59


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.4.59&pv=7.0&source=email_footer_2] On Sun, Jun 25, 2017 at 9:58am, Mark Moissette < notifications@github.com [notifications@github.com] > wrote:
Very strange!
What browser & browser version are you using ?

**Comment by Kenzu** [comment]
It's on Ext4 filesystem on a ssd disk.


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.4.59&pv=7.0&source=email_footer_2] On Sun, Jun 25, 2017 at 9:58am, Mark Moissette < notifications@github.com [notifications@github.com] > wrote:
Very strange!
What browser & browser version are you using ?

**Comment by Kenzu** [comment]
I made a small video of the problem. Is it maybe because i write in SCAD style and not JSCAD?
https://plus.google.com/photos/photo/101171137569571196735/6435574209034978914

**Comment by Kenzu** [comment]
Okay, the problem is only with scad code that needs to render/convert. If i test with jscad file and code, auto reload works on file change.

**Comment by kaosat-dev** [comment]
Ah ok, based on the video, that makes it clearer, I am still surprised it is an issue, given how autoreload works, but I will take a look at fixing it.

**Comment by z3dev** [comment]
@Kenzu sorry, but there’s not much hope of fixing this issue. Support for SCAD files has been dropped in V2 JSCAD.

there is some hope as another developer has been making some changes to the SCAD deserializer.
