### ISSUE TITLE
Proposal: Interactive debugger

### ISSUE THREAD

**Issue by jleppert** [jscad/OpenJSCAD.org#280]
For my more complicated designs, I find it hard to debug (at least in the UI) when there's a runtime exception. There's no information on where the actual error occurred, no ability to actually inspect values or the stack. I resort to having to use the CSG primitives/OpenSCAD API and the node debugger, which works, but it would be nice to support debugging directly in the UI. Even have an intelligible stack trace would be helpful.

This would also allow you to step through other people's designs to better understand how they are working.

Maybe by a simple implementation of continuations? I'd be willing to give it a shot if I have some more time..

http://jlongster.com/Whats-in-a-Continuation

**Comment by z3dev** [comment]
@jleppert thanks for this really cool information

I'm still digesting the article but have a question.

At what level do you think this would be beneficial? There are many libraries involved to openjscad.org.

**Comment by jleppert** [comment]
If you can control the actual debugger, you don't need to descend into library code. i.e. the same way that chrome doesn't jump down into native code for Array.map...of course there could still be exceptions in those libraries, but the main benefit would be to step through the higher-level CSG code, inspect objects, etc...

**Comment by z3dev** [comment]
I like the idea but I have to warn you.... the processor and viewer classes are not designed well. In addition the processor evaluates scripts in worker threads.

By the way, I'm available for chats via Hangouts

**Comment by jleppert** [comment]
No worries, I'll give it a shot. Love your project and want to contribute

**Comment by z3dev** [comment]
Super!
Let me know if you need to chat about thhings.

**Comment by z3dev** [comment]
@jleppert So... it's been a long time. Did you discover any cool insights? Or issues?

**Comment by z3dev** [comment]
@jleppert You might be interested in this small project. With this, the debugging of designs can be completed within a browser.

https://github.com/danmarshall/jscad-now

**Comment by z3dev** [comment]
@jleppert please reopen if still interested but basically this functionality is best left to the built in debuggers of the browsers or IDE tools.
