### ISSUE TITLE
Output STL not sliced correctly in Slic3r Prusa3D Edition

### ISSUE THREAD

**Issue by udif** [jscad/OpenJSCAD.org#284]
It seems that almost all (if not all) the models I prepare with OpenJSCAD do not slice correctly using Slic3r Prusa3D edition.
It may or may not slice under other software as well, but this is the only slicing software I've tried.

Here is a simple example:
https://www.openjscad.org/#https://raw.githubusercontent.com/udif/openjscad-objects/master/flexgrid.jscad
Loadging the STL generated by this object in Slicer and inspecting it will show you some strange triangles on the bottom. This is more clear when you slice it and look at the layers.
I also see issues when I load the STL in Windows 10's 3D Builder. It will load the object but warns that it needs to be fixed. Once I fix it and save the modified STL, it will slice just find in Slic3r.

Due to this, passing the STL through 3D Builder is now part of my flow :-(

**Comment by z3dev** [comment]
@udif thanks for the information

There's a known issue in the STL export function, which is not trivial to solve. Hopefully, we will have time to work on this, but until then continue to "clean" or "fix" all STL files.

**Comment by kaosat-dev** [comment]
@udif  very likely the same issue as this one : https://github.com/jscad/csg.js/issues/47
Perhaps try the fix mentionned there : 

> So I simply called the fixTJunctions() method just before the STL generation and it fixed my problem in slic3r.

**Comment by kaosat-dev** [comment]
this is now fixed in the latest patch release ( `1.0.4`): it is not yet available in the online version, but you can already try a local copy if you want.

**Comment by kaosat-dev** [comment]
closing since this is now deployed (from 1.0.4 onward)
