### ISSUE TITLE
Enhancement: add file upload button 

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#288]
Basically, the JavaScript detects that the browser is running on a mobile device (not easy), and then adds a file load button.
Oh, I see!

I think it would be very handy to also have a simple file upload button on desktop.
I know some people who don't actually have a graphical file browser installed, and in my opinion the drag-and-drop solution adds some unnecessary steps to the process - after all, I still have to navigate to the jscad file regardless of whether I'm doing so in nautilus/explorer/finder or in the browser's "upload file" popup.

**Comment by kaosat-dev** [comment]
@z3dev did you mean 'loadFile' rather than upload ?

**Comment by z3dev** [comment]
Correct. This is just a simple request for a button, rather then drag and drop. Seems some of the non-mainstream browsers don’t have drag and drop.

**Comment by z3dev** [comment]
The loading of 'projects' is possible in V2 of the WEB UI, via a button.
