### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by Kevin-Prichard** [jscad/OpenJSCAD.org#294]
I love OpenJSCAD, but it doesn't take long to discover that it's easy to lose all your work.

F5 rerenders the model, but only when focused in the code editor (maybe some other areas).

F5 also reloads the page -destroying any changes to code editor- when focused elsewhere.

Autosave should be trivial to implement, with a checkbox to select, or maybe "Number of Minutes between saves" input field.

**Comment by kaosat-dev** [comment]
Hi @Kevin-Prichard  !
Thanks for the feedback , and agreed !
There will be a interface redesign and upgrade in the next few months, so I'll try to add that even before that.
Btw about the re-render : perhaps favor using SHIFT + ENTER over F5, less dangerous

**Comment by z3dev** [comment]
@Kevin-Prichard are you using Firefox?

**Comment by z3dev** [comment]
@Kevin-Prichard thanks
A set of recent changes to V2 JSCAD add functionality to prevent navigating away from the website. This should prevent a lot of pain for many users.
Please keep,those suggestions coming!

**Comment by z3dev** [comment]
@Kevin-Prichard please try www.jscad.xyz as the V2 JSCAD 'alpha' has been released to this website. and hopefully, this issue has been resolved.

**Comment by z3dev** [comment]
www.jscad.xyz

SHIFT-RETURN is the default for recompile / rerender. Also, tryouts night to move away from the page will pop up a dialogue to confirm.

Closing this as this is not an issue with V2.
