### ISSUE TITLE
Share Online Designs: filename is undefined

### ISSUE THREAD

**Issue by sevkin** [jscad/OpenJSCAD.org#295]
from openjscad user guide
![share_online_designs-sample](https://user-images.githubusercontent.com/18633/31332366-d0e18192-acee-11e7-9e2c-ae64c1bc24f6.png)
1, 4 - work ok
2, 3 - cant work with message
![openscad_share-online-designs_bug](https://user-images.githubusercontent.com/18633/31332403-ef7ca794-acee-11e7-9f59-54bdb0e208be.png)

**Comment by z3dev** [comment]
Thanks. I'll look at that but I'm guessing that a recent security patch disabled some functionality.

**Comment by kaosat-dev** [comment]
@sevkin  thanks, we will look into it !
@z3dev  do you mean your recent fix for the .pl ? That is not possible since it is not yet deployed :)

**Comment by z3dev** [comment]
Actually, I think that the patch was deployed. I will double check.

**Comment by z3dev** [comment]
V2 JSCAD (www.jscad.org) can handle now handle all V2 supported formats via proxy URLs. 👍 

AMF
https://www.jscad.xyz#https://www.thingiverse.com/download:8726126
DXF
https://www.jscad.xyz#https://www.thingiverse.com/download:8705163
JS
https://www.jscad.xyz#https://www.thingiverse.com/download:8705160
JSCAD
https://www.jscad.xyz#https://www.thingiverse.com/download:8705161
OBJ
https://www.jscad.xyz#https://cdn.thingiverse.com/assets/32/b1/a6/20/08/cube.obj
SCAD
SVG
https://www.jscad.xyz#https://www.thingiverse.com/download:8726127
STL
https://www.jscad.xyz#https://cdn.thingiverse.com/assets/3c/8f/bb/06/78/multiple_objects.stl

**Comment by z3dev** [comment]
@sevkin This has been fixed... I believe. Please try the examples again. If fixed then please close this issue.

https://www.openjscad.org/#https://www.thingiverse.com/download:8726126
