### ISSUE TITLE
rotate in the infinite loop

### ISSUE THREAD

**Issue by drom** [jscad/OpenJSCAD.org#297]
I have trouble using rotate method. The website goes into infinite loop with the following code:

```js
const main = () =>
    cylinder({r: 1, h: 10})
        .union(
            cylinder({r: 1, h: 10})
            .rotate([10, 10, 10])
        )
```

**Comment by kaosat-dev** [comment]
@drom the current API for the rotate `method` is very weird 
https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide#Rotate
We intend to do a major overhaul / cleanup soon, in the meantime I recommend the functional approach, more future proof

```javascript 
const main = () =>
    union(
       cylinder({r: 1, h: 10}),
       rotate([10, 10, 10], cylinder({r: 1, h: 10}))
   )
```

**Comment by drom** [comment]
Thank you @kaosat-dev . Functional API does look better and it works.
Please use the case above for error checking of the future API.
About the future functional API. Have you considered even more pure functional approach with currying?

```js
const main = () =>
    union
        (cylinder({r: 1, h: 10}))
        (rotate([10, 10, 10])
            (cylinder({r: 1, h: 10}))
        )
   )
```

**Comment by kaosat-dev** [comment]
haha @drom I **love** Ramda & other curryable, functional tools !
One thing for sure is , I would really like to have at least all main Openjscad api methods curryable.
Not sure how/what/when though, as a lot [of the internals](https://github.com/jscad/csg.js/issues/55) make this harder.

Ideally it would be good to put all breaking API changes in a single upgrade to not discourage people from migrating , but there is a lot to do before that !

**Comment by drom** [comment]
I still new to me, but I have started using more functional, curryable, immutable API this year, I am getting it step by step. Most of the people use to more traditional APIs. JS allows you to do both = good thing.
Have you seen https://github.com/fantasyland/fantasy-land ?

**Comment by kaosat-dev** [comment]
That is great, functional is so much clean fun !

I have heard of fantasy-land , seen mentioned a lot in fp discussions but never looked at it in more details , will try that thanks!

**Comment by kaosat-dev** [comment]
closing this issue if you do not mind @drom  as it is was due to wrong input for the given method :)
