### ISSUE TITLE
Extrude shape along a 3D path

### ISSUE THREAD

**Issue by drom** [jscad/OpenJSCAD.org#298]
I am building coil like 3D object.

<img width="407" alt="screenshot_20171014_092824" src="https://user-images.githubusercontent.com/511872/31577420-fc6887e8-b0c2-11e7-9c47-1eccd551b250.png">

The best solution I found so far is `union` of rotated `cylinders` (see the code below), but:
  * it leaves the gaps between segments
  * it is slow

Wouldn't it be nice to have some sort of `extrude_along_the_path` API to do the trick?

```js
'use strict';

const mag = vec => Math.sqrt(
    vec.reduce((res, e) => res + Math.pow(e, 2), 0));

const rotx = vec => -Math.atan2(
    Math.sqrt(Math.pow(vec[0], 2) + Math.pow(vec[1], 2)),
    vec[2]
  ) * 180 / Math.PI;

const rotz = vec => -Math.atan2(vec[0], vec[1]) * 180 / Math.PI;

const wireSegment = (pos, vec) =>
    translate(pos,
        rotate([rotx(vec), 0, rotz(vec)],
            cylinder({r: .5, h: mag(vec), fn: 8})
        )
    );

const turnPattern = [
    [ 0, 2,  10], [ .5, .1,  1 ], [ .5, .1,  .5], [ 1 , .1, .5 ],
    [ 6, 1,   0], [ 1,  .1, -.5], [ .5, .1, -.5], [ .5, .1, -1 ],
    [ 0, 2, -10], [-.5, .1, -1 ], [-.5, .1, -.5], [-1,  .1, -.5],
    [-6, 1,   0], [-1,  .1,  .5], [-.5, .1,  .5], [-.5, .1,  1 ]
];

const genTurns = (nTurns, pattern) => {
    const patternLength = pattern.length;
    const fullTurns = nTurns | 0;
    const tailTurns = (nTurns - fullTurns) * patternLength;
    let res = [];
    for (let i = 0; i < fullTurns; i++) {
        res = res.concat(pattern);
    }
    for (let i = 0; i < tailTurns; i++) {
        res = res.concat([pattern[i]]);
    }
    return res;
};

const coil = nTurns => {
    const turns = genTurns(nTurns, turnPattern);
    const res = turns.reduce((res, turn, i) => {
        const {root, pos} = res;
        return {
            root: root.union(wireSegment(pos, turn)),
            pos: pos.map((e, i) => e + turn[i])
        };
    }, {
        root: {union: el => el},
        pos: [0, 0, 0]
    });
    return res.root.setColor([1, .3, .1]);
};

const main = () => coil(5 + 9/16);
```

**Comment by kaosat-dev** [comment]
Hi @drom !
There is something like that in the works :) I hope to get it done by the end of next week.
in the meantime , you can , with a bit of hacking around get close by using `solidFromSlices`

**Comment by kaosat-dev** [comment]
Side note : I really like your coding style of small specialized functions, if you can help out, it would be awesome :)

**Comment by drom** [comment]
@kaosat-dev thank you, I will try `solidFromSlices` and will test new API once available.

I would love to help with the project. I am new to solid geometry but using JS instead of some DSL language over OpenSCAD like approach is really powerful idea.

**Comment by kaosat-dev** [comment]
@drom I hope you do not mind, I created a copy of this here https://github.com/jscad/csg.js/issues/68 as it is part of the 'core' features (csg.js)
