### ISSUE TITLE
Rotate extrude error

### ISSUE THREAD

**Issue by runezor** [jscad/OpenJSCAD.org#301]
Running the following function inside min.js:
`
document.getElementById('execute3D').onclick = function(){
        var source=design;
        gProcessor.setStatus('Processing ' + design + " <img id=busy src='imgs/busy.gif'>");
        gProcessor.setJsCad(source, design); }`

With source being this design:
`function main() {
	return rotate_extrude( polygon({points:[ [0,0],[2,1],[1,2],[1,3],[3,4],[0,5] ]}) );
}`

Produces the result shown in the image
<img width="208" alt="rendererror" src="https://user-images.githubusercontent.com/17691976/31911715-dc48c262-b841-11e7-8eaf-369e46e6c3c2.png">

**Comment by runezor** [comment]
Actually, even running it by transferring the file onto the standard index.html produces the same result.

**Comment by z3dev** [comment]
@richievos thanks good news.

Do you know what the core issue was?

**Comment by runezor** [comment]
I can only guess
If it's any help, the failed installation happened when I copied and pasted
my files, and the succesful one happened by simply transferring the folder
inside the zip file.

Den 25. okt. 2017 2.07 AM skrev "Z3 Development" <notifications@github.com>:
