### ISSUE TITLE
Zooming is too fast on Apple trackpad

### ISSUE THREAD

**Issue by alexose** [jscad/OpenJSCAD.org#302]
Hi OpenJSCAD,

It's really hard to control the zoom action on my Macbook.  I've confirmed that this behavior doesn't occur on a non-apple machine-- It seems probable that this has to do with different sampling rates.

Other projects have encountered this problem as well.  See: https://github.com/darsain/sly/issues/67, https://github.com/Prinzhorn/skrollr/issues/278.

**Comment by kaosat-dev** [comment]
Hi @alexose !
I have an updated set of controls that should alleviate that, I will create PR soon, thanks for the links, very useful !

**Comment by alexose** [comment]
Thank you!  I look forward to it.
