### ISSUE TITLE
openjscad to explicit .stl file without -of says it's outputting stla but outputs stlb

### ISSUE THREAD

**Issue by donhatch** [jscad/OpenJSCAD.org#308]
The following invocation of the openjscad command falsely claims it's outputting ascii stl, when in fact it outputs binary stl:
  $ openjscad example001.jscad -o example001.stl;  file example001.stl
      converting example001.jscad -> example001.stl (STereoLithography, ASCII)
      example001.stl: data

In contrast, the following commands all speak the truth about what they are outputting:
  $ openjscad example001.jscad;  file example001.stl
      converting example001.jscad -> example001.stl (STereoLithography, ASCII)
      example001.stl: ASCII text
  $ openjscad example001.jscad -o example001.stl -of stla;  file example001.stl
      converting example001.jscad -> example001.stl (STereoLithography, ASCII)
      example001.stl: ASCII text
  $ openjscad example001.jscad -o example001.stl -of stlb;  file example001.stl
      converting example001.jscad -> example001.stl (STereoLithography, Binary)
      example001.stl: data

**Comment by kaosat-dev** [comment]
Thank you for the bug report @donhatch , I double checked, and that is indeed the case, I'll add a fix asap.
