### ISSUE TITLE
openjscad command can't read STL files

### ISSUE THREAD

**Issue by donhatch** [jscad/OpenJSCAD.org#310]
The manual https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide#Via_Command-Line claims that openjscad can read STL files from the command line:
> Additional you can import OpenSCAD (.scad), STL ASCII or Binary (.stl) and AMF (.amf) files, and create .jscad, .stl (ASCII or Binary), dxf or .amf:

and it gives the following example:
`% openjscad frog.stl -o frog2.stl             # does actually stl -> jscad -> stl (ascii)`

There is no frog.stl in the repo, but there's a frog-OwenCollins.stl, which seems to be valid (since, if I drag-and-drop it into the ui, a frog appears).  So I ran this instead:
`% openjscad frog-OwenCollins.stl -o frog2.stl`

but that fails with the following output:
```
converting frog-OwenCollins.stl -> frog2.stl (STereoLithography, ASCII)
SyntaxError: Invalid or unexpected token
    at createJscadFunction (/Users/donhatch/gitrepos/OpenJSCAD.org.pristine/dist/jscad/jscad-function.js:41:11)
    at /Users/donhatch/gitrepos/OpenJSCAD.org.pristine/dist/jscad/rebuildSolid.js:80:44
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

**Comment by kaosat-dev** [comment]
Hi @donhatch  , you are on a roll ! 
I can reproduce this error locally, good catch, will fix.

**Comment by kaosat-dev** [comment]
@donhatch please try the latest version, this is now fixed, and added tests to ensure no regressions, thanks for the feedback !
