### ISSUE TITLE
request: please make viewer menu open/close on click instead of hover

### ISSUE THREAD

**Issue by donhatch** [jscad/OpenJSCAD.org#316]
On the main website page, the viewer menu open/close on hover is clever, but I find it makes the page significantly less usable and less pleasant for me.

To enumerate my problems with it:
  - the menu opens frequently when I don't want it to
  - the menu closes frequently while I'm trying to read it
  - the menu opens-and-closes every time the mouse pointer crosses over it, which is useless and distracting
  - it's impossible to keep it open to read it while I am trying out the varous hotkeys it describes, or while I am comparing it with other documentation
  - it's impossible to keep the Examples submenu open while I select various examples and interact with some of them, or while I compare it with other documentation

How about changing it to an explicit open/close on click, just like the editor?
I've changed it to that in my local repo, and I am much happier.

**Comment by kaosat-dev** [comment]
Hi @donhatch , lots of good points !
I think:
- We would need to keep the initial 'default to open then close after a short while' behaviour to signify its presence
- add the explicit on click behaviour you mention

Btw , I am less than in love with the whole current UI, so there will likely be a major overhaul at some point in the future, even if that is not high on the list so far.

**Comment by donhatch** [comment]
Hi Mark, thanks for considering this.
Yes, retaining the initial 'default to open then close after a short while' sounds fine.

Clicking should probably cancel the initial timeout (so it doesn't automatically close after the user has explicitly opened it, which would be unfriendly).
