### ISSUE TITLE
request: standalone package to run as a native app

### ISSUE THREAD

**Issue by jtoy** [jscad/OpenJSCAD.org#317]
wrapped in something like electron some people can run it on their desktops as an electron app. is this something people wound find useful?

**Comment by z3dev** [comment]
There's an Atom plugin. Is that simular?

**Comment by kaosat-dev** [comment]
I am on the fence on this one because of the atom plugin but I think there is room for both. I had always planned to create an electron app for openjscad so ....I will ;-)

**Comment by z3dev** [comment]
@jtoy There seems to be interest here. Why don't you ask the User Group as well. It would be cool to see what others are thinking these days.

Open jscad.org needs to stay flexible and useable.

**Comment by jtoy** [comment]
ok I will ask around more

**Comment by kaosat-dev** [comment]
@jtoy I have started work on a prototype , and have done a poll in the community :  a great majority are also in favor of this, so expect it at some point in the not too distant future :)

**Comment by jtoy** [comment]
@z3dev is google+ the user group? shouldn't that be some kind of forum or email list?

@kaosat-dev great to hear! what are you doing? electron ?  Will the code be part of this repo or as a separate package?

**Comment by z3dev** [comment]
Correct. The user and development group are currently present on Google+

**Comment by kaosat-dev** [comment]
@jtoy  yes, using electron, not 100% sure where to put the code yet, perhaps it will be in another repo under the 'jscad umbrella' :) 
I have quite a few things working 
- [x] the basics of the viewer
- [x] loading current jscad files / examples
- [x] loading common.js / node module flavor jscad designs (the future)
- [x] auto reload/ file watching

Here are a few teaser images :)
<img width="1205" alt="screen shot 2017-12-11 at 21 19 02" src="https://user-images.githubusercontent.com/623281/33876928-2d01bd9c-df27-11e7-8929-4b1934074c90.png">

<img width="1199" alt="screen shot 2017-12-12 at 10 32 33" src="https://user-images.githubusercontent.com/623281/33877147-cdbc58f0-df27-11e7-86e0-2378524e83e0.png">

I still need to add & tweak a few stuff before I can put the code on Github
Not really sure if it even makes sense adding a code editor at this stage(it would en up being less good than any code editor out there)

**Comment by kaosat-dev** [comment]
@jtoy the first version of the jscad app has now been released (even if it is a pre pre alpha) : https://github.com/jscad/jscad-desktop
closing this ;)

**Comment by jtoy** [comment]
awesome, ill test it
