### ISSUE TITLE
union() with rotate_extrude object hanging  with infinite loop

### ISSUE THREAD

**Issue by jbodger** [jscad/OpenJSCAD.org#320]
## Expected Behavior
Union of the 2 objects

## Actual Behavior
If you union together an object created with rotate_extrude() with another object (cube and cylinder tried) the code hangs. The browser runs at high cpu and memory usage is high.

## Steps to Reproduce the Problem

Run the code below. If the final union is enabled the code hangs and the objects are not rendered. If the array of objects is returned you can see the objects. 

This has been run on the current openjscad.org and a local version of the dev branch with an apache server. 

Opera and firefox browsers have been used

I've added debug to the local code and it appears that the "do" loop in addPolygonTreeNodes() is never exiting for the object created with rotate_extrude()

function main() {
	var p, fuse, body;
	fuse = new CSG.Path2D([ 0, 0 ], false);
	fuse = fuse.appendBezier([ [ 20, 0 ], [ 40, 40 ], [ 20, 60 ] ]);
	fuse = fuse.appendPoint([ 0, 70 ]);
	fuse = fuse.close();
	// make the curve into a surface
	var area = fuse.innerToCAG();
	body = rotate_extrude(area);

	// intersecting cylinder or cube
	if (true) {
		p = cylinder({
			r : 10,
			h : 50
		});
		p = rotate([ 0, 90, 0 ], p);
		p = translate([ 0, 0, 20 ], p);
	} else {
		p = cube([ 10, 80, 10 ]);
		p = translate([ 0, 0, 20 ], p);
	}

	console.log("Doing union");

	if (true) {
		// this hangs
		p = body.union(p);
	} else {
		// this shows the shape
		p = [ body, p ];
	}
	console.log("Done union");
	return p;
}

**Comment by kaosat-dev** [comment]
Thanks a lot for the bug report @jbodger !
This is very good, and your workaround is also holding lots of information.
I believe, this is the same issue as this one  https://github.com/jscad/scad-api/issues/28 since they both use `rotate_extrude` under the hood and both result in infinite loops.

We will let you know once the issue is fixed.
