### ISSUE TITLE
Feature: add axis indicators to the 3d view

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#321]
## Expected Behavior
Being able to tell which way is +/- x/y/z axis.
It is very confusing to navigate the 3d view and do correct modelling without clearly indicated axis.
I will be adding this feature asap

## Actual Behavior
No indicator

## Steps to Reproduce the Problem
1 . start openjscad
2. see there is not axis indicator

## Specifications

  - Environment: browser

**Comment by z3dev** [comment]
Well... there is actually but you cannot see those easily. The axis lines have colors, and positive is the darker color. Not good.

By the way, please make this optional as well.

**Comment by kaosat-dev** [comment]
Wow ok , even now that you gave me this info , I still do not see it.
And yes, optional it will be.
Also in the new renderer ;)

**Comment by z3dev** [comment]
@kaosat-dev Have you seen the Autocad web viewer? It has a different way of showing the "orientation", using a little cube in the upper right hand corner. Each side of the cube has a name; left, right, front, back,etc. I kind of like it.

**Comment by kaosat-dev** [comment]
yep :) that is significantly harder to do  than simple axis indicators (I implemented such a thing once, not trivial) , so add that to 'some day at a later point' :)

**Comment by z3dev** [comment]
This is part of V2, so I'm closing this.

**Comment by JamesNewton** [comment]
For anyone who wants to stay on V1 or can't wait for V2 (while it's not out) here is a really crappy quick version of axis markers... just so someone else doesn't have to mess with it:

````js
function axis() {
    return union (
    color("red",cube([40,.1,.1],{center:true})), 
    text("X", 1).rotateZ(90).translate([42,-.7,0]),
    color("red",cube([.1,40,.1],{center:true})), 
    text("Y", 1).translate([-.5,41,0]),
    color("red",cube([.1,.1,40],{center:true})), 
    text("Z", 1).rotateX(90).translate([-.5,0,41])
    ,color("red",cube({center:true}))
    )
}
````
