### ISSUE TITLE
World center and Autorotate

### ISSUE THREAD

**Issue by loelkes** [jscad/OpenJSCAD.org#326]
It is a lot of code and I tried to figure it out myself but without success.

Question: the world center 0,0,0 is at the center of the viewer. I would like to shit it so that it is in the bottom left (for example). Moving the object is not an option, since i want the camera to move around it.

Question2: where in the code would I need to look if I want to add an z-axis-autorotate feature?

For both questions i would know how to do it with THREE.js but can't figure my way through this, sorry and thank you!

**Comment by kaosat-dev** [comment]
hi @loelkes !
Neither is trivial to do with the current 3D viewer, but in a week or so I will release a new , written from scratch 3D viewer (using [regl](https://github.com/regl-project/regl)) that will support
- centering the camera on any object/ point
- autorotate can be added trivially
- zoomToFit to focus on a given object and have the camera fit it inside the viewport etc

you can see it in action in a [preview video](https://www.youtube.com/watch?v=nJyede1Ah9k) for the upcoming Jscad desktop app : both the web & desktop version will use the same 3D viewer

**Comment by loelkes** [comment]
Oh, OK. Thanks for the update.
