### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#327]
## Expected Behavior
The language of the page is now only English. There are other languages in this world, and support for other languages would be very nice.

## Actual Behavior
The language of the page is now only English.

## Steps to Reproduce the Problem

  1. Set browser language to German
  2. Load the website
  3. Language of website is English

## Specifications

  - Version: Any
  - Platform: Any
  - Environment: Any browser

**Comment by kaosat-dev** [comment]
This is not too hard to do (did it a few times for various projects), but styling can be tricky. Very good idea either way !

**Comment by jtoy** [comment]
I can help with chinese translations

**Comment by kaosat-dev** [comment]
that is nice of you @jtoy ! very cool

**Comment by z3dev** [comment]
V2 now supports several languages in the WEB UI, so closing this issue.
