### ISSUE TITLE
Is possible to inject JS code into the jscad-container?

### ISSUE THREAD

**Issue by kevinmamaqi** [jscad/OpenJSCAD.org#329]
## Expected Behavior
Write several functions and load the one that I want into the jscad-container.

## Actual Behavior
I need to upload a .jscad file.

**Comment by z3dev** [comment]
@kevinmamaqi Hang in there!

It seems that you want to make a new website, using the libraries. Is this correct?

**Comment by z3dev** [comment]
@kevinmamaqi Cool project! I see what you want to do now by looking at the source of your site.

It looks like...
- create a webpage with several DIVs containing different information 
- one DIV is a JSCAD script
- the JSCAD script is reloaded periodically

Did I understand correctly?

**Comment by kevinmamaqi** [comment]
@z3dev yes, but I can not even load the initial JSCAD file.

**Comment by kaosat-dev** [comment]
can you explain a bit more what / you want to do things ? or what errors you are running into ?
is it as @z3dev  said, you have one div with the script, and you reuse the openjscad code for the rest ?

**Comment by z3dev** [comment]
The steps are fairly easy but takes some "changes". The website comes with several examples; index.js, min.js, opt.js. See the dist folder.

These are built from the library components by NPM, using...
- npm run build-web
- npm run build min
- npm run build opt

See src/ui/* for the base script for these "libraries".

I hope this provides a few hints at how to create your special "library".

Let us know if you still have issues. There are a lot of possibilities.

**Comment by kevinmamaqi** [comment]
Thanks @z3dev 

I understand what do you mean. but. I thought that index.js was ready to use in other website that incorporates the script. Am I right? and if not; How is it dependant on the src files from which was built?

**Comment by z3dev** [comment]
Take a little look at each of those files, index.js, min.js, opt.js. You will find different ways to "load" the JSCAD script. There is no single library because each HTML page does different things.

For example, viewer-minimal.html only loads a single design, which is provided by the options on the HTML DIV. If you see min.js then you will understand that drag-and-drop is not supported, options are not supported, menus are not supported, etc. This is a very small and compact "viewer" of a single design.

You have to decide what features to include, and NOT to include.

**Comment by kevinmamaqi** [comment]
Thanks again @z3dev still something is not clear to me.

1. I download OpenJSCAD via git clone, cd, npm run build-web and open index.html - result: I **can not load files**, I guess because it is not running in a server. *Is that correct?*

2. For my experiment I am using index.js (original) that contains most of the elements that I want to use and the following markup (see below) in my index.html. I already checked it out and I don't know which part are missing or giving an error. In `./ui/index.js` the expected elements from the html markup are conditionals, so if I don't use them should be an error.

```
<div id="viewerContext" design-url="./generative.jscad"></div>
<div id="tail">
  <div id="statusdiv"></div>
  <div id="filedropzone">
    <div id="filedropzone_empty">
    </div>
    <div id="filedropzone_input">
      <p>
        <label class="input-control">Add Supported Files: <input type="file" id="files-input" accept="*/*" multiple="1"></input></label>
      </p>
    </div>
    <div id="filedropzone_filled">
      <span id="currentfile">...</span>
      <div id="filebuttons">
        <button id="getstlbutton" onclick="getStl();">Get STL</button>
        <button id="reloadAllFiles">Reload</button>
       <!--button onclick="parseFile(gCurrentFile,true,false);">Debug (see below)</button-->
        <label for="autoreload">Auto Reload</label><input type="checkbox" name="autoreload" value="" id="autoreload"">
      </div>
    </div>
  </div>
</div>
```

**Comment by kaosat-dev** [comment]
@kevinmamaqi you cannot use ui/index or anything within `src`without using specific commands (ie npm run start dev , npm run build etc).
The prebuilt versions, as @z3dev  said so `dist/index.js , dist/min.js` etc should be the ones to use if you want to integrate into your website

**Comment by kevinmamaqi** [comment]
@kaosat-dev that is exactly what I am doing. I have:

```
<body>
  <mydivs></div> // code from my previous message
  <!-- Required for OpenJScad -->
  <link rel="stylesheet" href="./style.css" type="text/css">
  <link rel="stylesheet" href="./big.css" type="text/css">
  <script src="./index.js"></script>
</body>
```
And I can not load jscad files because it get the following message:

`Uncaught TypeError: Cannot read property 'setValue' of undefined Line: 87252,col: 13 (http://localhost:3000/index.js)`

And this error in the console:

```
Uncaught TypeError: Cannot read property 'setValue' of undefined
    at putSourceInEditor (test.js:87252)
    at onConversionDone (test.js:86919)
    at Worker.worker.onmessage (test.js:85337)
```

**Comment by kaosat-dev** [comment]
hmm ok not quite sure what is going on : 
is it in this  repo https://github.com/kevinmamaqi/TfCD_A2_Generative_Jar ? 
On first glance it would seem that it does not find the instance of the editor : 
https://github.com/jscad/OpenJSCAD.org/blob/a2125a9c8a6dc571e4d09e89e2f9bd0d7eacbcb9/src/ui/editor.js#L148

**Comment by z3dev** [comment]
Try adding one more DIV with the id="editor"
It may not look proper but this may solve your issue. You can hide the editor later using CSS.

**Comment by kevinmamaqi** [comment]
Thank you @z3dev it was the problem.

Although I find it impossible to:

Render the processor from node.js script. 
Load a . jscad code from my node script.

I tried to modify the examples and use the npm  as it is, but I find to much dependence between functions.

**Comment by z3dev** [comment]
Sorry that you are having so many issues.

Let's see if we can determin the solution by asking a few questions.
- can you provide an example of the JSCAD script?
- how will the script be loaded? As part of the HTML? As dynamic content from the web service? As a file?

**Comment by kevinmamaqi** [comment]
Hello @z3dev my full script is here: 
https://github.com/kevinmamaqi/TfCD_A2_Generative_Jar 

It is based on the jar-barrel example from openjscad. Although have a couple of modifications. The rotation and the scale are done randomly, using an uniform distribution each time, and the color is set by the data that I read from a sensor, here more info https://www.instructables.com/id/Generated-Jar-Generative-Design-TfCD/

To do so I have to pass these arguments as params everytime the user clicks on rebuild. So for the rotation/scale I have to :

1. Read the height from the user input (to determine number of slices) 
2. Send the data to the server to process it and generate the distribution.
3. Send data back to the browser and set it as a parameter that I hide from the user.
4. Create a button that executes the that.rebuild as is done by the processor function.

This was my last solution. Firstly I tried to just rewrite the jscad file and rebuild it, but it didn't take the new data. Then I saw the function rebuildfromworker() which I wasn't able to modify to use as I wanted. 

That's why I was asking how to inject the new (or modified code) directly from my node script, not using a Jscad file. I saw the example using regl but I wanted to use a couple of para so and the visual style of openjscad.

**Comment by z3dev** [comment]
@kevinmamaqi the scenario that you described looks a lot like a react based web application. Are you still interested? This should be possible now with V2 JSCAD.

**Comment by z3dev** [comment]
@kevinmamaqi it's been a long time. did you make any progress?

if you are still interested then there are some new reactive based frameworks that will help you get going faster.
- https://github.com/z3dev/vue-components

**Comment by z3dev** [comment]
@kevinmamaqi please reopen if there’s further desire to use JSCAD.
