### ISSUE TITLE
"CUSTOM" build script

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#330]
## Expected Behavior
Users are looking to create custom webpages which house JSCAD scripts, either static or dynamic. A method of creating the special composite "libraries" for these special websites would be beneficial.

User runs NPM command, which asks about required components, HTML layout, JSCAD script sources, etc. The script builds a "library" for use in the HTML page.

## Actual Behavior
Not available.

## Steps to Reproduce the Problem

  1. See history of raised issues.

## Specifications

  - Version: NEW
  - Platform: ALL
  - Environment: ALL

**Comment by kaosat-dev** [comment]
Yeah I agree something like this would be good, to make 'embedable' versions easilly.
What I think would help:
- seperate, reusable viewer
- reusable 'processor' / core
- reusable split out components (io, bla bla)

For now everything is still too tightly connected but we are on the right track

**Comment by z3dev** [comment]
@kaosat-dev thanks

I didn't know if this was tooooo far reaching or not.

**Comment by kaosat-dev** [comment]
@z3dev no I think it mostly is a question of exposing / reorganizing some of code in this repo.
I end up copy and pasting a lot of it for the jscad-desktop too, so it means candidates for re-use.
Not really sure at this stage how we would expose them: Ideally as node modules for nice composition.
But we would need to have something not-ui tighed to partially replace the messy 'processor' I think ...
(take this with a grain of salt)

**Comment by z3dev** [comment]
I think this his has been reached via V2 JSCAD.
Closing.
