### ISSUE TITLE
support in GUI  for ranges/steps in interactive params code

### ISSUE THREAD

**Issue by jtoy** [jscad/OpenJSCAD.org#332]
when people are playing with the interactive examples, sometimes they choose a number that wont fit properly for the generated model. I propose adding a start, stop , and step parameters to allow the GUI to generate valid values for the model. I made an example here: https://github.com/jtoy/cad_model_experiments/blob/master/gear.jscad#L10
I already use that file format for code that I work with.

**Comment by kaosat-dev** [comment]
Hi @jtoy there already is something like that in place :) you can specify
- min
- max
- step 
in your `getParameterDefinitions`
:)

**Comment by jtoy** [comment]
oh, that is great to know, I thought I tried this, I didn't see it in any of the examples and I tested it out in the GUI and it didnt seem to respect it. Is there an example script that shows this?

**Comment by kaosat-dev** [comment]
Yeah , I also tend to forget about these:), there is no example for this sadly, perhaps you could help out and add them to the gear example ;) ?

**Comment by jtoy** [comment]
ok, i will

**Comment by jtoy** [comment]
just made a pull request: https://github.com/jscad/OpenJSCAD.org/pull/333

**Comment by z3dev** [comment]
Discussed here just in case you need more information.

https://en.m.wikibooks.org/wiki/OpenJSCAD_User_Guide#Interactive_Parametric_Models

**Comment by kaosat-dev** [comment]
are you ok with closing this one @jtoy since it is resolved ?
