### ISSUE TITLE
1.4.0 website does not render object in Safari 11.0.3

### ISSUE THREAD

**Issue by johnwebbcole** [jscad/OpenJSCAD.org#334]
## Expected Behavior
Navigate to the website and see the default 3d logo.

## Actual Behavior
<img width="1078" alt="screen shot 2017-12-24 at 10 16 11 am" src="https://user-images.githubusercontent.com/230922/34327803-ae20ec7a-e893-11e7-80d8-9a67920d7187.png">

## Steps to Reproduce the Problem

  1.  Navigate to openjscad.org with Safari 11.0.3
## Specifications

  - Version: 1.4.0
  - Platform: MacOS 10.13.3
  - Environment: Safari

This works in iOS and in Chrome 63 on same OS version.  The canvas element exists and has the correct width and height.  Any ideas on narrowing down the issue?

**Comment by z3dev** [comment]
Strange indeed.
The examples are working with the latest Safari on iOS.

**Comment by kaosat-dev** [comment]
I have an older Safari (10.0.0) on a bit older MacOs, and all examples work fine : are you seing any errors in the console or just blank output ?

**Comment by z3dev** [comment]
I have MacOS 10.10.5 and Safari 10.1.2. Works just fine.

**Comment by johnwebbcole** [comment]
10.13.3 has hardware acceleration... and is beta (oops, didn’t think about that).

No errors and no console output. I’ll look into it further to see if there is some additional debug output in the system console.

I’ll also give the tech preview a go too.

**Comment by johnwebbcole** [comment]
Seems to be ok in Safari 12.0.2.

**Comment by kaosat-dev** [comment]
thanks !
