### ISSUE TITLE
Decouple mouse events from Viewer

### ISSUE THREAD

**Issue by danmarshall** [jscad/OpenJSCAD.org#336]
I know @kaosat-dev is working on a new Viewer, so I'm voting for a new feature :)
I'd like the mouse events to be decoupled from the Viewer, so that I can control the camera with other sensors. Here's a couple of ideas of how I'd like to control the camera:
* with the device accelerometer
* via scroll position
* via mousemove, without button

At the very least, it would be good to have an option to disable mouse listeners. Even better would be to decouple it so that the mouse event code is not in the JS for a Viewer.

**Comment by kaosat-dev** [comment]
Hi @danmarshall 
- I can see the point in various options, and the new viewer makes that rather trivial to add, either by piping in an observable with your custom data (https://github.com/jscad/csg-viewer/blob/master/src/cameraControlsActions.js) , or just using the viewer function directly https://github.com/jscad/csg-viewer/blob/master/example/demo.js#L52

However , even if I see the benefit of decoupling, In this case I think being able to disable the default mouse listeners is going to be the better option: I designed the viewer to be small and self contained, and easilly embedable into any site, but if I decouple the mouse events that means every user would have to add those , which is not ideal.
Compromises , compromises :)
Down the line, the viewer will likely be cut up into smaller reuseable components so you could make a custom version yourself , not sure how much better that is though.

**Comment by danmarshall** [comment]
That all that sounds reasonable to me, Mark 😃👍

**Comment by z3dev** [comment]
@danmarshall have you played with V2 yet? The rendering (regl-redemdered) does not have any event handling, only commands for setting content or adjusting camera views.

I also wrote a small VUE component using the regl-renderer as a library. Of course, I had to write the event handling, and convert into commands. It turned out pretty good, and I’ll continue to expand components.

From my perspective, this issue can be closed.

**Comment by danmarshall** [comment]
@z3dev I haven't seen where I can do it online. I went to jscad.xyz but it didn't seem to be functional. Where do people access v2 ?

**Comment by z3dev** [comment]
@danmarshall good news. V2 packages are published, and www.jscad.xyz now reflects the latest 'alpha' versions. please see the announcements on the user group.

**Comment by z3dev** [comment]
@danmarshall please try the new rendering engine; utils/regl-renderer

Also, the package now includes a web ready dist library. Hopefully, this can be used directly in various websites and frameworks.

**Comment by z3dev** [comment]
@danmarshall please take a look at these tutorials of this project.

https://github.com/z3dev/vue-components

I’ve been working on a set of tutorials that express the depth of what JSCAD provides. One of the strong points is the available rendering functions, which allow any kind of interaction.

**Comment by z3dev** [comment]
@danmarshall how about closing this issue now? i think you are convinced now.

**Comment by danmarshall** [comment]
Yes, thanks!
