### ISSUE TITLE
Why is not tree.js used again?

### ISSUE THREAD

**Issue by ignaciojuarez22** [jscad/OpenJSCAD.org#337]
I found some version where it was used and it works pretty well ...

Why is it no longer used?

**Comment by kaosat-dev** [comment]
Hi @ignaciojuarez22 : if you mean three.js , then it is most likely an alternative viewer using three.js :  which was never a part of OpenJSCAD: we do not intend to switch to three.js for the viewer : it will be using [regl](https://github.com/regl-project/regl) and the internal maths will be kept library independant.

**Comment by z3dev** [comment]
That’s correct. This project has never used Three.js
Is there some functionality that you need in the JSCAD viewer?

**Comment by kaosat-dev** [comment]
@ignaciojuarez22 I am closing this, do not hesitate to re-open if we have missed something :)
