### ISSUE TITLE
completely different output from browser vs CLI for interactive params example

### ISSUE THREAD

**Issue by jtoy** [jscad/OpenJSCAD.org#341]
## Expected Behavior
I tested generating STL files from a single interactive jscad example from both the browser and command line. The command line version generates garbage data:
openjscad models/testIssue/testIssue.jscad  --baseRadius 5  --baseHeight 40  --stageHeightRatio 0.6  --stageRadiusRatio 0.6  --noseHeight 10  --numberStages 2  -o cli.stl

https://cl.ly/3u1p1u0v0J1V

and the browser generates this one using the same params:
https://cl.ly/18190x0f3y3E
Here is a picture of what is expected: https://cl.ly/1l2X0N05330i

and here is the jscad file I use to test this with:
https://cl.ly/2M2Z452N3z0v

I tested this with 2 different computers (mac and linux) and with  different jscad files and get this issue. why is this happening? 

## Specifications

  - Version:  OpenJSCAD 1.4.0 [Darwin:14.5.0,darwin:x64]
  - Platform: mac 
  - Environment: browser, local server

**Comment by kaosat-dev** [comment]
Hi @jtoy  , very good catch :) thanks !
I will try out your script and investigate!

**Comment by jtoy** [comment]
this one really surprised me. Tried to dig in a bit, but didn't make it far.

**Comment by kaosat-dev** [comment]
Only source I see , is parameters not being correctly parsed/ parsed differently

**Comment by jtoy** [comment]
I tested this out by converting my script parameters that were floats to use all integers. It improves rendering, but still different from what is being generated from the GUI. How can this be possible? Any other issue ? Is CLI not a popular feature?

**Comment by kaosat-dev** [comment]
@jtoy I ran some tests, and I confirm that the parameters are ALL WRONG currently in the cli : with a simple debug, I can see that they all get converted to strings ouch !

**Comment by jtoy** [comment]
oh wow, that is kind of a big issue. Would the fix be as simple as converting these params to ints: https://github.com/jscad/OpenJSCAD.org/blob/master/src/cli/cli.js#L110-L115

**Comment by kaosat-dev** [comment]
Yeah this is a huge one. I started working on a fix.
And yes I guess the cli is not widely used.
Not even sure many people know there is one.
That might change soon, we also plan to have a seperate cli npm package dor ease of use.

**Comment by jtoy** [comment]
I think the CLI is a critical piece of the project. I was originally on openscad to do parametric design with code, but hated the non standard language. I love OpenJSCAD on the other hand because I can use a clean language with any libraries I want.  I'm generating 10's of thousands of different designs with the CLI.

**Comment by kaosat-dev** [comment]
wow that is quite impressive ! 
And yes, agreed it is very important that the CLI works reliably.
Given how the code was structured before It almost seems like it was an afterthought.
I should have a fix ready for this in a few hours :)

**Comment by kaosat-dev** [comment]
@jtoy , good news ! This image below is the resulting stl WITH the parameters passed to the CLI :) 
<img width="285" alt="screen shot 2018-01-05 at 20 43 49" src="https://user-images.githubusercontent.com/623281/34625536-562e9df8-f259-11e7-8e57-a44382bca3b3.png">

I need to add unit test(s) and I can push a PR with the fixes !

**Comment by jtoy** [comment]
awesome, so excited to test it out!

**Comment by kaosat-dev** [comment]
@jtoy what do you think the handling of 'choice' and 'checkbox/radio' parameters should be like in the CLI :  ie things like
`{
      name: 'mouseears', 
      type: 'choice',
      caption: 'Add mouse ears:',
      values: [0, 1],
      captions: ["No", "Yes"], 
      initial: 1
    },`
I think we can support both `--mousears 0` and `--mousears "yes"` ie re-using captions to map to the actual values, it seems more user friendly

**Comment by jtoy** [comment]
@kaosat-dev I personally think values as the programmer is already accustomed to them.  Captions also means more parsing.  As long as we make some clear documentation on it, I think either choice is ok.

**Comment by kaosat-dev** [comment]
@jtoy turns out there are some completely broken/ nonsensical things going on with some of the parameter handling in the GUI 
for 'choice' elements, all the values are returned as strings instead of the original format
so `{ name: 'mouseears', type: 'choice', caption: 'Add mouse ears:', values: [0, 1], captions: ["No", "Yes"], initial: 1 }` actually returns either "1" or "0" instead of 0 or 1.... which is just plain wrong sigh 
for now I will remove casting to the correct type on the CLI, and will add another issue to fix them both later ...

**Comment by z3dev** [comment]
Don’t get me wrong but basically the return type is whatever the HTML form type returns. So, don’t try to cast something unless the type is specified.

**Comment by kaosat-dev** [comment]
We cast a lot of the [inputs](https://github.com/jscad/OpenJSCAD.org/blob/master/src/core/getParamValues.js#L20) , and honestly , as a user If I specify possible values from a 'choice' to be [20, 40.7, 2] I expect to get those back, not some string , same for [false, true] or whatever :) 
Implementing casting based on the parameter definition values is trivial :)

**Comment by kaosat-dev** [comment]
The fix has now been released @jtoy , thanks for the feedback !

**Comment by jtoy** [comment]
@kaosat-dev awesome, thank you so much ! I want to showcase what I'm working on soon. im going to fix my pull request as well for the multijscad script as well in the  next couple of days.

**Comment by kaosat-dev** [comment]
@jtoy :) no problem ! Took a lot at your profile and projects on Github, very impressive stuff :) 
If you find some other / new issues or anything, please let us know !
