### ISSUE TITLE
Proposal : simple api for embeded version

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#344]
Given the difficulties currently to embed and configure OpenJSCAD I have following proposal for an upcoming version: 
A simple api to use for simple embeding : a single function, something like this

```javascript
// initialize
const initialOptions = {
  viewer : {camera:{xxx}},
  useBackgroundWorkers: true
}
const jscad = makeJscad(initialOptions)
// define your script
const yourSuperDesignScript = 'function main() { }'

// set parameters live , call this from callback/whatever
jscad({script: yourSuperDesignScript})
```

**Comment by z3dev** [comment]
I understand the need but have a few thoughts.

Can the viewer and processor be more decoupled? It seems that the major issues with imbedding are with the viewer, not the processor. The current model doesn’t expose the viewer so developers don’t understand how to set options, or properly embed the viewer (HTML divisions, styling, etc).

**Comment by kaosat-dev** [comment]
The new viewer is 100% decoupled: you just feed it csg/cag arrays, and some (optional) parameters.
The processor is not really decoupleable as it is , as it combines UI and logic.
There should be no need for complicated stuff, and even styling & such should be fire & forget :)

**Comment by z3dev** [comment]
Awesome. This will make the embedding tool easier as well.

**Comment by jtoy** [comment]
Is this so someone can embed a viewer for STL files in a web page? can someone explain the user cases more?

**Comment by z3dev** [comment]
@kaosat-dev can this be closed?

I think we could open new specific issues for anything else.

**Comment by kaosat-dev** [comment]
@z3dev sure !
closing now
