### ISSUE TITLE
Bring documentation/user guide into this repo as markdown 

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#346]
The user guide is out of date, unpractical (our edits take ages to be validated), it is time to bring things back here:
- in the form of markdown files
- simple 
- everybody can edit & help
- it can be made up to date easilly
- can be viewer offline
- can be embedded in the online version, the desktop app & cli

**Comment by z3dev** [comment]
Yeah. I’ve been thinking about this. Definitely need to move away from WIKIBOOKS.

I still think a full WIKI is best
- supports any kind of media
- table, sorts, references, etc
- themes and layouts
- anyone (maybe limit to G+ users) can edit
- revision controls

I’d be glad to set one up for trial.

I think the API can be generated and copied into the wiki as well.

https://www.dokuwiki.org/dokuwiki#
This is a really good WIKI. I use a lot for both business and development.

**Comment by kaosat-dev** [comment]
@z3dev I do not think it is mutually exclusive, but the main advantage of plain files is, it is *very* simple, no maintenance (and we are already stretched so thin :( ) and offline.

**Comment by z3dev** [comment]
I understand. The markdown is a must for the API documentation.

There’s a whole lot more that can be documented, such as cheat sheets, tutorials, etc.

Anyway, let’s try different things. The WIKI is available at
https://openjscad.org/dokuwiki/doku.php

The URL can be changed, as well as theme. I’ll add a few things to get started.
Users just register once, and start making changes.

**Comment by jtoy** [comment]
I would love to help write documentation, how can we start, do this?

**Comment by z3dev** [comment]
@jtoy Thanks!

Those BIG goals aren’t really achievable yet. I think first, we should bring back the user guide from WIKIBOOKS. I already imported the latest Quick Reference..

How about bringing back the User Guide? I suggest a few things:
 - Split the User Guide into pieces, and make small sections such as introduction, union, circle, etc.
 - Prefix the sections with user_guide

You should have access to the wiki already. 
https://openjscad.org/dokuwiki/doku.php

**Comment by z3dev** [comment]
By the way, other languages are possible.
