### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by delaneyj** [jscad/OpenJSCAD.org#350]
## Expected Behavior
Working Typescript definitions from `@types/openjscad`
```
import {CSG} from '@jscad/csg'
CSG.cube(
```
should autocomplete in VSCode.

## Actual Behavior
It appears the CSG class and namespace overlap.

## Steps to Reproduce the Problem
  - Version: Typescript 2.6
  - Platform: Win10

**Comment by kaosat-dev** [comment]
Hi @delaneyj !
A few things
- for the above (autocomplete in VSCode, I also use it), it should work as expected : 
<img width="516" alt="screen shot 2018-01-15 at 20 17 20" src="https://user-images.githubusercontent.com/623281/34958214-2c96779c-fa31-11e7-8e77-e87136c7f9e0.png">
- prefer using the functional API whenever possible, as that is more guarateed to stay intact going forward (for now still in scad-api, but going to be merged into @jscad/csg tonight)
 - for the Typescript definitions , this is unfortunately going to have to wait a bit : the internals of csg.js (where the types are defined) is a huge mess, we are in the process of cleaning up a lot of things, remove some classes etc in the process, and modifying a lot of things : also none of us really know Typescript to be honest :) would you be willing to help out with the definitions ?

**Comment by danmarshall** [comment]
Hi @delaneyj - I wrote the definition for `@types/openjscad` - by porting the code from js to ts.
The CSG class and namespace do overlap - because that's how OpenJscad is structured. It has classes within classes. TypeScript allows handling this by using a namespace.

I'm hesitating to rewrite the definitions while the new code is changing...

Thankfully - VsCode does a good job nowadays with pure js, as @kaosat-dev illustrates above.

**Comment by kaosat-dev** [comment]
@danmarshall  to the rescue :) Thanks for the useful infos & the definitions !
The CSG.xxx namespacing is very likely to go out of the window at some point soon (simplicity is the goal, so the api would be likely a LOT 'flatter' and less convoluted)

**Comment by delaneyj** [comment]
Wow, thanks for the quick responses.  Using require instead of import fixed my issue.  Would have to use a bit before feeling comfortable writing binding, especially with a moving target. Was trying to get jscad-desktop working.

**Comment by kaosat-dev** [comment]
that is interesting @delaneyj so it does work with require but not import ? that is strange, even if all of jscad is common.js modules, not sure why it would change the behaviour in vscode : are you using babel  ?

**Comment by delaneyj** [comment]
Was trying straight tsc

**Comment by kaosat-dev** [comment]
ah yes, doh'! my bad sorry
