### ISSUE TITLE
Missing offset 2d function

### ISSUE THREAD

**Issue by delaneyj** [jscad/OpenJSCAD.org#351]
## Expected Behavior
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#offset

## Actual Behavior
No matching function, no documentation on it being a missing feature, like minkowski.

**Comment by z3dev** [comment]
This shouldn't be difficult, and can be done via scaling the 2D object. I do this often.

The rounding of corners is a little more difficult but could be implemented with hull()

If you come up with a solution then please contribute.

**Comment by danmarshall** [comment]
Is this the same as https://github.com/jscad/csg.js/issues/75 ?

**Comment by delaneyj** [comment]
I'm not sure how that's implemented with scale. It's basically moving points along a normal. @danmarshall yes it appears to be the same underlying functionality

**Comment by scanlime** [comment]
fwiw, this is the main reason I'm passing over OpenJSCAD for a project it might otherwise be perfect for.

**Comment by danmarshall** [comment]
@scanlime @delaneyj you might want to take a look at [the expand() function in Maker.js](https://maker.js.org/docs/advanced-drawing/#Expanding%20paths). It is a slightly different paradigm.

You can then [export your drawing as a jscad CAG object](https://maker.js.org/docs/api/modules/makerjs.exporter.html#tojscadcag).

**Comment by z3dev** [comment]
Coming to V2

**Comment by z3dev** [comment]
offset() is now available in V2. Please try V2.

**Comment by delaneyj** [comment]
Thanks @z3dev
