### ISSUE TITLE
Hull primitive raises "Uncaught Error" when 3D primitives are provided.

### ISSUE THREAD

**Issue by feiteira** [jscad/OpenJSCAD.org#358]
## Expected Behavior
I'm trying to convert some code from OpenSCAD to JSCAD.
By mistake I used Hull with 3D primitives, which I now understand is unsuported.
A error message should e.g. "3D primitive while expecting 2D primitive"

## Actual Behavior
When using the "hull" primitive I get an "Uncaucht Error" message.
_Uncaught Error: Notification must be created with string message: [object Object]_

### Code 
```
function main() {
  return 	hull(
			cylinder({r:7/2, h:0.5}),
			cube({size: [7,7,0.5]}).translate([0,-7/2,0])
		) 
}
```

## Specifications
  - Platform: Windows 7
  - Environment: Atom plugin, atom-jscad 1.2.1

**Comment by feiteira** [comment]
I'm withdrawing this issue.
Using the webpage on OpenJSCAD.org I can see that this shows the proper message:
"Error: ERROR: hull() accepts only 2D forms / CAG"

**Comment by z3dev** [comment]
@feiteira thanks for posting back.

Hopefully, we will have 3D hull in the near future.
