### ISSUE TITLE
CLI cannot open OpenSCAD files

### ISSUE THREAD

**Issue by kristianbenoit** [jscad/OpenJSCAD.org#363]
## Expected Behavior
**Try** to open the SCAD file.

## Actual Behavior
OpenJSCAD report an error that the file is an invalid JSCAD file while it's an SCAD, I suppose it does not even try to load it as an SCAD file. Here's the error I get:
```
Error: The JSCAD script must return one or more CSG or CAG solids.
    at /usr/local/lib/node_modules/@jscad/openjscad/src/core/rebuildSolid.js:39:17
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

## Steps to Reproduce the Problem

  1. Create a symlink to `cli/cli.js` named `openjscad` and a variable named SCAD_FILE pointing to an SCAD file. ... It might have been done by node?
  2. On the command line run `openjscad $SCAD_FILE -o /dev/null`

## Specifications

  - Version: 1.4.0  & Web
  - Platform: Bash (from Ubuntu 17.10) & Web
  - Environment: The commandline version is installed from (node.js@v6.11.4) & the I tested the web version (https://openjscad.org/) with chromium.

**Comment by z3dev** [comment]
@kristianbenoit heres some information about using the CLI.

To use the CLI...
```
cd OpenJCAD.org/packages/cli
node ./cli.js example.js -of svg
```
This following design cannot be used as Node.js cannot look backwards from the current directory (for security reasons).
`node ./cli.js ../examples/testV2.js -of svg`

Please copy the designs to the current directory, or link designs to the current directory.
`cp -R ../examples .`
Or
`ln -s ../examples ./examples`
