### ISSUE TITLE
Enhancement:  provide ability to set global (world) background color of drawing workspace

### ISSUE THREAD

**Issue by cogito-clarus** [jscad/OpenJSCAD.org#364]
Most CAD systems have black as the drawing workspace background color to reduce eye strain and physical exhaustion from staring for hours at a rendered model - user should have a choice as to workspace background color.  If it's already a set-able system property somewhere, I can't find it, so it should at least be documented.

**Comment by kaosat-dev** [comment]
Hi @cogito-clarus do you mean something like  this ? ![this](https://github.com/jscad/jscad-desktop/raw/master/docs/jscad-desktop-dark.jpg)
In which case, it is already available in the desktop version, and coming soon to the web based version

**Comment by cogito-clarus** [comment]
Thank you - You brought a smile to my face this morning, that is awesome! That is exactly what I was talking about.  Normally I wouldn't ask, I'd contribute, but JS/ES/TS is not my strong suit in languages.

**Comment by z3dev** [comment]
Themes (light, dark, grass, ocean) are now available in the latest V2 branch.
