### ISSUE TITLE
sphere with cutouts exemple wait indefinitely

### ISSUE THREAD

**Issue by lautr3k** [jscad/OpenJSCAD.org#367]
## Expected Behavior
See the result of the example

## Actual Behavior
Wait indefinitely

## Steps to Reproduce the Problem

  1. Open https://openjscad.org/
  2. Load the sphere with cutouts exemple from the left panel

## Specifications

  - Version: Online
  - Platform: Win 10 - 64
  - Environment: Chrome 65.0.3325.181

**Comment by z3dev** [comment]
@lautr3k Thanks

Certainly looks like a regression. We will take a look as see if this can be fixed quickly.

**Comment by thehans** [comment]
Looks ok to me on current chrome release:
* Win 10 64
* Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by lautr3k** [comment]
@kaosat-dev fixed that a long time ago but did not close the issue ?

**Comment by z3dev** [comment]
Closing as this now seems fixed.
