### ISSUE TITLE
Import DXF error

### ISSUE THREAD

**Issue by yanwencheng** [jscad/OpenJSCAD.org#372]
Importing DXF format files is not rendered and reported wrong.

JS with random code

function main() {
  let layers = []
  return layers.concat(layer0(),layerDIM(),layerTABLE(),layer4(),layerÏßÉ«(),layer½Ó²å¼þ(),layer½Ó²å¼þB(),layer½Ó²å¼þÐÍºÅ(),layerTEXT(),layerÎÄ×Ö(),layerÏßÊø(),layerCAXA0(),layerCAXA3(),[])
}

**Comment by z3dev** [comment]
I would guess that the DXF file is using another “locale” other that English. If you can provide the DXF file then some fixes may be possible.

**Comment by yanwencheng** [comment]
@z3dev  Attachments cannot be uploaded because of unknown errors 。CAD contains Chinese characters

**Comment by z3dev** [comment]
Please rename the file to .txt
Then you can upload.

**Comment by yanwencheng** [comment]
@z3dev 
[123456.dxf.txt](https://github.com/jscad/OpenJSCAD.org/files/1922875/123456.dxf.txt)
[Drawing1.dxf.txt](https://github.com/jscad/OpenJSCAD.org/files/1922876/Drawing1.dxf.txt)

**Comment by z3dev** [comment]
@yanwencheng Thanks for the example files.

It looks like both files contain 2D designs with many **line segments**. The support for 2D line segments is not very good at this time. You will not be able to view these files. Probably, you will see 'Error: wrong arguments'

By the way, what application are you using to create the designs?

**Comment by z3dev** [comment]
V2 works much better, as lines are now rendered.

![3](https://user-images.githubusercontent.com/8969165/69209802-f7982080-0b9b-11ea-99ed-39d76e2503ef.png)

**Comment by gergul** [comment]
> V2 works much better, as lines are now rendered.
> 
> ![3](https://user-images.githubusercontent.com/8969165/69209802-f7982080-0b9b-11ea-99ed-39d76e2503ef.png)

Wow.This is good job. I want to import a dxf to jscad. But I do not know how to do it.Could u help me?Thanks.

**Comment by z3dev** [comment]
@gergul Thanks. We have been trying to improve everything in V2.

I will write a few notes on how to use V2. Please wait a few days.

**Comment by gergul** [comment]
> @gergul Thanks. We have been trying to improve everything in V2.
> 
> I will write a few notes on how to use V2. Please wait a few days.

waiting in hope.

**Comment by z3dev** [comment]
@gergul here’s the information on early adoption of V2. If you have time and can provide feedback then please join.

https://openjscad.org/dokuwiki/doku.php?id=early_v2

Let us know how things go!

**Comment by z3dev** [comment]
@gergul V2 website is now available at www.jscad.xyz
You can drag and drop DXF files to the web page.

Please close this issue.
If you have any new issues then please open a new issue.
Thanks again for using JSCAD.
