### ISSUE TITLE
Overhaul web version

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/OpenJSCAD.org#378]
the desktop app has more and more features (keybindings, updated 3d viewer, settable options , clear seperation of side effects from the main logic etc) and the web version is lagging behind: time to update it, and to unify as much code as possible, putting a lot of common codebase into the 'core' package for re-use

**Comment by z3dev** [comment]
Ok, but let’s make sure we cover all expected browsers, and operating systems.
