### ISSUE TITLE
Animation? Does $t work in OpenJSCAD ?

### ISSUE THREAD

**Issue by runsun** [jscad/OpenJSCAD.org#38]
Haven't found any description in the doc about the animation. Is it possible? How is the $t variable in jcad interpreted in jscad ?

**Comment by z3dev** [comment]
I don't see this being fixed ever, so closing.

**Comment by sdaau** [comment]
Hi, was just looking into animation in OpenJSCAD, and found this gist: [OpenJSCAD clock animation - profOnno/clock.jscad · GitHub](https://gist.github.com/profOnno/43871c166115540ee8b843a0f769f534). 

It's from 2016, but works for me as of today on https://openjscad.org/, in Firefox 79, Ubuntu 18.04 - though note that there is a delay of a second, before the animation starts rendering (that is, the very first frame is not drawn upon load, but upon first timeout; there are also comments in the code about workers)

**Comment by crysislinux** [comment]
I am playing with a different animation solution.

You can write the code like this:

![image](https://user-images.githubusercontent.com/5404597/96685413-a7c76800-13af-11eb-8b64-be582d47a88d.png)

![2020-10-21 15-05-25 2020-10-21 15_06_43](https://user-images.githubusercontent.com/5404597/96685311-82d2f500-13af-11eb-9c47-b2b016249372.gif)
