### ISSUE TITLE
desktop application have some visualisation problem

### ISSUE THREAD

**Issue by onekk** [jscad/OpenJSCAD.org#388]
## Expected Behavior
When you set some parameters, the choices has to be displayed.

## Actual Behavior
The choices aren't displayed at least on Firefox 52.8.1 running on Devuan Linux (Ascii) 64 bit

## Specifications

  - Version: Latest 0.6.1
  - Platform: Devuan Linux (Ascii) 64 bit
  - Environment:  Firefox 52.8.1 

Please feel free to ask more about the environment

**Comment by z3dev** [comment]
@onekk can you provide a simple example? there's nothing to review.

**Comment by onekk** [comment]
Sorry I can't, I'm not using OpenJSCAD anymore.
Regards
