### ISSUE TITLE
Doesn't work with webgl.min_capability_mode enabled

### ISSUE THREAD

**Issue by KOLANICH** [jscad/OpenJSCAD.org#390]
## Steps to Reproduce the Problem

  0. obtain Firefox
  1. go to about:config
  2. set `webgl.min_capability_mode` to `true`
  3. Open OpenJSCAD

More info:
* https://developer.mozilla.org/docs/Web/API/WebGL_API/WebGL_best_practices
* https://developer.mozilla.org/docs/Web/API/WebGL_API

**Comment by z3dev** [comment]
Great tips! Thanks.

Sadly, we are still using LightGL for the hooks into WebGL. This will change in the near future, and hopefully all those errors will disappear... of reappear as something else... :)

**Comment by z3dev** [comment]
Gecko notes

WebGL debugging and testing

Starting with Gecko 10.0 (Firefox 10.0 / Thunderbird 10.0 / SeaMonkey 2.7), there are two preferences available which let you control the capabilities of WebGL for testing purposes:

webgl.min_capability_mode

A Boolean property that, when true, enables a minimum capability mode. When in this mode, WebGL is configured to only support the bare minimum feature set and capabilities required by the WebGL specification. This lets you ensure that your WebGL code will work on any device or browser, regardless of their capabilities. This is false by default.

webgl.disable_extensions

A Boolean property that, when true, disables all WebGL extensions. This is false by default.

**Comment by z3dev** [comment]
Ditto for V2. Looks like V2 uses extensions, etc.

**Comment by z3dev** [comment]
@KOLANICH there's no intention to fix this as JSCAD works in all know browsers.

so, what's the issue, really?

**Comment by KOLANICH** [comment]
>so, what's the issue, really?

`webgl.min_capability_mode` is often used as a hardening measure against browser fingerprinting.

**Comment by z3dev** [comment]
I’m not sure what that means. I’m not even sure minimum WebGL capabilities are possible.

So, again, I have to ask... What’s the issue? What are the benefits? Are there performance gains? Improved compatibility to other devices?

**Comment by KOLANICH** [comment]
>What’s the issue?

No issue. I won't use it even if it supported `webgl.min_capability_mode`. I have WebGL and WebGPU disabled entirely. It is impossible to make WebGL secure.

>What are the benefits?

No benefits. The ones who don't have WebGL disabled are already hacked. The pref reduces fingerprinting surface, but it doesn't deal with allowing websites to interact with complex hardware sitting on PCIE bus and controlled by complex drivers and complex shaders compilers.

>Are there performance gains?

No gains.

>Improved compatibility to other devices?

Improved compatibility to users with this pref enabled.
