### ISSUE TITLE
Prevent Accidental Back Navigation with Backspace

### ISSUE THREAD

**Issue by hawkerm** [jscad/OpenJSCAD.org#400]
## Expected Behavior
Warn user if navigating away from page.

## Actual Behavior
Browser navigates.

## Steps to Reproduce the Problem

  1. Open a jscad file
  2. make changes
  3. manipulate the model
  4. Hit backspace

## Specifications

  - Version: 1.8.4
  - Platform: Edge
  - Environment: browser

Would be great to add navigation handlers to prevent this accidental navigation.  If you forget you're not in the editor (as a cursor is still shown from last known place) you can lose your work.

**Comment by z3dev** [comment]
@hawkerm thanks.
A recent set of changes to V2 JSCAD implemented a small change to prevent users from navigating away from the current page. His should prevent a lot of pain for many users.
Please keep those suggestions coming!
