### ISSUE TITLE
Which version of DXF file can I import?

### ISSUE THREAD

**Issue by somebodyZw** [jscad/OpenJSCAD.org#401]
I try to import the DXF file , But I always get the wrong feedback:
![image](https://user-images.githubusercontent.com/42363949/45804010-8fc31d00-bced-11e8-98e0-395a282afa14.png)，Which version is often used?

**Comment by somebodyZw** [comment]
![image](https://user-images.githubusercontent.com/42363949/45804457-bd5c9600-bcee-11e8-8890-27d123fd3339.png)
Sorry ,The picture is wrong,

**Comment by somebodyZw** [comment]
My DXF file is converted through DWG file

**Comment by z3dev** [comment]
@som Thanks for the information.

I tested using Autocad on macOS, latest version. So, the conversation is probably working fine. 
However, there are lots of issues with 2D lines, as JSCAD doesn’t display lines today. So, the results of conversion need a little manual editing.

Are there both 2D and 3D entities in the design?

I’d be glad to try if the DXF file is available on line.

**Comment by somebodyZw** [comment]
@z3dev  Here is DXF file,  When I open it with AUTOCAD, It works ,But when I import it into the web page, it will throw an exception，
[M-13283-51-PI-DGA-0001_1 - 0002_1 Piping Layout EL-0.100~EL+7.txt](https://github.com/jscad/OpenJSCAD.org/files/2403736/M-13283-51-PI-DGA-0001_1.-.0002_1.Piping.Layout.EL-0.100.EL%2B7.txt),
If circumstances permit, please help me to see what the reason is,Thanks advance.

**Comment by somebodyZw** [comment]
[M-13283-51-PI-DGA-0001_1 - 0002_1 Piping Layout EL-0.100~EL+7.000.zip](https://github.com/jscad/OpenJSCAD.org/files/2403761/M-13283-51-PI-DGA-0001_1.-.0002_1.Piping.Layout.EL-0.100.EL%2B7.000.zip)
I tried STL files too, but the browser always crashed.

**Comment by somebodyZw** [comment]
This problem arose when I used STL files:
![image](https://user-images.githubusercontent.com/42363949/45858332-868a8c80-bd8f-11e8-8990-da9bb1960b30.png)

**Comment by z3dev** [comment]
the STL file contains 306K vertices, 610K faces. that's going to max out any of the browsers as each has a limit on memory and runtime (cpu).

you'll definitely need to switch to the desktop application. but just what do you want to do? the design is large, and not very useful in JSCAD. our focus is on 3D printing, not industrial plant designs. :)

**Comment by somebodyZw** [comment]
Thanks for helping, this file  is a custom model file, I want to be able to see the data while showing the model.

**Comment by z3dev** [comment]
Ok. I think STL is the way forward. The current DXF import does not understand the binary ACIS entities.

Please try the STL file using the desktop application.  You need to  download and install a few things. Instructions are here...

https://github.com/jscad/OpenJSCAD.org/tree/master/packages/desktop

**Comment by z3dev** [comment]
Please reopen if you wish to persue the import of large DXF files. It may be possible once V2 is available.
