### ISSUE TITLE
V1 : rectangularExtrude()'s "roundEnds" boolean parameter seems to be ignored

### ISSUE THREAD

**Issue by gabrielgrant** [jscad/OpenJSCAD.org#404]
## Expected Behavior

The shape produced by the following code should be an "L" shape, with flat ends, and a sharp corner
```
function main () {
var path = new CSG.Path2D([[0,0], [10,0], [10, 10]], /* closed = */ false);
return path.rectangularExtrude(3, 4, 12, false);
}
```

## Actual Behavior

The ends are rounded:

![screenshot from 2018-10-15 13 48 14](https://user-images.githubusercontent.com/493968/46977410-fdf6c780-d080-11e8-8bbb-36da99ebb5e5.png)

Identical to when the `roundedEnds` parameter is `true`:

![screenshot from 2018-10-15 13 50 03](https://user-images.githubusercontent.com/493968/46977508-3e564580-d081-11e8-841d-7b837dd04263.png)

It's possible i'm just misunderstanding what this parameter is supposed to be doing. The description I read is from here: https://www.openjscad.org/dokuwiki/doku.php?id=design_guide_rectangular_extrude

> roundEnds: if true, the ends of the polygon will be rounded, otherwise they will be flat

## Steps to Reproduce the Problem

  1. paste the above code in https://openjscad.org/

## Specifications

  - Version: Current OpenJSCAD.org (v1.9.0)
  - Platform: Linux
  - Environment: Chromium

**Comment by gabrielgrant** [comment]
As a work-around, I tried reducing the number of end points, but that doesn't work either -- setting it to `1`, results in a single point (which makes sense):

![screenshot from 2018-10-15 13 56 23](https://user-images.githubusercontent.com/493968/46977884-2af7aa00-d082-11e8-9b89-8fdd7b1f9470.png)


However setting it to `0` results in it using three points:

![screenshot from 2018-10-15 13 56 10](https://user-images.githubusercontent.com/493968/46977869-2501c900-d082-11e8-84c5-5518101dc511.png)

**Comment by z3dev** [comment]
@gabrielgrant V2 has support for various round radius for extrusions, expansions, and offsets (NEW). If you have time, please try V2.

**Comment by gabrielgrant** [comment]
@z3dev good to know, sorry for the delayed reply. It seems OpenJSCAD.org is still using v1.9.0 -- is there an instance of V2 running online somewhere?

**Comment by z3dev** [comment]
Not yet, but pretty soon.

If you’d like there are some V2 notes for early adopters, here...

https://openjscad.org/dokuwiki/doku.php?id=early_v2

**Comment by z3dev** [comment]
@gabrielgrant www.jscad.xyz is now running the latest V2 JSCAD (alpha version). There's an example on the new offset functionality, which includes 'chamfer', 'edge', and 'rounded' corners.
