### ISSUE TITLE
V1 : cylinder({r: 5, round: true}) ignores r

### ISSUE THREAD

**Issue by rallant92** [jscad/OpenJSCAD.org#407]
## Expected Behavior

Using the round parameter should not affect the radius of a cylinder

## Actual Behavior

Using the round parameter appears to ignore the radius passed as a parameter to a cylinder.  The radius used seems to be 1, which happens to be the default.

## Steps to Reproduce the Problem

  1. Use this code with two identical cylinders and notice the difference

function main () {
  return union(
        cylinder({r: 5, h: 10, round: true}).translate([10, 0, 0]),
        cylinder({r: 5, h: 10, round: false})
    );
}

## Specifications

  - Version: 1.9
  - Platform: Windows
  - Environment: Firefox 62

**Comment by z3dev** [comment]
There's a BUG in the V1 cylinder() function, passing incorrect parameters to CSG.roundedCylinder().

The correct V1 CSG code is:
`CSG.roundedCylinder({start: [0, 0, 0], end: [0, 0, 10], radius: 5})`
This will produce a cylinder of height 10, with rounded ends (added to each end).

**Comment by z3dev** [comment]
The new V2 JSCAD API looks like this...
```
/**
 * Construct a solid cylinder in three dimensional space with rounded ends.
 * @param {Object} [options] - options for construction
 * @param {Array} [options.center=[0,0,0]] - center of cylinder
 * @param {Array} [options.height=2] - height of cylinder
 * @param {Number} [options.radius=1] - radius of cylinder
 * @param {Number} [options.roundRadius=0.2] - radius of rounded edges
 * @param {Number} [options.segments=32] - number of segments to create per full rotation
 * @returns {geom3} new 3D geometry
 * @alias module:modeling/primitives.roundedCylinder
 *
 * @example
 * let myshape = roundedCylinder({
 *   height: 10,
 *   radius: 2,
 *   roundRadius: 0.5
 * })
 */
```
