### ISSUE TITLE
Odd subtract behavior in 1.9.0

### ISSUE THREAD

**Issue by johnwebbcole** [jscad/OpenJSCAD.org#408]
Here's an odd one... subtracting a torus from another object and I'm not getting a clean subtraction.  One side does work, but the other side doesn't.  Are there older versions still available for testing regressions up?

## Expected Behavior
Clean subtraction

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/230922/48313673-5daf9800-e585-11e8-82f5-161942e0d56a.png">

## Actual Behavior

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/230922/48313652-4a9cc800-e585-11e8-808f-3834d0bcdf1b.png">

## Steps to Reproduce the Problem

  1. https://gitlab.com/johnwebbcole/shower-spacer
  2.https://openjscad.org/#https://gitlab.com/johnwebbcole/shower-spacer/raw/master/dist/shower-spacer.jscad
  3.

## Specifications

  - Version: 1.9.0
  - Platform: Chrome 70.0.3538.77 and Safari MacOS 10.14.1

**Comment by kaosat-dev** [comment]
hi @johnwebbcole, long time no see! 
 I will try to reproduce & investigate this week, in the meantime you all releases are tagged and can be found here https://github.com/jscad/OpenJSCAD.org/releases

**Comment by johnwebbcole** [comment]
Thanks, I tried 1.6.0, 1.7.0, and 1.8.4 all have the same issue :-(

I suspect that the union between the wire and wire end may be having issues.  https://gitlab.com/johnwebbcole/shower-spacer/blob/master/dist/shower-spacer.jscad#L88

**Comment by chriswal** [comment]
it looks as if there is some precision problem.
if you change outerRadius: 30.0000000001
it views ok

**Comment by z3dev** [comment]
I’m suspecting that the issue identified with mayOverlap() has caused this issue. Would be interesting to try.

**Comment by z3dev** [comment]
@johnwebbcole keep me posted once you migrate to V2. ;)

**Comment by johnwebbcole** [comment]
Are the V2 packages getting published?  I'm using @jscad/csg@0.7.0 and @jscad/scad-api@0.5.1 which are over a year old.

**Comment by z3dev** [comment]
> Are the V2 packages getting published?

Hope to publish the first ‘alpha’ packages next week, as the key functionality is now available.

**Comment by z3dev** [comment]
@johnwebbcole although not annouced yet (we are doing some late checks), the packages have been published.  also, www.jscad.xyz is running the latest release. you'll need to use the 'alpha' tag to get the latest V2 version from NPM.

`npm install @jscad/amf-deserializer@alpha`

**Comment by z3dev** [comment]
@johnwebbcole please move to V2 JSCAD. If this problem still exists then it can be addressed.
