### ISSUE TITLE
Tool for converting 2d sketch to xyz coordinates

### ISSUE THREAD

**Issue by beamplayer** [jscad/OpenJSCAD.org#409]
Hi,
I was wondering whether you guys don't have some tool for converting a 2d sketch (corner points of objects) to xyz coordinates (=vectors) so that you don't need to calculate this yourself ?
See https://github.com/opencv/opencv/issues/8762
https://www.researchgate.net/post/How_do_you_convert_2D_Image_pixel_coordinates_to_3D_object_coordinates_not_wolrd
https://stackoverflow.com/questions/76134/how-do-i-reverse-project-2d-points-into-3d

**Comment by beamplayer** [comment]
After thinking about it: how about just adding a third window at the bottom (which you can click open, similar like the left menu on the openjscad website). This third window would behave similar to one of the windows in gtkRadiant. This window can then show a grid unto which you can drag primitive shapes into (sphere, cuboid, cylinder, torus, polyhedron, ...) after clicking the appropriate button in this window (buttons can be made for all these primitive shapes). The grid can also allow scaling the shapes up/down, and moving them. Also, the grid should be settable to following 2d axles: xy , xz, xy.
In the main window, an xyz axle can be shown (mainly as a visual aid), and also: the primitive shapes can be made selectable in the grid window, and then indicate which parametric code corresponds to that selected shape in the main screen.

**Comment by z3dev** [comment]
That doesn’t sound like the original query.

There are other sites that provide a UI to JSCAD libraries.

https://www.blockscad3d.com/editor/
