### ISSUE TITLE
intersection of 3 boxes gives non-closed model

### ISSUE THREAD

**Issue by dagrende** [jscad/OpenJSCAD.org#412]
## Expected Behavior
A union of 3 stacked boxes.

## Actual Behavior
A union of 3 stacked boxes, with one missing wall on the middle box.

## Steps to Reproduce the Problem

  1. open openjscad.org in Chrome.
  2. paste the following script:
function main () {
    var c1 = cube({size: [44, 26, 2.5], center: true}),
        c2 = cube({size: [43, 25, 2.5], center: true}),
        c3 = cube({size: [44, 26, 1.8], center: true}),
        c1c2 = union(
            c1,
            c2.translate([0, 0, c1.getBounds()[0].z - c2.getBounds()[1].z])
        ),
        c1c2c3 = union(
            c1c2,
            c3.translate([0,0,c1c2.getBounds()[0].z - c3.getBounds()[1].z])
        );
    return c1c2c3.intersect(cube({size: 100, center: true}).translate([0, 50, 0]));
}
  3. rotate the result and look at the hole in the middle box.

## Specifications

  - Version: OpenJSCAD.org 1.9.0, MIT License, get your own copy/clone/fork from GitHub: OpenJSCAD
  - Platform: Browser runs on Ubuntu 18.10, Linux dag-ThinkPad-T480s 4.18.0-12-generic #13-Ubuntu SMP Wed Nov 14 15:17:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  - Environment: (browser, local server, node.js etc) 
     Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by dagrende** [comment]
Forgot to say, that if I change the height of the bottom box from 1.8 to 2, the hole disappears.

**Comment by z3dev** [comment]
@dagrende Welcome to JSCAD.

And welcome to the world of floating point rounding issues. I tried the code in various forms. And found that adjusting the size of c3 cured all issues; 1.8 to 1.81 to 1.80000001. These all worked.

The rounding issues come from the translate() method when using 1.8. There's a slight rounding introduced by the translate function.

c3 bounds
- _x: -22, _y: -13, _z: -0.9
- _x: 22, _y: 13, _z: 0.9
after translate([0,0,-4.65])
- _x: -22, _y: -13, _z: -5.550000000000001
- _x: 22, _y: 13, _z: -3.7500000000000004

For now, I suggest keep adjusting those numbers to get the desired results. You probably already know this. :)

I've also taken a variation of this example for testing in V2. Thanks.

**Comment by z3dev** [comment]
There was a fix to maybeOverlaps() function, which corrects this issue in V2.
There are now test suites as well for this function.
