### ISSUE TITLE
Is the module keyword supported?

### ISSUE THREAD

**Issue by CapnKernel** [jscad/OpenJSCAD.org#415]
I'm an OpenSCAD/JSCAD newbie.  I'd like to use JSCAD to view existing OpenSCAD designs. 
 But it seems that JSCAD doesn't support modules:

![ff foo](https://i.imgur.com/nu1jGyi.png "fdd")

JSCAD also seems to not like having two statements (a superior and inferior) on the same line, for example, on line 15.  Splitting the line makes the problem go away.

**Comment by WolfgangFahl** [comment]
Just enter 
//!OpenSCAD

as the first line of your file and you can use OpenSCAD files with module keyword support directly.
