### ISSUE TITLE
Missing file for V2 Demo

### ISSUE THREAD

**Issue by BarbourSmith** [jscad/OpenJSCAD.org#422]
## Expected Behavior

When launching the file `.\OpenJSCAD.org\packages\web.html` one would expect to see a demo of the JSCAD, I know this demo was just added today which is fantastic and thank you!

## Actual Behavior

A blank screen comes up instead. Pulling up the console I see that the issue is a file not found error with the line `<script language="javascript" src="./dist/jscad-full.min.js"></script>` and in fact the file is not present in the ./dist folder.

## Steps to Reproduce the Problem

  1. Git clone the repo (or download)
  2. Double click on demo.html

## Specifications

  - Version: V2.0
  - Platform: Windows 10
  - Environment: Chrome 

**Edit:** The [README](https://github.com/jscad/OpenJSCAD.org/blob/V2/packages/web/README.md) doesn't mention anything about the demo.html file being supposed to do anything the other two demos which are mentioned in the readme work great so maybe this isn't an issue.

**Comment by kaosat-dev** [comment]
hi @BarbourSmith , thanks for the bug report !
Just to clarify : V2 is not even alpha version yet ! things will change a lot , so nothing In README will pertain to V2 just yet until things are more stable
- demo.html is supposed to be demo for V2
- I removed jscad-full.min.js to avoid cluttering git with temporary builds, (normally users , me included should not include their own built files as part of PRS) but now that you mention it, for the 'V2 work in progress' stage, that might make sense to keep it ?
- I can either add it in a PR or you should be able to build a local version by running `npm run build-web` in packages/web

If this does not help

**Comment by kaosat-dev** [comment]
@BarbourSmith no need to apologize ! :) 
- yes, jscad-full.min.js will be among those (will likely replace the 'standard' build)
- hmm I never had either issue (`ENV` and the import issue), I will do a clean rebuild and push a PR to fix any problem in that area

**Comment by BarbourSmith** [comment]
I think my system is a contributing factor in both cases. The issue with `ENV` is a cross platform one with me using Windows (I know 🙄). A description of the issue and a cross platform solution are described [here](https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman) but it seems like more hassle than it is probably worth.

I've been reading what is out there about the second error message, and from what I can tell that message is usually caused by the file actually not being found. One thing I read which could be platform dependent would be a capitalization issue (`"./folder/fileName.js"` vs `"./folder/filename.js"`) which would work on OS X, but break on Windows. I couldn't find any issues like that, but I might not have looked in the right places. It's also very possible that the issue could be caused by me doing something silly with NPM because I'm still figuring it out 😀

**Comment by z3dev** [comment]
I would suspect that you still have some NPM environment issues. We have attempted to keep things simple, and standard. So, NPM should work as expected. Let us know if you cannot resolve.

**Comment by BarbourSmith** [comment]
I just ran through the test build process again using V2 this time and I can confirm that #423 fixed everything! Wonderful! 💯 That was so quick, thank you!
