### ISSUE TITLE
Can the AppImage be downloaded somewhere?

### ISSUE THREAD

**Issue by probonopd** [jscad/OpenJSCAD.org#424]
https://github.com/jscad/OpenJSCAD.org/blob/63054c61dec87e894873d0f438d1584c6e5c1d65/packages/desktop/package.json#L83

Can the AppImage be downloaded somewhere?

I have not found it on [GitHub Releases](https://github.com/jscad/OpenJSCAD.org/releases).

**Comment by kaosat-dev** [comment]
You can find them here for example:
https://github.com/jscad/OpenJSCAD.org/releases?after=%40jscad%2Fexamples%401.7.2
I have not had time to figure out/automated the upload of releases to Github yet. (It has very low priority until V2 is released, so a few months still), unless you know how to do it ? :)
I can put my local builds into the releases, but they are untested.

**Comment by kaosat-dev** [comment]
Here, uploaded them, AppImage included :https://github.com/jscad/OpenJSCAD.org/releases/tag/%40jscad%2Fdesktop%400.7.1

**Comment by probonopd** [comment]
Thanks. So jscad-desktop and OpenJSCAD are the same application? Which one is the proper name? Is https://appimage.github.io/jscad-desktop/ a correct representation of this application?

**Comment by kaosat-dev** [comment]
yes, jscad is the short name (and likely future name) of OpenJSCAD.
I do not know about that link though ? (Ich verstehe die zweite Frage nicht, ehrlich gesagt :)

**Comment by probonopd** [comment]
Thanks, that clarifies it. I was just wondering whether the application should be referred to as "jscad-desktop" or as "OpenJSCAD".

**Comment by kaosat-dev** [comment]
@probonopd Jscad or Openjscad is fine, the desktop suffix is perhaps not even essential ?
