### ISSUE TITLE
Is it using ThreeJS or raw WebGL ? 

### ISSUE THREAD

**Issue by ststeiger** [jscad/OpenJSCAD.org#434]
Question: 

Is OpenJSCAD using ThreeJS ? 
Or is it using raw WebGL ? 
Because [softwarerecs.stackexchange](https://softwarerecs.stackexchange.com/questions/33911/three-js-versus-babylon-js-for-cad-webapp) lists it as ThreeJS reference, but I can't find any (direct) dependency on ThreeJS in the package files.

**Comment by kaosat-dev** [comment]
Hi @ststeiger it uses 
- lightgl (a simple webgl wrapper) in V1
- [regl](https://github.com/regl-project/regl) in V2 (upcoming/ current)

no Three.js indeed :)
Though we will provide some very basic example on how to use three.js to render jscad data in the near future.

**Comment by ststeiger** [comment]
Thanks for the quick answer. 
Nah, nah, this was not a request. 
Just checking, because if it were using ThreeJS, I would refrain from using it ;-)
