### ISSUE TITLE
openJSCAD.org rendering on OSX

### ISSUE THREAD

**Issue by BarbourSmith** [jscad/OpenJSCAD.org#435]
Hello all. I was explaining how awesome jscad is to a friend and to show how it works I pulled up openjscad.org on her computer which is a slightly older (but not ancient) Mac and when the page loaded the rendering was very strange. It seemed like maybe some of the darker colors were ending up white or were simply not rendering.

## Expected Behavior

The normal rendering with a dark background color

## Actual Behavior

![screen shot 2019-03-04 at 8 06 11 pm](https://user-images.githubusercontent.com/9359447/53793706-616a8e80-3f69-11e9-9f14-1d71b193b44d.png)

## Steps to Reproduce the Problem

  1.It is a little bit tough for me to say exactly how to reproduce the issue other than to open jscad.org on my friends computer, but I am available to test if anyone has theories on what the issue might be.

## Specifications

  - Version: Current Website (1.?)
  - Platform: OS X
  - Environment: Browser

**Comment by kaosat-dev** [comment]
hi @BarbourSmith thanks for the feedback, not 100% sure where this could be coming from but I might have a hunch, could you please try jscad.xyz and see if the new renderer also has the same issue ?

**Comment by BarbourSmith** [comment]
@alzatin Will you give [jscad.xyz](https://jscad.xyz/) a try and see how it looks? Check the "grid" check box to see something show up.

**Comment by alzatin** [comment]
[image: Screen Shot 2019-03-05 at 7.05.37 PM.png]

**Comment by BarbourSmith** [comment]
Tragically the screenshot didn't upload 😢 

You can click the "preview" button to see if it is going to show up right

**Comment by alzatin** [comment]
![screen shot 2019-03-05 at 7 49 25 pm](https://user-images.githubusercontent.com/47953734/53854829-dc3ea400-3f7f-11e9-8aa8-1f15686e5050.png)

**Comment by z3dev** [comment]
@alzatin What browser is being used? version?

**Comment by z3dev** [comment]
@alzatin can you supply the environment information?
- OS version
- Browser version

If not then there’s no way we can test newer versions for this issue.

**Comment by z3dev** [comment]
@alzatin @BarbourSmith was this a hardware issue?

Can this issue be closed? Without feedback, we cannot work towards a solution.

**Comment by alzatin** [comment]
@z3dev  I no longer see this issue on https://openjscad.org/. It must have been a hardware issue.

**Comment by BarbourSmith** [comment]
Looks good to close to me 👍 👍
