### ISSUE TITLE
Clearing Cache of OpenJSCAD on MacOSX

### ISSUE THREAD

**Issue by WolfgangFahl** [jscad/OpenJSCAD.org#437]
## Expected Behavior
Clearing the cache should work

## Actual Behavior

Unclear how the shortcut ctrl-shift \ should be entered on a mac for the \ you already need to press option-shift 7 - so if it ctrl-shift-option-7 would work this would at least be very inconvenient. Tried it out and it seems to have no effect.

## Steps to Reproduce the Problem
1. Start dockerized version of openjscad see https://github.com/BITPlan/docker-openjscad
2. Visit a workspace example with an error e.g. "Unknown node type null"
3. Try to clear the cache to get the current version of the file
4. The "old" cached version of the file will reappear

## Specifications

  - Version: 1.10.0
  - Platform: macOS High Sierra 10.13.6 environment
  - Environment: Firefox 65 or Chrome72, dockerized version of openjscad

**Comment by z3dev** [comment]
@WolfgangFahl Can you explain the docker a little more? What is the web server?

Browsers have caching which can be cleared. Even then, sometimes the browser must be stopped and restarted to establish a new session.

**Comment by WolfgangFahl** [comment]
see https://github.com/BITPlan/docker-openjscad/blob/master/Dockerfile - it's just an automated install in a docker container that uses node. The repository https://github.com/BITPlan/docker-openjscad has some jscad example files

**Comment by z3dev** [comment]
@WolfgangFahl here's a little feedback on this issue.

Running another environment with OpenJSCAD.org installed should work fine. Even opening the webpage from the docker installation; index.html

In order to reference remote files in the URL (See examples), the backend poxy process (remote.pl) must be installed within a webserver, like Apache. (And configured properly). This little piece reads the contents of the remote files, caches them to disk, and provides the WEB PAGE with a URL to the cached file. This gets around issues with cross site access, which is not allowed in browsers.

Remote Access Examples
https://openjscad.org/#http://openjscad.org/examples/slices/tor.jscad

**Comment by WolfgangFahl** [comment]
@z3dev thanks for looking into this. I wouldn't know how to install the proxy process and it would be good to add this to the docker installation and make it available for public use. Is there an official OpenJSACD docker installation at this time?

By the way - i did not make any progress yet with the MediaWiki integration due to similar issues - the whole installation and configuration is too complex to get things working "out of the box" easily. Mediawiki 1.35 LTS is out now and that would be a good opportunity to re-address the issue. I think it would be good to have mediawiki based repositories of OpenJSCAD examples. How about creating an official OpenJSCAD repository with such an infrastructure?

**Comment by SimonClark** [comment]
Hey @WolfgangFahl, there is no docker installation that I know of, but there is a vagrant install (I'm a few years behind on my containerization skills). It is at https://github.com/jscad-community/jscad-vagrant and will be updated soon to run the proxy process.  @z3dev I'll also add an example for remote loading at the same time.

**Comment by z3dev** [comment]
Closing as support for vagrant instances has been added.

**Comment by WolfgangFahl** [comment]
I don't think this issus is related to containerization. My main need to properly use openjscad and reference it from a mediawiki isn't supported any way yet so this is just a puzzle piece for that need.

**Comment by z3dev** [comment]
The issue regarding Wikipedia integration #448 is still open.

But I think that this issue has been addressed by @SimonClark
