### ISSUE TITLE
SVG Import fails TypeError: right-hand side of 'in' should be an object, got undefined

### ISSUE THREAD

**Issue by WolfgangFahl** [jscad/OpenJSCAD.org#439]
## Expected Behavior
SVG import should work

## Actual Behavior
```
TypeError: right-hand side of 'in' should be an object, got undefined
Line: 24684,col: 0
(blob:https://www.openjscad.org/8e04e735-e15c-cd44-9431-127e3c824624)
```

## Steps to Reproduce the Problem

  1. Drag and Drop http://wiki.bitplan.com/images/wiki/7/7a/BITPlanLogo2012FontLess.svg
or try https://openjscad.org/#http://wiki.bitplan.com/images/wiki/7/7a/BITPlanLogo2012FontLess.svg

## Specifications

  - Version: 1.10.0
  - Platform: MacOS 10.3.6
  - Environment: Firefox 65

**Comment by z3dev** [comment]
@WolfgangFahl Please try again. I patched the website a few weeks back. This should be fixed.

**Comment by WolfgangFahl** [comment]
@z3dev  - the error seems to have gone. The result is not quite what i'd expect. Would that be a new ticket?
```
//
  // producer: OpenJSCAD.org 1.9.0 SVG Importer
  // date: Mon Aug 26 2019 11:14:38 GMT+0200 (Mitteleuropäische Sommerzeit)
  // source: BITPlanLogo2012FontLess.svg
  //
  function main(params) {
  var cag0 = new CAG();
    var cag1 = new CAG();
      var cag2 = new CAG();
        var cag3 = new CAG();
          var cag4 = new CAG();
        var cag30 = cag4;
        cag3 = cag3.union(cag30);
      var cag20 = cag3;
      cag20 = cag20.translate([5.644443999999999,-5.644443999999999]);
      cag2 = cag2.union(cag20);
    var cag10 = cag2;
    cag1 = cag1.union(cag10);
      var cag2 = new CAG();
        var cag3 = new CAG();
          var cag4 = new CAG();
        var cag30 = cag4;
        cag30 = cag30.translate([0,0]);
        cag3 = cag3.union(cag30);
      var cag20 = cag3;
      cag2 = cag2.union(cag20);
    var cag11 = cag2;
    cag11 = cag11.translate([342.05330639999994,-279.399978]);
    cag1 = cag1.union(cag11);
  var cag00 = cag1;
  cag00 = cag00.scale([0.29333,0.29333]);
  cag00 = cag00.translate([-47.977774,-10.1599992]);
  cag0 = cag0.union(cag00);
  return cag0;
}
```

does not show as 
![grafik](https://user-images.githubusercontent.com/1336221/63680027-fb154900-c7f2-11e9-8b87-b1ff707262e3.png)

**Comment by z3dev** [comment]
Yes, please. I’m working on the V2 version at this moment, so this may identify a new issue.

**Comment by WolfgangFahl** [comment]
see #460

**Comment by z3dev** [comment]
The initial issue has been fixed. And a new issue has been created.
