### ISSUE TITLE
Use in ObservableHQ

### ISSUE THREAD

**Issue by drom** [jscad/OpenJSCAD.org#445]
Any plans to support embedding JSCAD in https://observablehq.com notebook?

**Comment by kaosat-dev** [comment]
Hi @drom ! That would be nice indeed ! I will take a look at what would be needed/ is missing for that

**Comment by johnwebbcole** [comment]
@drom you may be able to use https://gitlab.com/johnwebbcole/vue-openjscad inside a notebook.  The instructions on using Vue don't have any gotcha's that look like it would prevent it from working :-) https://observablehq.com/@tmcw/using-vue-with-observable

**Comment by z3dev** [comment]
From @danmarshall 

Hello, just announcing yet another way to code your jscad stuff:
https://observablehq.com/@danmarshall/hello-jscad

Observable is a "magic notebook" for JavaScript. There is a learning curve to it, but it's very powerful.
One idea that makes this a different dev experience is the fact that you can have a page with multiple Jscad views at the same time. So you can work on coding a sub-component part while also seeing the pieces all together.

**Comment by hrgdavor** [comment]
Error reporting is pretty neat
![image](https://user-images.githubusercontent.com/2480762/116660603-2dddf000-a98b-11eb-9c05-1f4d0140c559.png)

**Comment by z3dev** [comment]
@drom There's an example now of using JSCAD with ObserverableHQ. Please discuss here...

https://openjscad.nodebb.com/topic/237/jscad-dev-environment-on-observable?_=1637976861258&lang=en-US

**Comment by drom** [comment]
Great @z3dev thank you
