### ISSUE TITLE
Wiki Documentation not up to date

### ISSUE THREAD

**Issue by WolfgangFahl** [jscad/OpenJSCAD.org#446]
## Expected Behavior
https://en.wikibooks.org/w/index.php?title=OpenJSCAD_User_Guide
should be up to date

## Actual Behavior
https://en.wikibooks.org/w/index.php?title=OpenJSCAD_User_Guide&oldid=3451090&diff=cur&diffonly=0

that is latest pendings changes aren't reviewed yet

## Steps to Reproduce the Problem

Visit https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide

**Comment by z3dev** [comment]
The documentation at wiki books is no longer maintained, as updates to that documentation were almost impossible.

How did you find those pages? All links should be pointing to...

https://openjscad.org/dokuwiki/doku.php

And you are welcome to post changes as well. :)

**Comment by WolfgangFahl** [comment]
Thx for getting back to this. The OpenJSCAD User guide is the first thing you find when searching with your favorite search engine.

My own Wikpage http://wiki.bitplan.com/index.php/OpenJSCAD is a Mediawiki page and naturally links to the "true" wiki page of OpenJScad

Personally I think using Doku wiki is a very bad idea since you limit the number of participants willing to get involved. E.g. I am not interested to work with dokuwiki since I am a Mediawiki author user and enthusiast and will not support another different platform that is only slightl different but incompatible. So I hold up my issue that the wike page should be up to date. At least it should point to the alternative dokuwiki page and there should be some effort to keep the pages in sync.

**Comment by z3dev** [comment]
Well... if you can get the idiots at wikibooks.org to do something rather then complain about syntax errors then I’d be glad to move back. So, the first step is to find someone who can and will review edits at wikibooks.org. As far as I’m concerned, that whole scheme smallest of ‘little kingdoms’.

**Comment by kaosat-dev** [comment]
@WolfgangFahl , as @z3dev  said we tried contacting the folks at Wikibooks on multiple occasions to update the content, and they just do react at all , we sadly have no control over that.
Personally I find both wiki solutions problematic, and favor using markdown files (right here !) that can be edited simply right here on github, and can be used to generate whatever output format is needed , and are also part of the repo, so available offline

**Comment by WolfgangFahl** [comment]
Just added https://en.wikibooks.org/wiki/Wikibooks:Requests_for_permissions#WolfgangFahl_(discuss_%C2%B7_contribs_%C2%B7_count_%C2%B7_logs_%C2%B7_block_log_%C2%B7_rfp_%C2%B7_rights_[change])_(Reviewer) to get the Issue on WikiBooks moving forward. With my https://github.com/WolfgangFahl/Mediawiki-Japi i could try markup-transfer from one source to another.

**Comment by z3dev** [comment]
@WolfgangFahl thanks for trying. 

I’m expecting that you receive the normal BS about ‘learning and gaining experience’ before being promoted. And of course, there’s probably no one looking at your request anyway.

**Comment by WolfgangFahl** [comment]
At least the review state has now been done.
https://openjscad.org/dokuwiki/doku.php does not have any info on plate examples nor does the original wikibooks page. So my question from #167 is open .

**Comment by WillAdams** [comment]
Trying to log in to edit some typos on the wiki, but get:

>Self-Registration is currently disabled or conf/users.auth.php is not writable. Please ask your DokuWiki administrator to create your account manually.

Should that be fixed? Or should I ask elsewhere (where?) for an account?

**Comment by z3dev** [comment]
Just push on the GITHUB button...

**Comment by WillAdams** [comment]
I did that. When I did so, I got the message which I quoted.

**Comment by z3dev** [comment]
I just tried again but didn't get a message.
Anyway, I adjusted the installation slightly. Please try again.

**Comment by WillAdams** [comment]
Thanks! That worked!

**Comment by z3dev** [comment]
@WolfgangFahl Did you receive any help on review the user guide at Wikibooks?

Looks like you received the same ‘pep’ talk that I received. 😔
