### ISSUE TITLE
OpenJSCAD not visible part  > scale / WebGL depth field

### ISSUE THREAD

**Issue by gitzdnex** [jscad/OpenJSCAD.org#449]
## Expected Behavior
User should see part even when it is big.

## Actual Behavior
Use attached code and you will not be able too see part.
`function main () {
    return cube({size: [2800, 2070, 18], center: false})
}
`

## Specifications

  - Version: current on web
  - Platform: Windows 10
  - Environment: FF67 and FF68

![2019-06-17_094815_openjscad](https://user-images.githubusercontent.com/51901600/59587247-2853c580-90e5-11e9-8926-13a3a1e2ee35.png)

**Comment by z3dev** [comment]
The V1 viewer does not scale automatically so you will have to scale the design.

**Comment by gitzdnex** [comment]
Ok, so in "V2" it will be scaled? Is it possible to test new version?

**Comment by z3dev** [comment]
@gitzdnex V2 has automatic camera positioning based on the size of the design, just double click. the new web site is coming soon.

Question... what do you expect to happen to the 'grid'? There's a simular issue to this #593

**Comment by z3dev** [comment]
@gitzdnex V2 JSCAD is now available at www.jscad.xyz
Your designs will need some changes, but the viewing of large designs is possible. Just double click on the window.
Note: There are other issues with large designs, so please scale appropriately.

**Comment by z3dev** [comment]
Closing, as this should not be an issue with V2 JSCAD.
