### ISSUE TITLE
Youmagine integration

### ISSUE THREAD

**Issue by camerin** [jscad/OpenJSCAD.org#45]
Hello,

I tagged this in a post on G+, but i realize that that network some times gets ignored. It would be really slick if there was a bidirectional link between openJSCAD and Youmagine. The Youmagine team seemed interested on G+.

Link, but currently shared privately. 

https://plus.google.com/u/0/108963302569247799288/posts/fo87CQF3aC3

**Comment by thehans** [comment]
The above link is no longer working.

**Comment by z3dev** [comment]
@camerin This might be an interesting discussion once 0.6.0 is released. Stay tuned.

**Comment by kaosat-dev** [comment]
Given the state of YouMagine (I will not go into details, but I worked for Ultimaker on Youmagine for the past 3 years) , this is pretty much a moot point at this stage. 
Closing the issue, if things change we can always reopen.
