### ISSUE TITLE
How could I edit (move, resize etc...) the objects via the mouse?

### ISSUE THREAD

**Issue by apbln** [jscad/OpenJSCAD.org#453]

**Comment by z3dev** [comment]
@apbln Thanks for the interest in JSCAD.

The design framework is based on scripts, so you will need to learn a few basics. To start, you can look at the examples, and learn how designs are created.

For interactive tools, you will have to download, install, and learn one of the popular applications.

**Comment by kaosat-dev** [comment]
Hi @apbln ! to clarify JSCAD is not a visual editor, so objects are not meant to be edited via mouse. Everything you create / edit is via code only.

**Comment by apbln** [comment]
@z3dev @kaosat-dev thanks for the quick answers. Do You know any csg frameworks, thatsupports this?

**Comment by kaosat-dev** [comment]
@apbln are you looking for something browser based or installed ?

**Comment by apbln** [comment]
something browser based.

**Comment by z3dev** [comment]
https://www.tinkercad.com/

**Comment by z3dev** [comment]
We will not fix, so I'm closing this.
