### ISSUE TITLE
V1 : roundedCube example does not work

### ISSUE THREAD

**Issue by WolfgangFahl** [jscad/OpenJSCAD.org#454]
## Expected Behavior
https://github.com/jscad/OpenJSCAD.org/blob/master/packages/examples/rounded-cube.jscad
should work

## Actual Behavior
There is no effect in rounding

## Steps to Reproduce the Problem

  1. cut&paste the example to http://www.openjscad.org

## Specifications
Current state of affairs as of today

**Comment by gilboonet** [comment]
Hello, looks like it is not the rounding itself that has no effect but the
`
if (params.rounded === 0)`
that returns false anytime, with only 2 == it is ok

**Comment by gilboonet** [comment]
Apparently it seems that === immediately returns false with differents types, and params.rounded is string as 0 is number, an explicit conversion should make it work
if (Number(params.rounded) === 0)

Looks like === implementation has changed.

**Comment by dirkncl** [comment]
If you replace
if (params.rounded === 1)
  with
if (params.rounded === '1')
  the result is correct, but it is still problematic in logic.

**Comment by z3dev** [comment]
V2 JSCAD works...

https://www.jscad.xyz/?uri=https://www.jscad.xyz/examples/core/primitives/roundedCuboid.js
