### ISSUE TITLE
Using CLI to generate STLs based on SVGs?

### ISSUE THREAD

**Issue by jasonwebb** [jscad/OpenJSCAD.org#464]
I'm looking for a way to provide an SVG file as an input to a JSCAD script via the CLI so that I can generate an STL file based on it's contents by simply extruding it's paths. I've put together a small Node script that essentially looks for SVG files within a set of folders, then runs the `openjscad` command via Node's `child_process.exec()` method.

What I'm hoping for is a way to pass SVG files into the openjscad script (like maybe with an `-i` option?), but I haven't found a way to do that in the User Guide yet. I see a package called [svg-deserializer](https://github.com/jscad/io/tree/V2/packages/svg-deserializer) over in the `io` repo, but I'm not sure how (or if) it can be used here.

Does anyone have any thoughts about how / if this can be done? Is there maybe another way I can try to approach this?

**Node script (`stl-creator.js`)**
```js
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

const components = getDirectories(path.resolve('./components'));

// Traverse all folders inside ./components
components.forEach((component) => {
  let fullPath = path.resolve('./components/' + component);

  // For each component folder ...
  fs.readdir(fullPath, (err, files) => {
    // Compile list of all the .svg files here
    let svgFiles = files.filter((file) => {
      return path.extname(file).toLowerCase() === '.svg';
    });

    // For each .svg file ...
    svgFiles.forEach((file) => {
      let filename = file.split('.').slice(0, -1).join('.')

      // Generate .stl file using OpenJSCAD
      exec('openjscad stl-creator.jscad -o ' + fullPath + '/' + filename + '.stl', (error, stdout, stderr) => {
        if (error) {
          console.error(`exec error: ${error}`);
          return;
        }

        // console.log(`stdout: ${stdout}`);
        // console.error(`stderr: ${stderr}`);
      });
    });
  });
});

function getDirectories(dir) {
  return fs.readdirSync(dir).filter((file) => {
    return fs.statSync(dir + '/' + file).isDirectory();
  });
}
```

**stl-creator.jscad**
```js
function main() {
   // Just generate a generic sphere for now
   return sphere()
}
```

I then run the Node script using `node stl-creator.js`, which produces STL files containing a sphere for each of the SVG files found. Now for the hard part: passing an SVG file (or filename) into the openjscad script and having it read it's contents, extrude paths, and spit out an STL file.

**Comment by z3dev** [comment]
Just change the main() to take a parameters object. You should see the file path.

Alternatively, you can build a script on the fly which imports the main conversion routine.

See some of the examples. 😃

**Comment by jasonwebb** [comment]
Thanks! I've updated my script to now just extrude the string provided through a param (`param.input`):

```js
function main(param) {
   var text = vectorText(param.input);
   return rectangular_extrude(text, {w: .1, h: 1});
}
```

And modified the `child_process.exec()` call like so:

```js
exec('openjscad stl-creator.jscad --input "' + inputFilename + '" -o "' + outputFilename + '"')
```

Where `inputFilename` and `outputFilename` are absolute paths to a real SVG file and the STL file I want to create, respectively.

The resulting 3D models look strange, but I suspect that's because of the use of `rectangular_extrude` rather than `linear_extrude`. When I try to use `linear_extrude` I get an error saying `baseShape.extrude is not a function`, so I'm just going to focus on getting the workflow working properly instead.

Right now I'm trying to get the `svg-deserializer` package working so I can actually parse my SVG files. However, when I include the package via `require()` as shown in the [example](https://github.com/jscad/io/tree/V2/packages/svg-deserializer#usage), I get the following error:

```sh
stderr: Error: no main() function found in the input script
    at validateDesignModule (C:\Users\uer\AppData\Roaming\npm\node_modules\@jscad\cli\node_modules\@jscad\core\code-loading\validateDesignModule.js:10:11)
    at requireDesignFromModule (C:\Users\uer\AppData\Roaming\npm\node_modules\@jscad\cli\node_modules\@jscad\core\code-loading\requireDesignFromModule.js:10:3)
    at Promise.then.prepareOutput.format (C:\Users\uer\AppData\Roaming\npm\node_modules\@jscad\cli\generateOutputData.js:80:22)
    at new Promise (<anonymous>)
    at generateOutputData (C:\Users\uer\AppData\Roaming\npm\node_modules\@jscad\cli\generateOutputData.js:42:10)
    at Object.<anonymous> (C:\Users\uer\AppData\Roaming\npm\node_modules\@jscad\cli\cli.js:67:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

Any ideas on what I might be doing wrong?

**Comment by jasonwebb** [comment]
A-ha! I see now that the SVG deserializer module is meant to be loaded into my Node script, not the JSCAD script. Now I just need to figure out how to inject or combine the generated CAG script into a script to extrude it.

Ultimately I want to be able to extrude different paths from my SVG file by different amounts programmatically - any ideas for doing that? For example, can I name my paths or use colors or some other parameter to inform my script how they need to be extruded?

I want to end up with a "stack" of extruded shapes, where each layer of the stack is a path (or set of paths) that has been extruded by a constant amount

**Comment by z3dev** [comment]
Hmm... V1 coverts all the paths to 2D shapes, and does a union(). So, it will be tricky to extrude different parts at different heights. No color support.

V2 (in progress) converts all the paths, and returns an array of paths. And there’s color support.

I would guess that V2 is probably a better choice. But it will be another month until we have V2 ready for use.

**Comment by jasonwebb** [comment]
Thanks for the info! I can wait :) I see work is already underway with PR #463, so I'll watch that for progress. This is a really cool project, and you guys are doing an outstanding job with it - keep it up!

Have any of the other deserializers been ported to V2 yet (like DXF or JSON)? Maybe I can use a different format in the meantime.

**Comment by z3dev** [comment]
DXF and STL will land soon.
