### ISSUE TITLE
V1 : How to specify roundedradius for cube()? (not using CSG.cube() )

### ISSUE THREAD

**Issue by udif** [jscad/OpenJSCAD.org#470]
## Expected Behavior
A way to specify rounded corner radius when creating cubes with V2-forward-looking API.

## Actual Behavior
Cannot find a way to specify rounded cube corner radius for cube() function - neither documentation nor examples

## Specifications

  - Version: As on www.openjscad.org
  - Platform: Window 10
  - Environment: Chrome

**Comment by z3dev** [comment]
We agree. V1 kind of sucks. Here's what V2 looks like.

```
/**
 * Construct an axis-aligned solid rounded cuboid.
 * @param {Object} [options] - options for construction
 * @param {Vector3} [options.center=[0,0,0]] - center of rounded cube
 * @param {Vector3} [options.size=[2,2,2]] - dimension of rounded cube; width, depth, height
 * @param {Number} [options.roundRadius=0.2] - radius of rounded edges
 * @param {Number} [options.segments=12] - number of segments to create per 360 rotation
 * @returns {geom3} new 3D geometry
 *
 * @example
 * let mycube = roundedCuboid({
 *   center: [2, 0, 2],
 *   size: [10, 20, 10],
 *   roundRadius: 2,
 *   segments: 36,
 * });
 */
```

**Comment by z3dev** [comment]
@udif the only solution for V1 is implementing a special function for yourself, and use CSG.cube() underneath. if you create the function signiture with something close to V2 then the conversion to V2 will be easy.
