### ISSUE TITLE
V1 : rounded cube's corners not created with a fixed radius

### ISSUE THREAD

**Issue by udif** [jscad/OpenJSCAD.org#471]
## Expected Behavior
Rounded corners should be created with a fixed radius, so when the cube is scaled, the corner should scale with it.

## Actual Behavior
Rounded corners are defined by a fixed ratio to the cube size, instead of fixed radius as CSG.cube(), so when 2 different-sized cubes are scaled to the same size, their rounded corners become the same radius.  
This breaks the only way I could think of, to create different rounded corners without actually having a roundradius parameter for cube().

## Steps to Reproduce the Problem
```javascript
function main(params) {
	return union(
		scale([10,10,10], cube({size:[1,1,1], round:true, fn:32})),
		translate([20,0,0], scale([0.1, 0.1, 0.1], cube({size:[100,100,100], round:true, fn:32})))
	);	
}
```
These 2 cube are sized 1:100, but when scaled, their corner radius is the same, indicating that when they were small, the corner radius was relative to the cube size instead of fixed radius.

## Specifications

  - Version: www.openjscad.org (as of this issue opening date)
  - Platform: Windows 10
  - Environment: chrome

**Comment by z3dev** [comment]
@udif please try using CSG.roundedCube() as this function allows the 'roundradius' to be specified.

`
/** Construct an axis-aligned solid rounded cuboid.
 * @param {Object} [options] - options for construction
 * @param {Vector3} [options.center=[0,0,0]] - center of rounded cube
 * @param {Vector3} [options.radius=[1,1,1]] - radius of rounded cube, single scalar is possible
 * @param {Number} [options.roundradius=0.2] - radius of rounded edges
 * @param {Number} [options.resolution=defaultResolution3D] - number of polygons per 360 degree revolution
 * @returns {CSG} new 3D solid
 *
 * @example
 * let cube = CSG.roundedCube({
 *   center: [2, 0, 2],
 *   radius: 15,
 *   roundradius: 2,
 *   resolution: 36,
 * });
 */
`
