### ISSUE TITLE
Local host OpenJSCad.org

### ISSUE THREAD

**Issue by ikeji** [jscad/OpenJSCAD.org#479]
My CAD machine is offline.
I want to setup local web server with OpenJSCad.org contents.

## Expected Behavior

the packages/web folder should have index.html

## Actual Behavior

There are no index.html file.

## Steps to Reproduce the Problem

I'm following "Use within a Web Site (pre built files)" steaps.
https://github.com/jscad/OpenJSCAD.org/tree/master/packages/web#use-within-a-web-site-pre-built-files
  1. Clone this repo.
  2. Setup webserver based on packages/web
  3. access to http://localhost/index.html

## Specifications

  - Version: latest V2 branch.
  - Platform: linux
  - Environment: local server

**Comment by z3dev** [comment]
@ikeji What HTTP server are you using?

The server needs to be configured properly.

**Comment by ikeji** [comment]
Just run
```python -m http.server 8000```

**Comment by z3dev** [comment]
I see... you are trying to use the V2 branch. We are getting close but V2 isn’t ready now.

**Comment by ikeji** [comment]
Oh, OK, thanks for clarification.
