### ISSUE TITLE
Troubles embedding OpenJSCad within my website ("min-version")

### ISSUE THREAD

**Issue by xCrowbar** [jscad/OpenJSCAD.org#480]
Hello everyone and welcome to my first issue here on GitHub.
As you can read from the title, I'm having serious problems while trying to embed OpenJSCad into my website. I downloaded the tools directly from the official website and I managed to include the 3D viewer correctly. Troubles begin when I want to render a pre-made 3D model (already coded in JavaScript) by linking it's loading to an HTML button.

## Expected Behavior
The button I created triggers an event, which transforms the JS script into the corrispondent 3D model, showing it correctly into the Editor.

## Actual Behavior
Nothing happens, basically. I still can't find the actual "link" between the HTML button and the event that must be triggered.

Currently awaiting for answers. Thank you for your time!

**Comment by z3dev** [comment]
@xCrowbar welcome

We don't have such an example but it should be possible. There are many ways to use JavaScript and HTML together.

For some smaller examples see these examples in packages/web/...
- viewer-minimal.html and src/ui/min.js
- viewer-options.html and src/ui/opt.js

Is the editor required?

**Comment by xCrowbar** [comment]
No. In my project sample, the editor is not visible by the user. Basically, my target is the to link an HTML button to some kind of JavaScript function which takes the js template of some 3D model and renders it automatically into the canvas contained in "viewer-minimal" (similar behavior of the button "update" in your website).
By studying the events linked to your update button, I kinda figured out that the function "runExec(editor)" has something to do with the 3D plot of the model. Can you please confirm this theory of mine?

**Comment by z3dev** [comment]
@xCrowbar Sorry for the late reply.

Yeah. The 'editor' is initialized with a event callback called runExec(), when the special keystrokes are activated. The 'src' in the editor is read from the editor, and sent to gProcessor.setJsCad()

Like I mentioned, you don't need the editor. You should be able to send the source directly to gProcessor.setJsCad(). You will also see this function being called in min.js (as part of viewer-minimal.html).

**Comment by xCrowbar** [comment]
Thank you. Now, I have to call the function "gProcessor.setJsCad()" from my script section in the HTML file, but I can't understand what is the first parameter required by the function. I yet got that the second one ("design") is the actual JS coding of your 3D model.
As a result, i get "Uncaught TypeError: Cannot read property 'setJsCad' of null"

Get me out of here, please!!

**Comment by z3dev** [comment]
Nope. You have it backwards...

```
>   // script: javascript code
>   // filename: optional, the name of the .jscad file
>   setJsCad: function (script, filename, includePathBaseUrl) {
>     ...
>   }
```

The first parameter is the JSCAD script (code for the model). The other parameters are optional, and you don’t need supply those.

**Comment by xCrowbar** [comment]
I'm sorry, but I can't really help with it. It feels like I'm missing something, which I don't know how to fix. Let me show you the code I wrote and the output I get from the actual web page. Can you please tell me where I get wrong and how to fix the code?
![1](https://user-images.githubusercontent.com/52099167/66570752-857cf680-eb6e-11e9-9e5e-66d98cdf63b9.png)
![2](https://user-images.githubusercontent.com/52099167/66570753-857cf680-eb6e-11e9-9fd0-5d1308508bbd.png)

**Comment by z3dev** [comment]
Try removing line 13... var gProcessor = null

**Comment by xCrowbar** [comment]
By doing so, neither gProcessor or setJsCad are defined...

**Comment by z3dev** [comment]
It’s defined as part of min.js

gProcessor should be a ‘global’ variable.

**Comment by xCrowbar** [comment]
Ok, I made some tweaks...
![Immagine](https://user-images.githubusercontent.com/52099167/66700557-d5d09180-ecf1-11e9-80ce-33cc3f23342c.png)
Now no errors seem to pop out (even the console is clean), but it doesn't plot the figure yet.

**Comment by xCrowbar** [comment]
UP.

**Comment by z3dev** [comment]
@xCrowbar Did you find a solution?

**Comment by xCrowbar** [comment]
Not yet. Now I came into another trouble: the Processor, which gets the ID of the viewer, is not defined. But I included the min.js into my HTML page, so it should be defined.

**Comment by gilboonet** [comment]
Hello, just in case you're still looking for a solution, I manage to make it work by moving the javascript function addCube() into dist/min.js by adding this to init() :
`  document.getElementById('addCubeButton').addEventListener("click", 
  function () {
    console.log("Add cube");
    var sampleCube = "function main() { return cube(); }"
    gProcessor.setJsCad(sampleCube);
  } 
  , false);`

**Comment by xCrowbar** [comment]
Can you please show me your coding? I'd like ti check both your HTML page and init() script!

**Comment by xCrowbar** [comment]
OMG THANK YOU! It finally worked, what a relief! I can happily close the issue, thank you so much!

**Comment by ponzifex** [comment]
thanks

**Comment by ponzifex** [comment]
replacing the call of init() in min.js to this:
`document.addEventListener('DOMContentLoaded', function (event) {
    document.jscad = function(viewer, source) {
        gProcessor = new Processor(viewer);
        gProcessor.setJsCad(source);
    }
});
`
Will let you input your scad data from browser input instead of a file.
