### ISSUE TITLE
Arrays not sorted correctly in Chrome

### ISSUE THREAD

**Issue by leomol** [jscad/OpenJSCAD.org#481]
## Expected Behavior
a = [[1,1],[2,2]];
console.log(a);
a.reverse();
console.log(a);

Should print
[[1, 1], [2, 2]]
Then
[[2, 2], [1, 1]]

## Actual Behavior
[[2, 2], [1, 1]]
Then again
[[2, 2], [1, 1]]

## Steps to Reproduce the Problem
Execute this code IN CHROME and see console output:
function main () {
    a = [[1,1],[2,2]];
    console.log(a);
    a.reverse();
    console.log(a);
    return cube();
}

## Specifications

  - Version:
  - Platform: Windows 10
  - Environment: (Version 77.0.3865.120 (Official Build) (64-bit))

**Comment by z3dev** [comment]
Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript

FYI, the data structure is ARRAY[ARRAY,ARRAY]

**Comment by drumline18** [comment]
Same behavior in Firefox but I believe this has nothing to do with OpenJSCAD. Removing the return cube(); line and running it in a blank window will give the same results.
