### ISSUE TITLE
Command for 3D to 2D Projection

### ISSUE THREAD

**Issue by geobruce** [jscad/OpenJSCAD.org#486]
## Expected Behavior
In the openSCAD documentation there is the [Project Command](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/3D_to_2D_Projection) to generate a 2d image (svg / dxf) from the cross section of a 3d model.

## Actual Behavior
I can't find this option in openJSCAD

**Comment by z3dev** [comment]
@geobruce please see #99 which is a long standing issue about projections.

If you have additional references or examples then please let us know. We are always looking for high quality implementations.

**Comment by geobruce** [comment]
> @geobruce please see #99 which is a long standing issue about projections.
In the issue you linked here ["a simple projection() function is coming very soon ! (yes , took a while :) API updates are under way"](https://github.com/jscad/OpenJSCAD.org/issues/99#issuecomment-348633445) is mentioned but I can't find any information of it anywhere.
Somewhere else: ["Orthonormal Basis section of the User Guide"](https://github.com/jscad/OpenJSCAD.org/issues/99#issuecomment-141293443) is mentioned by you but the only information I can find on this is using a cut by plane function, but this is [removed from v2](
https://openjscad.org/dokuwiki/doku.php?id=changes_v2&s[]=cutbyplane)
I would be happy with any option to get a dxf / svg from a 3D model.
But it seems there is no option for this at the moment. Please tell me if there is.

Another possibility would be to work in 2D from the start but I can't find how to control the fill of the shapes.

**Comment by z3dev** [comment]
There was never a true projection function. The closest V1 solution was taking a very thin slice, and converting to 2D.

I think @kaosat-dev may have some plans.

**Comment by geobruce** [comment]
Is this project still alive and kicking?
I thought this had the complete functionality of openSCAD already.
I moved to openJSCAD because the way openSCAD handles variables (not really as variables seemingly..) I'm looking for a powerfull way to code 3D models and convert them to SVG's, I also tried [maker.js](https://maker.js.org/) but this had some weird stuff going on as well.

Maybe somewhere is there is the perfect tool for my needs. But I haven't found it yet.

**Comment by z3dev** [comment]
I’ll look at the projection functions of OpenSCAD, but don’t expect anything soon.

There’s nothing simple about projections.
https://en.m.wikipedia.org/wiki/3D_projection#Perspective_projection

**Comment by geobruce** [comment]
Thank you I'm not specific looking for projection a cross section would be fine too, I can believe this is not an easy task. But it would be very use full for my laser cutter projects.

**Comment by geobruce** [comment]
Someone on stackoverflow posted [a way to do it](https://stackoverflow.com/questions/59178036/openjscad-cant-find-command-for-3d-to-2d-projection/59199005#59199005).

**Comment by kaosat-dev** [comment]
hi @geobruce !
I had a projection() function somewhere for V1, I'll try to dig it up asap !

**Comment by z3dev** [comment]
@geobruce  Just for your information, as part of the last release, there's a new project() function which can project a 3D shape to a 2D shape.
