### ISSUE TITLE
Confirm navigating away or refreshing

### ISSUE THREAD

**Issue by chingy1788** [jscad/OpenJSCAD.org#487]
## Expected Behavior
Pop up a dialog to confirm navigating away or refreshing the page to prevent losing unsaved jscad code.

## Actual Behavior
No confirm dialog, jscad code is lost.

## Steps to Reproduce the Problem

  1. Open openjscad page
  2. Work on model
  3. Accidentally press F6 (highlights browser address bar)
  4. Press F5
  5. Browser refreshes, model is lost. 

## Specifications

  - Version: 1.9.0
  - Platform: Windows 10 / Chrome browser
  - Environment: Browser

**Comment by z3dev** [comment]
We are at the mercy of the browsers. Each has a different set of ‘command’ keystrokes, behavior, etc. I’m not sure how much can prevented but we can try.

**Comment by z3dev** [comment]
Let’s try adding this to V2 WEB UI.

**Comment by z3dev** [comment]
@chingy1788 thanks.
Your suggestions have been integrated into V2 JSCAD via #687 
Please keep those comments coming!
