### ISSUE TITLE
V2: Remove 'center' on primitives

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#489]
## Expected Behavior

V2 primitives are centered at [0,0,0] by default. Therefore, the functionality to 'center' an object at another position can now be acheived via the center() function. In addition, the center() function also allows centering by axis (X Y Z).

```
let a = primitives.cube({size: [5,5,5]}) // centered at 0,0,0
let b = transforms.center({at: [5,5,5]}, primitives.cube({size: [5,5,5]})) // centered at 5,5,5
```

## Actual Behavior

`let a = primitives.cube({size: [5,5,5], center: [5,5,5]}) // centered at 5,5,5 WRONG`

## Steps to Reproduce the Problem

  1. As described above

## Specifications

  - Version: V2
  - Platform: All
  - Environment: ALL

**Comment by kaosat-dev** [comment]
Thanks for adding this !
I thought about this a bit more this morning and I think we should also rename the 'center' function to the slightly more explicit **centerAt** so that it is very clear that the api is about providing a point to center geometries at

Also , should we perhaps have functions like 'lakeFlat(axes)' ? (I think it would be useful and would emulate the boolean version of 'center' parameter from V1

**Comment by garrlker** [comment]
I can take this issue if noone else is already working on it.

**Comment by z3dev** [comment]
Cool.

We haven't quite decided on what the final API, so some mock up of the changes would be nice to see. Got any ideas?

I've been thinking off and on about this, and think maybe this needs to expanded as well, and include some thoughts about 'align'. Both 'center' and 'align' seem closely related.

**Comment by kaosat-dev** [comment]
@z3dev removing center seems to be our consensus , right ? Functions should do one thing only but do it well :) (so centering in addition to building the geometry is bleh)
I have a few alignment functions coming up, but they do not include 'center' since that is already sorta there .

@garrlker thanks for the offer, that would be great !
It would "just" be about removing the center params from all primitives, right @z3dev  ?

**Comment by z3dev** [comment]
I believe that’s correct. Remove ‘center’ parameters from the primitives.

**Comment by garrlker** [comment]
@z3dev @kaosat-dev 

Sounds good!
I'll get on it :)

**Comment by kaosat-dev** [comment]
thanks @garrlker ! much appreciated :)

**Comment by kaosat-dev** [comment]
@garrlker do you need a hand with the removal ? :)

**Comment by garrlker** [comment]
Thank you, but I think I've just about got it :)

I've removed the center param from all of the primitives that used it.

Now I'm fixing the modeling tests that broke.

**Comment by z3dev** [comment]
> Now I'm fixing the modeling tests that broke.

Great! I forgot to mention that... 😃

**Comment by kaosat-dev** [comment]
awesome @garrlker , thanks a lot !
And also, the failing tests are a good news, it means our tess are actually doing their job correctly haha :) Good luck on the fixing !

**Comment by z3dev** [comment]
@garrlker Any luck with the changes to the test suite?

**Comment by garrlker** [comment]
I've got all of the tests fixed except for 2.
*  The rounded cuboid tests are having an odd error I haven't figured out yet.
*  And the expand tests are getting a geometry with a different length.

I'm spinning my wheels on them, so I could use that help :smiley:

All other tests were using `center` plain as day and I've fixed those.
I also added a check to the center function.

The primitives were allowing a 2 value array for it's center param and that worked just fine, but when a 2 value array was passed into the center function the tests were hanging/failing.

The check just pads the input with 0's until the array has a length of 3.

**Comment by kaosat-dev** [comment]
@garrlker that is awesome already, thanks !
For the issues you ran into: could you please open a PR with your changes, then we can take a closer look at what is causing those issues.

2d vs 3d array: padding seems like a good generic solution, if something is really jarring, we can always tweak

**Comment by z3dev** [comment]
> The primitives were allowing a 2 value array for it's center param and that worked just fine, but when a 2 value array was passed into the center function the tests were hanging/failing.
> 
> The check just pads the input with 0's until the array has a length of 3.

@garrlker please update the checks to use arrays of length three(3) for now.

We have some more tweaks to the API planned to accommodate different size arrays, but that can be another set of changes.

**Comment by garrlker** [comment]
PR #512 is up!

@z3dev On it!

**Comment by garrlker** [comment]
I updated the check, and fixed the tests that were passing a 2 element array into the `center` function.

Now we're down to the tests that I couldn't figure out.

**Comment by z3dev** [comment]
Done as part of #512
