### ISSUE TITLE
Some diameter for PATH value can break geometry

### ISSUE THREAD

**Issue by gitzdnex** [jscad/OpenJSCAD.org#491]
## Expected Behavior
Path geometry should be created correctly with selected radius/diameter

## Actual Behavior
Path sometimes create corrupted geometry on some radius values

## Steps to Reproduce the Problem

  1. load attached code https://pastebin.com/erPEawYn
  2. change radius value to 10
  3. make render

You can see it clearly on video.

![2019-12-19_174920](https://user-images.githubusercontent.com/51901600/71192215-1fa49d80-2288-11ea-8a9f-60a7e7368be5.png)

## Specifications

  - Version: 1.9.0 -> openjscad.org
  - Platform: linux and windows
  - Environment: browser FF70 and Chrome 79

[openjscad_radius_path.zip](https://github.com/jscad/OpenJSCAD.org/files/3984629/openjscad_radius_path.zip)

**Comment by z3dev** [comment]
@gitzdnex thanks for this example.

I looked at the code. The path being created looks like this.

![a](https://user-images.githubusercontent.com/8969165/72860492-4e3fe900-3d0a-11ea-8029-a18345703251.png)

**Comment by gitzdnex** [comment]
Hello,

i understand that, but when radius is 1 or 15 it seems to be merging shape correctly?
Well small segments are needed, but okay.
I was actually wondering if there is some rounding issue. Could you please point me to area which code is responsible for this?
Thanks

**Comment by z3dev** [comment]
If you want to extrude this path then I suggest breaking it up into smaller pieces. It’s always better to use smaller pieces to make a larger piece.

The code is all over the place in V1, but extrusions are found in src/api/*.js

**Comment by gitzdnex** [comment]
Ok, thanks.

Does it work in V2 same? Btw do you know why different values like 1 or 15 works? I tried several and only some around 10 seems to have this problem.

**Comment by kaosat-dev** [comment]
@gitzdnex at a very cursory glance, it could be that a lot of values cause overlapping/coplanar polygons, while some others do not

**Comment by z3dev** [comment]
Just a follow up about V2. V2 can expand paths that are:
- non-crossing
- sufficiently spaced

The expansion of the path should produce non-overlapping 2D geometry. If something overlaps... well... it won’t be useable later.

**Comment by gitzdnex** [comment]
Okay, thanks. Then It will probably not work anyway, beacause in some situations I need overlapping geometry. So I guess I will need that boolean difference which is slow.

**Comment by z3dev** [comment]
Looking at the example path above...

You could split the path up into circular pieces, extrude those, and finally use union to put the pieces together.

**Comment by z3dev** [comment]
I’m not sure this can be fixed internally, as you mentioned that there are specific situations where the geometries would overlap. Is that correct?

@gitzdnex if you have a solution then please close this issue.

**Comment by gitzdnex** [comment]
Well I need them to be able to overlap sometimes. In current example it is just coincidence, but sometimes it is needed to be able to get on same position several times.

Anyway I do not have solution as using directly difference on this positions takes around 10x times more than with path whole. So currently I just try to adjust overlap to get good result. It is still better than using difference. My question was mostly about if there is way how to fix this as overlap? 

Btw is it possible to find code area for this? Last suggested area was quite big and I am not really familiar with this code so I could not experiment with it.

**Comment by z3dev** [comment]
> Anyway I do not have solution as using directly difference on this positions takes around 10x times more than with path whole. So currently I just try to adjust overlap to get good result. It is still better than using difference. 

That’s good to know. Sorry that a general solution doesn’t work.

> My question was mostly about if there is way how to fix this as overlap?

Detecting overlaps and fixing the given geometry will not be easy. I doubt that a general solution would be possible, nor efficient.

I still think that your geometries (paths) could be easier to manage in pieces.

> Btw is it possible to find code area for this? Last suggested area was quite big and I am not really familiar with this code so I could not experiment with it.

V1 code is very large and entangled. You can start with the ops-extrusions.js file.

**Comment by z3dev** [comment]
@gitzdnex is this a tool / bit path?

**Comment by z3dev** [comment]
@gitzdnex has this issue been resolved? are you able to continue?

**Comment by z3dev** [comment]
No replies. Closing.
