### ISSUE TITLE
drag and drop should ignore .files e.g. .gitignore, .git

### ISSUE THREAD

**Issue by WolfgangFahl** [jscad/OpenJSCAD.org#500]
## Expected Behavior
hidden files and directories e.g. .gitignore, .git should be ignored for drag&drop

## Actual Behavior
Drag & Drop does not work e.g. if git was used

## Steps to Reproduce the Problem

  1. create main.jscad with just function main() { return cube()}
  2. drag and drop it's directory (works)
  3. git init in the directory
  4. drag & drop of the directory fails

**Comment by WolfgangFahl** [comment]
Workaround is to put openjscad javascript files in a subdirectory e.g. src

**Comment by z3dev** [comment]
@WolfgangFahl A very good idea. Thanks.

**Comment by WolfgangFahl** [comment]
@z3dev  while at it you might want to make sure an error message is shown in case things don't work. It took me a few hours to find out why things were not working and i had no idea for quite a while ...

**Comment by kaosat-dev** [comment]
This is a good point @WolfgangFahl not sure about the best implementation though (very opinionated either way):
- ignore .git folder
- ignore .git folder AND all contents of .gitignore (more complex and tedious, require reading the file)
- have it configurable (horribly inconvenient, we have a ton of different types of UIs, CLIs etc , so nothing should depend on some user iterface), then again, drag & drop is specific to visual UIs ?

**Comment by WolfgangFahl** [comment]
for the time being it would be o.k. to ignore hidden folders and may be allow to configure what the positive extensions are. I'd expect the default to be ".jscad". In all cases there should be proper error handling and not just "no reaction".

**Comment by z3dev** [comment]
V2 WEB UI now ignores all '.' files. Closing.
