### ISSUE TITLE
V2: center() fails on primitives

### ISSUE THREAD

**Issue by faithhack** [jscad/OpenJSCAD.org#501]
center() doesn't seem to have any effect on my objects. 
I noticed issue #489 plans to remove built in 'center' but haven't seen any commits to that effect yet.
When I run 'npm test' it says all 4 'operations › transforms › center › center' tests pass

## Expected Behavior
index.js:
`const modeling = require('@jscad/modeling')`
`const { cube, cylinder } = modeling.primitives`
`const { center} = modeling.transforms`
``
`const paramDefaults = {}`
``
`const getParameterDefinitions = () => {`
`  return []`
`}`
``
`const main = (params) => {`
`    params = Object.assign({}, paramDefaults, params)`
`    let results = []`
``
`    results = [`
`      center({axes:[true,true,false]}, cylinder({startRadius: 4, endRadius: 4, height: 30})),`
`      center({axes:[false,false,false]},  cube({size: 20}))`
`    ]`
`    return results`
`}`
`module.exports = { main, getParameterDefinitions, paramDefaults }`

should render as a cylinder centered at [0,0,15] and a cube centered at [10,10,10] 

## Actual Behavior
Both primitives are centered at [0,0,0]

however,
`cube({size: 20, center:[10,10,10]})`
does produce the expect results

## Steps to Reproduce the Problem

  1. clone V2 ( current as of commit 5abe983 )
  2. $npm i; npm bootstrap; npm run web
  3. drag and drop folder with above as index.js

## Specifications

  - Version: commit 5abe98347981f272d76536198df7e5d4f10f7463 (HEAD -> V2, origin/V2)
  - Platform: Linux (ubuntu 19.10)
  - Environment: (firefox 72.0.1, localhost server, nodejs v8.16.1)

**Comment by z3dev** [comment]
The primitives are already centered at [0,0,0] by default. So, supplying axes: [true,true,false] doesn't really do much. You need to supply a 'center' point.

FYI, we are thinking of changing the name of center() to centerAt(), as the 'center' point is important to understand.

Thoughts?

**Comment by faithhack** [comment]
centerAt() sounds great - center({center:...}) looks a tiny bit odd. 
I was using 'axes' as a direct equivalent of the old primitive's 'center'.  The method docs in center.js confused me a bit. 
Therefore, to build on the X plane (my bias, since I treat it like my printer bed) I will need to create like  centerAt({center:[0,0,z/2]}, cuboid({size:[x,y,z]})
Hopefully, as new docs get created, there will be "V1 did it like this, here is the way to do the same in V2" statements. I'll close this and comment my message in the forums, too.
