### ISSUE TITLE
Working with DWG files

### ISSUE THREAD

**Issue by Hasan-git** [jscad/OpenJSCAD.org#503]
## Expected Behavior
Ability to import dwg files, 

## Actual Behavior
Not able to import dwg files

## Specifications

  - Version: 1.9 alpha
  - Platform: any
  - Environment: 

Please, even if there is a way to translate dwg to another file using javascript in which openjscad  would accept the exported file format

**Comment by z3dev** [comment]
This format is proprietary to AutoCAD applications. Lots of projects have attempted to use this but the format is two complex. I suggest converting the design to DXF (old but open) or another format.

**Comment by z3dev** [comment]
@Hasan-git please close this if the answer is sufficient 
If not then please add some comments, references, examples.
