### ISSUE TITLE
Save data from a .jscad script with localStorage for external use

### ISSUE THREAD

**Issue by gilboonet** [jscad/OpenJSCAD.org#506]
## Expected Behavior
Work without error
## Actual Behavior
Works but jscad raises an error :
`ReferenceError: localStorage is not defined`
Error can be catched on my dev local server on localhost
```
  dexport=JSON.stringify(data);
  try{
    localStorage.setItem("tr1_data", dexport);
  }catch(err){};
```
But if catched on my github.io hosted site, it doesn't work.

This error is not really important as the data from the jscad script can still be used by the html5 app, and I will try to use V2 now for my developments ASAP.

(One thing that can be interesting : this script allow the user to choose a jscad (the first button lines), then another one, and merges then into a script that it runs.)

## Steps to Reproduce the Problem

  1. open [this](https://gilboonet.github.io/OpenJSCAD.org/packages/web/scripts.html)
(scripts.html is derived from viewer-minimal.html)
  2. choose mode "2d modele" and click on "Update" 
  3. error message appears on the development console

## Specifications

  - Version: 1.10.0
  - Platform: Ubuntu 19.10
  - Environment: Firefox 72.0.1, site on github.io

**Comment by z3dev** [comment]
Shouldn’t that be...

`window.localStorage.setItem(...)`

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by gilboonet** [comment]
Yes, you're right, with "window." the exception doesn't fire anymore. Thanks a lot. I hope to update this code to V2 in order to get rid of the "Polygon is self intersecting" error that is the last error that I wasn't able to manage.
