### ISSUE TITLE
V1 : Torus fno doesn't seem to support less than 8 sides

### ISSUE THREAD

**Issue by iammikecohen** [jscad/OpenJSCAD.org#511]
## Expected Behavior
The torus 3D primitive should be able to create triangles, squares and other geometry shown in the documentation:
https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide#Torus

## Actual Behavior
any value below 8 passed to fno produces an octogon torus.

## Steps to Reproduce the Problem
Repro: https://openjscad.org/#https://raw.githubusercontent.com/iammikecohen/jscad-error/master/openjscad.jscad

## Specifications

  - Version: 1.9.0
  - Platform: macOS
  - Environment: openjscad.org; latest chrome and firefox

**Comment by z3dev** [comment]
@iammikecohen thanks for the new issue.

I believe that 8 is the default value for FNO, and values less then 4.

**Comment by iammikecohen** [comment]
ok. So how do you create a triangle like what is shown in the docs?

**Comment by iammikecohen** [comment]
edit: initial repro link was wrong

**Comment by z3dev** [comment]
It looks like a bug was introduced with some changes a while back. see line 213 of ops-extrusions.js

```
  // adapt to the totalAngle : 1 extra segment per 45 degs if not 360 deg extrusion
  // needs to be at least one and higher then the input resolution
  const segments = Math.max(
    Math.floor(Math.abs(totalAngle) / 45),
    1,
    fn
  )
```

**Comment by z3dev** [comment]
FYI, V2 can create a torus with 3 or more sides. In V2, this is controlled by the 'segments' option.

`let obs = torus({innerRadius: 1.0, innerSegments: 4, innerRotation: Math.PI/4, outerRadius: 5, outerSegments: 3})`

![torus](https://user-images.githubusercontent.com/8969165/94103262-22639d00-fe6f-11ea-9ce0-fd5edc343e95.png)

**Comment by z3dev** [comment]
@iammikecohen sorry but V1 bugs will not be fixed.
