### ISSUE TITLE
Enhancement: Improve text support

### ISSUE THREAD

**Issue by matthijskooijman** [jscad/OpenJSCAD.org#53]
Currently, there is basic text rendering support. I can see two ways to improve this:
1. Better integration with the 2D subsystem.
2. Somewhat normalize the font size of rendered text.
3. Allow rendering different fonts.
#### 2D integration

It makes sense to let the text functions return `Path2D` objects instead of an array with point coordinates. This makes them easier to use, and makes them useful for a 2D drawing as well. In this case, instead of having a `rectangular_extrude` that works on an array of points, users can just call the `Path2D.rectangularExtrude` directly.

Having a way to easily transform an array of `Path2D` objects could be easy as well (e.g. to scale a piece of text). Perhaps calling `addTransformationMethodsToPrototype` on the array prototype (and adding an appropriate `transform` implementation for array) might be useful in general? Alternatively, adding a `Paths2D` object and appropriate `Path2D.union` implementation could be useful? The latter could allow to add other methods as well (like `rectangularExtrude` or `expandToCAG` to quickly work with text or multiple paths in general).
#### Normalize font sizes

Regarding the font sizes, it seems that the concept of "font size" [is not entirely well-defined](http://www.thomasphinney.com/2011/03/point-size/). In general, though, it seems that the font size should be at least as big as the biggest character, and often includes a bit of spacing as well (though with modern fonts, it depends on the font itself what the "font size" actually measures. In the hershey font used, the biggest characters (`(`, `/` and `[` it seems) range from -7 to 25, so they are 32 "units" high. I wonder if it would make sense to scale this so that text returned is always 1 high? Then callers can just scale afterwards to whatever size they need (and add any extra linespacing if needed).
#### Rendering default fonts

It seems that [opentype.js](https://github.com/nodebox/opentype.js) might be useful to do the grunt work for this?

When picking an API for this, it is interesting to note that the current text functions return characters as unclosed paths, so they trace the character once. When support for other fonts is added, these would return closed paths that would need to be filled, which requires different processing. Even if custom fonts aren't implemented now, it would be good to somehow make the API future-proof in this regard?

**Comment by z3dev** [comment]
Full font support is probably not possible, i.e. creating a new font. But rendering text in any chosen font, style, and size would be very beneficial for all. There are some others working with the opentype.js library now. #72 

Also, you might be interested in the new support for SVG import / export. If the text can be converted to SVG paths then import is possible. You can try the tracing tool at Z3D Lab (http://www.z3d.jp/lab/tracetool.php) to convert SVG images to paths. This is what I do...

**Comment by z3dev** [comment]
@matthijskooijman it's a bit complicated but creating outlines from fonts is now possible by using several libraries as part of a JSCAD project.

https://github.com/jscad-community/jscad-text

See the Project section on how to assemble the project contents.

**Comment by z3dev** [comment]
@matthijskooijman please reopen if there’s something further to discuss.
