### ISSUE TITLE
V2: cuboid and cube center 

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#530]
## Expected Behavior
center parameter along with size to control relative position

## Actual Behavior
center parameter ignored

## Steps to Reproduce the Problem

  1. create simple script with cube()
  2. cube is center unlike in V1
  3. try to affect center bahavior with cube({center:false})
  3. nothing happens

## Specifications

  - Version: V2
  - Platform: any
  - Environment: browser

the sourcecode reveals a center variable inside cuboid function,
that can not be changed by options

```
const cuboid = (options) => {
  const defaults = {
    size: [2, 2, 2]
  }
  let center = [0,0,0];
  let {size} = Object.assign({}, defaults, options)
```

the center array is pointless in the followup code

this change in behavior greatly affects  the effort of converting existing V1 jscad code

**Comment by z3dev** [comment]
See #525 as well.

We have had several discussions about the center function.

**Comment by hrgdavor** [comment]
I have taken a look at #525 and it does not help this situation

but my issues here are:

1. cube is centered by default, which is different than V1 behavior
 this is either 
 - a bug 
 - new behavior that dramatically affects porting V1 jcscad code
2. center array variable in the cuboid function code is redundant as it is filled with zeros, and can not be changed

**Comment by hrgdavor** [comment]
sry if nagging,
but at least let me know what is the default object placement strategy for V2,
is it like V1 where a cube is placed with corner at 0,0,0 or it will be centered by default like I observed within this issue.

**Comment by z3dev** [comment]
All primitive shapes are centered at 0,0,0
That’s the best way to know where shapes start, and the best way to reposition shapes in designs.

Also, JSCAD is breaking from the old ways of  OPENSCAD, as we have further plans.
