### ISSUE TITLE
V2: No radius or diameter option for circle and cylinder primitives

### ISSUE THREAD

**Issue by garrlker** [jscad/OpenJSCAD.org#533]
## Expected Behavior
Circles have diameter option and Cylinders have radius and diameter options.

## Actual Behavior
Circles do not have a diameter option.
Cylinders do not have a radius or diameter option, only start and end radius options.

I'll need to fill this in some more as I get time.

**Comment by z3dev** [comment]
Well... if your go to add ‘diameter’ to the primitives then please look at
- circle
- sphere (inside ellipsoid)
- cylinder
- roundedCylinder
