### ISSUE TITLE
V2: new default behavior for centering net described in "Summary of V2 changes"

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#538]
## Expected Behavior
Description of how default centering new objects in V2 works.
What is intended behavior, and changes from V1

## Actual Behavior
no description of centering in V2

## Steps to Reproduce the Problem

  1. open https://openjscad.org/dokuwiki/doku.php?id=changes_v2
  2. 
  3.

## Specifications
related to #530 

example:
V1: cube corner is at 0,0,0 residing in positive:x,positive:y positive:z
V1: cube is centered on x,y,z, center of the cube at 0,0,0

V1: cylinder bottom is at 0,0,0 centered:x centerd:y positive:z
V1: cylinderis  centered on x,y,z, center of the cylinder at 0,0,0

This is important info for early adopters to convert existing code to V2

  - Version: V2
  - Platform: all
  - Environment:  all

**Comment by hrgdavor** [comment]
I can see now a sentence there:
"MAJOR CHANGE primitives are centered at 0,0,0 only. use center() to translate the shape into place"

but if primitives are already centered, what does the center  function do ?

**Comment by z3dev** [comment]
@hrgdavor a very good point. i updated the documentation again. how does that look?

**Comment by hrgdavor** [comment]
I am looking at https://openjscad.org/dokuwiki/doku.php?id=changes_v2
where is the documentation for v2 and center explanation u mention ?

**Comment by z3dev** [comment]
Same page on the wiki... BOLD RED... 

MAJOR CHANGE primitives are centered at 0,0,0 only. use translate() to position the shape

**Comment by hrgdavor** [comment]
Yeah, I missed the "translate" part. it was misspelled before
MAJOR CHANGE primitives are centered at 0,0,0 only. use center() to position the shape

so when I refreshed, I have not noticed the slight difference :)

**Comment by z3dev** [comment]
@hrgdavor I appreciate the dialogues. I hope you can make some great designs with V2.

**Comment by hrgdavor** [comment]
I od think my designs are great :D 
I use https://openjscad.org/ on daily basis, as I enjoy making many of prototypes for 3d print by coding openjscad.

I have few projects like knife sharpening tools, magnetic puzzles, vaccuum foil slicing ..
I plan to convert th code to V2 as early adopter to help with the feedback, That is why having exact idea on the centering in V2 was a must for me. I many many objects without centering so it will require careful refactoring. I do however force myself while still using V1 to center everything so it is easier to port to V2.
