### ISSUE TITLE
V1: error: wrong arguments when importing DXF

### ISSUE THREAD

**Issue by rgrastur** [jscad/OpenJSCAD.org#540]
## Expected Behavior
My dwg file:
![image](https://user-images.githubusercontent.com/48772925/77295824-e34d6700-6ce6-11ea-86a7-cb71cf0050ac.png)

I have dxf file of this dwg but I have this error:

## Actual Behavior
![image](https://user-images.githubusercontent.com/48772925/77295483-573b3f80-6ce6-11ea-9ef1-3c7864b9fafa.png)

## Steps to Reproduce the Problem

  1. Cloned repository
  2. Open Index in OpenJSCAD.org-master\packages\desktop
  3. Upload a dxf file.

**Comment by z3dev** [comment]
@rgrastur Thanks for using JSCAD

Sadly, V1 suppprt for 2D drawings is not good. The real focus of JSCAD is 3D designs for 3D printing.

**Comment by z3dev** [comment]
@rgrastur if still interested then please try V2.

**Comment by z3dev** [comment]
@rgrastur please provide an example, otherwise this issue will be closed.
