### ISSUE TITLE
Add select box or radio option to getParameterDefinitions

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#547]
## Expected Behavior
I need a way to have a picker for a project with multiple parts to test and print.
I need this selection to be maintained while automatic reload, so I can test part by part.
This way a single script can be used with single set of customization parameters 
to make multiple pieces fit together, and to be able to export STL for each separately.

## Actual Behavior
I use combination of number input and fake checkboxes.
clicking checkbox does nothing(intended) number must be entered to choose the piece 

## Steps to Reproduce the Problem

  1. paste this in https://openjscad.org/
```
var funcs = {};
const _r1 = 2.45;
const _dip = 3;
function getParameterDefinitions() {
	const pieces = {
		_p_slider_top_a: 'Slider top A',
		_p_slider_top_b: 'Slider top B',
		_p_slider_top_c: 'Slider top C',
	}
	var defs = [];
	var i=1;
	for(var p in pieces){
		defs.push({ name: p, type: 'checkbox', checked: p=='pin_', caption: pieces[p] + ' ' + i });
		i++;
	}
	defs.push({name:'piece', caption:'Pick one', min:1, max:defs.length, type:'int' });
    return defs;
}
function main(params){
	var list = [''];
	for(var p in params){
		if(p.substring(0,3) == '_p_') list.push(funcs[p]);
	}

	return list[params.piece || 1]();
}

funcs._p_slider_top_a = function({h=1, w=44, l=44}={}){
	return funcs._p_slider_top_x({h, w, l});
}
funcs._p_slider_top_b = function({h=1, w=44, l=44}={}){
	return funcs._p_slider_top_x({h, w, l, holes:true});
}
funcs._p_slider_top_c = function({h=16, w=8, l=44, l2=20.1}={}){
	return difference(
		cube({size:[w,l,h], center:true}),
		translate([0,l/2-l2/2-5,0],cube({size:[2.3,l2,h], center:true})),
		translate([0,-l2/2+2,1],cube({size:[0.3,8,h], center:true})),
		translate([0,0,_dip-0.2],cube({size:[2.3,l,h], center:true}))
	);
}

funcs._p_slider_top_x = function({h=1, w=44, l=44, holes=false}={}){
	var hh = holes ? h:1;

	var pins =
	translate([0,l/2+_dip/2-19, holes ? 0 : h/2+0.5],
		translate([0,  0,0], cylinder({r:_r1, h:hh, center:true})),
		rotate([0,0,45], translate([0, 13,0], cylinder({r:_r1, h:hh, center:true}))),
		rotate([0,0,45], translate([0,-13,0], cylinder({r:_r1, h:hh, center:true})))
	)
	let aw = 1;
	var arrow = [
		// arrow
		translate([7, -12,0], cube({size:[8,aw,h], h:h, center:true})),
		translate([12.1, -12.75,0], rotate([0,0,45],cube({size:[3,aw,h], h:h, center:true}))),
		translate([12.1, -11.3,0], rotate([0,0,-45],cube({size:[3,aw,h], h:h, center:true})))
	];

	var main = cube({size:[w,l-_dip,h], center:true});
	if(holes){
		main = [difference(main, pins, ...arrow)];
	}else{
		main = [difference(main, ...arrow), pins];
	}

	return [
		...main,
		translate([-7, l/2,0], cube({size:[20,_dip,h], center:true})),
	];
}
```
## Specifications

  - Version: V1, V2
  - Platform: ALL
  - Environment:  ALL

**Comment by hrgdavor** [comment]
Although sample code is for V1, it should not be a problem, as it is here just to demonstrate the use-case

**Comment by z3dev** [comment]
I do the same for multi-part designs. I suggest setting 'initial' values for each parameter, otherwise you will get the default from the browser (which varies).

`	defs.push({name:'piece', caption:'Pick one', min:1, max:defs.length, initial: 1, type:'int' });`

**Comment by z3dev** [comment]
http://www.z3d.jp/lab/view.php?design=lab-000000050

**Comment by hrgdavor** [comment]
ma bad, I totally missed the taype:choice ... and that is exactly what I needed.

**Comment by z3dev** [comment]
My bad, actually. I forgot to add that t9 the user guide.. I just updated that part of the guide. Please review @hrgdavor

**Comment by hrgdavor** [comment]
@z3dev I already used it and changed my script. Looks good :)
