### ISSUE TITLE
Render 2d paths

### ISSUE THREAD

**Issue by matthijskooijman** [jscad/OpenJSCAD.org#55]
Currently, the rendering result can only be CAG/CSG objects. However, I want to mark some lines using a laser cutter, for which 2d paths seem a perfect match. However, it's not currently possible to return these paths, even though it should be possible to represent them in a DXF file.

**Comment by z3dev** [comment]
This is a really late comment, but I believe that OpenJSCAD should be able to render CSG and CAG, as well as the building blocks of these objects. Such as
- CSG.Path2D
- CSG.Line3D
- CSG.Line2D
- CSG.Vector2D
- CSG.Polygon
- CSG.Plane
- CSG.Vertex
- CSG.Vertex3D
- CAG.Vertex
- CAG.Side
It's not an issue about the these objects, but an issue with interpreting these objects into 3D space for viewing. All of which is possible.

**Comment by matthijskooijman** [comment]
@z3dev, I'm not sure you understood my issue entirely. What I was saying is that the final result (which can be exported to a file) must be a CSG/CAG, and cannot be a Path2D. You can use a Path2D to create a CAG I believe, but that always turns the path into a closed shape. Note that I haven't checked if this has changed since I submitted this issue, I haven't been using openjscad in a while.

**Comment by z3dev** [comment]
You are correct. Only CSG/CAG are possible for export, but that will change. Some formats can and should be able to export additional object types.

The title says "render". Is this about export?

**Comment by matthijskooijman** [comment]
> The title says "render". Is this about export?

It is really about both. The main function cannot currently return Path2D objects, so they cannot be rendered or exported. Allowing them to be exported without rendering them does not really make sense, so this should probably be implemented together.

**Comment by z3dev** [comment]
I thought so. That's why I added a comment about the list of possible render-able objects. It was meant as a reference point, i.e. what's missing.

Sorry for any confusion.

For now, let's keep this issue open. I think further discussion would be good.

**Comment by z3dev** [comment]
FYI, rendering and export of 2D paths are possible in V2. Please try V2.

**Comment by z3dev** [comment]
@matthijskooijman this issue can finally be closed, as V2 exports paths to supporting formats (DXF, SVG, etc), and the viewer renders paths as well. (See the README files of the IO modules)

I’d like to close this issue. Is there anything else that you’d like to see?

**Comment by matthijskooijman** [comment]
I haven't been able to test this yet (haven't been running any projects in jscad since quite some time), but it soundsl like it is fixed entirely, so I'll close this. If something comes up later, I can always reopen or create a new issue.

Thanks or working on this!

**Comment by z3dev** [comment]
@matthijskooijman looking forward to your designs!
