### ISSUE TITLE
3MF Support

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#557]
Requirements:
- Support serialization (import) of designs in 3MF format
- Support deserialization (export) of designs to 3MF format
- Seperation of 'parts' by color, supporting printers with multiple color capabilities

_From @z3dev on June 28, 2016 6:44_

http://www.3mf.io/what-is-3mf/

Here's where to start.

_Copied from original issue: Spiritdude/OpenJSCAD.org#160_

**Comment by z3dev** [comment]
@hrgdavor do you have any progress on the deserializer?

**Comment by hrgdavor** [comment]
I have a serializer prototype. Did not start on deserializer, but it should not be a big problem.

**Comment by z3dev** [comment]
Ok. I’m going to make a small release which has a few small fixes. The next release can have some NEW functionality.

**Comment by z3dev** [comment]
3MF serializer completed as part of #1036

**Comment by z3dev** [comment]
The new 3MF deserializer (import) has been added to V3.
