### ISSUE TITLE
V2 : Performance Ideas

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#562]
Some ideas on boosting performance.

- [x] change math functions to require an 'out' parameter (like glmatrix)
- [x] poly3.transform() is calling mat4.isMirroring(), expensive on large 3D geometries
- [X] measureBounds() is called multiple times during boolean operations, cache the bounds for later use
- [BAD] create fast array concat (See [discussion](https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki))

## Expected Behavior
Blazing fast with same behaviour

## Actual Behavior
Slighter faster then V1

## Steps to Reproduce the Problem

  1. Run performance suite

## Specifications

  - Version: V2
  - Platform: ALL
  - Environment: ALL

**Comment by z3dev** [comment]
Caching of bounding box and other measurements was implemented via

**Comment by ahdinosaur** [comment]
hi @z3dev, how does someone run the performance suite?

i noticed these caches when trawling through the code, and i'm curious about the performance impact of using a WeakMap to store cached values rather than mutating the object, as i wonder if mutating the object would lead to JavaScript engine de-optimizations due to polymorphism. ([:information_source:](https://www.digitalocean.com/community/tutorials/js-v8-engine))

**Comment by z3dev** [comment]
> hi @z3dev, how does someone run the performance suite?
> 
> i noticed these caches when trawling through the code, and i'm curious if there might be a performance improvement in using a [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) to store cached values rather than mutating the object, as i wonder if mutating the object would lead to JavaScript engine de-optimizations due to polymorphism. ([ℹ️](https://www.digitalocean.com/community/tutorials/js-v8-engine))

Interesting idea.

I’ve looked at WeakMap before and it seems kind of incomplete. I’m not sure why the standards introduced them. SIGH

I have a performance suite that runs whenever changes are merged into the V2 branch. It actually lives outside of this project, here.

**Comment by hrgdavor** [comment]
Something is fishy in the renderer when geenrating regl code for 1000 cubes takes 4 seconds, but rotating the scene and zooming is snappy and works fine (so likely is at least 60fps).

my knowledge here is limited, but I am sensitive to performance of the tools I use.

It is not unusual for designs to have multiple instances of "same" geometry that is only copied and translated 
to multiple places. 

```js
const jscad = require('@jscad/modeling')
const { cube } = jscad.primitives

function main(){
  var ret = []
  var size = 10
  for (var i = 0; i < size; i++) {
    for (var j = 0; j < size; j++) {
      for (var k = 0; k < size; k++) {
        ret.push(jscad.transforms.translate([i*2, j*2, k*2], cube({size:1})))
      }
    }
  
  }
  return ret;
}
module.exports = {main}
```


Is there a way to generate a design right now that would have better performance when scene is filled with same geometry in multiple locations (translations)?

**Comment by z3dev** [comment]
> Something is fishy in the renderer when geenrating regl code for 1000 cubes takes 4 seconds, but rotating the scene and zooming is snappy and works fine.

Nothing fishing going on... the rendering just changes the position of the camera. All those visible shapes (packed arrays) are cached.

Just a tip... create the cube once... translate 1000 times.

**Comment by hrgdavor** [comment]
Am I doing it wrong here ? 
```js
  var _cube = cube({size:1})
  for (var i = 0; i < size; i++) {
    for (var j = 0; j < size; j++) {
      for (var k = 0; k < size; k++) {
        ret.push(jscad.transforms.translate([i*2, j*2, k*2], _cube))
      }
    }
  }
 ```

it did not gain any speed

**Comment by z3dev** [comment]
> Am I doing it wrong here ?

Nope. You won’t improve performance further using a browser.

**Comment by hrgdavor** [comment]
Sure there is limit to what some code could do in js. But you missed one detail. Both versions when cube is created once ona 1000 times inside loop has the same performance. So no instancing is used, which is a shame.

**Comment by hrgdavor** [comment]
This is my first time playing with three.js but creating many cubes there is much faster

I took a number that takes three.js just a bit of time to generate and render (8000 cubes in 20x20x20 formation) but takes jscad a very long time.

http://3d.hrg.hr/jscad/three/three.js.webgl.exporter.stl.html

you can test 2 versions of add mesh (refresh the page after each test)

version without mesh reuse that creates a cube every time
```js
geometry = new THREE.BoxBufferGeometry( 1, 1, 1 )
```
takes on my pc a second or two.

version that reuses same cube but creates different mesh translated is displayed instantly


and you can compare that to jscad version
https://jscad.xyz/#http://3d.hrg.hr/jscad/manyCubes.jscad

I am doing all of this because the long time waiting for scene to render in this case is not from csg operations
but from regl renderer. I am guessing that you did plenty optimizations for csg part, and it is shame that the renderer is the bottleneck.

**Comment by z3dev** [comment]
@hrgdavor It's very simple. All the math is done in the JSCAD internals, running in the JavaScript engine. Three.js creates WebGL structures that are shoved onto the 3D graphics card. Which do you think will be faster?

The goals of the two libraries are very very different.

**Comment by hrgdavor** [comment]
Yes, but my perception is that after csg operations are done faster (for number of models I made), I have to wait for renderer that is slow. My example here is exaggareted to show the difference.

If I create a mesh like this (what is interesting this one does no csg)
![image](https://user-images.githubusercontent.com/2480762/106883907-ebd14500-66e0-11eb-86a0-277dfd258f9e.png)
and want to add more stuff to the model, things become slower and slower. When I see modeling part done in 10, 20, 100, 200 ms and then renderer lagging and waiting for 1,2,3,4,... 10 seconds ... it makes me a  sad puppy :( :( .

I was looking (googling) option to replace current renderer with Three.js as the main point of using openjscad is to model things and not to wait for renderer more than I absolutely have to. 

https://gist.github.com/chandlerprall/1590424
https://github.com/jscad/csg.js/issues/92

Also I am looking to create a workspace form myself that supports multiple jscad models that are then laid out and animated as different scenes (assembly instructions, etc.).

**Comment by hrgdavor** [comment]
Hi,

I have created a hacked-up (do not look at the code) example of jscad with threejs as renderer to show what is possible.

Here is one of my recent projects in my fancy/ugly jscad+threejs demo
http://3d.hrg.hr/jscad/three/three.js.webgl.jscad.html

to compare here is a link to the same basic script that can be viewed usin jscad.xyz
https://jscad.xyz/#http://3d.hrg.hr/jscad/three/aqua_pump.jscad

you can look at browser console for timings and compare visually the speed difference.

--------------------------------------------------------------------
there is also a bonus "ANIMATE" button that shows animated csg
![image](https://user-images.githubusercontent.com/2480762/109568791-b3f2cd00-7ae7-11eb-9fd0-c1561fe47cc2.png)
 - it is a cube minus 2 cylinders rotated in each animation step.
 - animation rotates 2 degrees each iteration and geometries are cached
 - at first it will go slowly and then speed up after cached geometries start to be used

--------------------------------------------------------------------
I have also added axis preview in top right corner (optimized to rendered only when orbit controls change)
![image](https://user-images.githubusercontent.com/2480762/109568362-1a2b2000-7ae7-11eb-9176-e43f9072f65a.png)

--------------------------------------------------------------------
I have also configured rendering to stop after few ms if
 - no updates in scene
 - no rotation/pan control is happening

jscad.xyz on the other hand keeps rendering regardless 

--------------------------------------------------------------------
some inital unfiltered thoughts:
it seems that there is quite more that can be done for performace regarding 4x4 transforms 
for example as there is no need for transform and rotate to create new geometry, but conserve the ref to original and
create new object with new matrix....  
my idea of having jscad to create multipart projects that are snappy to develop and update with additional layouts functions seem close ... at least some form of it I can use myself as creating such a tool for others is next level pain in the ass (and I do appreciate all of your efforts in creating jscad, and that allowed me to come to this point)

**Comment by z3dev** [comment]
Performance improvements to mat4.isMirroring() completed.
