### ISSUE TITLE
v2: Unexpected color api

### ISSUE THREAD

**Issue by RedHatter** [jscad/OpenJSCAD.org#564]
Most jscad functions that take an object return a new object with the changes applied. I was surprised to discover that the color function modifies the original object. What's the reasoning behind this? Shouldn't the color function mach the rest of the api?

**Comment by z3dev** [comment]
A good point on consistency. It’s kind of 50/50 wether a **new** geometry should be returned.

Did you find this while converting an old design?

FYI, the color is set on the geometry object. We think that most designs work with colors at the geometry level. Thoughts?

**Comment by kaosat-dev** [comment]
thanks for the feedback @RedHatter ! That is indeed an error and should be fixed Imho, as it is , it makes having the same object in multiple colors impossible

**Comment by kaosat-dev** [comment]
@z3dev I think consistency (immutability) is more important than performance so we should change this
