### ISSUE TITLE
V2: Torus creates a sphere

### ISSUE THREAD

**Issue by RedHatter** [jscad/OpenJSCAD.org#567]
## Expected Behavior
I expect `primitives.torus` to create a torus.

## Actual Behavior
`primitives.torus` actually creates a sphere.

## Steps to Reproduce the Problem

```js
const { primitives } = require('@jscad/modeling')

function main () {
  return primitives.torus({ innerRadius: 10, outerRadius: 100 })
}
```

## Specifications

  - Version: 1b159c0
  - Platform: Ubuntu 20.04
  - Environment: Chrome

**Comment by z3dev** [comment]
@RedHatter excellent find!

It looks like our test suite for torus is not very good, as testing should have caught that. :(
