### ISSUE TITLE
V2: colors.colorize

### ISSUE THREAD

**Issue by RedHatter** [jscad/OpenJSCAD.org#572]
`require('@jscad/modeling').color.color()` is slightly confusing api wise (as noted in #419). I would like to propose `color.colorize()` as an alternative.

**Comment by kaosat-dev** [comment]
@RedHatter Thanks for the suggestion ! We also had doubts about the naming with @z3dev  and this is a very good solution ! What do you think @z3dev  ? (I like it !)

**Comment by z3dev** [comment]
I'd be glad to discuss again. :)

It's a good suggestion. But we need to decide if 'color' becomes 'colors'. We have decided both ways in the V2 Checklist #419 

I really think that 'color' should be 'colors', then you have a nice name space like...
`
const {colors, primitives} = require('@jscad/modeling')
let mysphere = colors.color(colors.hexToRgb('#000080'), primitives.sphere()) // navy blue
`
OR
`
const {color, hexToRgb} = require('@jscad/modeling').colors
const {sphere} = require('@jscad/modeling').primitives
let mysphere = color(hexToRgb('#000080'), primitives.sphere()) // navy blue
`

**Comment by RedHatter** [comment]
I like the color -> colors change. Keeps things consistent. I do still like `colors.colorize` though over `colors.color`.

**Comment by kaosat-dev** [comment]
I like both the namespace change and colorize aswell :)

**Comment by z3dev** [comment]
Cool! It looks like we have a plan then.

I did a preliminary analysis on the color => colors change. It's not that trivial as IO packages use color as well as tests suites.

**Comment by RedHatter** [comment]
I don't mind making the change. Shouldn't that hard with a few fancy sed commands.

**Comment by z3dev** [comment]
> I don't mind making the change. Shouldn't that hard with a few fancy sed commands.

I was hoping that you would... but maybe first, those lint changes need to be merged.

**Comment by z3dev** [comment]
@RedHatter your up...
- namespace change
- colorize changes

**Comment by RedHatter** [comment]
It's in progress.

**Comment by z3dev** [comment]
Done as part of #591
