### ISSUE TITLE
V2: should geometry clone() produce SHALLOW copies

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#573]
The clone functions of geom2/geom3/path2/poly3 produce DEEP copies of the data structures. This is unnecessary as these objects are immutable by design. All operations on these geometries create new copies, e.g. geom3.transform(), etc. Also, all higher level operations produce new geometries, e.g. subtract()

## Expected Behavior

New geometry is created which reuses the data structures. SHALLOW CLONE

For example with geom2, the sides and the transforms are passed on... like this.
```
const clone = (geometry) => {
  let out = create()
  out.sides = geometry.sides
  out.transforms = geometry.transforms
  return out
}
```

## Actual Behavior

The whole data structure is copied. DEEP CLONE
```
const clone = (geometry) => {
  let out = create()
  out.sides = geometry.sides.map((side) => {
    return [vec2.clone(side[0]), vec2.clone(side[1])]
  })
  out.transforms = mat4.clone(geometry.transforms)
  return out
}
```

## Steps to Reproduce the Problem

  1. clone any of the geometry objects

## Specifications

  - Version: V2
  - Platform: all
  - Environment: all

**Comment by z3dev** [comment]
actually, we could introduce the 'copy' function, which makes a shallow copy of the geometry. this is a common function in the glmatrix library, so we can follow the same.

 Logic:
- clone ~ 'create a new geometry initialized with the values from an existing geometry' (DEEP)
- copy ~ 'copy the values from one geometry to another' (SHALLOW)

**Comment by kaosat-dev** [comment]
Shallow clone in either seems like a bad idea to be honest, because if you mutate the original data , the copy is also changed, leading to unexpected results, which is not what a clone() should be doing

I kinda like the idea of COPY VS clone though:
but we do agree that the values inside the copy are not just references to the original data structure, but an actual copy ? 
```out.sides = geometry.sides``` would not work for example

**Comment by z3dev** [comment]
Recent changes have reworked the geometry objects to retain user assigned attributes, like color, name, etc. As a result, clone() is now shallow.

Closing.
