### ISSUE TITLE
V2: Errors starting web related to vtree, fails to render simple shapes

### ISSUE THREAD

**Issue by faithhack** [jscad/OpenJSCAD.org#576]
## Expected Behavior
'npm run dev' should start web and allow me to render a simple script

## Actual Behavior
Errors from missing modules in 'packages/vtree/core/modeling/primitives' 

## Steps to Reproduce the Problem
on Ubuntu 20.04
```
$ nvm use lts/carbon
Now using node v8.16.1 (npm v6.4.1)
$ git clone https://github.com/jscad/OpenJSCAD.org.git
$ cd OpenJSCAD.org; git checkout V2; npm install; npm run bootstrap; npm test
```
(all seems well)
```
$ cd packages/web
$ npm run dev
Error: Cannot find module './cylinderElliptic' from '/home/chris/lib/JSCAD-dev/OpenJSCAD.org/packages/vtree/core/modeling/primitives'
$ cd ../../packages/vtree/core/modeling/primitives
$ cp cylinder.js cylinderElliptic.js
```
(run again)
```
`Error: Cannot find module './roundedCylinder' from '/home/chris/lib/JSCAD-dev/OpenJSCAD.org/packages/vtree/core/modeling/primitives'`
(create roundedCylinder.js in packages/vtree/core/modeling/primitives based on roundedCuboid.js)
```
(run again)
```
`Error: Cannot find module './star' from '/home/chris/lib/JSCAD-dev/OpenJSCAD.org/packages/vtree/core/modeling/primitives'`
```
(copy 'roundedRectangle copy.js' to star.js in packages/vtree/core/modeling/primitives)

It runs this time!
However it fails to render any shapes with curves:
```
    return [
            torus(), 
            translate([0,5,0], cube()), 
            translate([0,10,0],cylinder()),
            translate([0,15,0], sphere())
           ]
```
![Screenshot from 2020-05-11 08-22-38](https://user-images.githubusercontent.com/42535/81564720-30a09900-9366-11ea-8ddb-f4d932337b7d.png)

so I am not sure my "fixes" are correct.

## Specifications

  - Version: V2 as of fb73090b88ca42e7534eceba73468b1944bb0806
  - Platform: Ubuntu 20.04
  - Environment: (browser, local server, node.js etc) Chromium, localhost, node v8.16.1

**Comment by faithhack** [comment]
A little additional info: the cli produces the correct results (except the torus looks like a sphere - I assume that is related to it's defaults). 
An export from the web app produces an stl that looks like the included image above.

**Comment by z3dev** [comment]
@faithhack there's a pull request to correct the vtree issues.

those inverted shapes are due to the new compact binary functions. there are no issues with the 2D geometries, only the 3D geometries.

**Comment by z3dev** [comment]
the final changes are part of #578, which corrects the compact binary functions.

**Comment by z3dev** [comment]
This should work now. Please pull the latest changes from V2 branch.
