### ISSUE TITLE
error in npm run dev

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#579]
## Expected Behavior
run dev web 

## Actual Behavior
fails with error
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at createTextureSet (regl.js:2600)
    at wrapREGL (regl.js:9157)
    at prepareRender (render.js:23)
    at viewer (viewer.js:57)
    at dom (main.js:19)
    at dom.js:10
    at invoke (invoke.js:19)
    at CombineSink.event (combine.js:131)
    at IndexSink.event (IndexSink.js:28)

## Steps to Reproduce the Problem

  1. npm run clean
  2. npm run bootstrap
  3. cd packages/web
 4. npm run dev
  5. open browser http://192.168.1.105:8081/

## Specifications

  - Version: V2
  - Platform: Windows
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment]
@hrgdavor welcome
Is this the latest V2 code? There was a recent fix.
Which browsers are you working with?

**Comment by hrgdavor** [comment]
Dammit,

sorry, my fault... I was using brave and it Fingerprint protection did something to it to fail.

I should have tried Chrome and FF before posting ticket...
Chrome and FF work, and now Brave also works after disabling protections.

**Comment by kaosat-dev** [comment]
Hi @hrgdavor  !
Thanks for the feedback !
I am a bit surprised, I also use Brave , even for dev work on Jscad, and have not had issues before, which version of Brave are you using ? (I am a bit behind on updates, so might have dodge a bullet)

**Comment by hrgdavor** [comment]
Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by kaosat-dev** [comment]
thanks @hrgdavor ! Will investigate !
