### ISSUE TITLE
objects completely broken #V2

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#580]
## Expected Behavior
cylinder

## Actual Behavior
messed up triangles

## Steps to Reproduce the Problem

  1. load simple project

const jscad = require('@jscad/modeling')
const { cuboid, sphere, cylinder, circle, star } = require('@jscad/modeling').primitives
const main = () => {
  return [
    cylinder({ radius: 1 }),
  ]
}
module.exports = { main }

  2.
  3.

## Specifications

  - Version: v2
  - Platform: Windows
  - Environment: browsers: Chrome, FF

**Comment by hrgdavor** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/2480762/82020939-5097cb80-968a-11ea-8a3d-07dd7f07a310.jpg)

**Comment by z3dev** [comment]
@hrgdavor thanks

Also reported in #576 
I have already added a pull request to fix this #578 
Hold on...

**Comment by hrgdavor** [comment]
sorry to bother u, but I tried to switch to the branch with the fix, (v2-fix-compact-binaries)
did npm run clean
npm run bootstrap
went into packages/web
npm run dev


```
Error: Cannot find module './cylinderElliptic' from 'C:\wrk\OpenJSCAD.org\packages\vtree\core\modeling\primitives'
    at C:\wrk\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\wrk\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\wrk\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\wrk\OpenJSCAD.org\packages\web\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (fs.js:166:21) {
  stream: [Labeled]
```

**Comment by z3dev** [comment]
@hrgdavor You are fast...

OK. Once again, pull the latest updateds on that branch (v2-fix-compact-binaries)
I think that will work now.

**Comment by hrgdavor** [comment]
nice, it works now on that branch :) :) :)

**Comment by z3dev** [comment]
This should work now. Please pull the latest changes from V2 branch.
