### ISSUE TITLE
shape extruded from points causes infinite render if there are duplicate points  #V2

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#584]
## Expected Behavior
extrude a cuboid from points

## Actual Behavior
render hangs indefinitely

## Steps to Reproduce the Problem

  1. packages/web
  2. npm run dev
  3. load sample code

pausing worker in debug sees code stuck most of the time in 
module:modeling/geometry/poly3.measureBoundingBox

## Specifications
This also happens on some more complex lines where it is harder to reason why,
so I am hoping that solving this issue will help with those more complex shapes too.

sample stack:
```
module:modeling/math/vec3.max
module:modeling/geometry/poly3.measureBoundingBox
module:modeling/geometry/poly3.measureBoundingSphere
_splitByPlane
splitByPlane
addPolygonTreeNodes
```

code that works
```
function main(params){
  var points = [[1,1],[5,1],[5,5],[1,5]];
  points = geometry.geom2.fromPoints(points);
  return jscad.extrusions.extrudeLinear({height:1},points);
}
```
add a point to points
```
  var points = [[1,1],[5,1],[5,5],[1,5],[1,1]];
```
and it hangs

  - Version: V2
  - Platform: all
  - Environment: Brave, Firefox

**Comment by z3dev** [comment]
@hrgdavor thanks

By definition, 2D geometry cannot overlap. So, that closing end point [1,1] is going to cause issues later. This definition allows for the 2D geometry to support holes.

You can use the same points for 2D paths, without issues. And, if you look at the 2D path then the last point is gone, and the isClosed flag is ‘true’.

Does that help?

**Comment by hrgdavor** [comment]
ok, this one is easy to fix, so I'll have to find another example where I have same issue and the last and first is not same .. (I will check there if maybe I have same point twice or similar issue).

I also had issue if I run the points in oposite direction array.reverse() ... the extrusion would have walls inverted suvh that it would render like it is hollow (faces in wrong direction, so the dissapear while rotating).

Basically I need one of two
 1) function that would get me from list of points to a good extrusion 
(one would cleanup my path so I can get expected extrusion, delete last point if it is identical to last) 

 2) a guide what to avoid to not break the extrusion 
(constraints to know when generating 2d path to extrude so I know to avoid cases that will cause issues)

The issues I am having are from porting code from V1 to V2, as I am looking to switch to V2 for ongoing projects, but I have still issues to overcome.

**Comment by hrgdavor** [comment]
here is an example that breaks in V2 and works in V1 and first and last point are not same.

shape without arc works
```
[[-10,0],[-10,0.8],[0,1.5],[8,5],[9,5],[9,0]]
```
![Screenshot_2](https://user-images.githubusercontent.com/2480762/82141502-74981000-9836-11ea-9895-8d86bfd66548.jpg)

......
.....

shape with arc breaks in V2
```
[[-10,0],[-10,0.8],[0,1.5],[0,1.5],[0.83,2.24],[1.73,2.91],[2.68,3.49],[3.68,3.98],[4.72,4.38],[5.79,4.69],[6.89,4.89],[8,5],[8,5],[9,5],[9,0]]
```
![Screenshot_1](https://user-images.githubusercontent.com/2480762/82141498-71048900-9836-11ea-8e83-b44a86f840e1.jpg)
it looks like thins in V1

**Comment by z3dev** [comment]
Ok. The set of points are very different. How are you creating those points?

**Comment by hrgdavor** [comment]
Ok, I found the issue. Not sure why I did not notice it immediately, but I have two instances of repeating same point: close to the begining `[0,1.5]` and `[8,5]` close to end

the resulting arc id added by a utility function. It was duplicating the first and last point of the section when it was adding the arc.

![Screenshot_1](https://user-images.githubusercontent.com/2480762/82143699-107d4800-9846-11ea-8468-a38e66772c89.jpg)
Screenshot  above shows debug output of my eperimental 2D shape utility.

I am experimenting with my own utility for doing 2D shapes for extrusion (I tend do extrusions often as it simplifies some shapes that would require multiple CAG ops).
Yellow line is original line, red line is after modifier like arc are executed on sections, and blue cylinders are final set of points.

The conclusion is for both of my cases that do not work it is **a simple mistake** of having **same point repeated** due to bugs in code generating the line before extruding. This is simple to avoid and I can easily add this to my function that does the steps to check and remove such points.

Well at lest if somebody else has this problem this ticket will be useful :)

**Comment by z3dev** [comment]
The check of first and last points would be easy. What do you think?

**Comment by hrgdavor** [comment]
Yes check of first and last point would help in cases like the original example I gave me and is not expensive to add.


Hm, there is also a question of precision. I was able to remove duplicates in points I generate after reducing them to 2 decimal points, though this issue is specific to me.

After that said, I wonder: What is recommended precision for openjscad?

**Comment by z3dev** [comment]
@hrgdavor there was an enhancement to the geom2.fromPoints() function to allow the same start and end points.
If this is resolved then please close this issue.

> After that said, I wonder: What is recommended precision for openjscad?
It's not really about precision, but scale of the shapes due to the use of floating point numbers. The booleans work best from 1~200 units (mm for 3D printers).

**Comment by hrgdavor** [comment]
cool, works now with the same start and end points.
