### ISSUE TITLE
color not applied on simple example sphere #V2

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#585]
## Expected Behavior
red sphere

## Actual Behavior
default color sphere

## Steps to Reproduce the Problem

  1. packages/web
  2. npm run dev
  3. run simple example sphere code

## Specifications
```
function main(params){
  return jscad.color.color([1,0,0], sphere())
}
```

I am aware refactor is in progress on color->colorize ... maybe check this after refactor
  - Version: V2
  - Platform: all
  - Environment: Brave, Firefox

**Comment by z3dev** [comment]
This should work now. Please pull the latest changes from V2 branch.

**Comment by hrgdavor** [comment]
works in V2 branch, and compactBinary stuff too  :) thanks
