### ISSUE TITLE
please allow ES6 language features

### ISSUE THREAD

**Issue by SebiTimeWaster** [jscad/OpenJSCAD.org#586]
## Expected Behavior
i can use trailing commas

## Actual Behavior
i cannot use trailing commas

## Steps to Reproduce the Problem
try to use trailing commas

**Comment by z3dev** [comment]
I use trailing commas often when writing quick and dirty designs. No problems.

Are you using the website?

**Comment by SebiTimeWaster** [comment]
yes, i do, is there something else?

**Comment by z3dev** [comment]
Just wondering.

So, what's the issue? The web should work just fine, but it depends on the browser. The browser provides the JavaScript interpreter. What are you using?

**Comment by SebiTimeWaster** [comment]
I use Chrome, but to be honest it does not matter, trailing commas are supported since ES 5 and even IE 9 had them.

**Comment by z3dev** [comment]
Why do you say that it's not supported? Because the editor flags them as errors?

**Comment by hrgdavor** [comment]
It works for arrays, i am sure. Maybe you have issue when using functions like translate. ES says its ok for arrays, but functions will get an extra param undefined if u use trailing comma. Translate, union, difference will fail if usin trailing comma. To use ES to allow trailing comna you can use array wrapper:

` ` `
union(... [
  sphere(),
   sphere(),
]) 
` ` `

**Comment by SebiTimeWaster** [comment]
@hrgdavor that explains it, thx. 
apparently we have a babel plugin in our project that allows this, i am so used to it that i thought trailing commas means trailing commas everywhere (and i don't want to miss it ever again...).

your proposal would actually be a nice solution for this...

**Comment by z3dev** [comment]
You’ll both be happy, because V2 functions accept individual arguments.

`union(a,b,c,d)`

Or arrays

`union([a,b,c,d])`

**Comment by SebiTimeWaster** [comment]
awesome! is there an ETA for V2 you can communicate?
