### ISSUE TITLE
V2 : cli could not be executed

### ISSUE THREAD

**Issue by minatani** [jscad/OpenJSCAD.org#589]
## Expected Behavior
Cli works properly.

## Actual Behavior
Cli could not executed at 828394ddb88fc1139b1daf155548aa9fab7de823.
(The package might not be well organized.)

## Steps to Reproduce the Problem

  1.
$ git checkout V2; npm install; npm run bootstrap; npm test

  2.
$ nodejs ~/git/openjscad.org/packages/cli/cli ./binder-test.js -o ../stl/binder-test.stl
JSCAD: generating output
 from:  binder-test.js
 to: ../stl/binder-test.stl (STereoLithography, Binary)

{ Error: Cannot find module '@jscad/modeling'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/expshare/storage/jscad/binder-test.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3) code: 'MODULE_NOT_FOUND' }
$

**Comment by z3dev** [comment]
This is running from a developer environment, so you have to run from the CLI directory; OpenJSCAD.org/packages/cli

**Comment by skyl** [comment]
> This is running from a developer environment, so you have to run from the CLI directory; OpenJSCAD.org/packages/cli
> 
> ```
> cd ~/git/openjscad.org/packages/cli
> nodejs ./cli.js ./binder-test.js -o ../stl/binder-test.stl
> ```

Hi, thanks for the tip; even running in the cli directory it doesn't work as noted in duplicate #600

**Comment by z3dev** [comment]
@skyl there was a major name change to the 'colors' module, which broke some things internally.

please pull the latest V2 and try again. i just applied another patch.

**Comment by minatani** [comment]
Thank you for your attention on this issue.
It seems to be not solved at the latest V2 (f3211c0e3b9ea6728407241c2bfaa997a9178ea8).
I think this problem was occured between 2b5183e3f65e2a44752ddd30d4c73ced1e5baf29 and 828394ddb88fc1139b1daf155548aa9fab7de823.

**Comment by z3dev** [comment]
@minatani please supply the output again.

I tested with the latest V2. Everything is working fine.

**Comment by minatani** [comment]
Please check below.
binder-test.js is a testing code which I mentioned at #570 .

~/git/openjscad.org/packages/cli$ nodejs ./cli ~/storage/jscad/binder-test.js -o ~/stor

JSCAD: generating output
 from:  /home/expshare/storage/jscad/binder-test.js
 to:  /home/expshare/storage/stl/binder-test.stl (STereoLithography, Binary)

{ Error: Cannot find module '@jscad/modeling'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/expshare/storage/jscad/binder-test.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3) code: 'MODULE_NOT_FOUND' }
~/git/openjscad.org/packages/cli$

I don't know detail of npm packaging system well so I might make some misconduct.

**Comment by z3dev** [comment]
It's close.

Please run these commands.

```
cd ~/git/openjscad.org
npm run clean (You must answer "Y" to the question)
npm run bootstrap
npm test
```

If all goes well then the test suite will pass.

Then, please try CLI again.

**Comment by minatani** [comment]
Finally I seem to hit the core of this issue.
The code below works well.
(The binder-test.js is a test script of #570, so many NaN are printed badly, but in this #589's context it is not matter.)
The key is a directory an input file is placed.
I had placed the binder-test.js out of openjscad.org/packages/cli, now I placed it in this directory.

$ cp ~/storage/jscad/binder-test.js ./
$ nodejs ./cli binder-test.js -o ~/storage/stl/binder-test.stl
cp ~/storage/jscad/binder-test.js ./
JSCAD: generating output
 from: binder-test.js
 to: /home/expshare/storage/stl/binder-test.stl (STereoLithography, Binary)

y pos: 0, Area: 2119.3960341600755, Bounds: 0,-4.75,-0.5,100,4.75,0.5, Volume: 918.8502466189506

y pos: 0.1, Area: 2119.3960352091794, Bounds: 0,-4.650000095367432,-0.5,100,4.849999904632568,0.5, Volume: 918.850245295189

y pos: 0.2, Area: 2119.396034497149, Bounds: 0,-4.550000190734863,-0.5,100,4.949999809265137,0.5, Volume: 918.8502463007035

y pos: 0.30000000000000004, Area: 2118.6048976514753, Bounds: 0,-4.449999809265137,-0.5,100,5.050000190734863,0.5, Volume: 918.8502439008802

y pos: 0.4, Area: 2118.6048907689556, Bounds: 0,-4.349999904632568,-0.5,100,5.150000095367432,0.5, Volume: 918.8502473475542

y pos: 0.5, Area: 2119.3959444156785, Bounds: 0,-4.25,-0.5,100,5.25,0.5, Volume: 918.8502457010868

y pos: 0.6, Area: NaN, Bounds: 0,-4.150000095367432,-0.5,100,5.349999904632568,0.5, Volume: 918.850247132975

y pos: 0.7, Area: 2118.3715885676015, Bounds: 0,-4.050000190734863,-0.5,100,5.449999809265137,0.5, Volume: 918.8502530404409

y pos: 0.7999999999999999, Area: NaN, Bounds: 0,-3.950000047683716,-0.5,100,5.550000190734863,0.5, Volume: 918.8502596073905

y pos: 0.8999999999999999, Area: NaN, Bounds: 0,-3.8499999046325684,-0.5,100,5.650000095367432,0.5, Volume: 918.8502462744733

y pos: 0.9999999999999999, Area: NaN, Bounds: 0,-3.75,-0.5,100,5.75,0.5, Volume: 918.8502466793348

y pos: 1.0999999999999999, Area: NaN, Bounds: 0,-3.6500000953674316,-0.5,100,5.849999904632568,0.5, Volume: 918.8502459412603

y pos: 1.2, Area: NaN, Bounds: 0,-3.549999952316284,-0.5,100,5.949999809265137,0.5, Volume: 918.850226839214

y pos: 1.3, Area: NaN, Bounds: 0,-3.450000047683716,-0.5,100,6.050000190734863,0.5, Volume: 918.8502634587122

y pos: 1.4000000000000001, Area: NaN, Bounds: 0,-3.3499999046325684,-0.5,100,6.150000095367432,0.5, Volume: 918.8502417385671

y pos: 1.5000000000000002, Area: NaN, Bounds: 0,-3.25,-0.5,100,6.25,0.5, Volume: 918.8502432917679

y pos: 1.6000000000000003, Area: NaN, Bounds: 0,-3.1500000953674316,-0.5,100,6.349999904632568,0.5, Volume: 918.8502455080442

y pos: 1.7000000000000004, Area: NaN, Bounds: 0,-3.049999952316284,-0.5,100,6.449999809265137,0.5, Volume: 918.8502307906864

y pos: 1.8000000000000005, Area: NaN, Bounds: 0,-2.950000047683716,-0.5,100,6.550000190734863,0.5, Volume: 918.8502654973489

y pos: 1.9000000000000006, Area: NaN, Bounds: 0,-2.8499999046325684,-0.5,100,6.650000095367432,0.5, Volume: 918.8502454141769

y pos: 2.0000000000000004, Area: NaN, Bounds: 0,-2.75,-0.5,100,6.75,0.5, Volume: 918.8502403192497

y pos: 2.1000000000000005, Area: NaN, Bounds: 0,-2.6500000953674316,-0.5,100,6.849999904632568,0.5, Volume: 918.8502450097537

y pos: 2.2000000000000006, Area: 2118.371338503303, Bounds: 0,-2.549999952316284,-0.5,100,6.949999809265137,0.5, Volume: 918.8502345393318

y pos: 2.3000000000000007, Area: 2118.371434824409, Bounds: 0,-2.450000047683716,-0.5,100,7.050000190734863,0.5, Volume: 918.8502634772797

y pos: 2.400000000000001, Area: NaN, Bounds: 0,-2.3499999046325684,-0.5,100,7.150000095367432,0.5, Volume: 918.8502405812686

y pos: 2.500000000000001, Area: NaN, Bounds: 0,-2.25,-0.5,100,7.25,0.5, Volume: 918.8502428005027

y pos: 2.600000000000001, Area: NaN, Bounds: 0,-2.1500000953674316,-0.5,100,7.349999904632568,0.5, Volume: 918.8502488915908

y pos: 2.700000000000001, Area: 2118.3713358883074, Bounds: 0,-2.049999952316284,-0.5,100,7.449999809265137,0.5, Volume: 918.8502309740544

y pos: 2.800000000000001, Area: 2118.3714317036597, Bounds: 0,-1.9500000476837158,-0.5,100,7.550000190734863,0.5, Volume: 918.8502623214841

y pos: 2.9000000000000012, Area: NaN, Bounds: 0,-1.8499999046325684,-0.5,100,7.650000095367432,0.5, Volume: 918.8502427359307
$


In binder-test.js, these lines may make problem.

const { cuboid, cylinder } = require('@jscad/modeling').primitives
const { translateX, translateY } = require('@jscad/modeling').transforms
const { subtract } = require('@jscad/modeling').booleans
const { measureArea, measureBounds, measureVolume } = require('@jscad/modeling').measurements

**Comment by z3dev** [comment]
@minatani nice detective work.

Ok. So, a script outside the CLI directory has issues running. I’ll investigate further now.

**Comment by minatani** [comment]
Situation may be become worse.
Now the cli also can not be executed in packages/cli directory.

**Comment by z3dev** [comment]
@minatani did you pull a recent version of the V2 branch?

There has been changes so please rebuild.
```
npm run clean
rm -rf node_modules
npm install
npm run bootstrap
npm Test
```

**Comment by z3dev** [comment]
Just some feed back... Node.js has specific logic when looking for modules. So this command will not work, as Node.js does not look outside of the current directory (and sub-directories).

`node cli.js ../examples/testV2.js -o foo.svg`

The best way to organize designs is by creating a folder, and putting all the code (pieces) into that folder.

- folder
  - index.js
  - part1.js
  - part2.js

**Comment by minatani** [comment]
Sorry, my choppy response.
But until now, I have no idea on this issue.


$ git clone https://github.com/jscad/openjscad.org.git && cd openjscad.org/ && git checkout V2 && npm install && npm run bootstrap && npm test && cd packages/cli/ && nodejs cli.js ../examples/testV2.js -o testV2.svg



JSCAD: generating output
 from:  ../examples/testV2.js
 to:  testV2.svg (Scalable Vector Graphics Format)

{ Error: Cannot find module '@jscad/modeling'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/expshare/git/openjscad.org/packages/examples/testV2.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3) code: 'MODULE_NOT_FOUND' }

**Comment by z3dev** [comment]
This is not possible as Node.js cannot look backwards from the current directory.

`../examples/testV2.js`

Please copy the examples to the current directory, or link examples to the current directory.

`cp -R ../examples .`

Or

`ln -s ../examples ./examples`

**Comment by minatani** [comment]
Thank you for your step by step guidance.
Finally I confirmed the issue was solved.
