### ISSUE TITLE
All Lerna runs fail with "lerna: Permission denied"

### ISSUE THREAD

**Issue by SebiTimeWaster** [jscad/OpenJSCAD.org#590]
## Expected Behavior
i can run scripts

## Actual Behavior
All Lerna runs fail with "lerna: Permission denied"

## Steps to Reproduce the Problem

  1. git clone
  2. run npm install
  3. run npm run web

## Specifications

  - Version: master / V2 branch, fresh pull
  - Platform: Ubuntu 20.04
  - Environment: node.js

i tried master and V2 branch, i tried setting 777 rights, i tried running it per sudo, nothing changes the outcome. searching online yields no result whatsoever, no one seem to have this problem.

log (which is not helpful at all):
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'clean' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle @jscad/openjscad@1.6.1~preclean: @jscad/openjscad@1.6.1
6 info lifecycle @jscad/openjscad@1.6.1~clean: @jscad/openjscad@1.6.1
7 verbose lifecycle @jscad/openjscad@1.6.1~clean: unsafe-perm in lifecycle true
8 verbose lifecycle @jscad/openjscad@1.6.1~clean: PATH: [...redacted]
9 verbose lifecycle @jscad/openjscad@1.6.1~clean: CWD: /home/bla/OpenJSCAD.org
10 silly lifecycle @jscad/openjscad@1.6.1~clean: Args: [ '-c', 'lerna clean' ]
11 silly lifecycle @jscad/openjscad@1.6.1~clean: Returned: code: 126  signal: null
12 info lifecycle @jscad/openjscad@1.6.1~clean: Failed to exec clean script
13 verbose stack Error: @jscad/openjscad@1.6.1 clean: `lerna clean`
13 verbose stack Exit status 126
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @jscad/openjscad@1.6.1
15 verbose cwd /home/bla/OpenJSCAD.org
16 verbose Linux 5.4.0-31-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "clean"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 126
22 error @jscad/openjscad@1.6.1 clean: `lerna clean`
22 error Exit status 126
23 error Failed at the @jscad/openjscad@1.6.1 clean script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 126, true ]
```

**Comment by z3dev** [comment]
It looks like you missed a few steps. Please see https://openjscad.org/dokuwiki/doku.php?id=early_v2

**Comment by SebiTimeWaster** [comment]
no, i did not skip anything, this is a rights problem i did not understand yet.
i just found out when i move (copy) the project into my home directory it runs fine, but since it lies on a mounted second disk it produces this error. 
but i run other projects from that disk without problems, just lerna fails.

**Comment by z3dev** [comment]
Cross disks... hmm... I would have expected the file system to handle that easily.

I suspected something was missed because of "@jscad/openjscad@1.6.1", which is an old V1 version. That should not be possible in V2, as the version numbers have changed across all the modules.

**Comment by SebiTimeWaster** [comment]
> I would have expected the file system to handle that easily.
yes, me too. and since the log is not helpful at all i have no clue what lerna tries to access that fails.

i just double checked, i am on the V2 branch, and i killed and recreated my node_modules directory, but it still shows "@jscad/openjscad@1.6.1", no clue why...

**Comment by z3dev** [comment]
This might have something to do with local vs. global installation of lerna. For me it helps to run lerna bootstrap, wait for the EPERM error, close the terminal and run lerna bootstrap again.

Another thing that might work is to run lerna clean.

Also watch out for any running scripts - that can lock up some dependencies making you unable to remove them without admin rights. Especially watch scripts.

I'm on Windows using git bash.

=============

Found that on stack exchange... the interesting point was the “running scripts” part. There may be a running process blocking the file system.

Have you tried running “npm run clean”?

**Comment by SebiTimeWaster** [comment]
i checked there is nothing running. and clean shows the same. i give up, i moved it to my home directory. @z3dev thx for the help!

**Comment by SebiTimeWaster** [comment]
i ran into the same problems with browserify, the only solution i found is to fully qualify the call:
`node node_modules/browserify/bin/cmd.js ...args`
this is some really quirky rights problem under linux.
