### ISSUE TITLE
Blocks variables not working

### ISSUE THREAD

**Issue by RobBott** [jscad/OpenJSCAD.org#592]
## Expected Behavior
To be able to rename and create new variables when using blocks

## Actual Behavior
In blocks all variables are named item and clicking new variable and rename variable have no effect.  Makes blocks pretty much unusable.

## Steps to Reproduce the Problem

  1. Use desktop openjscad
  2.click blocks - new window
  3.click variables - set item block
  4. Click the variable item dropdown carrot in the variable block to get rename and/or new variable options. Click an option and nothing happens

## Specifications

  - Version: Alpha
  - Platform: Windows 10 x64
  - Environment: (browser, local server, node.js etc) App

**Comment by z3dev** [comment]
@RobBott can you provide a screen shot?

I keep scratching my head on this one as JSCAD doesn’t have any ‘blocks’.

**Comment by RobBott** [comment]
Yikes.  I hardly even remember this over a year later.  I just hopped on
http://openjscad.azurewebsites.net/ and there are blocks.  Lol not sure
what's going on on your end but blocks are there.  A year late and you are
scratching your head about blocks?????  Blocks are in the top middle of
this screenshot!
[image: image.png]

**Comment by z3dev** [comment]
Ahhh… I see. That little piece of mess was created by a user. JSCAD does not maintain anything there.

I’ll see if the user can take that down now. It causes a lot of pain.

**Comment by z3dev** [comment]
Update: I asked Azure to take that application down, as it is very confusing for users and unmaintained.

FYI, I did find another 'blocks' based UI that uses JSCAD V1. And this one is maintained as well.

https://makecode.buildbee.com/

**Comment by RobBott** [comment]
Thank you

**Comment by z3dev** [comment]
The old website application is gone now. Closing.
