### ISSUE TITLE
V2 color lost if translate sphere

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#594]
## Expected Behavior
translated red sphere

## Actual Behavior
translated default color sphere

## Steps to Reproduce the Problem

  1. packages/web
  2. npm run dev
  3. run simple example sphere code

## Specifications
```
function main(params){
  return translate([1,0,0],color([1,0,0], sphere()))
}
```
fails

```
function main(params){
  return color([1,0,0],translate([1,0,0], sphere()))
}
```
works and sphere is red

  - Version: V2
  - Platform: all
  - Environment: Brave, Firefox

**Comment by z3dev** [comment]
Correct.  Color has to be applied as the last step.

I’ll keep this open, as other users might want to comment.

**Comment by hrgdavor** [comment]
yeah, It is not  a problem to work around, but a step forward be to make a decision
 - to fix if feasible (may be too much trouble)
 - decide to leave it and document it in migration guide

Sry bout this ..., one unrelated question: is there a link with API docs for parameters for the functions.. right now I am looking into the source. Can I maybe build docs since I have the source checked out ?

**Comment by z3dev** [comment]
You can build the API docs. :)

`npm run docs`

There will be a set of HTML files created in the ‘out’ directory.

**Comment by BarbourSmith** [comment]
I want to add another voice in favor of color being preserved through operations. 

My workflow involves making a lot of things like libraries for bolts and whatnot when then lose their color when imported and used in a project.

I'm guessing that if this hasn't been done by now it's probably difficult to do though

**Comment by crysislinux** [comment]
I couldn't see any workaround to this problem when assembling parts together. Only the big parts in the last assembling step can have color. But parts of big parts cannot have any colors.

**Comment by z3dev** [comment]
@crysislinux and folks

Keep in mind that many pieces can be returned from a design, each having colors.

**Comment by z3dev** [comment]
> My workflow involves making a lot of things like libraries for bolts and whatnot when then lose their color when imported and used in a project.

Not really. It depends on what’s being done with the parts.
Not everyone wants a black bolt or a gold bolt either.

> Doesn't this make it impossible to generate the two tone jscad logo?

The two tone piece was not by choice. It was a result of boolean operations. That little piece of ‘functionality ‘ always drove me crazy. It’s not coming back.

**Comment by BarbourSmith** [comment]
If not the V1 behavior, what would be the ideal behavior of subtract(A,B) where A and B are different colors? The result is the color of A?

**Comment by crysislinux** [comment]
> Keep in mind that many pieces can be returned from a design, each having colors.

Yeah, that's why I said:

> Only the big parts in the last assembling step can have color as a whole. But parts of big parts cannot have any colors.

translate is required when assembling parts together, then you can only specify colors for parts in the final step.

After all, this is a really great thing to have, if it's adorable.

**Comment by z3dev** [comment]
> If not the V1 behavior, what would be the ideal behavior of subtract(A,B) where A and B are different colors? The result is the color of A?

Now, V2 does not set a color after operations.

Ideal color after booleans? I don't think there is one. The old V1 boolean operations were just weird.

**Comment by BarbourSmith** [comment]
It makes sense to me that most of the boolean operations would have a clear behavior when it comes to color, or at least an answer which is more user intuitive than no color at all.

I guess union would be the tricky one, because looking at the way color works there isn't a way for an object to have multiple colors.

If the decision is that the way things work now is the way things will stay, should we tag this as "wontfix" or close the issue? Personally I liked the way color in V1 worked better, although I agree it was weird for sure 😛

**Comment by z3dev** [comment]
Visually, V1 might be better at times.

But colors really need to be applied per solid for 3D printing. Many of the slicers use colors to determine which filament to select, and produce multi-color prints. The focus of JSCAD is still 3D printing. 👍

**Comment by crysislinux** [comment]
It's actually fine to lost colors when doing transformations. It's useful when designing the parts. But we can have a `main` function for each part and work with a standalone part at a time most of the time.

Off-topic, 

@z3dev could you please take a look at https://github.com/jscad/OpenJSCAD.org/issues/719 is that a limitation or bug?

**Comment by z3dev** [comment]
I've been thinking about this further. Basically, there are some 'operations which produce a new geometry.
- extrusions
- expansions
- hull
It's pretty clear that these would produce a new geometry without 'color'.

Next up are the booleans (union, subtract, intersect) which also produce a new geometry. (Forget V1 behaviour please.) So, I still think that a new geometry without 'color' is the best behaviour. If not then the boolean operations will be slower to retain color at the 'polygon' level.

Last are the transforms (align, center, mirror, rotate, scale, translate) which basically become a 'transform' on the geomtry, e.g. newgeometry = geom3.transform(matrix, oldgeometry). I think these could retain 'color' (and other attributes).

I think this makes working with parts (especially those with color) slightly easier.

**Comment by z3dev** [comment]
@hrgdavor @crysislinux @BarbourSmith

This is fixed. Please try the latest release of JSCAD.

**Comment by hrgdavor** [comment]
The transforms now preserve color. This issue is fixed :)

**Comment by johnwebbcole** [comment]
I'd like to add that the change in the way colors are handled impacts me a lot.  I often will color one part before a boolean operation so I can see that it was properly done.  For example coloring all the hole solids red before subtracting them from the main object, which now has the holes lined in red.

For 3d printing and selecting filaments by color, the change also hurts me there.  Assembling a complex object with boolean operations and losing the color info makes V2 almost useless for this case.

It would be nice if all of the operations had an option to retain the v1 color behavior, is that a possibility?

**Comment by hrgdavor** [comment]
@johnwebbcole rendering I think still supports colorPerVertex. I think someone would need to port booelans from v1 to use functional style (instead of being part of classes) and then simply use that boolean when you need preview for the boolean operation with colors. You are not limited to jscad when writing jscad scripts, you can use any js library, so you might find a variant of csg.js that has the booleans that would keep color info.

**Comment by RuneSP** [comment]
It seems that color is lost when applying a mirror transformation on a geom2 object, but not on a path2 object. I'm not sure if this is desired, but its a bit confusing. For my application I'm generating a 2D design based on various parameters. Sometimes I need to mirror the whole design which is easily done as the last step, but some of the geometries (geom2) are not retaining the color. I'm exporting the design to DXF files for laser cutting where I'm using the color of the lines to control how the laser should cut the lines.

**Comment by z3dev** [comment]
> It seems that color is lost when applying a mirror transformation on a geom2 object, but not on a path2 object. I'm not sure if this is desired, but its a bit confusing. For my application I'm generating a 2D design based on various parameters. Sometimes I need to mirror the whole design which is easily done as the last step, but some of the geometries (geom2) are not retaining the color. I'm exporting the design to DXF files for laser cutting where I'm using the color of the lines to control how the laser should cut the lines.

@johnwebbcole can you open a new issue for this? It really doesn't make sense to open an issue from two years ago.
