### ISSUE TITLE
Integration with Global context of browser

### ISSUE THREAD

**Issue by Evgsurf** [jscad/OpenJSCAD.org#601]
## Expected Behavior
I would like to have access to global functions and variables

## Actual Behavior
There is Runtime error at attempt to call global function

## Steps to Reproduce the Problem

I used viewer-options.html from WEB at browser
  1. I added code into  viewer-options.html 
```
<script>
function globalF()
{
console.log("Global context");
 }
</script>
```

  2. I added into JSCAD file into main function 
`globalF();`

  3.  Looks like system tries to call globalF twice for one page loading. 
It is ok for first time and it is runtime error **VM4:108 Uncaught ReferenceError: globalF is not defined** at second time

## Specifications
  - Version: 1.10.0
  - Platform: Ubuntu 19.04 x64
  - Environment: Chrome 83.0.4103.61

**Comment by Evgsurf** [comment]
There is an screenshot. 
![rter](https://user-images.githubusercontent.com/853852/84042137-6066af00-a9ad-11ea-8b4b-894527bbaaf3.png)
![rter](https://user-images.githubusercontent.com/853852/84042207-707e8e80-a9ad-11ea-8b9f-ef47f11bbe32.png)

**Comment by Evgsurf** [comment]
This is an screenshot 
![rter](https://user-images.githubusercontent.com/853852/84042255-7f654100-a9ad-11ea-88a4-7ab6c8e3eae7.png)

**Comment by z3dev** [comment]
It’s one of the ‘features’ of the website. In order to allow the user to interact with the UI, the processing is performed in webworkers. Webworkers do not have access to global functions or data.

**Comment by Evgsurf** [comment]
It is really very convoluted piece of browser functionality. So , I have to think a lot of time now :) Thank You
