### ISSUE TITLE
V2: npm install fails on Windows

### ISSUE THREAD

**Issue by picklit** [jscad/OpenJSCAD.org#614]
[2020-07-03T00_10_55_708Z-debug.log](https://github.com/jscad/OpenJSCAD.org/files/4867724/2020-07-03T00_10_55_708Z-debug.log)
## Expected Behavior
npm install completes successfully with no Errors

## Actual Behavior
npm install fails with:  

npm ERR! Unexpected end of JSON input while parsing near '...ventional-changelog-a'

## Steps to Reproduce the Problem

  1. clone the OpenJSCAD.org github repository
  2. git checkout V2
  3. npm install

## Specifications

  - Version: 2  (commit  abb9c833e4a28c8070c2ee0d8f88fed80710a73f )
  - Platform: Windows 10
  - Environment: (browser, local server, node.js etc)
     node.js v12.18.2
     npm 6.14.5

**Comment by z3dev** [comment]
@picklit thanks
sadly, i don't have a PC with windows installed. however, i'm willing to help out. :)

can you try changing this line in package.json?
    "lerna": "3.19.0",
to
    "lerna": "3.22.1",

I'm hoping that a newer version of Lerna works on windows.

**Comment by z3dev** [comment]
Hmm... I'm not sure but it seems that the fetch of the package manifest from NPM.org failed.
```
4810 silly resolveWithNewModule semver@6.3.0 checking installable status
4811 http fetch GET 304 https://registry.npmjs.org/conventional-changelog-angular 1467ms (from cache)
4812 silly fetchPackageMetaData error for conventional-changelog-angular@^5.0.3 Unexpected end of JSON input while parsing near '...ventional-changelog-a'
...
```
I have never seen this before so please try the install several times. You may have to delete the contents of 'node_modules' directory before running again.

**Comment by z3dev** [comment]
@picklit any luck getting the 'npm install' to complete?

**Comment by z3dev** [comment]
@picklit can you try the latest V2 branch? All the development dependencies have been updated so things should work better now.

**Comment by z3dev** [comment]
@picklit have you tried the latest version of V2?

I was able to install V2 on Windows 10. No issues with the installation.
