### ISSUE TITLE
better doc on  @jscad/core

### ISSUE THREAD

**Issue by zfan40** [jscad/OpenJSCAD.org#617]
Hi team, thanks for the great efforts on the fantastic library.
I used to use the lib as jscad.compile(script, params), well after the updates, it doesn't work that way any more.
and I guess @jscad/core is the right way to execute the compile function.
The usage has little information on that. Could you please add more details on the usage.

Sorry if I am abusing the issues section and please feel free to close the issue.

Regards

**Comment by z3dev** [comment]
@zfan40 no problem.

the building of the script (from pieces) and parameters is slightly different between CLI and WEB. Are you looking for a WEB solution?

**Comment by zfan40** [comment]
@z3dev yes I am looking for the web solution.

**Comment by z3dev** [comment]
So, there’s the UMD version of the V1 viewer [here](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/web/src/ui/umd.js).

**Comment by zfan40** [comment]
Thanks @z3dev 
I find the [test case](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/core/module.test.js) quite helpful
and looking at the core lib, compile and generateOutput are core functions that are preferably added into the doc. As this isn't a production issue, I am going to close it.
