### ISSUE TITLE
V1 : openjscad.generateOutput not working for certain jscad

### ISSUE THREAD

**Issue by zfan40** [jscad/OpenJSCAD.org#619]
Here are two example jscad files.
The working one is from the example
`function main () {
  return union(
    difference(
      cube({size: 3, center: true}),
      sphere({r: 2, center: true})
    ),
    intersection(
      sphere({r: 1.3, center: true}),
      cube({size: 2.1, center: true})
    )
  ).translate([0, 0, 1.5]).scale(10);
}`
the not working one is
`function main () {
  return union(
    difference(
      CAG.circle({center: [0,0], radius: 8.9, resolution: 150}),
      CAG.circle({center: [0,0], radius: .25, resolution: 50})
    )
  ).translate([0, 0, 0]).scale(10);
}`

## Expected Behavior
```
const script = fs.readFileSync('data/notworking.jscad','UTF8')
openjscad.compile(script,{}).then((input)=>{
        const output = openjscad.generateOutput('stlb', input)
})
```
this should run correctly without errors
## Actual Behavior
It generate errors like:
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at reTesselate (/Users/xxx/node_modules/@jscad/core/node_modules/@jscad/csg/src/core/utils/retesellate.js:12:18)
    at CAG.reTesselated (/Users/xxx/node_modules/@jscad/core/node_modules/@jscad/csg/src/core/CAG.js:169:12)
    at transform (/Users/xxx/node_modules/@jscad/io-utils/ensureManifoldness.js:10:45)
    at ensureManifoldness (/Users/xxx/node_modules/@jscad/io-utils/ensureManifoldness.js:15:40)
    at Object.serialize (/Users/xxx/node_modules/@jscad/core/node_modules/@jscad/stl-serializer/index.js:13:10)
    at prepareOutput (/Users/xxx/node_modules/@jscad/core/io/prepareOutput.js:53:45)
    at Object.generateOutput (/Users/xxx/node_modules/@jscad/core/module.js:45:24)

## Steps to Reproduce the Problem

  1. creating the notworking jscad
  2. run similar test cases for this jscad on generateOutput
  3. the errors should come out

## Specifications

  - Version:"@jscad/core": "^0.4.0",
  - Platform:Mac
  - Environment: node.js

**Comment by zfan40** [comment]
I named two jscad working and notworking based on their results... both should work and pass the test cases. Thanks please let me know if you need any other information.

**Comment by zfan40** [comment]
@z3dev could you please take a look at this case? Both script could work on JSCAD web. they were working in the last version, I am not sure if the current version doesn't support 2D for generateOutput

**Comment by z3dev** [comment]
STL is composed of 3D triangles, so those 2D shapes will not be exported. Please try SVG or DXF exports.

**Comment by z3dev** [comment]
However, this still looks like a bug, as the code should not blow up.

**Comment by zfan40** [comment]
Thanks @z3dev , I guess that's the reason. I really don't have much context how the new version changed the behavior. But the previous one could definitely work on 2D shapes.
I am not sure if this could potentially be a feature/bug, definitely hope it could work again
