### ISSUE TITLE
Feature/brainstorm: workspace for multipart project with layouts

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#620]
moved to https://github.com/jscad/OpenJSCAD.org/discussions/823

**Comment by z3dev** [comment]
@hrgdavor thanks for these excellent thoughts.

I’m sure that you will find that JSCAD is missing some functionality. Please feel free to add comments here, or open a specific issue.

One area that I recently bumped into was “align”. I wanted to align two parts at the bottom.
