### ISSUE TITLE
V1 : Random artifacts on certain rounded rectangles

### ISSUE THREAD

**Issue by platypii** [jscad/OpenJSCAD.org#626]
I've seen this manifest a number of times as I've been using OpenJSCAD. I finally got around to isolating a minimal example:

`cube({size: [50, 40, 10], radius: [3, 3, 0], fn: 15})`

Will produce a weird triangle to the side of the rounded cube. This artifact changes with different cube dimensions, radius, and fn quality.

## Expected Behavior

Just a rounded cube.

## Actual Behavior

A rounded cube with an additional non-manifold triangle to the side of it.

![openjscad](https://user-images.githubusercontent.com/1766297/87835627-8734c280-c842-11ea-858c-d5abc8e77c6e.png)

## Steps to Reproduce the Problem

  1. Generate a model from:

```javascript
function main() {
  return cube({size: [50, 40, 10], radius: [3, 3, 0], fn: 15})
}
```

## Specifications

  - Version: 1.9.0
  - Platform: Chrome
  - Environment: Browser

**Comment by z3dev** [comment]
@platypii thanks for this information.

I reviewed the code quickly. Basically, cube({round: true, ...}) is equivalent to CSG.roundedCube(). Here's doc from CSG.roundedCube().

```
/** Construct an axis-aligned solid rounded cuboid.
 * @param {Object} [options] - options for construction
 * @param {Vector3} [options.center=[0,0,0]] - center of rounded cube
 * @param {Vector3} [options.radius=[1,1,1]] - radius of rounded cube, single scalar is possible
 * @param {Number} [options.roundradius=0.2] - radius of rounded edges
 * @param {Number} [options.resolution=defaultResolution3D] - number of polygons per 360 degree revolution
 * @returns {CSG} new 3D solid
 *
 * @example
 * let cube = CSG.roundedCube({
 *   center: [2, 0, 2],
 *   radius: [15, 15, 15],
 *   roundradius: 2,
 *   resolution: 36,
 * });
 */
```
Please notice that roundradius is a single Number. The original cube() function passes "roundradius: radius". However, passing roundradius as a Number or an array of Number values is fine. So, your code should work. ;)

However, there's definitely some kind of bug inside, as the code has this.

`  let minRR = 1e-2 // minroundradius 1e-3 gives rounding errors already`

I think you hit this bug.

**Comment by z3dev** [comment]
FYI, V2 roundedCuboid() only accepts a Number value for roundRadius.

**Comment by platypii** [comment]
I tried to see if this would reproduce on V2, since it seems that's where the majority of development effort is focused, but I wasn't able to get it running locally, sorry.

The reason I care: I am using OpenJSCAD to develop 3d-printed objects. It is very helpful to have a flat base for adhesion to the print surface, but having rounded edges on 2-of-3 axes so that the 3d printer doesn't have to make a hard right angle. (results in better print quality).

Since you mention "V2 roundedCuboid() only accepts a Number value for roundRadius" is the plan to remove `radius: Array` as an option? Would you recommend that I define my own custom function to generate a roudedCuboid, and then chop off the top and bottom using a `difference` or `intersection?

Thanks for the response!

**Comment by z3dev** [comment]
@platypii welcome.

V2 roundedCuboid() checks that roundRadius is a real Number. So, yeah. Only Numbers are accepted.

Did you follow the [Early Adoption ](https://openjscad.org/dokuwiki/doku.php?id=early_v2)notes on the WIKI? You should be able to get V2 running fairly easily. Keep trying.

**Comment by z3dev** [comment]
If you really want flat then extruding a 2D object into 3D space is probably the easiest. See extrudeLinear() in V2.
