### ISSUE TITLE
STL Generation Failure while running Locally

### ISSUE THREAD

**Issue by lingschl** [jscad/OpenJSCAD.org#629]
## Expected Behavior
After pressing f5 to render the object, an option to generate files such as STL or DXF appears. Clicking on "generate STL" should generate an STL file which can then be downloaded.

## Actual Behavior
After pressing f5, the "generate STL" does indeed show up. However, when it is clicked, a "script error: Script error. Line: 0,col: 0 ()" shows and nothing happens. The option to download to file does not appear.

## Steps to Reproduce the Problem

  1. Download the OpenJSCAD.org-master.zip from GitHub
  2. Unzip in a local directory and run index.html from OpenJSCAD.org-master/packages/web
  3. Press f5 to render the JsCad design and make the "generate STL" button appear
  4. Click "generate STL" and get the error

## Specifications

  - Version: V1.10.0
  - Platform: Windows
  - Environment: running locally from my computer on Google Chrome browser

** This is my first issue on Github and first experience doing any web development/ coding projects exceeding just a single file, so please let me know if I am missing any information or have done something wrong!

**Comment by z3dev** [comment]
@lingschl thanks for the new issue.

FYI, you are probably using V1.9.0, which is the last release.

Are you making a new design? You can drag and drop any file to the window.

**Comment by lingschl** [comment]
Thank you for that info.

Yes, I have made a new design, that process went smoothly. I'm trying to create a local website for people to quickly and easily alter this design, and then upload the site to an intranet server. But for the problem I am experiencing, I didn't change the design that normally shows up (cube with cutouts and sphere inside).

**Comment by lingschl** [comment]
![image](https://user-images.githubusercontent.com/66765265/88133220-889e1c00-cbaf-11ea-8f42-1f82738b7241.png)

**Comment by lingschl** [comment]
I just tried to drag my own file into that space and nothing happened. I also see that it says OpenJSCAD.org 1.10.0 at the bottom. Is that referring to the version number or is that something else?

**Comment by z3dev** [comment]
Yeah. You have to drag and drop the file onto the bottom left box. That should work.

**Comment by lingschl** [comment]
I tried that and it is not working. Should I open up a new issue for that as well? I may try deleting the openjscad-master directory and downloading it from Github once again because it seems like these issues shouldn't be present in the regular files.

**Comment by lingschl** [comment]
UPDATE: Opening the page in Edge resolved all the issues. That makes me think there are some incompatibility issues with OpenJsCad and Chrome at the moment.

**Comment by z3dev** [comment]
Hmm... I use Chrome for debugging so I doubt that’s the issue.

What versions of Chrome and Edge are you using?

**Comment by lingschl** [comment]
Chrome: 84.0.4147.89
Microsoft Edge: 44.18362.449.0 (this is not the most up to date version)

but you are saying that I should be able to download and unzip the library from github and run packages/web/index.html with no issues?

Also, I am not sure if this is relevant, but neither edge nor chrome render the object as they are opened - I am required to press f5 first, (shift+enter does not work to render)

**Comment by z3dev** [comment]
I don’t have Windows but will try the latest tomorrow.

**Comment by lingschl** [comment]
I tried to run the standard packages/web/index.html from a mac today. Safari allowed for STL generation and download, but chrome produced the same script error. 
Chrome version 83.0.4103.116
Safari version 13.0.5 (14608.5.12)

**Comment by z3dev** [comment]
I was able to reproduce the issue by opening packages/web/index.html via Chrome. Firefox and Safari worked fine. (I run MacOS) Definitely an issue with Chrome. However, if you do this...
```
cd packages/web
npm run start-dev
```
An open the URL show, then Chrome works fine.

**Comment by lingschl** [comment]
Terrific! I'll go ahead and close the issue.
