### ISSUE TITLE
V1 : Add a warning/error message for cubes with dimensions of 0

### ISSUE THREAD

**Issue by DeflateAwning** [jscad/OpenJSCAD.org#633]
## Expected Behavior
Give an error and continue to render fine when a cube is created with 1 or more dimensions equal to 0.

## Actual Behavior
Browser loads forever until a memory overflow (presumably). 

## Steps to Reproduce the Problem
1. Load the attached JSCAD file. 
2. See that it loads fine as it is.
3. Change the cube on Line 26 to be: `cube([1000, 0, 0])`.
4. Reload.
5. It loads forever until a memory overflow (presumably). 

## Specifications

  - Version: 1.9.0
  - Platform: Windows
  - Environment: browser
[Arm Rest Clamp.txt](https://github.com/jscad/OpenJSCAD.org/files/5004546/Arm.Rest.Clamp.txt)

**Comment by z3dev** [comment]
@ThePiGuy thanks for the request.

We aren't sure how much checking of parameters should be performed, however V2 does additional checks.

```
  if (!Array.isArray(size)) throw new Error('size must be an array')
  if (size.length < 3) throw new Error('size must contain width, depth and height values')

```

**Comment by z3dev** [comment]
The new V2 JSCAD API looks like this...
```
/**
 * Construct an axis-aligned solid cuboid in three dimensional space.
 * @param {Object} [options] - options for construction
 * @param {Array} [options.center=[0,0,0]] - center of cuboid
 * @param {Array} [options.size=[2,2,2]] - dimensions of cuboid; width, depth, height
 * @returns {geom3} new 3D geometry
 * @alias module:modeling/primitives.cuboid
 *
 * @example
 * let myshape = cuboid(size: [5, 10, 5]})
 */
```
