### ISSUE TITLE
V2 code editor window is blank?

### ISSUE THREAD

**Issue by TomSwift** [jscad/OpenJSCAD.org#634]
Not sure what I'm doing wrong trying out the V2 branch.   I've followed the instructions and can load the site after running `npm run dev`.   I can drag/drop STL files and see them render, but I cannot figure out how to load or edit a JSCAD program or any of the examples.   The editor window is blank, both in Chrome and Safari.   The dev console isn't showing any errors on initial load (it was showing 404's for missing OpenSans fonts, but I corrected that).  

Also not able to load anything via the "Load a JSCAD project" button.

Am I doing something obviously wrong?

![Screen Shot 2020-07-31 at 3 44 12 PM](https://user-images.githubusercontent.com/575821/89083223-29759f80-d345-11ea-9ec9-90e3a14f854a.png)

**Comment by TomSwift** [comment]
https://github.com/jscad/OpenJSCAD.org/blob/1613c9119e079feb2ff8f2c9c21ca8027314d691/packages/web/src/ui/views/editor2.js#L42

Looks like it's just not implemented fully yet, yes?

**Comment by z3dev** [comment]
The editor window is probably going to vanish, as we expect users to take advantage of projects (with multiple parts) rather then single file designs.

Try putting your design inside a directory. You should be able to “Load a JSCAD project”, and load that directory.

You can also “Enable Auto Reload”, which will detect when a file changes. (Still a little flaky)

**Comment by z3dev** [comment]
Examples... not V2 ready yet as those require a total rewrite.

**Comment by TomSwift** [comment]
> The editor window is probably going to vanish, as we expect users to take advantage of projects (with multiple parts) rather then single file designs.

Thanks.   FWIW, I think this would be unfortunate.  Having the "playground" with a built in code editor makes the 1.x OpenJSCAD highly approachable and lowers the friction a potential new user would experience in trying out JSCAD for the first time.

**Comment by z3dev** [comment]
@TomSwift the editor window is back, and functional. 👍 

**the editor works for single file designs only.**

if you drag-n-drop a file to the main canvas then the source code will become available in the editor. just open the editor window and click on the window.

examples are also available, and can be opened from the help (?) window. once again, the source code will become available in the editor.
