### ISSUE TITLE
Use the NoScript element

### ISSUE THREAD

**Issue by vanillajonathan** [jscad/OpenJSCAD.org#637]
## Expected Behavior
Application should inform me that JavaScript is required to use the application.
Use the [&lt;noscript&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) HTML element.

## Actual Behavior
Application did not inform me that JavaScript is required.

## Steps to Reproduce the Problem

  1. Disable JavaScript (or use a browser extension such as [NoScript](https://noscript.net/))
  2. Visit https://openjscad.org/
  3. See that the app is broken.

**Comment by z3dev** [comment]
@vanillajonathan thanks.
Your suggestions have been integrated into V2 JSCAD via #687 
Keep those suggestions coming!
