### ISSUE TITLE
extrudeRectangular() produces inside-out geometry

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#646]
## Expected Behavior
```
let aLine = line([[0, -3], [0, 3], [3, 3]])
extrudeRectangular({ size: 1, height: 4 }, aLine)
```
should produce a valid solid.

## Actual Behavior
Produces an inside-out solid.

## Steps to Reproduce the Problem

 ```
const jscad = require('@jscad/modeling')
const { line, rectangle } = jscad.primitives
const { extrudeRectangular, extrudeLinear } = jscad.extrusions
const { expand } = jscad.expansions
const { translate } = jscad.transforms
const {path2 } = jscad.geometries

function doExtrudes (aLine, y) {
  let out = []

  out.push(translate([-18,y,0], aLine))

  out.push(translate([-12,y,0], extrudeRectangular({ size: 1, height: 4 }, aLine)))

  var tmp = expand({delta: 1, corners: 'round'}, aLine);
  out.push(translate([-6,y,0], tmp))

  out.push(translate([0,y,0], extrudeLinear({height: 4}, tmp)))

  tmp = expand({delta: 1, corners: 'chamfer'}, aLine)
  out.push(translate([6,y,0], tmp))

  out.push(translate([12,y,0], extrudeLinear({height: 4}, tmp)))

  tmp = expand({delta: 1, corners: 'edge'}, aLine)
  out.push(translate([18,y,0], tmp))

  out.push(translate([24,y,0], extrudeLinear({height: 4}, tmp)))

  return out

}

function main () {
  let out = []
  
  out = out.concat(doExtrudes(line([[0, -3], [0, 3], [3, 3]]), 10))
  out = out.concat(doExtrudes(line([[0, -3], [0, 3], [-3, 3]]), 0))
  out = out.concat(doExtrudes(line([[-3, -3], [0, -3], [0, 3], [3, 3]]), -10))
  out = out.concat(doExtrudes(line([[3, -3], [0, -3], [0, 3], [3, 3]]), -20))
  out = out.concat(doExtrudes(path2.fromPoints({closed:true}, [[2, -3], [2, 3], [-2, 3]]), -30))
  out = out.concat(doExtrudes(path2.fromPoints({closed:true}, [[-2, -3], [-2, 3], [2, 3]]), -40))
// console.log(out)
  return out

}

module.exports = { main }
```

## Specifications

Fix is in progress.

**Comment by SimonClark** [comment]
Working fix is in https://github.com/SimonClark/OpenJSCAD.org/tree/V2-fix-extrude-rectangular

Currently looking for a more elegant fix...

**Comment by z3dev** [comment]
Hmm... if so then either the expand is producing reversed points (clock wise rotation) or the expand is producing polygons with reverse rotation.

**Comment by SimonClark** [comment]
Yep, expansions.offsetFromPoints() measure the area and behaves differently.  That is the root of this.  I have a fix, but it’s not the right one yet.

The code above produces this:
<img width="1538" alt="Screen Shot 2020-08-11 at 9 36 38 PM" src="https://user-images.githubusercontent.com/354357/90011447-9bb48100-dc6f-11ea-89b1-04a5e2c358f0.png">

The goal is to produce this:
<img width="1538" alt="Screen Shot 2020-08-11 at 9 33 17 PM" src="https://user-images.githubusercontent.com/354357/90011455-9eaf7180-dc6f-11ea-81ba-76327c4efa99.png">

**Comment by z3dev** [comment]
It’s looks like an issue when the direction of the line changes.

It’s probably an issue with the offset code, so let’s spend some time to fix this.
(I rewrote offset / expand)

**Comment by SimonClark** [comment]
Addressed by https://github.com/jscad/OpenJSCAD.org/commit/43ce5dd4341935966ed976ce16cb5a7e452becc2
