### ISSUE TITLE
V2 - Offset a straight line with multiple segments produces impossible geometry

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#649]
## Expected Behavior
```
const points = [[0, 0], [0, 5], [0, 10]]
const linePath2 = path2.fromPoints({ closed: false }, points)
const offsetLinePath2 = offset({ delta: 2, corners: 'edge', segments: 8 }, linePath2)
```
should produce valid geometry, ideally with only 3 points.

## Actual Behavior
Produces geometry with 5 points, some with coordinates of 'infinity'

## Steps to Reproduce the Problem
Run the code above

## Specifications

  - Version: V2 2.0.0-alpha.0
  - Platform: Mac
  - Environment: Chrome, node unit tests

**Comment by z3dev** [comment]
@SimonClark This issue should be fixed with changes in #705 . Please close this issue if satisfied.
