### ISSUE TITLE
V2 - Torus creation with innerRotation produces offset geometry

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#650]
## Expected Behavior
setting an innerRotation value should only affect the rotation of the extruded shape.

## Actual Behavior
Since the change to the transform matrix application, it causes the torus to be offset in the z direction.

## Steps to Reproduce the Problem

```torus({ innerSegments: 4, outerSegments: 4, innerRotation: degToRad(90) })```
should produce identical geometry to 
```torus({ innerSegments: 4, outerSegments: 4 })```

## Specifications

  - Version: V2 2.0.0-alpha.0
  - Platform: Mac
  - Environment: Chrome

**Comment by z3dev** [comment]
FYI, I don't like torus as this shape is a composite of circle and extrudeRotate(). So, I have no idea why there's a feature called innerRotation, except that historically that option has existed. I hope this can be fixed easily.

**Comment by SimonClark** [comment]
Yeah, it seems a bit funny, but it should be easy to fix.  I suspect we just need to either reverse a couple of transforms, or call applyTransforms() before doing the extrudeRotate
