### ISSUE TITLE
V2 - Color/shading is messed up when geometry is scaled right before main.return

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#651]
## Expected Behavior
Geometry is always nicely shaded.

## Actual Behavior
If you scale the only geometry before returning it, it can appear as black, unshaded.

## Steps to Reproduce the Problem
```
const main = () => {
   const a = sphere({})
   return scale([10, 10, 10], a)
}
```
should be the same as, but renders very differently than:
```
const main = () => {
   return sphere({ radius: 5 })
}
```

## Specifications

  - Version: V2 2.0.0-alpha.0
  - Platform: Mac
  - Environment: Chrome

**Comment by z3dev** [comment]
See #594

**Comment by z3dev** [comment]
Hmm... there may be something strange happening inside the renderer code. I’ll check it tomorrow,

**Comment by SimonClark** [comment]
Yep, it's unrelated to #594 

Essentially, if the transform information survives the transition out of the client script, it changes the render.  If you do something that applies the transform, it renders correctly.  If you return the geometry with other geometries, it applies correctly (I assume it does a union, if it receives an array)

**Comment by z3dev** [comment]
I’ve looked at this further.

There was an issue calculating the bounds of each shape, which have been fixed and tested.

However, there’s still some issue in the rendering, which looks to be related to the use of colors by the shaders or calculation of colors by the shaders.
