### ISSUE TITLE
STL export rendering incorrectly

### ISSUE THREAD

**Issue by mountainstorm** [jscad/OpenJSCAD.org#652]
## Expected Behavior

A ring, with three helical levers inside

## Actual Behavior

A ring, with three helical levers inside - but with holes in the ring

## Steps to Reproduce the Problem

  1. Goto https://openjscad.org
  2. Add the code below
  3. Notice it looks good in the 3d view
  4. export as stl (or anything)
  5. View the stl and notice big holes in the base of the ring

Each lever appears to cause a error in the ring

## Specifications

  - Version: 1.10.0
  - Platform: darwin
  - Environment: (browser, local server, node.js etc)

## Test data

```
function bayonet_lever({a=45, r=0.5, h=2, ri=22.1, ro=23.2, fa=12}) {
    let step_rise = r/(a/fa)
    let points = []
    let faces = []
    function add(angle, rise) {
        let pi = { x: ri*cos(angle), y: ri*sin(angle) }
        let po = { x: ro*cos(angle), y: ro*sin(angle) }
        points.push([pi.x, pi.y, 0+rise])
        points.push([pi.x, pi.y, h+rise])
        points.push([po.x, po.y, h+rise])
        points.push([po.x, po.y, 0+rise])
        let pl = points.length
        if (pl >= 8) {
            faces.push([pl-4, pl-3, pl-7, pl-8])
            faces.push([pl-3, pl-2, pl-6, pl-7])
            faces.push([pl-2, pl-1, pl-5, pl-6])
            faces.push([pl-8, pl-5, pl-1, pl-4])
        }        
    }

    for (let sa = 0, sr = 0; sa < a; sa += fa, sr += step_rise) {
        add(sa, sr)
    }
    // draw the last step - this way it's accurate
    add(a, r)

    // fill the ends
    let pl = points.length
    faces.push([0, 1, 2, 3])
    faces.push([pl-1, pl-2, pl-3, pl-4])
    return polyhedron({ points: points, polygons: faces })
}

function main() {

    function bl(as, al) {
        return bayonet_lever({ a: al, fa: 3 }).rotateZ(as)
    }

    return [
        difference(
            cylinder({ h: 6.1, r: 28.5, fa: 3, fs: 0.1 }),
            cylinder({ h: 6.1, r: 25.3, fa: 3, fs: 0.1 })
        ),
        union(
            bl(92.2-59.27154611254943, 50), //59.27154611254943),
            bl(-23.4-70.60722930657451, 50), //70.60722930657451),
            bl(-153.9-53.41848093393517, 50) //53.41848093393517)
        ).translate([0, 0, 3.1]),
    ]
}
```

**Comment by z3dev** [comment]
@mountainstorm thanks for using JSCAD

Can you take a look at the code that creates the polyhedron again? It seems to have some issues.

If you change the last part of your design to...
```
    let obj3 = union(
        difference(
            cylinder({ h: 6.1, r: 28.5, fa: 3, fs: 0.1 }),
            cylinder({ h: 6.1, r: 25.3, fa: 3, fs: 0.1 })
        ),
        union(
            bl(92.2-59.27154611254943, 50), //59.27154611254943,
            bl(-23.4-70.60722930657451, 50), //70.60722930657451,
            bl(-153.9-53.41848093393517, 50) //53.41848093393517
        ).translate([0, 0, 3.1])
    )
    return obj3
```
You will see that there is something being 'subtracted' from the outside ring.

**Comment by mountainstorm** [comment]
hmm, strange. I don't see any issue with my faces; they all face out, are described clockwise and view correctly.  But theres definitely some error as I get the intersection issue.

If I use tris instead it does work 🤷‍♂️

function bayonet_lever({a=45, r=0.5, h=2, ri=22.1, ro=23.2, fa=12}) {
    let step_rise = r/(a/fa)
    let points = []
    let tris = []
    function add(angle, rise) {
        let pi = { x: ri*cos(angle), y: ri*sin(angle) }
        let po = { x: ro*cos(angle), y: ro*sin(angle) }
        points.push([pi.x, pi.y, 0+rise])
        points.push([pi.x, pi.y, h+rise])
        points.push([po.x, po.y, h+rise])
        points.push([po.x, po.y, 0+rise])
        let pl = points.length
        if (pl >= 8) {
            tris = tris.concat([
                [pl-4, pl-3, pl-7], [pl-4, pl-7, pl-8],
                [pl-1, pl-5, pl-6], [pl-1, pl-6, pl-2],
                [pl-2, pl-6, pl-7], [pl-2, pl-7, pl-3],
                [pl-1, pl-4, pl-8], [pl-1, pl-8, pl-5]
            ])
        }        
    }

    for (let sa = 0, sr = 0; sa < a; sa += fa, sr += step_rise) {
        add(sa, sr)
    }
    // draw the last step - this way it's accurate
    add(a, r)

    // fill the ends
    let pl = points.length
    tris = tris.concat([
        [0, 1, 2], [0, 2, 3],
        [pl-1, pl-2, pl-3], [pl-1, pl-3, pl-4]
    ])
    return polyhedron({ points: points, triangles: tris })
}


function main() {

    function bl(as, al) {
        return bayonet_lever({ a: al, fa: 3 }).rotateZ(as)
    }

    return union(
        difference(
            cylinder({ h: 6.1, r: 28.5, fa: 3, fs: 0.1 }),
            cylinder({ h: 6.1, r: 25.3, fa: 3, fs: 0.1 })
        ),
        union(
            bl(92.2-59.27154611254943, 50) //59.27154611254943),
            //bl(-23.4-70.60722930657451, 50), //70.60722930657451),
            //bl(-153.9-53.41848093393517, 50) //53.41848093393517)
        ).translate([0, 0, 3.1])
    )
}

**Comment by z3dev** [comment]
You seem to have a solution. Can you complete your design using these changes?

**Comment by mountainstorm** [comment]
yep.  thanks
