### ISSUE TITLE
V2 : Viewport rotation inertia, does not stop when mouse stops

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#657]
## Expected Behavior
exact rotation using mouse

## Actual Behavior
rotation continues for a while in the same direction, and it is longer, faster the mouse moved.

## Steps to Reproduce the Problem

  1. npm run dev
  2. turn on grid to see more clearly
  3. rotate view

## Specifications

This type rotation feels odd, like the app is too slow,
and is impossible to set view exactly, or rotate quickly
as it does not stop when mouse stops

  - Version: V2 latest
  - Platform: all 
  - Environment: Chrome, Firefox

**Comment by z3dev** [comment]
@hrgdavor can this be closed now?

I believe the latest release contained the changes for improving the rendering.

**Comment by hrgdavor** [comment]
Yes

**Comment by gilboonet** [comment]
The changes made to resolve this issue is now causing moving (shift + mouse RB and mouse move) of very big 2D renderings (like furniture, not 3d print, and on 4K screen) very very slow and hard to track as the render move slower than the cursor.

**Comment by hrgdavor** [comment]
@gilboonet do you have a sample to share that is causing this issue ? I would need sth to test.

**Comment by gilboonet** [comment]
@hrgdavor the code where I have this is here : https://jscad.xyz/#https://raw.githubusercontent.com/gilboonet/gilboonet.github.io/master/sq_edit/demo_big2dmove.js. If you zoom out to see all the pieces, it becomes hard to move the render

**Comment by hrgdavor** [comment]
Yes, I see, it is not relatad to performance or complexity. 
The issue is that amount of pan is same regardless of zoom, so when you zoom out to far as in your model the pan is hardly moving :)

@gilboonet
I found a possible solution and created a pull request: 
https://github.com/jscad/OpenJSCAD.org/pull/735

Please test if it works better now by running local web from my branch:
https://github.com/hrgdavor/OpenJSCAD.org/tree/V2-fix-pan-related-to-zoom

If you like the change,  maybe @z3dev will too and publish it.

**Comment by z3dev** [comment]
I’ll try out the changes as well.

**Comment by gilboonet** [comment]
I tried to run local web with "npm run dev" into the folder extracted from your branch downloaded code, but it didn't work. Do i need to use git clone instead ?

**Comment by hrgdavor** [comment]
If you download or pull from git, you need to follow the steps the same as for main repo.
https://github.com/jscad/OpenJSCAD.org#development

in the openjscad main directory , you need to run 
```
npm run bootstrap
```
and then go to `packages/web/` and run
```
npm run dev
```

**Comment by gilboonet** [comment]
Sorry, I have troubles installing local web version, I'll try again later.

**Comment by hrgdavor** [comment]
It's ok :). gl next time :)  
... it took me few attempts at first. But it is worth it so you can sometimes use a different branch that has a fix you need :)

**Comment by z3dev** [comment]
FYI, I reviewed, tested, and merged the PR from @hrgdavor 
The fixes for PAN are now part of the V2 branch.
