### ISSUE TITLE
V2 reload changes faster for locally run openjscad instance

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#661]
## Expected Behavior
fast reload (at least as fast as V1) or faster

## Actual Behavior
waits for few seconds

## Steps to Reproduce the Problem

  1. npm run dev
  2. open web
  3. import project
  4. edit and save file

## Specifications
Maybe this is alerady possible, I dont know.
Livereload is much faster than polling for changes (I assume that is how it is done).
It would be nice to run openjscad instance that is immediately loading
a specific project folder and using livereload to speedup the refresh delay.

Speed that v1 was refreshing was ok for me, but v2 is annoyingly slower :)

  - Version: V2
  - Platform: All
  - Environment: all

**Comment by z3dev** [comment]
The reload speed needs to be dynamic based on the speed of the last reload. There will be various sizes of projects from 1 to hundreds of files.

**Comment by hrgdavor** [comment]
This is a "nice to have" feature request, it is not a bug or some kind priority for the community. Just personally current delay for refresh in V2 when I have 4 files total in the project folder is too slow for regular use versus V1.

Yes, I am aware of the trade-off for code that does polling on files,  and that is fine for the online web based version.

Purpose of this issue/ticket is to request a feature to enable those using locally run instance to make use of livereload-like system hooks to have much faster refresh.

I am using build scripts on daily basis for my regular projects that work like livereload (hook to native OS events) and refresh immediately (sometimes with intentional 50-100 ms delay). 

I do not like delays when coding, so in the past I have often switched to simpler text editors from more capable ones just because those capable editors were bit slow when switching editor windows.

**Comment by z3dev** [comment]
@hrgdavor probably not what you actually want, but the delay intervals are now dynamically calculated. for small projects, the reload time should be about 1 second. how's that?

**Comment by hrgdavor** [comment]
yes, and will be even nicer with livereload pull req :) https://github.com/jscad/OpenJSCAD.org/pull/729
