### ISSUE TITLE
V2 measurements on an array of geometries returns an array of results

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#667]
## Expected Behavior
If I ask for the bounding box for an array of geometries, I expect a single bounding box for the array, not an array of bounding boxes for individual geometries.

## Steps to Reproduce the Problem
get the bounding box, area or volume for two shapes.

## Specifications

  - Version: 2.0
  - Platform: Mac
  - Environment: (browser, local server, node.js etc) Chrome

**Comment by z3dev** [comment]
Hmm... I see the point but the documentation says one or many.

Question...

If this is changed to return the SUM of the measurements then does the API conflict with other operations that return one or many objects?

For example, translate.

**Comment by SimonClark** [comment]
Been mulling this over.  The documentation can change, but as it is written, it does explicitly say "Returns the min and max bounds for each geometry, i.e. [[X,Y,Z],[X,Y,Z]]"

As it is, for groups, I don't see it as terribly useful.  Anyone getting the min/max (for instance) of each, would either be combining them anyway, or would want to iterate over them to map them back to the source object. I believe the former use case would be more common, and the latter is cleaner code to just iterate over the objects and call the measure function for each individually.

I guess the ambiguity is what to do when measuring areas or volumes, and the geometries overlap.  This isn't helped though, by either aggregate or individual results.

I don't see any conflict between the behaviour of translate and measure.  I don't think there could be any expectation of them behaving the same way.  But if you think there is, let's add a options object to the method, and let them specify aggregate.  I think this is unnecessary though.

**Comment by SimonClark** [comment]
**ok, Proposal:**
- Change the measure functions to return a single value regardless of if the input is single or multiple.
- Add an 'align' function that moves objects individually:
```
align( {
   method: ['center'|'lower'|'upper'|'none', ... ],
   on: [ 'min'|'max'|'origin'|value, ... ],
   grouped: true|false 
}, objects)
alignX( {method: 'lower', on: 10 }, objects )
```
- Change the center function to act on an array as a group (retain their position to each other, but center as a group). So center() becomes and alias for ```align({method:['center','center',center'], on: [0,0,0], grouped: true }, objects)

**Comment by SimonClark** [comment]
There is some internal logic (ie packages/vtree/core/modeling/operations/measurements/measureArea.js ) that calls these methods.  I'd need to dig in, but it seems (according to the javadoc) like those expect a single number returned.

CSG seems to have it's own measureArea and MeasureVolume that is independent.

MeasureEplison only ever gets called in the code on unified geometry.

**Comment by z3dev** [comment]
It seems reasonable that users will want an aggregate value from the measurements. But there’s probably use cases for individual measurements as well. Maybe we could support both by allowing another option. Something like...

`const volume = measureVolume({aggregate: true}, shape1, shape2, ...)
`

**Comment by z3dev** [comment]
> * Add an 'align' function that moves objects individually:

Yeah. Its kind of missing in action. There’s an issue for this already #643 

We should probably keep the align functionality in mind while discussing measurements but track separately in order to discuss the fine details.

I will think this means that align / center will be using measureBounds, and potentially using both aggregate and individual values while aligning geometries.

**Comment by z3dev** [comment]
FYI, SVG serializer has an aggregate bounds function. It uses the aggregate bounds to place geometries into positive axis, regardless of position.

**Comment by SimonClark** [comment]
> `const volume = measureVolume({aggregate: true}, shape1, shape2, ...) `
> 
> This API signature is also familiar to users.

hmmm, alternate suggestion: 
```
const aSphere = sphere()
const aCube = cube()
const shapes = [aSphere, aCube]

measureVolume(aCube) // returns 1
measureVolume(aCube, aSphere) // returns [1, 6.2830]
measureVolume(shapes)  // returns 7.2830
measureVolume(...shapes) // returns [1, 6.2830]
```
Thoughts?

**Comment by z3dev** [comment]
> ```
> const aSphere = sphere()
> const aCube = cube()
> const shapes = [aSphere, aCube]
> 
> measureVolume(aCube) // returns 1
> measureVolume(aCube, aSphere) // returns [1, 6.2830]
> measureVolume(shapes)  // returns 7.2830
> measureVolume(...shapes) // returns [1, 6.2830]
> ```
> 
> Thoughts?

Not bad. The distinction between individual measurements and aggregate measurements is very subtle. Hmm...

How about this?

```
const volumes = measureVolumes( g1, g2, g3, ... )
const volume = measureAggregateVolume( g1, g2, g3, ... )
```

Kind of interesting... there are lots of options.

**Comment by SimonClark** [comment]
I could get behind that.  measureAggregateVolume() is unambiguous.  It must return a single value.

measureVolumes() is a little trickier...
```
measureVolumes(g1, g2) // returns [volume1, volume2] - obvious
measureVolumes(g1) // returns [volume1] or volume1?
measureVolumes([g1,g2], g3) // returns [volume1, volume2, volume3] or [volume1 + volume2, volume3]?
```

**Comment by z3dev** [comment]
> I could get behind that. measureAggregateVolume() is unambiguous. It must return a single value.

Oh! Progress! 👍 

> measureVolumes() is a little trickier...
> 
> ```
> measureVolumes(g1, g2) // returns [volume1, volume2] - obvious
> measureVolumes(g1) // returns [volume1] or volume1?
> measureVolumes([g1,g2], g3) // returns [volume1, volume2, volume3] or [volume1 + volume2, volume3]?
> ```

I suggest we follow the operations, such as translate. When you provide a single geometry then you get back a single result.

`const myNumber = measureVolumes( g1 )`

And get back multiple results for anything else.

`const myVolumes = measureVolumes( g1, g2, ... )`

**Comment by SimonClark** [comment]
so what about 
```
measureVolumes([g1,g2], g3) // returns [volume1, volume2, volume3] or [volume1 + volume2, volume3]?
```

**Comment by z3dev** [comment]
> so what about
> 
> ```
> measureVolumes([g1,g2], g3) // returns [volume1, volume2, volume3] or [volume1 + volume2, volume3]?
> ```

I hope users don’t do this nesting of arrays. We worked around this by using a function called flatten(). So, in this example, an array of three volumes would be returned.

**Comment by SimonClark** [comment]
and, fair enough, that is what everything else does (transform, etc).  It makes for some interesting cases:
```
subtract([g1,g2],g3) === subtract(g1,g2,g3)
etc...
```
But yeah, I can respect that.

ok, last question.  measureVolumes() and measureAggregateVolume() ?
I like measureVolumes() and measureVolume(), but I can see that being a bit subtle, perhaps :)

**Comment by z3dev** [comment]
> ok, last question. measureVolumes() and measureAggregateVolume() ?
> I like measureVolumes() and measureVolume(), but I can see that being a bit subtle, perhaps

Maybe we could replace ‘aggregate’? It’s a tad long.

```
measureAggregateVolume()
measureSumOfVolumes()
measureTotalVolume()
aggregateVolumes()
sumVolumes()
```

**Comment by SimonClark** [comment]
I think I'm convinced on Aggregate...
```
measureAggregateVolume()
measureAggregateArea()
measureAggregateBoundingBox()
measureAggregateEpsilon()
```
makes sense for all.  No other option does.

**Comment by z3dev** [comment]
👍

**Comment by z3dev** [comment]
@SimonClark thanks for the new functionality.

If this is resolved then please close.

**Comment by SimonClark** [comment]
There are the other aggregate functions still to come.  Should be landing shortly.
