### ISSUE TITLE
V2 : Revisit the way the examples menu is generated

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#673]
## Expected Behavior
- move example files to jsdoc style file comments
- annotate core functions with supporting examples to be linked in docs.
- Build from the available examples in the examples folder, possibly as part of bootstrap.
- allow grouping into collapsible subgroups. ( // group : 1. Creating Shapes )
- allow order of appearance by complexity ( // experience level : 1 (?) )

## Actual Behavior
- examples are manually configured, prone to error and decay

## Specifications

  - Version: all
  - Platform: all
  - Environment: browser

**Comment by z3dev** [comment]
@SimonClark can this be closed?

**Comment by SimonClark** [comment]
Yeah, sorry, I suck at housekeeping
