### ISSUE TITLE
V2 : Multifile examples loaded from the example menu do not work

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#674]
## Expected Behavior
If there is a multi-file example in the examples menu, it should load

## Actual Behavior
It does not load

## Steps to Reproduce the Problem
Click on the STL Import example in the examples menu

## Specifications

  - Version: 2.0.0
  - Platform: all
  - Environment: browser

**Comment by z3dev** [comment]
I don't think this can be fixed. Here's why...

A project is a hiearchy of related files. From the examples...
```
module-design/
    index.js
    mountPlate.js
    package.json
    subFolder/
        sphereShape.js
```
The design uses 'relative' require statements to access the pieces.
```
const mountPlate = require('./mountPlate.js')
const sphereShape = require('./subFolder/sphereShape')

```
Unlike drag-n-drop, the actual file system structure is unknown (unavailable). So, somehow, a file system needs to be created. There might be several solutions:

1. load the file system from the server. this is only possible by configuring the HTTP server, and totally insecure.
2. load the 'required' files from the server. this would require parsing the code to determin the relative paths, loading, etc.

Neither of these are realy possible.

The solution is... 'drag-n-drop a project' or 'load a project'.

**Comment by z3dev** [comment]
V1... yeah. it supported 'include()'. this was pretty much a hack, which scanned the scripts and replaced the 'include()' statements with call to a function lookup. very ugly and very limited. also, there was a relative URL being composed / decomposed to obtain the 'relative' URL of the included file.

**Comment by z3dev** [comment]
Closing, as these 'project' based examples have been removed from the list of examples.
