### ISSUE TITLE
V2 - Extruded polygons are hollow

### ISSUE THREAD

**Issue by MathieuLoutre** [jscad/OpenJSCAD.org#683]
## Expected Behavior

When extruding polygons, the resulting shape should be full.

## Actual Behavior

The extruded polygons create a hollow shape (all the sides are there but the inside is empty).

## Steps to Reproduce the Problem
I'm deserializing an SVG and converting every path into a polygon, then extruding the polygon and making a union of the shape (to account for holes).

The resulting shape needs to be inverted (otherwise it looks kinda weird/transparent as in https://github.com/jscad/OpenJSCAD.org/issues/584#issuecomment-629770821). But even then, when slicing the shape, you can see the inside is empty.

```
const shapes = []
const letter = svgDeSerializer.deserialize({ 
	output: 'geometry',
	target: 'path', 
	segments: 360
}, `<svg PXPMM="1" xmlns="http://www.w3.org/2000/svg">${path}</svg>`)

const polyLetter = transforms.scale([scale, scale, 1], letter.map((shape) => primitives.polygon({ points: shape.points })))
const letterShape = geometries.geom3.invert(booleans.union(extrusions.extrudeLinear({ height: 10 }, polyLetter)))
```

## Specifications

  - Version: 2.0.0-alpha4
  - Platform: OSX 10.14.6
  - Environment: Node.js

**Comment by z3dev** [comment]
In order to extrude, paths must wind CCW about the Z axis. You can determine CC vs CCW by measureArea().

**Comment by MathieuLoutre** [comment]
Around the Z axis! That makes sense. I'm unsure why things are not winding properly at the moment, but I'm struggling to correct them.

Now, I'm trying

```
const polyLetter = booleans.union(transforms.scale([scale, scale, 1], letter.map((shape) => primitives.polygon({ points: shape.points }))))

// This returns a geom2 with measureArea < 0 so we want to reverse that

let letterShape = extrusions.extrudeLinear({ height: 10 }, geometries.geom2.reverse(polyLetter))
```

I don't really get what's going wrong here. That's an example SVG path that's parsed:

```[{"points":[[105,-700],[38,-700],[38,0],[224,0],[224,-60],[105,-60]],"isClosed":true,"transforms":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}]```

**Comment by z3dev** [comment]
@MathieuLoutre thanks. I’ll  look at the example. It should be possible to determine CW VS CCW winding.

Are you working with fonts? If so then keep in mind that font outlines can overlaps.

**Comment by MathieuLoutre** [comment]
Thank you! Yes, I'm working with fonts. I'm getting an SVG path from [opentype.js](https://github.com/opentypejs/opentype.js) and then was hoping to pass that to JSCAD and extrude it. I'm expecting opentype.js not to change the winding (which should be correct in the font — I have control over that) but maybe it does?

What I'm not clear on — and this is maybe very basic — is how to change the winding around the Z axis. I'm quite familiar with fonts (this is one of my own design) and the CW/CCW issues in fonts themselves but I didn't expect to find it again in 3D. Ah!

**Comment by z3dev** [comment]
FYI, I created a simular add-on to V2 JSCAD using opentype.js.

https://github.com/jscad-community/jscad-text

I'm not sure this is 100% complete or correct as I have only used this in one design.

It would be cool if our code bases were simular, then we could improve this library. There are several requests per year for this functionality, and it would be nice have a single library.

**Comment by z3dev** [comment]
@SimonClark is also working with font outlines, and has an improvement in the works. He might have some suggestions.

**Comment by MathieuLoutre** [comment]
Thanks, that's super useful. I was hoping the SVG deserialiser would essentially do the heavy lifting your add-on is doing by doing the path conversion. 

I've extracted the main `switch` statement into a function in my script to build up the path and getting better results with TTF than OTF files of the same font (OTF seem to need more flipping/reversing of paths). However, I'm still getting hollow shapes with either files and either techniques.

Here are the commands and generated path for an L (no counters, no bezier):

```
[
  { type: 'M', x: 38, y: 700 },
  { type: 'L', x: 105, y: 700 },
  { type: 'L', x: 105, y: 60 },
  { type: 'L', x: 224, y: 60 },
  { type: 'L', x: 224, y: 0 },
  { type: 'L', x: 38, y: 0 },
  { type: 'L', x: 38, y: 700 },
  { type: 'Z' }
]

[{"points":[[38,700],[105,700],[105,60],[224,60],[224,0],[38,0]],"isClosed":true,"transforms":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}] 
```

Something in the conversion to polygon must be going wrong...

**Comment by MathieuLoutre** [comment]
This is an SVG that when imported and extruded in SCAD directly works fine and when imported, converted to polygons and extruded in JSCAD creates a hollow shape (SVG is generated by "create outlines" in Illustrator using the same font).

```<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" width="12.7mm" height="25.4mm" viewBox="0 0 36 72"><path d="M18.29,69.65c9.75,0,13.12-6.74,13.12-17.12,0-12-5.05-17.56-10.46-21.46-3.11-2.31-9.49-5.5-9.49-15.25,0-5.59,2.39-9.4,6.38-9.4,6.3,0,6.65,9.84,5.68,15.87l6-1.05C31.41,7.82,27.42.65,18,.65,9.68.65,5.25,7.13,5.25,16.44c0,9.49,4.52,13.74,10.64,18.53,5,3.9,9.31,6.48,9.31,18,0,7.9-2,10.82-6.47,10.82-8,0-7.72-9.13-6.3-19.86l-5.67.71C4.63,56.17,5,69.65,18.29,69.65Z"/></svg>```

**Comment by z3dev** [comment]
@MathieuLoutre good research.

However, i’m still not sure where the issue lies. I’ll try your examples tomorrow, and let you know if there’s anything strange happening internally.

**Comment by MathieuLoutre** [comment]
Great! I'm intrigued by how the SCAD importer is using `push_back` for the vertices (https://github.com/openscad/openscad/blob/e30f54f5454568f4f88dd933b82d09d2cbb63346/src/import_svg.cc). Will play around with some idea of reversing maybe... Looking forward to your thoughts tomorrow :)

**Comment by z3dev** [comment]
> This is an SVG that when imported and extruded in SCAD directly works fine and when imported, converted to polygons and extruded in JSCAD creates a hollow shape (SVG is generated by "create outlines" in Illustrator using the same font).

I took this example SVG, and did some different conversions on the data. Then, I put the data into the initial code that you provided for extruding the letter.
```
const { path2, geom2, geom3 } = require('@jscad/modeling').geometries
const { polygon, square } = require('@jscad/modeling').primitives
const { scale } = require('@jscad/modeling').transforms
const { union } = require('@jscad/modeling').booleans
const { extrudeLinear } = require('@jscad/modeling').extrusions
const { measureArea } = require('@jscad/modeling').measurements

const letter = require('./issue683.svg')

const main = () => {
  //return letter

  const polyLetter = union(scale([5, 5, 1], letter.map((shape) => polygon({ points: shape.points }))))

  // letter area: 2502.0003947811274
  console.log('letter area:',measureArea(polyLetter))

  //return polyLetter

  let letterShape = extrudeLinear({ height: 10 }, polyLetter)

  return letterShape
}

module.exports = { main }
```
It seems to work fine, and extrudes a nice well-formed 3D solid.

Please notice that the area for this polyLetter is positive(+).

Also, union() requires properly formed CCW 2D geometry to perform correctly, so those outlines need to be closed and CCW when creating the polygon().

**Comment by z3dev** [comment]
Going back to the initial comment for this issue... "The extruded polygons create a hollow shape (all the sides are there but the inside is empty)."

3D shapes in JSCAD are empty inside. Only the external facing polygons are retained. In fact, the 3D primitives of JSCAD create the external facing polygons, which are hollow by definition.

Did you expect something else?
Once you have a 3D polyletter, what do you want to do with it?

**Comment by MathieuLoutre** [comment]
Thanks for looking into this. The final application is to 3D print this (specifically, slice it in Chitubox). I think it might be my own misunderstanding of 3D printers and 3D shapes which made this more confusing. If the code you've provided gives the expected outcome then I've had similar results for a while unknowingly. 

Looking back at the SCAD STL output, it seems to give similar results in Chitubox (though I swear it used to look different, particularly the shading inside). I've attached the STL output of JSCAD (with reading from an otf file through opentype.js and then getting the SVG path and feeding that to the deserializer and extruding) for your perusal but I now believe that's the expected output.

[ampersand.stl.zip](https://github.com/jscad/OpenJSCAD.org/files/5224169/ampersand.stl.zip)

Thanks again for your time, the flipping/reversing of the polygons was initially the problem and that was solved with measuring the area.

**Comment by z3dev** [comment]
@MathieuLoutre all good, I think.

Yeah. It’s a little confusing as to what defines a ‘solid’. JSCAD is concentrated on providing great 3D models for 3D printing. In order to make that happen, all those points, edges, polygons need to connect perfectly, every time. Hopefully. V2 provides a better experience for everyone.

However, once those 3D models are ‘sliced’, ‘mixed’, ‘mended’, etc by other applications then there’s not much JSCAD can assist. We are working with other software to improve things, even working with Prusa from time to time.

So, from this discussion, what have we learned? Anything missing functionality in V2? What improvements can be made to code or documentation?

**Comment by MathieuLoutre** [comment]
I think functionality-wise there's everything you might need for what I wanted to use it for. honestly approached JSCAD after a couple days playing with SCAD so I worked by comparison and used the source code rather than a tutorial or docs. I suspect a lot of my confusion was due to the reversing of the points and polygons but measureArea was a good way to check on that and I think that's the kind of thing that would be in a beginner-oriented tutorial/doc.

I see there are some tutorial files in the V2 branch (they weren't massively helpful in my case but that's probably because I was after a very specific use) but is there an up to date doc?

**Comment by z3dev** [comment]
@MathieuLoutre thanks for the great feedback.

the documentation for V2 is just beginning. there's a lot to do, and some missing pieces, like V1 to V2 migration guide, etc.

we are trying to embed as much documentation into the code as possible, but there will be limitations on content and format. so there will probably be another WIKI for V2 as well.

**Comment by z3dev** [comment]
Closing this. A new issue has been created to improve documentation.
