### ISSUE TITLE
V2 : remote loading of designs via proxy caching

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#688]
## Expected Behavior

URLs with specific queries or hashes should be loaded by the backend, cached, and presented back to the WEB UI for rendering. This functionality is one of the most well used pieces of V1, which is missing in V2.

Examples of queries

Examples of hashes

- https://openjscad.org/#http://openjscad.org/examples/slices/tor.jscad 
- https://openjscad.org/#https://www.thingiverse.com/download:3591322

## Actual Behavior

No loading of anything.

## Steps to Reproduce the Problem

  1. Rework the above examples to V2, and post to those sites.
  2. Load the URLs into any browser
  3. ...nothing happens...

## Specifications

  - Version: V2
  - Platform: All
  - Environment: All browsers

**Comment by z3dev** [comment]
I got a working version of this today. Wow!

**Comment by SimonClark** [comment]
Very nice!  I'll check it out shortly

**Comment by hrgdavor** [comment]
I  must be blind or something ..... I have not seen it mentioned it in the docs

I have totally missed that feature .... the url loading of the design so I can make a link to it was something 
... I wanted to do that for a long time...   :D

**Comment by z3dev** [comment]
@hrgdavor thanks for the excitement!

Here’s some information from the pull request.

These changes fix the loading of designs from remote URLs, using the webserver as a proxy cache for the contents of the URLs. This allows:
- URL addresses containing hashes; http://jscad.xyz#http://external.com/data/design.js
- URL addresses containing queries; http://jscad.xyz#uri=http://external.com/data/design.js
- drag and drop of URLs

**Comment by hrgdavor** [comment]
Some thing you dont know until you try.
I have joined plenty dev mailing lists to ignore them and unsubscribe
this one I look forward reading comments on issues and progress 

... I get to know the features that are added, or how things work from conmments on bugs and fixes

It just happens that openjscad fits the way I think about designing stuff that I want to 3d print, so I use it  for almost all

**Comment by SimonClark** [comment]
> It just happens that openjscad fits the way I think about designing stuff that I want to 3d print, so I use it for almost all

I know, right!

I'll work on pulling together a remote example shortly, and post it to this ticket as well.

**Comment by hrgdavor** [comment]
I have one that I used to test the functionality
https://openjscad.org/#https://gist.githubusercontent.com/hrgdavor/a55e27701ae3080e75998944a9f471ff/raw/b2fdab71416a19e1e17f25f1994889c265e5b259/organizers.js

![clipboard_image_3c09ee40](https://user-images.githubusercontent.com/2480762/94149555-5a231280-fe78-11ea-83a0-b5a2719a374a.jpg)
