### ISSUE TITLE
V2 UI scrollbar-flutter on Chrome

### ISSUE THREAD

**Issue by risacher** [jscad/OpenJSCAD.org#693]
## Expected Behavior

The UI picks a size, and sticks with it

## Actual Behavior

The scroll bars on the right size of the browser window constantly pop-in, then disappear, then pop-in, creating a flutter effect.

## Steps to Reproduce the Problem

  1. open jscad.xyz in Chrome 
  2. do pretty much anything.

## Specifications

  - Version:  jscad.xyz on 2020-09-23
  - Environment: Ubuntu 20.04; Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by z3dev** [comment]
@risacher thanks for the information. I’ll check this on the latest V2.

FYI, we haven’t released the V2 to www.jscad.xyz yet. Coming soon! :)

**Comment by z3dev** [comment]
I tested the website with 
- Chrome on MacOS, Version 85.0.4183.121 (Official Build) (64-bit)
- Chrome on WIndows 10, Version 85.0.4183.121 (Official Build) (64-bit)

There was no flutter on MacOS. But on Windows 10, there was major flutter of both the vertical and horizontal scroll bars.

**Comment by z3dev** [comment]
@risacher please try www.jscad.xyw again. the V2 JSCAD 'alpha' has been release to that website.

**Comment by z3dev** [comment]
@risacher if the updated website is fine then please close this issue.

Please try www.jscad.xyz

**Comment by z3dev** [comment]
Closing as V2 has been released to www.jscad.xyz, and this issue no longer exists.
