### ISSUE TITLE
As G+ is gone, I invite you to discord. There is a OpenJSCAD channel and a lot of other cad related.

### ISSUE THREAD

**Issue by Kenzu** [jscad/OpenJSCAD.org#694]
https://discord.gg/TkTsCp

**Comment by Kenzu** [comment]
A link that works :-) https://discord.gg/UXtQcA6

**Comment by z3dev** [comment]
The User Group is here... https://openjscad.nodebb.com/

The links at www.openjscad.org have been updated.

What’s missing?
