### ISSUE TITLE
V2 keyboard commands for changing view do not work

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#700]
## Expected Behavior
When I press the keys listed in the options pop-up for changing the view, it changes the view.

## Actual Behavior
It does not change the view.

## Specifications

  - Version: 2.0.0.alpha5
  - Platform: Mac
  - Environment: Chrome

**Comment by z3dev** [comment]
I tried to fix this once and actually was able to get the events created and dispatched. However, there are no functions to set the viewer to predefined rotations, so gave up. This functionality needs to be developed first.

**Comment by SimonClark** [comment]
Hah, you got further than I did!  I found the code that handles interactions on the website to be utterly confounding.  Even dropping in breakpoints or examining the event listeners led to more confusion.  What library are we using for event dispatching, etc?

**Comment by z3dev** [comment]
It’s called most, which is a reactive framework for setting up a series of streams / pipes to process the events. And very challenging to make work.

I’ve trawled the code many times now. @kaosat-dev is correct o point out that the event handling needs to be split out from the core library. That would help to understand that flows easier. There are many many inside the WEB UI.

**Comment by z3dev** [comment]
Also see #235

**Comment by amca01** [comment]
I was just about to ask about this when I saw this issue here.  In that case, maybe the list of keyboard shortcuts should simply be removed from the settings menu until such time as they might be implemented?   cheers, Alasdair

**Comment by z3dev** [comment]
This is still a target functionality of V2, so let's leave those shortcuts. Hopefully, someone will find some time to work on this soon.

**Comment by z3dev** [comment]
Now available on the www.jscad.xyz website. Closing.
