### ISSUE TITLE
V2 Loaded model scripts do not show up in the editor content popup

### ISSUE THREAD

**Issue by SimonClark** [jscad/OpenJSCAD.org#701]
## Expected Behavior
When I load a script, I can see (and edit) the code in the editor popup (or it's not there)

## Actual Behavior
The popup window remains blank

## Steps to Reproduce the Problem
Load a script, either from local or from the examples menu
Open the editor popup from the top right menu
Gaze upon the vast empty field.

## Specifications

  - Version: 2.0.0.alpha5
  - Platform: Mac
  - Environment: Chome

**Comment by z3dev** [comment]
See #634 as well.

**Comment by z3dev** [comment]
@SimonClark there's an implementation of the editor now, as part of V2 Pre-Release 2021 Jan 04. it's not perfect yet but allows users to view and edit designs on-line. please review.

**Comment by z3dev** [comment]
@SimonClark please close if satisfied.
