### ISSUE TITLE
cli install error

### ISSUE THREAD

**Issue by minatani** [jscad/OpenJSCAD.org#706]
At 62017a41214169d6e000f1e0c11aaefdd68e1097, after npm install, npm run bootstrap does not work with below error.

npm ERR! missing script: bootstrap

**Comment by z3dev** [comment]
@minatani please check contents of package.json
The ‘bootstrap’ command is defined in this file.

Can you also supply...
- operating system and version number?
- npm version

**Comment by minatani** [comment]
Sorry, that was caused by a misconfiguration of local directories.
So there is nothing should be done.
