### ISSUE TITLE
Question / FAQ? creating a 3D solid from points in 3D space or multiple 2D shapes

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#707]
Not sure if it is documented, between v1 and v2 doc, I am bit confused where to look.

I am wondering for some shapes that I have an idea to create points in space,
but not sufficient knowlegdge to convert to a solid. Is there somewhere in the code
a function that could make a solid from points in space (if it is even feasible, my knowledge of this domain is limited).

Another question: 
  is there a function I can give a stack of 2d shapes that makes them in to a 3d solid.

I am also looking if I can create a cuboid where only top edges are rounded or only one edge is rounded.

**Comment by z3dev** [comment]
@hrgdavor it seems that you are learning very very fast now. 👍 

There are some examples on how to extrudeFromSlices(). I think these will be the best place to start.
- packages/examples/core/extrusions/extrudeFromSlices.js
- packages/examples/core/curves/bezier/extrudeAlongPath.js

You will probably catch on very quickly. But let us know if you have questions.

**Comment by gilboonet** [comment]
Thanks to the quality of the new examples, I was able to make a furniture feet generator using extrudeFromSlices. https://openjscad.nodebb.com/topic/168/v2-feedback-extrudefromslices?_=1601887651876

**Comment by hrgdavor** [comment]
ok, thnx for the hint. I will look into the examples. 
and hope we can also get to the bottom of render issues I have.  V2 render is pretty slow it is annoying af for me.

**Comment by hrgdavor** [comment]
One questio aslo:
 - are there some limitations I should be aware of ? (except of stupid shapes that are impossible to connect)
 - do slices need to have same number of points ?

**Comment by hrgdavor** [comment]
did it ! :D
gist:
https://gist.github.com/hrgdavor/7419194097fc2ffd42d840f82fc83ca1

preview:
https://jscad.xyz/#https://gist.githubusercontent.com/hrgdavor/7419194097fc2ffd42d840f82fc83ca1/raw/31e0194693629e780e3b82848f9082d1796814ec/rounded_top.js

**Comment by z3dev** [comment]
Cool! I foresee many new inventions from @hrgdavor. 👍 

Slices can have have different shapes and number of points. But there are limitations. Just be sure to provide enough slices to make the transitions easy to stitch together.

Slices can also have holes as well. Same limitations apply.

**Comment by hrgdavor** [comment]
I would be honored if you add my script above to examples :)

.. now I am think bit further in this regard ...
Are there functions in jscad I could use to inflate / deflate a slice ?
simple scaling works for my example above, but is wrong for other shapes.

for example this Q on stacko
https://stackoverflow.com/questions/1109536/an-algorithm-for-inflating-deflating-offsetting-buffering-polygons

**Comment by z3dev** [comment]
Inflate / Deflate... JSCAD calls those offset(+/-). But offset() only works on path2 and geom2, not slices.

Note: offset() doesn't work on geom3 (3D) yet. it's a BIG TODO.

**Comment by hrgdavor** [comment]
well path2 could be sufficient, offset path2 and create slice after. Thnx for the hint :)

**Comment by z3dev** [comment]
Also, if you want to create a 3D solid from a set of 3D points then there’s the polyhedron primitive. There’s an example as well.

**Comment by hrgdavor** [comment]
That is next level :) ... for now I am playing with extrude. Still playing with few concepts around 2D shapes, making basic shape and then rounding corners or making sections curved :)

**Comment by hrgdavor** [comment]
For now there is useful information in this ticket for someone looking for similar info. Closing this ticket, to maybe reopen later or another one that is more specific.
