### ISSUE TITLE
V2 increase polling rate for refreshing display for snigle file scripts

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#710]
## Expected Behavior
faster reload after save.

## Actual Behavior
slower reload than V1

## Steps to Reproduce the Problem

  1. open single file script
  2. change script
  3. wat for refresh

## Specifications
I have asked for similar thing but more complicated regarding usage of livereload.
This request is different. Although for folders and big projects, polling rate should be carefully picked
to avoid spamming the system this is not the case for single file projects.

A different(faster) polling rate should be used for single file projects :)

  - Version: V2
  - Platform: all
  - Environment: (browser)

**Comment by z3dev** [comment]
@hrgdavor probably not what you actually want, but the delay intervals are now dynamically calculated. for small projects, the reload time should be about 1 second. how's that?

**Comment by hrgdavor** [comment]
yes, dynamic delay is better, and livereload support is underway :)
