### ISSUE TITLE
Summary for curated list of code CAD

### ISSUE THREAD

**Issue by Irev-Dev** [jscad/OpenJSCAD.org#728]
Hey 👋 ,

I finally got around to putting together a list of all of the code-CAD projects that I know of here, and also on Github.

I've put a short summary of each one, but it's hard to do them all justice. for JSCAD I've only got:
Formerly OpenJsCad, also inspired by OpenScad. The project is close to a v2.0 release. Implemented in javascript allowing it to be modelled directly within a browser.

If you would like to give me a summary of the project, and perhaps some points of how it differs from other similar projects would be happy to include it. I think max three paragraphs would be about right. Open a PR on reply to this issue and I'll include it.

**Comment by z3dev** [comment]
@Irev-Dev what’s the audience for the summary?

There’s a on line user guide which explains JSCAD in more depth.
https://openjscad.org/dokuwiki/doku.php?id=start

**Comment by Irev-Dev** [comment]
@z3dev Thanks,

The audience would know what code-cad is (probably from openscad), and is interested in alternatives.

**Comment by gilboonet** [comment]
I use JSCAD to pick a volume and process it (slice or unflatten) to render 2d surfaces to lasercut. I think lots of people do the same with lots of software tools. It doesn't seem possible to do that with OpenSCAD where you cannot dynamically compute bounding box. Maybe your list could provide uses cases for each project.

**Comment by z3dev** [comment]
Overview / Introduction 

JSCAD (formally know as OpenJSCAD) provides a programmer’s approach to develop 3D models. In particular, this functionality is tuned towards creating precise models for 3D printing.

JSCAD provides
* ability to create and manipulate 3D models, as well as 2D models
* ability to use JavaScript programming concepts, and libraries
* ability to save 3D models as STL (and other) formats

JSCAD is available as
- a website; www.jscad.xyz
- a command line application for backend processing
- a user application 
- a set of packages (libraries) for building custom applications 

JSCAD allows anyone to create 3D (or 2D) designs by combining simple shapes. And any shape can be rotated, moved, scaled, etc. Complex shapes can be saved as parts, which can used later. And the final design can be exported into various standard formats, i.e. STL, DXF, SVG, etc.

**Comment by z3dev** [comment]
@Irev-Dev let me know if that will suffice. It contains just the basic information, but probably enough for your site.

Please let us know when the information is posted.

**Comment by Irev-Dev** [comment]
@z3dev  Thanks,
I've made those changes.

**Comment by Irev-Dev** [comment]
Hey @z3dev , I've been modelling the same bird house in a couple of different Code-CAD packages and adding them to the repo as examples.
https://github.com/Irev-Dev/curated-code-cad/pulls
![OpenScad](https://user-images.githubusercontent.com/29681384/102965894-e4941480-4542-11eb-822d-c7ac8bd58c25.png)
![cadquery](https://user-images.githubusercontent.com/29681384/102965901-e6f66e80-4542-11eb-9897-97b4577656f9.png)
![CascadeStudio](https://user-images.githubusercontent.com/29681384/102965904-e958c880-4542-11eb-9102-0ca0eb03e4fa.png)
I was going to add a JSCAD one too, but I can't figure out how to use https://www.jscad.xyz/. Is there a trick to it or should I use https://openjscad.org/ instead?

**Comment by z3dev** [comment]
> I was going to add a JSCAD one too, but I can't figure out how to use https://www.jscad.xyz/. Is there a trick to it or should I use https://openjscad.org/ instead?

Cool! Should be fun!

I suggest that you use an external editor, and drag and drop the file to www.jscad.xyz. Then just check auto-reload.

There's a new user guide at www.jscad.xyz/dokuwiki/ which should get you running quickly.
And there the API documents at www.jscad.xyz/docs/

**Comment by Irev-Dev** [comment]
Thanks for the quick response. I've added it, but since this kinda becomes public example code, I'm more than happy for anyone from JSCAD to review the code before I merge it in.
https://github.com/Irev-Dev/curated-code-cad/pull/16

**Comment by z3dev** [comment]
@Irev-Dev there’s a new kid in town...

https://bitbybit.dev/home

Also, BlocksCad hasn’t been updated for years, and looks dead. You might want to mention this point when software is stale / unmaintained.

**Comment by Irev-Dev** [comment]
Thanks @z3dev, Both good points. I'll make some changes to the readme.

**Comment by Irev-Dev** [comment]
Me again.

I also want to add some of the best real-world examples of Code-CAD being used out in the wild. Do you know of any good projects using JSCAD that I can feature?

So far what I've found is:
- [Acedemics using it for reactor design](https://github.com/ukaea/paramak)
- [Lego compatible blocks](https://fxbricks.com/)
- [specialised in-house equipment for drones](https://twitter.com/robsmallshire/status/1343477584458346497)
- [Pruse 3d printer](https://github.com/prusa3d/Original-Prusa-i3)

**Comment by z3dev** [comment]
> Me again.
> 
> I also want to add some of the best real-world examples of Code-CAD being used out in the wild. Do you know of any good projects using JSCAD that I can feature?
> 
> So far what I've found is:
> 
> * [Acedemics using it for reactor design](https://github.com/ukaea/paramak)
> * [Lego compatible blocks](https://fxbricks.com/)
> * [specialised in-house equipment for drones](https://twitter.com/robsmallshire/status/1343477584458346497)
> * [Pruse 3d printer](https://github.com/prusa3d/Original-Prusa-i3)

@Irev-Dev Hello again! I think this would be a great question for the user group. I’ve seen lots of great projects from several of the members.

**Comment by Irev-Dev** [comment]
Good call, done.
