### ISSUE TITLE
Can't npm install @jscad/web@2.0.0-alpha.12

### ISSUE THREAD

**Issue by maspe36** [jscad/OpenJSCAD.org#736]
Sorry if this is known but I didn't see an issue for it. It looks to be expecting a version of a package that isn't released on npm yet. https://www.npmjs.com/package/most-gestures only goes up to 0.4.1

## Expected Behavior
I can install the latest 2.0 alpha build from npm. 

## Actual Behavior
```
C:\Users\Sam\Repos\addifactory>npm i @jscad/web@2.0.0-alpha.12
npm ERR! code ETARGET
npm ERR! notarget No matching version found for most-gestures@0.4.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@jscad/web'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sam\AppData\Roaming\npm-cache\_logs\2020-11-18T22_49_35_005Z-debug.log

C:\Users\Sam\Repos\addifactory>
```

## Steps to Reproduce the Problem

  1. `npm i @jscad/web@2.0.0-alpha.12` in an empty project

## Specifications

  - Version: @jscad/web@2.0.0-alpha.12
  - Platform: Windows 10 
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment]
@maspe36 welcome!

Yeah. Sorry. I need to push a change to this library.

Just to be sure, do you really want @jscad/web ?
This is really for the website. It’s based on MOST is not user friendly.

**Comment by maspe36** [comment]
Thanks!

Yeah I do mean `@jscad/web`, but in the future we may drop down to `@jscad/regl-renderer`. I really just wanted to play around with the 2.0 API and see how much effort it'd be to update from 1.0

**Comment by z3dev** [comment]
@maspe36 Great! It would be beneficial to have another framework around V2 JSCAD.

I’ve been working on some tutorials for V2 JSCAD libraries via VUE. It been going well, and some recent changes were made to ease the pain. I think there are still some improvements to be made. Please see...

https://github.com/z3dev/vue-components

**Comment by z3dev** [comment]
> Yeah I do mean `@jscad/web`, but in the future we may drop down to `@jscad/regl-renderer`. I really wanted to play around with the 2.0 API and see how much effort it'd be to update from 1.0

If you decide to use V2 @jscad/web then you will be tied to MOST, as I doubt that other frameworks can interact with MOST. Also, @jscad/web is packed full of functionality, which may not be appropriate in other websites. There’s no way to disable functionality, and there’s only one configuration of MOST streams.

**Comment by maspe36** [comment]
Very cool, I'll check it out 👍 

I'm familiar with MOST. Our original project wrapped the 1.0 Viewer in a React component so I was planning to upgrade to 2.0 and fix what broke. 

Slightly off topic but, would you recommend using `@jscad/regl-renderer` to create that React component? Or am I missing something else?

**Comment by z3dev** [comment]
> Slightly off topic but, would you recommend using `@jscad/regl-renderer` to create that React component? Or am I missing something else?

Correct. The regl-renderer and core will provide the necessary functionality. I would guess that a react component would be fairly easy to create, very much like VUE.

**Comment by z3dev** [comment]
@maspe36 I'm thinking about two options for this package; most-gestures.

#1 suck in the code and make it part of the web package; 7 files, 980 lines (This has been done before.)
#2 make most-gestures into a JSCAD package, which means publishing it under @JSCAD on NPM

Either solution will fix this issue. Any preference?

**Comment by maspe36** [comment]
Hey thanks for reaching back out about this. I have actually stopped development for now on the project I was working on so I would say what ever makes the most sense for your project maintenance structure. As long as folks have a way to opt out of using most-gestures I don't think it matters and both options would work well for my use case if I ever pick the project back up
