### ISSUE TITLE
V2 : Text example can't render 'e', 'i', or 'j' correctly

### ISSUE THREAD

**Issue by faithhack** [jscad/OpenJSCAD.org#737]
I suspect this has more to do with the example code than the simplex.js font or the text API but I thought I should report it.
I have used lautr3k/jscad-vector-fonts to make new font files like camBamStick1 and they have similar issues (or worse)
## Expected Behavior
render "e", "i", and "j" correctly

## Actual Behavior
using examples/core/text/text.js produces non-manifold letters for 'e', 'i', 'j'

## Steps to Reproduce the Problem

  1. run jscad web
![Screenshot from 2020-11-24 11-49-30](https://user-images.githubusercontent.com/42535/100126848-775e6800-2e4c-11eb-9bc1-4c8c89061ebe.png)

  2. load text.js
  3. watch the magic

## Specifications

  - Version: orign/v2 as of commit 9ad661c44cb87ee6ae58f20a69eaad5fd83a05a6
  - Platform: ubuntu 20.10
  - Environment: (browser, local server, node.js etc)

**Comment by z3dev** [comment]
Hmmm... it looks like the extrudeLinear() is creating some overlapping polygons. Maybe those font outlines overlap at certain points.

An alternative would be to use chainHull between circles, where a circle is placed at the point in the font segments.

**Comment by SimonClark** [comment]
The problem is due to the expand() method creating a polygon that overlaps itself. Z3Dev's solution would work, as it would treat each line segment as a discrete polygon.  Performance would suffer for large strings though.  I have a fix in progress, but not much time to work on it a the moment.
