### ISSUE TITLE
Very difficult to change text parameter value

### ISSUE THREAD

**Issue by gilboonet** [jscad/OpenJSCAD.org#742]
## Expected Behavior
without automatic refresh; one should be able to change parameter values then hit refresh button to render

## Actual Behavior
but when the script already has lots of parameters set, it seems to render automatically or at least perform parameter checks while typing and it melts parameter value with keystrokes. 
To make it work I type the value somewhere else, copy it, then paste it. 

## Steps to Reproduce the Problem

  1. open https://jscad.xyz
  2. download and extract https://github.com/gilboonet/gilboonet.github.io/blob/master/sq_edit/sqed.zip
  3. load project from extracted folder sqed
  4. set more than one slider values for the two groups (lignes/colonnes)
  5. try to change "model" parameter value (try to type "QTable01")

## Specifications

  - Version: JSCAD v2.0.0-alpha.12
  - Platform: Ubuntu 20.10 64 bits
  - Environment: Firefox 83.0 64 bits

**Comment by z3dev** [comment]
@gilboonet a fix to 'Instant Update' has been release as part of V2 Pre-Release 2021 Jan 04. the instant update can be disabled (uncheck), which will allow the text to be updated easily. if this fix corrects this issue, then please close this issue.

**Comment by gilboonet** [comment]
I just tested it again, and effectivey, with current web version (JSCAD V2.0.0-alpha.13) it works fine with instant update unckecked. Thanks a lot.
