### ISSUE TITLE
V2 strange artifact when extruding

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#749]
## Expected Behavior

just extrusion without bottom square that surrounds it

## Actual Behavior
extrusion with bottom square that surrounds it

## Steps to Reproduce the Problem

  1. save script in file
```
const jscad = require('@jscad/modeling')

function main(){
	let points = [
		[4,0],[4,5],[6,5],[4,7],
		[-4,7],[-6,5],[-4,5],[-4,0]
	]
	let shape = jscad.geometries.geom2.fromPoints(points)
	return jscad.extrusions.extrudeLinear({height: 2}, shape)
}

module.exports = {main}
```
  2. load in jscad.xyz
  3.

![image](https://user-images.githubusercontent.com/2480762/103152509-fff06100-4788-11eb-828d-75c38e8003e8.png)

## Specifications

  - Version: all
  - Platform: all
  - Environment: browser

**Comment by z3dev** [comment]
@hrgdavor this fix has been released as part of V2 Pre-Release 2021 Jan 04. if the fix resolves this issue then please close this issue.

**Comment by hrgdavor** [comment]
works :)
