### ISSUE TITLE
Export renders scene without transforms

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#755]
## Expected Behavior
scene does not change whan exporting

## Actual Behavior

scene is rendered again, but without transforms applied

## Steps to Reproduce the Problem

  1.
```
const jscad = require('@jscad/modeling')

function main(){
	return [
		jscad.primitives.cuboid({size:[10,2,2]}),
		jscad.transforms.translate([5.5,0,0],jscad.primitives.cuboid({size:[2,10,2]})),
	]
} 

module.exports = {main}
```
  2. press export(and cancel)

before export
![image](https://user-images.githubusercontent.com/2480762/104089311-39879880-526e-11eb-8c27-fdd6123ec9db.png)

after export
![image](https://user-images.githubusercontent.com/2480762/104089316-43a99700-526e-11eb-8232-5d91def45f10.png)

## Specifications

  - Version: V2
  - Platform: all
  - Environment: (browser)

**Comment by z3dev** [comment]
@hrgdavor the latest V2 JSCAD ALPHA release contained a fix for this. please try www.jscad.xyz again

**Comment by hrgdavor** [comment]
works ! :)
