### ISSUE TITLE
V2 extrusion issues

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#758]
## Expected Behavior

There seems to be some issues with the extrusion logic.
- Only closed slices (those that defined closed sets of edges) can be extruded
- Uncapped extrusions seem strange, where sides are built between end edge and start edge

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: V2
  - Platform: All
  - Environment: (browser, local server, node.js etc) ALL

**Comment by gilboonet** [comment]
Here a little comparison of a typical combination of operations I do (2d geometry made from boolean operation on polygons, then linear extrusion of the result). I tried it on those 4 platforms
- OpenSCAD where it renders a STL with no holes
- OpenJSCAD v0.4 (using my old website) where it renders a STL with 23 holes
- OpenJSCAD v1.9 (latest v1 web) where it renders a STL with no holes
- JSCAD v2.alpha 13 (latest v2 web) where it renders a STL with 66 holes

![Capture d’écran de 2021-01-18 10-31-07](https://user-images.githubusercontent.com/22082873/104897943-51030780-5979-11eb-9baa-956338cb43c0.png)

**Comment by z3dev** [comment]
>     * Uncapped extrusions seem strange, where sides are built between end edge and start edge

This is true. This functionality was added in order to 'close' shapes that complete a rotation (torus). In general, the behaviour is:
- if isCapped then generate caps at the start and the end of the extrusion.
- if NOT isCapped then generate sides between start and end

I may be useful NOT to generate sides between start and end.

**Comment by z3dev** [comment]
>     * Only closed slices (those that defined closed sets of edges) can be extruded

Not true. Actually, 'unclosed' slices can be extruded. The results are not very viewer friendly but may be useful.

![issue758_1](https://user-images.githubusercontent.com/8969165/105146181-0634eb80-5b43-11eb-8c5a-ee7cd43f45c5.png)

**Comment by z3dev** [comment]
> Here a little comparison of a typical combination of operations I do (2d geometry made from boolean operation on polygons, then linear extrusion of the result). I tried it on those 4 platforms

@gilboonet thanks again. nice detective work. fyi, a review of the new snap, etc. functionality is in progress as part of PR #743

**Comment by z3dev** [comment]
@gilboonet please try the latest release of V2 JSCAD. there's a new funcation called generalize()

```
/**
 * Apply various modifications in proper order to produce a generalized geometry.
 * @param {Object} options - options for modifications
 * @param {Boolean} [options.snap=false] the geometries should be snapped to epsilons
 * @param {Boolean} [options.simplify=false] the geometries should be simplified
 * @param {Boolean} [options.triangulate=false] the geometries should be triangulate
 * @param {Boolean} [options.repair=false] the geometries should be repaired
 * @return {Object|Array} the modified geometry, or a list of modified geometries
 */
```

**Comment by gilboonet** [comment]
First of all, thank you for this Alpha 14 release. I did a quick test of generalize and here it is
![testGeneralize](https://user-images.githubusercontent.com/22082873/107209698-72e52c80-6a03-11eb-9462-44641a209c9e.png)
Apparently there's no change when using only snap.

I need now to close holes with each configuration to see if one of them render the model as needed.

**Comment by z3dev** [comment]
@gilboonet a quick update...

I ported the old fixTJunctions() function to V2 JSCAD, and found out that it doesn't fix anything.
This function changes the polygons, and ADDS points at the T junctions. It does not fix the polygons.

The good news is that those additional points allow the creation of water-tight triangles. And the results are very good.

![issue_758_1](https://user-images.githubusercontent.com/8969165/109114355-d8197b80-7780-11eb-96cb-ab525a66e127.png)
![issue_758_2](https://user-images.githubusercontent.com/8969165/109114359-da7bd580-7780-11eb-8466-e26a297fc98b.png)

**Comment by z3dev** [comment]
The improvements to snap and triangulate have been released. Closing.
