### ISSUE TITLE
V2: Some DXF entities could not convert correctly.

### ISSUE THREAD

**Issue by jzyzxx** [jscad/OpenJSCAD.org#759]
Cound you update the libary version of your offcial website to 2.0?Some 2D enties could not convert collectly.

**Comment by z3dev** [comment]
@jzyzxx welcome!

V1 is still available at www.openjscad.org
V2 Alpha is available at www.jscad.xyz

Are you using V2?

**Comment by jzyzxx** [comment]
> @jzyzxx welcome!
> 
> V1 is still available at [www.openjscad.org](http://www.openjscad.org)
> V2 Alpha is available at [www.jscad.xyz](http://www.jscad.xyz)
> 
> Are you using V2?

Yes,i am using V2,Here is my dxf file,when i droped my file o the window,i found some relative position cound not convert collectly,I am sorry that i colud not upload the dxf file

**Comment by z3dev** [comment]
> Yes,i am using V2,Here is my dxf file,when i droped my file o the window,i found some relative position cound not convert collectly,I am sorry that i colud not upload the dxf file to here

There are know issues with the DXF import. Please see Issues.
Also, JSCAD converts the DXF entities into JSCAD objects, so there is always some loss of detail, colors, etc.
V2 has improved the DXF conversation but there’s still a lot to do. :(

**Comment by z3dev** [comment]
If you rename the DXF file to *.txt then you can attach here.

**Comment by z3dev** [comment]
@jzyzxx sorry. i'm closing this. if you can provide an example DXF file then please attach to this issue and reopen.
