### ISSUE TITLE
Enhancement: ECMAScript 6/7 support

### ISSUE THREAD

**Issue by hovissimo** [jscad/OpenJSCAD.org#76]
It would be really nice to get some of the new language features.  Browsers are gearing up their support right now, and it would be really nice if JsCad didn't get stuck on older versions of Js.

Specifically, it would be nice to see support for iterators, generators, and proxy objects so that we can create better part design libraries.

**Comment by Spiritdude** [comment]
Can you provide some links or more detailed explanation on "so that we can create better part design libraries.", right now NPM'fying of OpenJSCAD.org has started with the main aim to make it easier to incorporate later 3rd party libraries co-working with OpenJSCAD.org core library.

**Comment by hovissimo** [comment]
Most important for me is getting the new standard in modules: https://github.com/lukehoban/es6features#modules

But also:

But arrow syntax, block scoping, and the new Classes would all make OpenJSCAD easier to use because our code can be better structured.

Iterator and generator expressions are VERY powerful, especially when generating detailed geometry from functions.
https://github.com/lukehoban/es6features#iterators--forof

There are also new standard math libraries that are much more capable than what we're used to.
https://github.com/lukehoban/es6features#math--number--string--array--object-apis

**Comment by BrianGenisio** [comment]
Agreed.  Importing modules would be pretty great, but in general, going to ES2015 would make this project shine.  Might not be too hard either... either use Babel.js to transpile, or if you are running this code in the Node engine, newer versions of Node support it out of the box.

This project is really, really cool, BTW.

**Comment by z3dev** [comment]
Thanks for the feedback.
I've started down the road to breaking the code into separate "parts". Once that's complete, then those parts can be easily encapsulated, and exported.
Sadly, there's so much to do. If interested then please contact me off-line.

**Comment by meta-meta** [comment]
I just discovered OpenJSCAD. Very excited about using it. ES2015 would make things way better. What's the current state of affairs?

**Comment by z3dev** [comment]
@meta-meta Not much movement on this front as there's far too much to do already.

I'm sure that the project can move towards ES2015. What are you thinking about?

**Comment by kaosat-dev** [comment]
@z3dev @Spiritdude  @hovissimo , @BrianGenisio @meta-meta 
It will not deal (yet) with Es6/2016 support (harder to do because of the not yet universal support in browsers) for the jscad scripts themselves , but the codebase is at least partially being ported to modules/es2015 in PR #205 , which should help this in the future

**Comment by z3dev** [comment]
I really hate to rely on a "crutch", but does the use of BABEL resolve the need for ES6? ES2015? Anything else in mind?

**Comment by kaosat-dev** [comment]
@z3dev  two different aspects : ES6 in our code base , and ES6 in the user defined scripts
Babel works for us (although I am stripping it out where it is not absolutely necessary).
Regardless  , almost ALL modern environements Chrome, Firefox, Safari, and yes, even the new 'Internet Explorer' (now called Edge) support almost all of the ES6 features :
https://kangax.github.io/compat-table/es6/

The one thing that is not universal , is the es6 modules syntax (import export), and it is not looking so good timewise : https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c 
(this is why I am moving some modules to common.js , if the only special es6 features we use are modules)

**Comment by kaosat-dev** [comment]
at this stage, 
- a lot of the internal code has been at least partially ported to / uses es6 features.
- openjscad and all its sub repos support latest versions of node.js
- for discussions about modules etc for user content please see #245 
- because of the complexity of the project, and the endless headaches of transpiling etc and to keep things simple, for now everything is using common.js modules until there finally is a reasonable consensus for es6 modules for node.js (not any time soon)

So I am closing this issue for now as most concerns have been either addressed or are discussed elsewhere.
Feel free to reopen if needed, thanks !

**Comment by meta-meta** [comment]
I had the pleasure of doing some design work with openjscad over the
weekend. Delighted to see arrow functions and other es6 features working.
I'm in love. The experience felt productive and expressive. Thank you so
much for all the hard work!!

**Comment by kaosat-dev** [comment]
@meta-meta thanks a lot for the kind words ! It is really nice to know that all the work has not been for nothing :)
Lots of nice new things coming up in the next few months ! (finally getting to the interesting parts)
Btw if you have feedback for #245 please let us know, I really think it is critical for the future of the project.
