### ISSUE TITLE
V2: mat4 enhancement

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#760]
## Expected Behavior

I find this function very useful at times, and think that other users will be interested. From the example, extrudeAlongPath.js

```
  function rotationMatrixFromVectors (srcVector, targetVector) {
    // From https://gist.github.com/kevinmoran/b45980723e53edeb8a5a43c49f134724
    srcVector = maths.vec3.normalize(srcVector)
    targetVector = maths.vec3.normalize(targetVector)
  
    const axis = maths.vec3.cross(targetVector, srcVector)
    const cosA = maths.vec3.dot(targetVector, srcVector)
    const k = 1 / (1 + cosA)
  
    return maths.mat4.fromValues(
      (axis[0] * axis[0] * k) + cosA, (axis[1] * axis[0] * k) - axis[2], (axis[2] * axis[0] * k) + axis[1], 0,
      (axis[0] * axis[1] * k) + axis[2], (axis[1] * axis[1] * k) + cosA, (axis[2] * axis[1] * k) - axis[0], 0,
      (axis[0] * axis[2] * k) - axis[1], (axis[1] * axis[2] * k) + axis[0], (axis[2] * axis[2] * k) + cosA, 0,
      0, 0, 0, 1
    )
  }
```

## Actual Behavior

Not available

## Steps to Reproduce the Problem

  1. NA

## Specifications

  - Version: V2
  - Platform: all
  - Environment: all

**Comment by z3dev** [comment]
Suggested names...
- mat4.fromVectors(source, target)
- mat4.fromVectorRotation(source, target)

**Comment by hrgdavor** [comment]
That is cool. Could you give few more use cases ? I am curious :)

**Comment by z3dev** [comment]
I'll try...

Currently, the API has a transform function called rotate([x, y, z], ...objects) which is based upon the mat4.fromTaitBryanRotation function, i.e. yaw, pitch, roll rotations. All fine for those that think in X, Y, Z rotations.

An alternative (and possibly more mathematically correct) is basing rotations upon directional vectors. For example, rotating a direction vector to point to 5, 5, 5. Hmm... getting a little tough to use rotate([?, ?, ?]). Maybe easy if the original vector is going to 0, 0, 20, but what about if the original vector is going to -3, -3, -3? Oooo... I don't want to do the math for the current rotate() function.

Another possible application is 'connecting' geometries; A and B. If you know the directional vectors of the connection points then it's pretty easy to connect there
- get a rotation from A' to B' minus, and rotate
- translate A to B

**Comment by z3dev** [comment]
@SimonClark might have some nice applications as well.

**Comment by hrgdavor** [comment]
Could it be used to make a simpler version of this ?
https://openjscad.nodebb.com/topic/183/cylinder-between-points?_=1611131975841

**Comment by z3dev** [comment]
> Could it be used to make a simpler version of this ?
> https://openjscad.nodebb.com/topic/183/cylinder-between-points?_=1611131975841

I would think so... the directional vector (DV) is just P2 - P1
Then it’s just get the rotation from 0,0,1 to DV

**Comment by hrgdavor** [comment]
Huh,

I am having issues with your function. I might be using it incorectly, please check.

![image](https://user-images.githubusercontent.com/2480762/105555721-4e523a80-5d0a-11eb-9b83-242faab04638.png)

green is double the starting vector,  and red is the rotated vector using the function.

blue sphere is where it should go through.

Script:
```js

const {primitives, transforms, maths, colors} = require('@jscad/modeling')
const {translate, rotate} = transforms
const {cylinder, sphere, cube} =primitives

var _parameters = [];

var funcs = new Map();

function main(){

	var vecTo = [10,10,10]
	var vecFrom = [0,0,10] //
	var rot = rotationMatrixFromVectors(vecFrom,vecTo)
	// var rot = rotationMatrixFromVectors([1,1,1],[0,0,1])
	//var rot = [-Math.PI/4,Math.PI/5,0]
	//var rot = [0,0,0]
	// cylinder is larger on purpose
	var cylinderForVector = translate([0,0,10],cylinder({radius:0.5, height:20}))
	return [

		// vecFrom
		colors.colorize([0,1,0,0.5],cylinderForVector),
		
		// blue sphere where it should point 
		translate([10,10,10],sphere({radius:0.5})),
		// vecTo
		colors.colorize([1,0,0,0.5],rotate(rot,cylinderForVector)),
		
		// green sphere where it almost points
		colors.colorize([0,1,0],translate([-10,-10,10],sphere({radius:0.5}))),

		// cube that is also with 10x10x10
		colors.colorize([0,0,1,0.5],translate([5,5,5],cube({size:10}))),
		// cube that is also with 10x10x10
		colors.colorize([0,0,1,0.5],translate([-5,-5,5],cube({size:10}))),
	]
}


function rotationMatrixFromVectors (srcVector, targetVector) {
	// From https://gist.github.com/kevinmoran/b45980723e53edeb8a5a43c49f134724
	srcVector = maths.vec3.normalize(srcVector)
	targetVector = maths.vec3.normalize(targetVector)

	const axis = maths.vec3.cross(targetVector, srcVector)
	const cosA = maths.vec3.dot(targetVector, srcVector)
	const k = 1 / (1 + cosA)

	return maths.mat4.fromValues(
	  (axis[0] * axis[0] * k) + cosA, (axis[1] * axis[0] * k) - axis[2], (axis[2] * axis[0] * k) + axis[1], 0,
	  (axis[0] * axis[1] * k) + axis[2], (axis[1] * axis[1] * k) + cosA, (axis[2] * axis[1] * k) - axis[0], 0,
	  (axis[0] * axis[2] * k) - axis[1], (axis[1] * axis[2] * k) + axis[0], (axis[2] * axis[2] * k) + cosA, 0,
	  0, 0, 0, 1
	)
}

module.exports = {main}
```

**Comment by z3dev** [comment]
> I am having issues with your function. I might be using it incorectly, please check.

Real close... remember that rotationMatrixFromVectors is returning a math.mat4. So...

`	var **matrix** = rotationMatrixFromVectors(vecFrom,vecTo)`

**Comment by hrgdavor** [comment]
ok works now
![image](https://user-images.githubusercontent.com/2480762/105575344-352da600-5d6b-11eb-8624-f263e6b23267.png)

I am completely clueless what mat4 is :)

**Comment by z3dev** [comment]
There is nothing special about mat4, which is a 4 x 4 matrix. However, understanding matrix math is always a challenge. You can find lots of information on matrix mathematics. One of the best websites for beginners (of all ages) is [MathIsFun](https://www.mathsisfun.com/algebra/matrix-transform.html)

**Comment by hrgdavor** [comment]
I am familiar with matrix math.  But I googled why 4x4 matrix is used in 3D  to learn a bit about the concept :)

**Comment by z3dev** [comment]
FYI, this is required for the new X3D serializer, so a small pull request to add this function will happen soon.
