### ISSUE TITLE
V2 union() does not work properly.

### ISSUE THREAD

**Issue by minatani** [jscad/OpenJSCAD.org#778]
Union() does not work properly.
This code can be expected to produce a crossing bars, but in fact makes cuboids with complicated facets.

const { cuboid } = require('@jscad/modeling').primitives
const { union } = require('@jscad/modeling').booleans

const main = () => {
    let juuji=[];
    const vertical=cuboid({size: [10, 60, 10]});
    const horizontal=cuboid({size: [40, 10, 10]});
    juuji.push(vertical);
    juuji.push(horizontal);
   const ret=union(juuji);
    return [ ret ];
}

module.exports = { main}

**Comment by z3dev** [comment]
@minatani good to hear from you again.

So, here are the polygons after the boolean operation.

![issue778](https://user-images.githubusercontent.com/8969165/110398136-9957bf80-80b6-11eb-81dd-10752b08763b.png)

Are you expecting a different set of polygons (faces)?

**Comment by z3dev** [comment]
@minatani Please reopen if there are still issues.
