### ISSUE TITLE
jscad.xyz is down

### ISSUE THREAD

**Issue by arcanemachine** [jscad/OpenJSCAD.org#779]
## Expected Behavior
jscad.xyz resolves properly

## Actual Behavior
Connection times out

## Steps to Reproduce the Problem

  1. Go to jscad.xyz in the browser.
  2. Wait for it to load.
  3. It doesn't load

## Specifications

  - Version: N/A
  - Platform: The Web
  - Environment: Browser

**Comment by rachidlamouri** [comment]
Is jscad.xyz the same as openjscad.org? Because I have been using openjscad.org and it is also not responding.

**Comment by arcanemachine** [comment]
I pushed a clone of the web packages to jscad.surge.sh if anyone needs to whip anything up in the meantime.

**Comment by udif** [comment]
@arcanemachine you have pushed a copy of the old 1.x code. jscad.xyz was running the new v2 branch when it was up.
openjscad.org was running the old 1.x code.

**Comment by z3dev** [comment]
Yeah. Both websites are down... have sent the notices for help but this may take some time.

**Comment by gilboonet** [comment]
If this is due to OVH data center fire, they said the servers will be replaced on monday for some of them and next friday for the last one.

**Comment by z3dev** [comment]
> If this is due to OVH data center fire, they said the servers will be replaced on monday for some of them and next friday for the last one.

Possibly... hanks for the information.

**Comment by z3dev** [comment]
V2 DOCUMENTATION...

I put the documentation online at http://www.gfnews.net/jscad/docs/index.html

**Comment by z3dev** [comment]
For those in a bind, I put V2 JSCAD online at www.gfnews.net/jscad/

**Comment by z3dev** [comment]
> > If this is due to OVH data center fire, they said the servers will be replaced on monday for some of them and next friday for the last one.
> 
> Possibly... thanks for the information.

The Strasbourg OHV data centers are coming online again. Servers are being checked, then brought online. It may take a few more days. It seems that the main UPS in data center 2 started on fire, and took all four centers offline. Nice design... 😔

**Comment by vorpalhex** [comment]
@z3dev I can probably help provide hosting in the meantime if that's helpful.

**Comment by z3dev** [comment]
> @z3dev I can probably help provide hosting in the meantime if that's helpful.

@vorpalhex thanks for the offer.

the latest is that the servers will be brought back on-line sometime this week. not the best news but let's wait a few more days.

**Comment by jfo8000** [comment]
There's a V1 mirror of OpenJSCad up at https://creator.buildbee.com/ - I couldn't figure out how to host the docs, but the site is up if anyone needs it.

**Comment by jonsadka** [comment]
@z3dev any updates on this?

**Comment by jfo8000** [comment]
I have updated the documentation to the wikibooks version but if there is a more recent one let me know!
https://creator.buildbee.com

**Comment by z3dev** [comment]
There's a new website for V2 JSCAD... www.openjscad.xyz

Enjoy!
