### ISSUE TITLE
No Clear documentation on for loops

### ISSUE THREAD

**Issue by The3rdIcon** [jscad/OpenJSCAD.org#78]
While I see them mentioned there is no clear documentation on how to use them or if the openscad version of a for loop will work. Can you please add specific directions about them. or direct me to the specific documentation in the user guide.

**Comment by thehans** [comment]
Its just javascript so any type of loop supported by javascript will work.
I don't think its within the scope of this project to teach javascript from scratch.

Here is some external documentation on javascript loops:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements#Iterations

If the OpenSCAD syntax is preferred you can use that by setting the top line in your script to:
//!OpenSCAD
as explained here https://github.com/Spiritdude/OpenJSCAD.org/wiki/User-Guide#direct-openscad-source-import

**Comment by kaosat-dev** [comment]
@The3rdIcon as @thehans  said, it is all standard javascript so all js loops work
there are however no list comprehensions out of the box in js
