### ISSUE TITLE
How can I access CodeMirror via Javascript from the browser when using v2?

### ISSUE THREAD

**Issue by arcanemachine** [jscad/OpenJSCAD.org#780]
Rookie question ahead...

## Expected Behavior

When using the v2 version in the browser, I want to access the CodeMirror instance through some variable connected to the jscad instance running in the browser (e.g. jscadInst1.codeMirrorEditor.doc.blahBlah() ).

## Actual Behavior

The setup code returns a Promise, and I have no idea how to interface with the CodeMirror instance (or any of the "backend" code in dist/jscad-web.min.js for that matter).

## Steps to Reproduce the Problem

  1. Go to a jscad instance (I have one running at https://jscad.surge.sh/ until the real one is back up)
  2. Open the code editor
  3. The only relevant variable is jscadInst1, and it offers no apparent way of accessing any other data on the page (editor, programmatically triggering desired methods, etc).

## Specifications

  - Version: v2
  - Platform: Browser (Firefox)

Thanks a bunch. I'm sure there's an easy answer out there that I'm missing. The v1 version allows easy access to the editor by accessing `ace.edit['editor']` . I want to know if I can do the same thing with v2. Cheers

**Comment by z3dev** [comment]
@arcanemachine thanks for using V2.

The WEB UI for V2 is very very different. The interaction of components (canvas, editor, etc) is based on 'most', which is not very easy to understand or extend.

So, what are you looking for? Do you want to create a new web site? Use V2 as a component?

**Comment by arcanemachine** [comment]
Basically, I'm running the entire page in an iframe. Users can write data into the editor, preview the results, then save the results in the profile for other users to view. It's basically just a "wrapper" (if that is the correct use of the word) for the openjscad/jscad web apps.

The hope is, of course, to contribute to the code base as well, once I can get a handle on things. The ~66k lines in the unminified jscad-web.js file is certainly intimidating in that regard, but it seems that a alot of that is just imports from other projects (e.g. codemirror, etc.)

Many thanks for your help!

**Comment by z3dev** [comment]
Ok. I see where you are headed now.

The compiled library (jscad-web-min.js) was created for the JSCAD website, and includes EVERYTHING. You might be able to use it but it probably wouldn’t be a good idea. It can change, and there are no hooks for developers.

There are several packages that wrap JSCAD in different styles, and far easier to work with. You can find most of those by just following the Used By links.

I have a set of tutorials for VUE, which have smaller components. These were created for starting projects like yours.

We understand that people want to create more applications, and have shifted towards smaller packages to support developers. Hopefully, you can assemble something quickly.

**Comment by arcanemachine** [comment]
I appreciate the quick replies.

I'd gotten to the point where I was just gonna manually add some buttons before re-Browserify-ing everything, but I will take a look at the Vue stuff (I know enough Vue to get by, fortunately).

Thanks again :)

**Comment by z3dev** [comment]
@arcanemachine super! i think you will be successful using the vue components.

all changes are welcome as well! :)

**Comment by arcanemachine** [comment]
The Vue components work very well. I hope to be able to give back something of worth to the project. Thanks yet again.
