### ISSUE TITLE
V2 rotate() doesn't seem to use 360 degree angles when rotating

### ISSUE THREAD

**Issue by kenianbei** [jscad/OpenJSCAD.org#781]
## Expected Behavior

This is happening on the V2 latest alpha.

Rotation should follow normal angle degrees of 0-360. When using:
```js
function main () {
  return rotate([90,0,0], cube())
}
```
cube should align with grid and only have rotated 90 degees.

## Actual Behavior
Cube is rotated a huge number of revolutions. It seems like 90 degrees is close at [1.6, 0, 0].

## Steps to Reproduce the Problem

1. Go to a sample site like http://www.gfnews.net/jscad/
2. Paste in:
```js
function main () {
  return rotate([90,0,0], cube())
}
```
3. Shift-Enter

## Specifications

  - Version: 2
  - Platform: Liniux, actually running regl-renderer in a react component with jscad-react V2.
  - Environment: browser

**Comment by z3dev** [comment]
All angles are now RADIANS as the JavaScript math library uses radians as well.

It’s a little confusing at first but pretty easy to use after a while. There’s a utility function to convert from degrees to radians called ‘degToRad()’.

`const { degToRad } = require(‘@jscad/modeling’).utils`

**Comment by kenianbei** [comment]
Perfect, thanks for the update!

**Comment by kenianbei** [comment]
BTW I created a react component if anyone needs one for V2: https://github.com/kenianbei/jscad-react

**Comment by z3dev** [comment]
@kenianbei no problem.

The online API documentation has some good references, and examples.

Sorry, but the User Guide is not available. The websites are still down. 😔

**Comment by z3dev** [comment]
> BTW I created a react component if anyone needs one for V2: https://github.com/kenianbei/jscad-react

OOOO...nice! I’ll take a look.

Please post to the User Group. There are many folks creating websites, components, etc.

**Comment by kenianbei** [comment]
Cool I will do that...

**Comment by z3dev** [comment]
Super. If you found a solution then please lose this issue. ;)
