### ISSUE TITLE
Clean up usability and documentation mess

### ISSUE THREAD

**Issue by WolfgangFahl** [jscad/OpenJSCAD.org#783]
## Expected Behavior
OpenJsad should be useable and documented 

## Actual Behavior
- the website is down
- there are two different versions of openjscad - the old one has flaws and the new one is not ready
- google search points to outdated documentation

## Steps to Reproduce the Problem

  1. try using openjscad with an existing openjscad project - the website is down - work around it
  2. try fixing a problem with a parameter definition of type choice - a web search points you to https://en.wikibooks.org/wiki/OpenJSCAD_Quick_Reference which is outdated
  3. get frustrated

To avoid this frustration i'd suggest to be more consistent in the plan for moving to version 2 including the necessary infrastructure and documentation. As I a start I'd suggest to open up github discussion to have a more consistent experience in the dicussion forum. Then the DNS entry for openjscad.org should be made more flexible so that a week long outtage as the one we are experiencing with #779 should not have such a bad effect. 

It should be made more clear where the current documentation is and how a migration from V1 to V2 can be done. Also I'd love to get #448 going which is long overdue due to the complexity of the environment and project. I'd love to see more simplicity in the approaches.

**Comment by z3dev** [comment]
I (and others) understand the frustration, but no one expects four(4) major data centers to go down at the same time. OpenJSCAD isn’t the only website down still.

In addition, those domain names are owned by individuals, who have drifted away from the project. Request for help was sent, but... yeah.

**Comment by WolfgangFahl** [comment]
@z3dev  thank you for your swift answer which clarifies the DNS problem. When following a workaround such as https://creator.buildbee.com/ and then the documentation link you end up in https://openjscad.org/dokuwiki/doku.php which is also offline at this time - what's the workaround for that one?

The major question is to avoid such disruption and confusion in the future as well as make it easier to get to know openjscad and use components others have designed and more. This issue is calling for some strategic move that would position openjscad better. The current outage is IMHO just a clear warning what happens if the strategic part is not accounted for. I don't even know where the discussion/chatroom ended up so that's why i am asking to move it to github discussion got get more focussed.

**Comment by danmarshall** [comment]
I am personally a fan of using all the GitHub resources. GitHub pages for web hosting (both docs and online web app), and GitHub Discussions. Everything can be contained in this single repo.

**Comment by z3dev** [comment]
@danmarshall please remember that the websites need that little Perl script. as far as I know, only static content can be served up by GIST. is there something that I missed?

For the API documentation, it's possible to create both HTML and MARKDOWN versions. The question is... where to put the MARKDOWN versions.

Discussions? Do you mean Team discussions? That's the only discussions that I know about at GitHub.

**Comment by WolfgangFahl** [comment]
@z3dev  Discussions are for creating a forum/chat room and are effectively handled like issues so that e.g. issues changes and discussion entries can be linked. See https://github.com/somnathrakshit/geograpy3/discussions for an example.

The MARKDOWN can be put directly in the github pages which are effectively just a branch gh-pages of  the main gitrepository. Where is the content and the perl script right now?

**Comment by z3dev** [comment]
Always something new at GitHub.... discussions are enabled.

**Comment by WolfgangFahl** [comment]
See #785 for a first followup

**Comment by jfo8000** [comment]
I have updated the documentation to the wikibooks version but if there is a more recent one let me know!
https://creator.buildbee.com

**Comment by WolfgangFahl** [comment]
https://en.wikibooks.org/w/index.php?title=OpenJSCAD_User_Guide&action=history shows the history of the page. I also had the assumption that this is the official documentation but it seems not to be any more and at least that should be pointed out

**Comment by z3dev** [comment]
As discussed earlier, WIKIBOOKS is the V1 Documentation from a long while back. I’d be glad to use WIKIBOOKS again if they improved the review process. But waiting 6 months for some old fart to review two changes is ridiculous. I doubt that you can even make changes to those pages. I doubt that anyone can delete those pages.

😔

**Comment by jfo8000** [comment]
@z3dev is the newer v1 documentation checked in anywhere?

**Comment by z3dev** [comment]
> @z3dev is the newer v1 documentation checked in anywhere?

Sadly, no.
Both V1 and V2 WIKIs are still offline. I’ve been following the OHV recovery process but it’s going slow. I’ll start some discussions with OHV this week, and try recovering everything.

I had an old copy of the V2 wiki and put it online at openjscad.xyz/guide.html which forwards to the wiki. This is the new website.

**Comment by WolfgangFahl** [comment]
Just added a hint to the wikibooks page about the deprecation:
https://en.wikibooks.org/w/index.php?title=OpenJSCAD_Quick_Reference&type=revision&diff=3826690&oldid=3583623

**Comment by z3dev** [comment]
@WolfgangFahl thanks.

Do you know if books can be removed from WIKIBOOKS?

**Comment by WolfgangFahl** [comment]
@z3dev  with admin right pages can be deleted in a wiki. There is a deletion log then but the page won't be visible any more and robots won't pick it up. It better practice to remove all content and place a redirect on the page to make sure outdated content is not referenced any more.

**Comment by z3dev** [comment]
Closing this issue. Let's open new issues for anything left over.
