### ISSUE TITLE
"Cannot read property 'length' of undefined" during generalize for STL serializer

### ISSUE THREAD

**Issue by hobofan** [jscad/OpenJSCAD.org#786]
## Expected Behavior

I can correctly export my model via the STL serializer

## Actual Behavior

It crashes with the following error:
<details>
<summary>Full error</summary>

```
TypeError: Cannot read property 'length' of undefined
    at deleteSide (/Users/hobofan/landau/landau/node_modules/@jscad/modeling/src/operations/modifiers/insertTjunctions.js:51:32)
    at insertTjunctions (/Users/hobofan/landau/landau/node_modules/@jscad/modeling/src/operations/modifiers/insertTjunctions.js:229:17)
    at generalizeGeom3 (/Users/hobofan/landau/landau/node_modules/@jscad/modeling/src/operations/modifiers/generalize.js:56:16)
    at /Users/hobofan/landau/landau/node_modules/@jscad/modeling/src/operations/modifiers/generalize.js:90:37
    at Array.map (<anonymous>)
    at Object.generalize (/Users/hobofan/landau/landau/node_modules/@jscad/modeling/src/operations/modifiers/generalize.js:87:30)
    at Object.serialize (/Users/hobofan/landau/landau/node_modules/@jscad/stl-serializer/index.js:63:33)
    at prepareOutput (/Users/hobofan/landau/landau/node_modules/@jscad/io/prepareOutput.js:49:45)
    at Object.solidsAsBlob (/Users/hobofan/landau/landau/node_modules/@jscad/io/index.js:13:56)
    at appendChildToContainer (/Users/hobofan/landau/landau/src/renderer.js:104:26)
```

</details>

## Steps to Reproduce the Problem

// TODO: Code to reproduce - Will try to get to it the coming days

I think the problem is that I'm trying to `union` a `cylinder` and a `cylinderElliptic` in some edge case position.

When it looks like this, it doesn't work:
![image](https://user-images.githubusercontent.com/601283/113941272-0fa72900-97ff-11eb-9014-b3f0d1c827ad.png)

However when I first `align` the bottom `cylinder` (which shifts it upwards a bit), it works without problems. (As I ended up wanting to do that anyway, this is not a urgent issue, but I assume that other people will run into the same bug sooner or later.) It then looks like this:
![image](https://user-images.githubusercontent.com/601283/113941517-83493600-97ff-11eb-9d3e-88d674a834d3.png)

## Specifications

  - Version:
  ```
    "@jscad/io": "^2.0.0-alpha.13",
    "@jscad/modeling": "^2.0.0-alpha.11",
  ```
  - Platform: MacOS 10.14.6
  - Environment: node.js v14.15.4

**Comment by z3dev** [comment]
@hobofan can you share the design? that would help write a test case.

**Comment by hobofan** [comment]
I built it with my project Landau, which is still experimental and I didn't want to bother you with for this bug (the main mechanics work though, so I'm pretty sure the bug doesn't come from there).

Anyways, I put the design online [here](https://github.com/hobofan/landau-net-cup). You can try to build the model with `npm run build-model-broken` and the relevant parts of the code are [here](https://github.com/hobofan/landau-net-cup/blob/4bfabcd78ff011b36e84822ec8313b18cf0ce692/src/broken-build.js) and [in this file](https://github.com/hobofan/landau-net-cup/blob/main/src/index.js).

**Comment by hobofan** [comment]
I reproduced it with plain `@jscad/modeling`: https://gist.github.com/hobofan/d5840fdb0f0978c19f4e8a7d5bf0bc55

A few observations that might help to narrow it down:

- Error only occurs when both `snap` and `triangulate` are `true` for `generalize`
- When `times` is changes to any value other than `10` https://gist.github.com/hobofan/d5840fdb0f0978c19f4e8a7d5bf0bc55#file-broken-generalize-js-L59, the error doesn't occur (which is a bit strange because every value above ~5 should result in the same model)

In general the error is pretty flaky, and I also encountered it a few more times when finishing my original design, and was able to get rid of it again by making small trial-and-error adjustments to my input variables.

**Comment by z3dev** [comment]
@hobofan thanks for the example.

looks like snap() is merging very close vertices, and sometimes those vertices are within the same polygon.
```
{
  vertices: [
    [ -24.445112000000115, 19.346837333333426, 46.47572533333356 ],
    [ -24.44446933333345, 19.346837333333426, 46.47508266666689 ],
    [ -23.70540266666678, 18.79864266666676, 39.56448800000019 ],
    [ -23.70540266666678, 18.79864266666676, 39.56448800000019 ]
  ]
}
```
I think snap() should check the polygons, and throw one of the vertices away.
