### ISSUE TITLE
Support for old V1 designs

### ISSUE THREAD

**Issue by z3dev** [jscad/OpenJSCAD.org#790]

**Comment by platypii** [comment]
I've been porting several models written in V1 to V2. In the process I have made this compatibility shim which makes things work like in V1. All you need to do is add imports and exports around your V1 code. It is by no means complete, but maybe helpful?

```javascript
const { intersect, subtract, union } = require('@jscad/modeling').booleans
const { colorize, colorNameToRgb } = require('@jscad/modeling').colors
const { cuboid, cylinder, cylinderElliptic, polygon, roundedCuboid } = require('@jscad/modeling').primitives
const { extrudeLinear } = require('@jscad/modeling').extrusions
const { rotate, translate } = require('@jscad/modeling').transforms
const { degToRad } = require('@jscad/modeling').utils

module.exports = {
  color: (color, obj) => {
    if (typeof color === "string") {
      return colorize(colorNameToRgb(color), obj)
    } else {
      return colorize(color, obj)
    }
  },
  cube: (opt) => {
    if (opt.radius) {
      opt.roundRadius = opt.radius
      if (opt.fn) {
        opt.segments = opt.fn
      }
      return translate([opt.size[0] / 2, opt.size[1] / 2, opt.size[2] / 2], roundedCuboid(opt))
    } else {
      return translate([opt.size[0] / 2, opt.size[1] / 2, opt.size[2] / 2], cuboid(opt))
    }
  },
  cylinder: (opt) => {
    const rot = [0, 0, 0]
    const center = [0, 0, 0]
    if (opt.start && opt.end) {
      center[0] = (opt.start[0] + opt.end[0]) / 2
      center[1] = (opt.start[1] + opt.end[1]) / 2
      center[2] = (opt.start[2] + opt.end[2]) / 2
      opt.height = Math.hypot(opt.start[0] - opt.end[0], opt.start[1] - opt.end[1], opt.start[2] - opt.end[2])
      if (opt.start[0] != opt.end[0]) {
        rot[1] = -Math.PI / 2 * Math.sign(opt.start[0] - opt.end[0])
      }
      if (opt.start[1] != opt.end[1]) {
        rot[0] = Math.PI / 2 * Math.sign(opt.start[1] - opt.end[1])
      }
    }
    if (opt.fn) {
      opt.segments = opt.fn
    }
    if (opt.r) {
      opt.radius = opt.r
    }
    if (opt.r1 === 0) {
      opt.r1 = 0.01
    }
    if (opt.r2 === 0) {
      opt.r2 = 0.01
    }
    if (opt.r1 && opt.r2) {
      opt.startRadius = [opt.r1, opt.r1]
      opt.endRadius = [opt.r2, opt.r2]
      return translate(center, rotate(rot, cylinderElliptic(opt)))
    } else {
      return translate(center, rotate(rot, cylinder(opt)))
    }
  },
  difference: subtract,
  intersection: intersect,
  linear_extrude: extrudeLinear,
  polygon: (opt) => {
    if (Array.isArray(opt)) {
      return polygon({points: opt})
    } else {
      return polygon(opt)
    }
  },
  rotate: (r, obj) => rotate(r.map(degToRad), obj),
  translate: translate,
  union: union
}
```

**Comment by z3dev** [comment]
FYI, all support for V1 will be removed in the WEB APP soon, which basically is broken anyway.

The proper way to support V1 is via a ‘shim’ like above. But the shim has to be supported outside of the core as there’s way too much work already.

@platypii how about adding the above shim to the JSCAD Community repositories? That would allow others to contribute, and / or use the code directly.

**Comment by hrgdavor** [comment]
Also in migration guide discussion #883  there is a link to an automatic script that converts v1 to v2.

And if you have more ideas for integration guide we could improve it.

**Comment by apla** [comment]
I've just uploaded latest version of [my V1 => V2 converter](https://gist.github.com/apla/90edff2e4993f3e3592f8795c2050cc5), converted successfully almost anything.

**Comment by hrgdavor** [comment]
@apla I was not sure if the link is the same, so I updated the migration guide just in case.

**Comment by z3dev** [comment]
> I've just uploaded latest version of [my V1 => V2 converter](https://gist.github.com/apla/90edff2e4993f3e3592f8795c2050cc5), converted successfully almost anything. Probably the best place for this converter in this repo.

Wow! Full conversion is really nice. Thanks @platypii 

I kind of like both approaches…
- Full conversion from V1 to V2 using the converter
- Some guides on creating small ‘shims’ for specific V1 functionality

We can probably use the discussion as the guide #883 for both approaches.

**Comment by platypii** [comment]
@z3dev I made a repo containing my v1 -> v2 migration shim. I would be happy to transfer it to JSCAD Community Repo ownership if you are willing. I don't currently have permission to transfer ownership to jscad-community.

https://github.com/platypii/jscad-migrate

**Comment by z3dev** [comment]
> @z3dev I made a repo containing my v1 -> v2 migration shim. I would be happy to transfer it to JSCAD Community Repo ownership if you are willing. I don't currently have permission to transfer ownership to jscad-community.

Community repository is on the way. Once you accept membership, you can add your code import… I think.

**Comment by platypii** [comment]
@z3dev I accepted the invite, but still don't have write access. And I can't even fork it to make a PR because the repo is empty :upside_down_face:
![Screenshot at 2021-12-12 13-56-05](https://user-images.githubusercontent.com/1766297/145731115-6f570876-2810-4319-ab99-31a09bb5a610.png)

**Comment by z3dev** [comment]
@platypii please try again. You should have admin privileges now.

github provides some notes on importing from another repository as well.

**Comment by platypii** [comment]
@z3dev I still don't have write access to https://github.com/jscad-community/jscad-migrate

**Comment by z3dev** [comment]
> @z3dev I still don't have write access to https://github.com/jscad-community/jscad-migrate

UG… my bad, I think. I added you to the team, so you should have write access now.

**Comment by z3dev** [comment]
Done
