### ISSUE TITLE
Inverted extrusion on clockwise polygon

### ISSUE THREAD

**Issue by platypii** [jscad/OpenJSCAD.org#808]
## Expected Behavior

When extruding a valid 2D shape, the "direction" of the points should not matter. Note that I'm porting some code from V1 to V2, and this worked in V1.

## Actual Behavior

If you define a polygon with counter-clockwise points, then extrudeLinear works fine. If you pass a clockwise polygon, the resulting geometry is inverted, with faces pointing in.

![inverted_poly](https://user-images.githubusercontent.com/1766297/115979957-daf4da80-a53d-11eb-8997-b47f3a53d26b.png)

## Steps to Reproduce the Problem

```
const { extrudeLinear } = require('@jscad/modeling').extrusions
const { polygon } = require('@jscad/modeling').primitives

function main() {
  return extrudeLinear(
    {height: 2},
    polygon({points: [[3, 3], [3, 0], [0, 0]]})
  )
}
module.exports = { main }
```

## Specifications

  - Version: 2.2.0
  - Platform: Linux 64
  - Environment: node.js 14.3.0

## Notes

It seems like the problem is that the "side" detection in the polygon doesn't look what is inside vs outside. I'd be willing to try and make a PR if you agree that is the right fix.

Alternatively, would be nice to point out in the docs that point direction matters.

Also, the docs incorrectly state that you can create a polygon like `polygon([ [0,0],[3,0],[3,3] ])` without an object, but that is no longer true in V2.

Thanks for the hard work, V2 is a huge step forward!

**Comment by z3dev** [comment]
> Alternatively, would be nice to point out in the docs that point direction matters.

The API documentation explicitly says... "NOTE: The ordering of points is VERY IMPORTANT."

https://openjscad.xyz/docs/module-modeling_primitives.html#.polygon

Sadly, we lost some of the documentation on orientation in the User Guide.

**Comment by platypii** [comment]
Ah fair enough. I just updated doc wiki [here](https://openjscad.xyz/dokuwiki/doku.php?id=en:design_guide_polygon)

**Comment by z3dev** [comment]
> Ah fair enough. I just updated doc wiki [here](https://openjscad.xyz/dokuwiki/doku.php?id=en:design_guide_polygon)

@platypii thanks. I saw the changes to the user guide.

If satisfied then please close this issue.
