### ISSUE TITLE
Improve regl-renderer to use less power (skip repaint when not needed)

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#813]
## Expected Behavior
renderer repaint stops when there are no changes to the view (orbit, model change)

## Actual Behavior

renderer draws constantly and 

## Steps to Reproduce the Problem

  1. this is not clearly visible to users
  2. but developer can see it easily
  3.

## Specifications
this will be an issue for anyone showing rendered models on a phone or on laptop on battery power.
this is also wasteful as it uses cpu/gpu even if I switch to other tabs/things.

  - Version: V2
  - Platform: all
  - Environment: browser

**Comment by z3dev** [comment]
@hrgdavor Are you going to make some changes? This seems something that you could fix easily. 😃

**Comment by hrgdavor** [comment]
ok, I'll take a look and try to make a fix
