### ISSUE TITLE
jscad WASM port discussion

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#815]
This is just a placeholder issue for anyone else wondering if WASM would bring even more performance to jscad.

I was wondering about that, and it is not clear cut at all (from what I gathered so far). 

What is more, it could easily be less performant, but WASM is also about portability now and is all the rage....

One exploration where it shows how difficult it is to outperforms js: https://surma.dev/things/js-to-asc/

**Comment by z3dev** [comment]
Can these discussions be move to the Discussions area?

**Comment by hrgdavor** [comment]
I wanted to make an issue so if someone else wants to propose wasm  in the future they can find it. Using discussion is better. But I would keep this issue and link to discussion, then close the issue so it does not count towards open issues.

**Comment by z3dev** [comment]
I was able to search for information, which found both issues and discussions. So, I think an issue isn’t necessary. Let’s use issues for real issues. ;)

**Comment by hrgdavor** [comment]
Ok :) 👍
