### ISSUE TITLE
Editor panel hides error messages

### ISSUE THREAD

**Issue by JamesNewton** [jscad/OpenJSCAD.org#884]
## Expected Behavior
When making a programming error, and then pressing shift+enter in the editor window at 
https://openjscad.xyz/
I expected to see an error message

## Actual Behavior
The error message was hidden behind the editor panel.

## Steps to Reproduce the Problem

  1. Go to https://openjscad.xyz/
  2. Press the editor icon.
  3. enter "alsdkfjsaldkfj" and press Shift + Enter
  4. Notice you can't see the error message
  5. Click the 

## Specifications

  - Version: whatevers at openjscad.xyz
  - Platform: Current Chrome on Ubuntu 18.04
  - Environment: browser

**Comment by z3dev** [comment]
@JamesNewton the latest release of openjscad.xyz now has a change that addresses this issue. all messages are now shown on the left hand side of the window.

if those changes resolve this issue then please close this. thanks
