### ISSUE TITLE
TypeError: Cannot read property 'isClosed' of undefined during svg deserialization

### ISSUE THREAD

**Issue by brucedjones** [jscad/OpenJSCAD.org#885]
## Expected Behavior

The SVG below is successfully deserialized

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="5.791015625" height="11.71875"><path d="M1.84-3.17L0.53-3.48L0.97-7.11L5.12-7.11L5.12-5.83L2.30-5.83L2.14-4.42Q2.32-4.52 2.60-4.60Q2.89-4.68 3.16-4.68L3.16-4.68Q4.22-4.68 4.79-4.05Q5.36-3.42 5.36-2.29L5.36-2.29Q5.36-1.61 5.06-1.05Q4.75-0.50 4.20-0.20Q3.65 0.10 2.90 0.10L2.90 0.10Q2.23 0.10 1.64-0.18Q1.05-0.45 0.72-0.94Q0.39-1.42 0.40-2.02L0.40-2.02L2.05-2.02Q2.07-1.63 2.29-1.40Q2.52-1.17 2.89-1.17L2.89-1.17Q3.72-1.17 3.72-2.40L3.72-2.40Q3.72-3.54 2.70-3.54L2.70-3.54Q2.12-3.54 1.84-3.17L1.84-3.17Z"/></svg>
```

## Actual Behavior

Deserializer throws `Cannot read property 'isClosed' of undefined`

## Steps to Reproduce the Problem

run
```
import { deserializers } from "@jscad/io";

const svg =
  '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="5.791015625" height="11.71875"><path d="M1.84-3.17L0.53-3.48L0.97-7.11L5.12-7.11L5.12-5.83L2.30-5.83L2.14-4.42Q2.32-4.52 2.60-4.60Q2.89-4.68 3.16-4.68L3.16-4.68Q4.22-4.68 4.79-4.05Q5.36-3.42 5.36-2.29L5.36-2.29Q5.36-1.61 5.06-1.05Q4.75-0.50 4.20-0.20Q3.65 0.10 2.90 0.10L2.90 0.10Q2.23 0.10 1.64-0.18Q1.05-0.45 0.72-0.94Q0.39-1.42 0.40-2.02L0.40-2.02L2.05-2.02Q2.07-1.63 2.29-1.40Q2.52-1.17 2.89-1.17L2.89-1.17Q3.72-1.17 3.72-2.40L3.72-2.40Q3.72-3.54 2.70-3.54L2.70-3.54Q2.12-3.54 1.84-3.17L1.84-3.17Z"/></svg>';
const shapes = deserializers.svg({ output: "geometry" }, svg);
```

## Specifications

  - Version: `"@jscad/modeling": "^2.5.0",`
  - Platform: mac/chrome
  - Environment: browser

**Comment by brucedjones** [comment]
The above is from running in my own app. Running this at https://www.openjscad.xyz/ it throws a different error:
`cannot append points to a closed path`

```javascript
const { deserializers } = require("@jscad/io");

const main = () => {
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="5.791015625" height="11.71875"><path d="M1.84-3.17L0.53-3.48L0.97-7.11L5.12-7.11L5.12-5.83L2.30-5.83L2.14-4.42Q2.32-4.52 2.60-4.60Q2.89-4.68 3.16-4.68L3.16-4.68Q4.22-4.68 4.79-4.05Q5.36-3.42 5.36-2.29L5.36-2.29Q5.36-1.61 5.06-1.05Q4.75-0.50 4.20-0.20Q3.65 0.10 2.90 0.10L2.90 0.10Q2.23 0.10 1.64-0.18Q1.05-0.45 0.72-0.94Q0.39-1.42 0.40-2.02L0.40-2.02L2.05-2.02Q2.07-1.63 2.29-1.40Q2.52-1.17 2.89-1.17L2.89-1.17Q3.72-1.17 3.72-2.40L3.72-2.40Q3.72-3.54 2.70-3.54L2.70-3.54Q2.12-3.54 1.84-3.17L1.84-3.17Z"/></svg>';
  return deserializers.svg({ output: "geometry" }, svg);
}

module.exports = { main }
```

**Comment by hrgdavor** [comment]
@brucedjones if you are ok with starting local jscad from source can you check if this fix #886 works for you.

**Comment by brucedjones** [comment]
i can take a look at this tonight, thanks for looking in to it!

**Comment by brucedjones** [comment]
Tested locally and that appears to work, thanks!

**Comment by brucedjones** [comment]
Looks like the same bug existed in `appendBezier` and `appendArc`

https://github.com/jscad/OpenJSCAD.org/blob/2e52f104e569f2bb7dd9e1be3d238f471f4d3dfa/packages/modeling/src/geometries/path2/appendBezier.js#L40

https://github.com/jscad/OpenJSCAD.org/blob/2e52f104e569f2bb7dd9e1be3d238f471f4d3dfa/packages/modeling/src/geometries/path2/appendArc.js#L50

**Comment by hrgdavor** [comment]
@brucedjones my first attempt did remove the error. But it was not the right way to fix. New version of the fix will still complain but will tell you what part of svg is broken.

as mentioned in #886 :
------------------------
The problem is that the test sample svg is malformed and now error is thrown
`Malformed svg path at 2:445. Path closed itself with command #29: Q2.12 -3.54 1.84 -3.17`

The problem is that the mentioned command adds last point that is the same as first point in the path, so the appendPoints closes it. So I have added a check for such case and throw an error with the location of the problematic svg.

**Comment by brucedjones** [comment]
Interesting. If this is detecting that the path closed itself, wouldn't it be better to be robust to this and handle it accordingly rather than throwing an error? At the very least an option to ignore this would be nice.

**Comment by hrgdavor** [comment]
> wouldn't it be better to be robust to this and handle it accordingly rather than throwing an error? 

well, what would be "accordingly" ?  different users would have different expectations 😐  

> At the very least an option to ignore this would be nice.

that would be nice, but also what would it mean ? 
What to do with a line that is added to a closed path:
 - return as an additional path ?
 - ignore it ?
 - ...
 -

**Comment by brucedjones** [comment]
So in this case you specifically noted that the polygon is self closing ie the last point is coincident with the first. The code could be robust to this specific case. The outstanding edge case is, as you noted, what happens if there are points *after* the point that is coincident with the first point. You could

* throw an error
* ignore it
* add an additional path.

IMO returning an additional path is what I would expect. That option is robust and the most faithful representation of the STL possible.

**Comment by hrgdavor** [comment]
> So in this case you specifically noted that the polygon is self closing ie the last point is coincident with the first. The code could be robust to this specific case.

that case is ok :) it does not throw an error.

I would go in this direction
 - pathSelfClosed: 'error' - default throw an error
 - pathSelfClosed: 'trim' - ignore it
 - pathSelfClosed: 'split' - add an additional path.

default would make it less likely to break extrude if it passes

**Comment by brucedjones** [comment]
Sounds good!

**Comment by z3dev** [comment]
@brucedjones the latest version of openjscad.xyz has the modified SVG deserializer (import function), but the default is 'error' at this time. hopefully, the error message will be meaningful.

please try it out, and let us know if anything should be adjusted.

**Comment by brucedjones** [comment]
Nice thanks!
