### ISSUE TITLE
Can we extrude arbitrary and changing 2D shapes along a 2D/3D path?

### ISSUE THREAD

**Issue by jgrizou** [jscad/OpenJSCAD.org#89]
Imagine a function that takes a path and a list of shapes and extrude the shapes following the path. At each point/intersection of the path is associated a shape. The shape at the point1 morphing into the shape at point2 along the path from point1 to point2. 

I see that you already have [rectangularExtrude()](https://github.com/Spiritdude/OpenJSCAD.org/wiki/User-Guide#rectangular-extrude), would it be hard to generalize it to any shapes? Is [solidFromSlices()](https://github.com/Spiritdude/OpenJSCAD.org/wiki/User-Guide#solid-from-slices) the place to start?

In OpenScad, they are working on the following: https://github.com/openscad/list-comprehension-demos, see the skin() and sweep() function. As well as the morph() function that progressively morph a 2D shape into another. See https://github.com/jgrizou/segment-scad-dev/blob/master/compare.scad for an example that generate the objects below (its adaptable to any 2D shapes, not only rectangles):

![skin_sweep_morph](https://cloud.githubusercontent.com/assets/1609708/7565611/af858660-f7f1-11e4-8980-462e592841f7.png)

That would be very helpful to create this kind of segments https://github.com/jgrizou/segment-scad in a much more elegant way.

**Comment by z3dev** [comment]
Correct. See the examples that use solidFromSlices(). Basically, the slices define the next step in 3D space, which allow the 2D shape to morph, rotate, or translate. Please let me know if you need more examples.

**Comment by kaosat-dev** [comment]
This is really needed, and sadly a lot less trivial to implement then it seems. (we currently have no good way of fetching points along a path)
Will try to find a solution

**Comment by z3dev** [comment]
@jgrizou there have been some additionals to V2 JSCAD, especially in the 3D space. There is now a new set of functionality called 'curves'. The bezier curves provide the ability of extracting points in 3D space following the curver definition, and that can be used to extrude some interesting 3D shapes. Here's our on-line example.

https://www.jscad.xyz?uri=https://www.jscad.xyz/examples/core/curves/bezier/extrudeAlongPath.js

**Comment by z3dev** [comment]
Considered done.

@jgrizou Reopen and comment if you feel differently.
