### ISSUE TITLE
file import "Cannot find relative path to module /babypanda2.svg"

### ISSUE THREAD

**Issue by Sam-Apostel** [jscad/OpenJSCAD.org#896]
I seem to be unable to get any imports working. After some testing this issue appears in the [hosted version](https://www.openjscad.xyz/#) too.

## Expected Behavior
file is imported and contents can be used.

## Actual Behavior
error is thrown
```
ERROR:
Error: Cannot find relative path to module /babypanda2.svg
Line: 38
```

## Steps to Reproduce the Problem
  1. Go to https://www.openjscad.xyz/#
  2. Open an example from the `imports` section or the `Modular Project Design Example` example.

## Specifications

  - Version: 2.4.0
  - Platform: macOs / safari & chrome
  - Environment: browser & local server

**Comment by hrgdavor** [comment]
Not sure why links at https://openjscad.xyz/ don't work. But the modular projects examples work if you:
 - go to https://github.com/jscad/OpenJSCAD.org/tree/master/packages/examples/import
 - download the folders
 - open  https://openjscad.xyz/
 - drag/drop one of the example folders

I have just tried it and it works as expected. So if you have a modular project, try those as a starting point.

**Comment by Sam-Apostel** [comment]
Ah, drag the entire folder over. Makes sense! Will try to fix the examples.

**Comment by z3dev** [comment]
Folders cannot be loaded from the examples. It’s a know issue.

It’s probably best to remove those from the examples until a solution is found.

**Comment by gilboonet** [comment]
For the moment the only solution I found for a script to be able to use files is to ask users to download it an run it locally as @hrgdavor does, and if they want to use a new file with a running script, the script must be reload first.
