### ISSUE TITLE
New Feature: DAG node editor

### ISSUE THREAD

**Issue by alranel** [jscad/OpenJSCAD.org#90]
Functional programming languages like the scad format can be represented as DAG (like in Grasshopper, Blender, Antimony). Each variable or primitive or function is a node of the graph.

I think many users would appreciate a node-based graph editor. It would reduce the learning curve and it would provide good eye-candy for skeptical people. :P

**Comment by eric-schleicher** [comment]
A scheme based FBP designer already exists, and also uses a version of
csg.js aw well.

See:  https://github.com/pboyer/flood

Eric

**Comment by EternityForest** [comment]
I think a tree-like structure may be easier, both for developers and anyone used to traditional CAD. Graph-like features can happen on top of the tree by having a node that sets a variable to whatever it gets from child nodes, and another node that has a value equal to that variable.

A graph editor plus a 2D sketcher with basic constraints(or not) would almost be a full basic CAD.

**Comment by z3dev** [comment]
Here's another node based design tool, which incorporates JSCAD, and even more.

https://polygonjs.com/

**Comment by z3dev** [comment]
@alranel Closing this issue as there are no plans, and probably never will be plans, to create a node based design tool. There are now tools available, which use JSCAD underneath. Please try those.
