### ISSUE TITLE
A questions about project()

### ISSUE THREAD

**Issue by JessYan0913** [jscad/OpenJSCAD.org#916]
When I use `project()` to try to project the `.stl` model onto a 2d plane, the console prompts:

![image](https://user-images.githubusercontent.com/52144974/134876229-91a32353-44c8-44c1-b59e-2e81c1da2752.png)

But the 3d model can be displayed normally.

This problem does not appear in all `.stl` models, only complex `.stl` models will appear in this problem.

I debugged and found that the cause of this problem was that `poly3.toPoints()` returned an empty array.

![image](https://user-images.githubusercontent.com/52144974/134876270-1d91639a-569e-41c4-9e47-3b6e9e66ffa2.png)

Should the empty array be filtered before calling `poly3.toPoints()`？

- bad `.stl` file:
[coffeeLid.zip](https://github.com/jscad/OpenJSCAD.org/files/7234980/coffeeLid.zip)

**Comment by z3dev** [comment]
@JessYan0913 thanks again.

the STL file provided looks fine, and has no errors in Meshlab. 👍 

so, there's something else going on internally. i suspect that the union is failing somehow, and producing bad polygons. this may take some time.

**Comment by z3dev** [comment]
> When I use `project()` to try to project the `.stl` model onto a 2d plane...

@JessYan0913 can you provide an example of your jscad script? i would like to see that parameters being passed to project()

thanks

**Comment by z3dev** [comment]
There are issues with the booleans again, which do not do what's expected. If the shape is complex then the 2D projection is too complex for the calculations. And you end up with something like this... or worse.

![issue916_1](https://user-images.githubusercontent.com/8969165/136156815-ce06da2e-5227-4476-8df1-b1104091d15c.png)

**Comment by JessYan0913** [comment]
@z3dev 
This is a code part.
```js
          pre.left.push(rotateZ(degToRad(90), project({ axis: [1, 0, 0] }, cur)));
          pre.front.push(project({ axis: [0, 1, 0] }, cur)); 
          pre.top.push(project({ axis: [0, 0, 1] }, cur)); 
```
