### ISSUE TITLE
Model is not fully rendered

### ISSUE THREAD

**Issue by baburgess** [jscad/OpenJSCAD.org#92]
The model is only rendering partially.  The source code for the model is at https://baburgess.com/keys/output.jscad/ .  I get the exact same output when I try to render the OpenSCAD version with OpenJSCAD.  That model can be found here https://baburgess.com/keys/uploads/752471-857172-776461-438791.scad .  OpenSCAD renders the model perfectly, I've included a picture of it's rendering.

![screenshot from 2015-06-17 20 50 26](https://cloud.githubusercontent.com/assets/7611850/8221907/7febec38-1532-11e5-978c-fa42ab1f4a2e.png)

![screenshot from 2015-06-17 20 36 36](https://cloud.githubusercontent.com/assets/7611850/8221779/942024be-1530-11e5-9dd6-1e4dd19517cb.png)

**Comment by z3dev** [comment]
@baburgess Does the source code still exist? Can you attach your code to this issue?

**Comment by kaosat-dev** [comment]
@baburgess same question, do you have the files somewhere ? going to close this issue otherwise: we do not have 100% openscad compatibility, but we cannot know the specific issue without the source.
