### ISSUE TITLE
problems with ellipsoid and cube boolean operations

### ISSUE THREAD

**Issue by Carl-Hughes-Cerberus** [jscad/OpenJSCAD.org#921]
I have two objects, a cube and an ellipsoid which overlap.

![problem1](https://user-images.githubusercontent.com/48712218/135433341-72a6c0a1-337b-4da2-949b-f1684f3e6069.JPG)

which is a result of the following code: 
```
const jscad = require('@jscad/modeling')
const {operations, booleans, colors} = jscad
const { colorize} = colors
const { cuboid, ellipsoid, } = jscad.primitives
const { intersect, union, subtract } = booleans
const { translate } = jscad.transforms

const main = () => {
 let cube = colorize([1,0,0],cuboid({center:[250,250,250], size: [500, 500, 500] }))
let eli = colorize([0,1,0],ellipsoid({ center:[5,200,5], radius: [20, 20, 30], segments: 25, axes: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]}))
return [cube, eli]
}

module.exports = { main }
```

However, when I try and intersect the two objects and return the resultant model, it doesn't work as expected. It produces what looks like a subtraction of the cuboid.

![image](https://user-images.githubusercontent.com/48712218/135435529-9c22c23d-9dc2-4a14-a4a4-ae9d7031bcee.png)

the union operation also looks like a subtraction of the ellipsoid:

![image](https://user-images.githubusercontent.com/48712218/135435715-0779c69a-904d-4325-9ec0-d95e7cc6e992.png)

and the subtraction just looks wrong.

![image](https://user-images.githubusercontent.com/48712218/135435754-d0b6c29b-c921-4b75-ab3f-3224d242adc3.png)

I'm using the version 2 website, with the original code as posted above just with the operations union, subtraction or intersect applied. 

Can someone explain what's going wrong?

**Comment by hrgdavor** [comment]
just remove the axes parameter, `ellipsoid({ center:[5,200,5], radius: [20, 20, 30], segments: 25})`
it was causing it to create and inverted sphere for some reason, and then booleans produced unexpected results

**Comment by Carl-Hughes-Cerberus** [comment]
Thank you, that makes everything better!
