### ISSUE TITLE
host v1 version of jscad too

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#934]
## Expected Behavior
official V1 hosted version is needed

for the purpose of allowing ppls to use old examples and maybe get motivated to move to V2, here is a version that supoprts remote urls via hash

https://3d.hrg.hr/jscad/V1/

## Actual Behavior
No V1 to be found

## Steps to Reproduce the Problem

open https://openjscad.xyz/ 
no link to V1 instance anywhere

## Specifications

it needs to be linked for users returning to jscad, to allow them to use old designs, and keep them interested enough to start converting to V2

community is really small, and loosing the few that have V1 scripts is not good :(

**Comment by platypii** [comment]
Not sure who is responsible for hosting these, but there's at least 2 mirrors that are already search ranked higher than the official v2 if you google for "openjscad":

https://openjscad.com/

http://openjscad.azurewebsites.net/

**Comment by z3dev** [comment]
I'm not really interested in V1, nor interested in bringing V1 back on-line. So, having those websites available is fine.
- no time for V1 website
- no time for V1 questions
- no time for V1 docs
- no time for V1

The focus should be pushing users to V2, which is now over 6 months old, and totally functional.
