### ISSUE TITLE
Missing faces in exported files

### ISSUE THREAD

**Issue by platypii** [jscad/OpenJSCAD.org#940]
## Expected Behavior

Objects should be solid.

## Actual Behavior

There is a bug that results in missing faces on objects when exported into any format. I run into this pretty frequently when making real world designs. This causes problems in 3D printing software.

It's interesting that if you just drag the .js file onto jscad, it renders correctly. If you export as any file type (stl, json, dxf, etc) they all have missing faces.

## Steps to Reproduce the Problem

It's fairly easy to find examples of missing faces if you start doing boolean operations with cylinders. For example, modeling screw holes. Cylinders must have a fairly high number of segments, and helps to be off-center.

```
const { subtract } = require("@jscad/modeling").booleans
const { cylinder } = require("@jscad/modeling").primitives

function main() {
  return subtract(
    cylinder({radius: 20, center: [1, 1, 0], segments: 200}),
    cylinder({radius: 11, center: [1, 1, 0], segments: 200})
  )
}

module.exports = { main }
```

  1. Open .js file
![jscad-error1](https://user-images.githubusercontent.com/1766297/138584312-7f31bc78-e5dc-4bd8-bdf4-5cc7386a5c43.png)

  2. Export as STL
  3. Open .stl file
![jscad-error2](https://user-images.githubusercontent.com/1766297/138584318-6c4e479f-141b-448e-99c1-76da6dfa7666.png)

## Specifications

  - Versions: 2.0.0 ... 2.4.4
  - Platform: Web, CLI
  - Environment: chrome and node.js

**Comment by platypii** [comment]
Fixed by #941

**Comment by z3dev** [comment]
@platypii sorry but I’d like to reopen until the root cause is identified.

**Comment by platypii** [comment]
I can tell you exactly the root cause. The snapping causes a polygon to become non-convex. Specifically there is a pentagon which is convex before the snapping. After snapping, the first three points in the vertices become "inverted". It's important that the _first_ three points become inverted, because only the first three points are used to compute a face's "plane" [[1]](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/modeling/src/geometries/poly3/plane.js#L6)

This results in the plane facing inwards instead of outwards.

Before snapping:
![face1](https://user-images.githubusercontent.com/1766297/140787143-9ce1c292-39d1-4288-a881-4ad11a6e3f08.png)

After snapping:
![face2](https://user-images.githubusercontent.com/1766297/140787158-4bb07b4d-0de6-4c83-a5bc-af8132ebeec2.png)

**Comment by platypii** [comment]
This shows the same example as above, but AFTER the fixes which were just merged. Previously this showed a missing face. Now the face is there, but the lighting is wrong because the `plane` is pointing inward.

```js
const { subtract } = require("@jscad/modeling").booleans
const { cylinder } = require("@jscad/modeling").primitives
const { generalize } = require("@jscad/modeling").modifiers
const { poly3 } = require("@jscad/modeling").geometries

function main() {
  const obj = subtract(
    cylinder({radius: 20, center: [1, 1, 0], segments: 200}),
    cylinder({radius: 11, center: [1, 1, 0], segments: 200})
  )
  return generalize({snap: true}, obj) // snapped
}
module.exports = { main }
```

![lighting](https://user-images.githubusercontent.com/1766297/140814671-e63e29d2-416d-4f60-809a-8296bb8234de.png)

**Comment by platypii** [comment]
If you isolate the bad faces I can show in isolation what happens:

```js
  // original polygon
  console.log("plane1", maths.plane.fromPoints(maths.plane.create(),
    [20.109190830176846, -4.894094744768961, -1],
    [20.02113032590307, -5.180339887498954, -1],
    [20.020247929539956, -5.182917156373431, -1],
    [10.09788631702021, -5.182917156373431, -1],
    [10.287607180522166, -4.894094744768961, -1]
  ))
  // polygon after snap
  console.log("plane2", maths.plane.fromPoints(maths.plane.create(),
    [20.109133333333336, -4.894033333333335, -1.0001266666666668],
    [20.021120000000003, -5.1802133333333344, -1.0001266666666668],
    [20.020300000000002, -5.182946666666668, -1.0001266666666668],
    [10.097753333333335, -5.182946666666668, -1.0001266666666668],
    [10.287720000000002, -4.894033333333335, -1.0001266666666668]
  ))
```

```js
plane1 [0, 0, -1, 1]
plane2 [0, 0, 0.9999999999999999, -1.0001266666666666]
```
The `plane` vector is inverted after the snap, because the polygon is no longer convex.

**Comment by hrgdavor** [comment]
I may be completely wrong on this, but I have an idea that could help.

a trick to keep it form breaking the calculation for normals later-on could be like this:
 - calculate ccw of the 3 points before snap
 - perform snap 
 - calculate ccw again 
 - then rotate the points in the array until the first 3 points have same ccw as before snap

by rotate I mean move a point from the start of the array to the end

**Comment by z3dev** [comment]
It seems that snap needs to become a little more savvy when snapping polygons with more than three points, and possibly split the polygon to make sure the results are concave.

**Comment by jue89** [comment]
I'm observing the same symptoms, but I guess, I have another problem: the polygon area is not negative, it's `NaN`.

See #951.

**Comment by z3dev** [comment]
@platypii @jue89 The latest release of JSCAD (including the WEB UI) has a fix for this issue. Please give it a try, and if all works fine then close this issue.

**Comment by platypii** [comment]
Confirmed fixed on my example :heavy_check_mark:
