### ISSUE TITLE
Path extrude function is missing!

### ISSUE THREAD

**Issue by jeremyjacob** [jscad/OpenJSCAD.org#943]
## Expected Behavior
Hi all, I'm trying to extrude an SVG which as I understand is a path2 once deserialized.
`extrusions.extrudeLinear` should work on a path2, no?

## Actual Behavior
I get the error:
`if (objects3d.length === 0) throw new Error('only 3D geometries can be serialized to STL')`

Looking into the code I see this is because there is a commented line that handles path2s. Why is this the case? The docs make no mention of it, in fact, they state the contrary.
![image](https://user-images.githubusercontent.com/44799944/139477580-f911f58b-e948-43df-9163-2274d4dd63be.png)

## Steps to Reproduce the Problem

  1. Create a path2 such as by importing SVG
  2. Use linearExtrude on it
  3. Don't profit

## Specifications

  - Version: The NPM packages
  - Platform: Macos
  - Environment: Node v14.16.1

**Comment by z3dev** [comment]
@jeremyjacob Welcome!

Almost… The path has to be converted to a 2D shape before extruding. There are many ways to use paths from SVG files, so the automatic conversion is not performed by just a simple import.

https://openjscad.xyz/dokuwiki/doku.php?id=en:design_guide_path

Also beware the complex paths cannot be converted to 2D shapes, i.e. paths that cross itself.
