### ISSUE TITLE
measureBoundingBox has bad min max bounds when mirroring geometry

### ISSUE THREAD

**Issue by glennerichall** [jscad/OpenJSCAD.org#945]
## Expected Behavior
After transform, geometry should have correct bounds. But as we can see in the screen capture of Chrome console above, y min,max bounds are swapped, ie, min=2 and max=-18. This has an impact to subtract the two shapes because in function subtractGeom3Sub(), if geometries do not overlap, a clone of the  first geometry is returned.

Rendering two shapes independently:
![image](https://user-images.githubusercontent.com/2382170/139605499-6a44481a-9a29-4886-ad41-1ac17f8582ba.png)

Rendering the substraction:
![image](https://user-images.githubusercontent.com/2382170/139605520-d1265453-b78c-4812-a60b-b51771421594.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/2382170/139605306-5bb3d343-62ad-46a2-aaea-879123c0b0c6.png)

## Steps to Reproduce the Problem

```
    const shape = cuboid({size: [5, 20, 5]});
    const mat1 = mat4.mirrorByPlane(mat4.create(), plane.fromNormalAndPoint(plane.create(),  [0, 1, 0], [0, -2.5, 0]));
    const mat2 = mat4.fromTranslation(mat4.create(), [-4,-3,-4]);
    const mat = mat4.multiply(mat4.create(), mat2, mat1);
    const newShape = transform(mat, shape);

    console.clear();
    console.log(measureBoundingBox(shape));
    console.log(measureBoundingBox(newShape));

    return [shape, newShape];
    return subtract(shape, newShape)
```

## Specifications

  - Version: v2
  - Platform: Linux
  - Environment: browser

**Comment by hrgdavor** [comment]
fix incomming :)
![image](https://user-images.githubusercontent.com/2480762/139720223-37650927-e264-4964-b380-18ed48c4ac31.png)

**Comment by z3dev** [comment]
@glennerichall The fix has been released. If you have time then please try again.

**Comment by glennerichall** [comment]
Excellent! Thank you for your time.
![image](https://user-images.githubusercontent.com/2382170/141165191-4950f56c-12c8-4199-9a1a-2ca1b62aed0a.png)
