### ISSUE TITLE
cloned site doen't work

### ISSUE THREAD

**Issue by MichaelJumble** [jscad/OpenJSCAD.org#948]
## Expected Behavior
Last working version I used was 1.9.0. Now I want to repro the latest JSCad Web Site on my local server.

## Actual Behavior
BlankScreen with cords. Same like https://www.openjscad.xyz/

## Steps to Reproduce the Problem
Cone git clone https://github.com/jscad/OpenJSCAD.org and start webserver on path ./packages/web.

**Comment by z3dev** [comment]
@MichaelJumble Super!

We had a user that cloned the V2 website to create a new website. Please see this thread at the User Group. If you have any issues then please let us know via this issue or the user group.

https://openjscad.nodebb.com/topic/309/proxyurl-setting

**Comment by z3dev** [comment]
@MichaelJumble Any luck creating a new website using V2?

**Comment by z3dev** [comment]
@MichaelJumble any luck duplicating the website?

I may have misunderstood the initiative information. The new website is different in appearance. The functionality is about the same.

To start, just drag and drop a design to the page, which will load, compile, and render the design. Of course, the design has to be compatible with V2 JSCAD.

There’s a user guide listed under the help, as well as an API reference, and links to the user group, etc.

**Comment by z3dev** [comment]
@MichaelJumble ping… count down begins…

**Comment by z3dev** [comment]
@MichaelJumble closing this as feedback has not been provided. Feel free to reopen if you need further assistance.
