### ISSUE TITLE
require does not cache files

### ISSUE THREAD

**Issue by glennerichall** [jscad/OpenJSCAD.org#950]
## Expected Behavior
If the logic behind require is to mimic node's require behavior, then it should cache files after loading content. 
Here's a log of running the code in node:
![image](https://user-images.githubusercontent.com/2382170/140746455-a2317421-849e-4310-805f-9ec6664331e4.png)

## Actual Behavior
Here's a log of running the code in jscad web:
![image](https://user-images.githubusercontent.com/2382170/140746535-079eb677-1fb7-48d9-b288-f9177cb67f2d.png)

## Steps to Reproduce the Problem
**index.js**
```
let sphere;
if (require.main === module) {
    sphere = () => { };
} else {
    sphere = require('@jscad/modeling').primitives.sphere;
}

module.exports = {
    main: params => {
        console.clear();

        require('./test1');

        console.log('In file index.js ------> ')
        console.log(require('./test2').data.value++);
        console.log(require('./test2').data.value++);
        console.log(require('./test2').data.value++);

        return sphere({radius: 10});
    }
}

if (require.main === module) {
    module.exports.main();
}
```

**test1.js**
```

console.log('In file test1.js ------> ')
console.log(require('./test2').data.value++);
console.log(require('./test2').data.value++);
console.log(require('./test2').data.value++);
```

**test2.js**

```
const data = {
    value: 0
};

module.exports = {
    data
}
```

**Comment by z3dev** [comment]
@glennerichall thanks for the nice example.

A fix may not be possible as require() is faked within the browser, as you know.

**Comment by hrgdavor** [comment]
Could be possible. I will take a look into it :)

**Comment by hrgdavor** [comment]
@glennerichall there is a new PR #971 that adds the caching. 

I agree that this is a useful thing to have and is more inline with nodejs behavior.

**Comment by z3dev** [comment]
@glennerichall The fix from @hrgdavor has been published. Please close this issue if the require() functions are now functioning as expected.
