### ISSUE TITLE
Faces are lost during generalize({snap: true}, ...)

### ISSUE THREAD

**Issue by jue89** [jscad/OpenJSCAD.org#951]
## Expected Behavior

Faces stay in the model.

## Actual Behavior

1. `require('@jscad/stl-serialize').serialuze` makes use of `modifiers.generalize({snap: true}, ...)`.
2. `modifiers.generalize({snap: true}, ...)` makes use of `poly3.measureArea()`.
3. The following geom3 returns an area of `NaN`:
   ```
   {
     vertices: [
       [ 24.499800000000008, 47.50044000000001, 30.000360000000008 ],
       [ 24.500580000000006, 47.50044000000001, 30.000360000000008 ],
       [ 24.988080000000007, 47.50044000000001, 30.000360000000008 ],
       [ 24.988080000000007, 55.04772000000001, 30.000360000000008 ],
       [ 24.499800000000008, 55.000140000000016, 30.000360000000008 ]
     ]
   }
   ```

The problem is that the normal vector of the first 3 vertices is `[0, 0, 0]`.
https://github.com/jscad/OpenJSCAD.org/blob/fcaff870fcd63d3d6047af122f1e79d1d4774aea/packages/modeling/src/geometries/poly3/measureArea.js#L18-L23

I'm not sure if this is the root cause or if straight lines (in this example vertices[0..2] are a straight line) shouldn't occur in the first place.

Currently I'm working around this problem by calling `generalize({triangulate: true}, ...)` on my model before returning it.

## Steps to Reproduce the Problem

```
const {poly3} = require('@jscad/modeling').geometries;

console.log(poly3.measureArea(poly3.fromPoints([
  [ 24.499800000000008, 47.50044000000001, 30.000360000000008 ],
  [ 24.500580000000006, 47.50044000000001, 30.000360000000008 ],
  [ 24.988080000000007, 47.50044000000001, 30.000360000000008 ],
  [ 24.988080000000007, 55.04772000000001, 30.000360000000008 ],
  [ 24.499800000000008, 55.000140000000016, 30.000360000000008 ]
])));
```

## Specifications

  - Version: @jscad/modeling@2.6.0
  - Platform: MacOS, Linux
  - Environment: nodejs

**Comment by platypii** [comment]
Worth mentioning that the serializers already triangulate before exporting [[1]](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/io/stl-serializer/index.js#L63). So I'm not sure why you need to explicitly call generalize with triangulate yourself?

Can you give example code which demonstrates the problem?

**Comment by jue89** [comment]
I made a mistake and updated `@jscad/modeling` to 2.6.1 - and the issue is gone :D

I don't have the time right now, but I'll try to downgrade back to 2.6.0.

The example code I used in the first place: https://github.com/jue89/node-quickbox

**Comment by z3dev** [comment]
> I made a mistake and updated `@jscad/modeling` to 2.6.1 - and the issue is gone :D

Thanks good news.

Really nice design, @jue89 

This little discussion has stirred up some possible issues with a key calculation for planes; plane.fromPoints()

I suspect that polygons with near co-linear segments will have invalid planes. And I need to review V1 code as well to determine if this issue was there as well, which I believe is true.

**Comment by z3dev** [comment]
V1 and V2 use the first three pints of a polygon to calculate the plane (normal + w)

internally, planes are used heavily by booleans, expansions, and extrusions. And the internals favor polygons with more than three points. So, this could be a real issue, very subtle but real.

**Comment by z3dev** [comment]
@jue89 The latest release of JSCAD (including the WEB UI) has a fix for this issue. Please give it a try, and if all works fine then close this issue.

**Comment by jue89** [comment]
Yes, works fine. Thank you a lot!
