### ISSUE TITLE
export of 2d scene to svg lose transformations and has default black fill even on lines 

### ISSUE THREAD

**Issue by gilboonet** [jscad/OpenJSCAD.org#963]
## Expected Behavior
add a 2d shape, translate it on X and/or Y, render, export to svg. The shape is correctly positioned

## Actual Behavior
add a 2d shape, translate it on X and/or Y, render, export to svg. The shape is stuck at the center 

I made a version where the 2d shape are directly injected with their finished coordinates, this way it works, but the counterpart is that the script cannot use functions like align(), measurements, center()

As a workaround I'm using now dxf output as it works better (no fill on lines)

## Specifications

  - Version: V2.5.0
  - Platform:Ubuntu 21.10 64 bits
  - Environment: Firefox 950b12

**Comment by z3dev** [comment]
Just a reminder, SVG is aligned from the top left (0, 0), and extends in positive X and Y only. So, JSCAD does an automatic translation of shapes to this alignment.

**Comment by gilboonet** [comment]
You're absolutely right, I changed my design to make is start from the top left and extend in positive and the svg output was correctly aligned. For the moment I'm making the style customization by hand find and modify and I get this
![Capture d’écran de 2021-12-10 08-29-23](https://user-images.githubusercontent.com/22082873/145535439-2c14da6f-d28a-428d-adcb-83939942b534.png)
