### ISSUE TITLE
Missing breakouts in my model due to eliminated allocations of measureBoundingBox

### ISSUE THREAD

**Issue by jue89** [jscad/OpenJSCAD.org#966]
## Expected Behavior

This model creates two STL files for a 3D-printable enclosure:

https://github.com/jue89/homie/tree/main/devices/relay/housing

With the old version of @jscad/modeling everything looks fine:

<img width="1136" alt="Screenshot 2021-12-17 at 17 15 45" src="https://user-images.githubusercontent.com/6105784/146575141-a345b022-1838-483e-acf0-cd1338e7ca25.png">

## Actual Behavior

The `subtract()` on one screw hole doesn't seem to be applied. I've used `git bisect` to identify the commit breaking my model: 8abe361fc0249ec10e438382353b316aec4644a4

<img width="1136" alt="Screenshot 2021-12-17 at 17 14 23" src="https://user-images.githubusercontent.com/6105784/146575167-ba59fdc4-272f-4f80-9c95-2563b7ec5da6.png">

## Steps to Reproduce the Problem

  1. Clone the repo stated above, checkout 959d6b6e6c94df76b4af7d1000838112e0785d16 and cd into the dir `devices/relay/housing`
  2. `npm install && node mains-relay.js` and see everything working ... (package-lock.json picks the old version)
  3. `cd node_modules/quickbox && npm install && cd ../.. && node mains-relay.js` and observe the missing screw hole.

## Specifications

  - Version: @jscad/modeling@2.7.0
  - Platform: MacOS
  - Environment: nodejs

**Comment by jue89** [comment]
Those are the lines creating the breakouts: https://github.com/jue89/node-quickbox/blob/d84e8b3d89ee814a8a9eeb87933413dcf657a587/lib/box.js#L151-L154

**Comment by z3dev** [comment]
UG… I’ll look at the recent changes but those should not have changed any behavior. I suspect that the caching logic has issues.

**Comment by hrgdavor** [comment]
@jue89 can you give an example of box constructor that produces model in screenshots ? I need a sample code to test

**Comment by hrgdavor** [comment]
@z3dev 
> UG… I’ll look at the recent changes but those should not have changed any behavior. I suspect that the caching logic has issues.

The issue is that applyTransforms is not respecting immutability. I think it was the next step that we decided to do separately and forgot to do.
I will make i PR with fix applyTransforms and it should also fix this issue.

ofc. it then causes issue with caching. the inline change of polygons of geometry has no performance benefit, so it is definitely better to make applyTransforms respect immutability

**Comment by hrgdavor** [comment]
@SimonClark thnx. I will check it too.

**Comment by z3dev** [comment]
@jue89 the latest release has rolled back the changes to measureBoundingBox(). this is just a quick fix to insure that designs are not impacted. but please try out your designs once again.

**Comment by hrgdavor** [comment]
@SimonClark @jue89 there is a PR #970

I have tested with your examples and it seems to be working good

**Comment by jue89** [comment]
Yes, I can confirm that all my design are looking good with @jscad/modeling@2.7.1.

Thank you for taking care of my problem! Shall we close this issue or shall we keep it open for the solution you are aiming for?

**Comment by hrgdavor** [comment]
Hi. Yes I would prefer it stay open until my PR is in a published version so we can confirm the fix.
