### ISSUE TITLE
packages/web/src/ui/umd.js is broken (and unused?)

### ISSUE THREAD

**Issue by paulftw** [jscad/OpenJSCAD.org#978]
## Actual Behavior
File `umd.js` tries to require [`processor-bare`](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/web/src/ui/umd.js#L8) but `processor-bare` [has been deleted](https://github.com/jscad/OpenJSCAD.org/commit/5e666327a8b50a7fa6baa4bbdfd790d243f8064f#diff-aa1ae8074878b503b7e92241a4730e5d2fcf8110e0281de36e957e36ecdc01cd) back in 2019.

It's not right to keep a broken file in the source tree, but I'm not sure what's the right fix is.
Since umd.js has been broken for almost 3 years and nobody noticed it's a totally unused feature. I'd simply delete the umd.js and maybe revert the entire umd pull request.
What do maintainers think?

`umd.js` and `processor-bare` were introduced [here](https://github.com/jscad/OpenJSCAD.org/commit/f25d8c0b8af42e9e4fe9b8b626bc39afa9bbaf15#diff-2b98fc9e5ad810ee5543e11ca47115bd4d6950e14e72a2864a2f7a76b235a85eR8).

**Comment by z3dev** [comment]
@paulftw Definitely NOT used anymore, and should be deleted. Thanks for the notice.

**Comment by z3dev** [comment]
@paulftw this file is now GONE
