### ISSUE TITLE
A mistype described in the doc of roundedCylinder() and extrudeLinear()

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#986]
## Expected Behavior
height should be Number instead of Array

## Actual Behavior
wrong type described

## Steps to Reproduce the Problem

  1. go to https://www.openjscad.xyz/docs/module-modeling_primitives.html#.roundedCylinder
  2. go to https://www.openjscad.xyz/docs/module-modeling_extrusions.html#.extrudeLinear
  2. check "options for construction"
  3.

## Specifications

  - Version: production
  - Platform: all
  - Environment: browser

**Comment by z3dev** [comment]
Doc change has been released.
