### ISSUE TITLE
hueToColorComponent() doc seems incomplete

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#989]
## Expected Behavior
It should indicate a return type

## Actual Behavior
It doesn't indicate a return type in the doc.
[nit]It doesn't point to a reference why this util function is useful (One can google for sure...)

## Steps to Reproduce the Problem

  1. go to https://www.openjscad.xyz/docs/module-modeling_colors.html#.hueToColorComponent

## Specifications

  - Version: production
  - Platform: all
  - Environment: all

**Comment by z3dev** [comment]
Doc change has been released.
