### ISSUE TITLE
New Feature: Projections

### ISSUE THREAD

**Issue by g19fanatic** [jscad/OpenJSCAD.org#99]
OpenSCAD supports a feature [to obtain a 2D projection of a 3D object](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/3D_to_2D_Projection) on the Z=0 plane.

This feature is very useful for CNC router and laser cutter workflows.

It would be very useful here as well.

**Comment by z3dev** [comment]
I believe that the Orthonormal Basis section of the User Guide explains a similar concept for creating a 2D representation of the 3D object as sliced across a plane. Although, this is not a "projection" of the 3D object looking down.

Is this the functionality that you're looking for?

Also, a simple version of this "slice" functionality would be nice.

**Comment by BrianGenisio** [comment]
I am also thinking that this feature would be useful.  I use SCAD all the time for laser-cut designs, and I use projections to make them 2D, and then (very important), I export those 2D projections as SVG so that I can import the designs in a vector tool (like Inkscape, Corel Draw, Illustrator, etc).

**Comment by g19fanatic** [comment]
@z3dev, Slicing 'could' work but so long as @BrianGenisio's suggestion about the slice being able to be exported as a SVG holds. (We also use, which is very common, a SVG workflow for CNC router work).

**Comment by z3dev** [comment]
SVG is coming. :)

**Comment by luciancd** [comment]
What is the status on the projection enhancement ?

**Comment by z3dev** [comment]
@luciancd Welcome

SVG import and export is now available. Hopefully that provides some good news.

We just spent a ton of effort splitting up the functionality into useful libraries. We hope that others will jump in and make some changes.

As for projection, I will have to look over the SCAD implementation. I think that this functionality exists but not easily used.

**Comment by kaosat-dev** [comment]
a simple `projection()` function is coming very soon ! (yes , took a while :) API updates are under way

**Comment by z3dev** [comment]
A nice discussion on projections from Stack Exchange.

https://math.stackexchange.com/questions/2305792/3d-projection-on-a-2d-plane-weak-maths-ressources

**Comment by z3dev** [comment]
@g19fanatic @BrianGenisio @luciancd  Just for your information, as part of the last release, there's a new project() function which can project a 3D shape to a 2D shape.
