### ISSUE TITLE
doc issue in geometries geom3 toPoints() and invert()

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#990]
## Expected Behavior
the function signature is not properly documented

## Actual Behavior
missing argument

## Steps to Reproduce the Problem

  1. go to https://www.openjscad.xyz/docs/module-modeling_geometries_geom3.html#.toPoints
  2. go to https://www.openjscad.xyz/docs/module-modeling_geometries_geom3.html#.invert

## Specifications

  - Version: production
  - Platform: all
  - Environment: all

**Comment by z3dev** [comment]
Doc change has been released.
