### ISSUE TITLE
path2 eachPoint() has an unused argument in its signature

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#991]
## Expected Behavior
If the "options" not in use, should it be deleted? It is currently being documented in the official doc.
```
const eachPoint = (options, thunk, path) => {
  toPoints(path).forEach(thunk)
}
```
## Actual Behavior
Shown in the doc and the source but not being used. 

## Steps to Reproduce the Problem

  1. go to https://www.openjscad.xyz/docs/modeling_src_geometries_path2_eachPoint.js.html
  2. inspect the doc and the source

## Specifications

  - Version: production
  - Platform: all
  - Environment: all

**Comment by z3dev** [comment]
Probably this function should be fixed or removed.
