### ISSUE TITLE
modifier/generalize() is missing argument in the doc

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#993]
## Expected Behavior
It should document the repeatable argument "geometries".

## Actual Behavior

It is not documenting the repeatable argument "geometries".

## Steps to Reproduce the Problem

  1. go to https://www.openjscad.xyz/docs/module-modeling_modifiers.html#.generalize

## Specifications

  - Version: production
  - Platform: all
  - Environment: all

**Comment by z3dev** [comment]
Doc change has been released.
