### ISSUE TITLE
Parameter is not applied correctly

### ISSUE THREAD

**Issue by mtsmfm** [jscad/OpenJSCAD.org#994]
## Expected Behavior

Modified cuboid is rendered

## Actual Behavior

- Initial parameter is passed always
- Update button doesn't respond

![jscad-bug](https://user-images.githubusercontent.com/1796864/152667351-af8c31c3-ebf4-40c9-8a91-547372f638c6.gif)

## Steps to Reproduce the Problem

  1. Visit https://openjscad.xyz/
  2. Paste following script:
```js
const { primitives } = require("@jscad/modeling");

const main = ({slider: size}) => {
  return primitives.cuboid({size: [size, size, size]});
}

const getParameterDefinitions = () => {
  return [{ name: 'slider', type: 'slider', initial: 3, min: 1, max: 10, step: 1, caption: 'Slider:' }]
}

module.exports = { main, getParameterDefinitions }
```
  3. Shift-Enter
  4. Change parameter

**Comment by hrgdavor** [comment]
I have just tried it in FF chrome and Firefox on Windows 10 and it works as expected. Please give some more details.

**Comment by z3dev** [comment]
@mtsmfm thanks for the very nice issue.

I watched the video again, and think that the issue might be the RESET button. I have never tested that completely.

what do you think?

**Comment by mtsmfm** [comment]
@hrgdavor I tried with Google Chrome 97.0.4692.99 with Win 10. I've noticed it's old and updated Google Chrome to the latest (98.0.4758.82).
Perhaps reloading solves this problem though, now it works. Let me close this issue.

@z3dev Hmm, I can't reproduce this problem anymore...
