### ISSUE TITLE
Uncaught Type Error in viewer.js in package Web 

### ISSUE THREAD

**Issue by samuelwang48** [jscad/OpenJSCAD.org#999]
## Expected Behavior

A model related method should not break if provided with invalid values such as null values.

## Actual Behavior

Given any method that takes repeatable geom2, geom3 or etc, upon being flatten, it doesn't detect or filter the value of being a null type, resulting in an Uncaught Javascript error. 

For example, the null should either be ignored, filtered or captured but it is let through and results in an uncaught error in viewer.js
```
  return [Primitive.sphere({
    center: [0, 0, 0],
    radius: 12
  }), null];
```

## Steps to Reproduce the Problem

  1. paste this piece of code into codemirror editor
  ```
const jscad = require('@jscad/modeling');
const Primitive = jscad.primitives;

function main() {
  return [Primitive.sphere({
    center: [0, 0, 0],
    radius: 12
  }), null];
}

module.exports = { main }
```
  2. SHIFT+ENTER
  3. Uncaught error thrown and there isn't any way to rerun except for a hard reload of the page.

## Specifications

  - Version: production
  - Platform: all
  - Environment: browser

**Comment by samuelwang48** [comment]
Line 266 is assuming the object is an object instead of being a null
Line 264 is the fix I made locally

![Screen Shot 2022-02-18 at 01 05 13](https://user-images.githubusercontent.com/23735294/154628405-51ddec57-6ab5-483f-b8a0-3d272d2971b7.png)
![Screen Shot 2022-02-18 at 01 06 06](https://user-images.githubusercontent.com/23735294/154628407-69762b1b-7933-4c4a-a793-8a13b0b8452d.png)

**Comment by samuelwang48** [comment]
I am open for a discussion on this issue.
Given the complexity of the codebase there might be several ways to solve it.
Here are a few options I can think of.
1. Address this issue in flatten() but IMO flatten should just do flatten even there are null elements in the list. Introducing filtering logic seems a bit off.
2. In all the model methods, every single one of them, add a filtering logic to make sure null is either not accepted, ignored or filtered to protect the existing implementations anywhere else.
3. In `compareSolids`, return false if any null is detected. It is not wrong to assert that because any solid compares to null is not equal but should a solid be compared to a null?

Option 2 seems to be a right thing to do
Option 3 generates no error in all existing test cases but side effect is unknown to someone new

**Comment by hrgdavor** [comment]
I am in favor of viewer handling null by ignoring it.

**Comment by samuelwang48** [comment]
@platypii you are absolutely right here. I wanted to fix it so any errors including this one and even user syntax errors can be captured and handled in a recoverable way. That would be ideal but I am still digging into the whole design to find out how. At a first glance it seems non-trivial. Not sure if this is something has been discussed before in the community.

**Comment by hrgdavor** [comment]
@samuelwang48 current viewer uses most library that streams events and personally it is annoying to deal with, or trach what code does. Fixing the viewer to ignore nulls among geometries would be nice, but I personally am working on a new viewer prototype rather than dealing with most library.

**Comment by samuelwang48** [comment]
@hrgdavor thanks for providing the background and I agree. Will submit a change along with test cases later.

**Comment by z3dev** [comment]
@samuelwang48 interesting issue.

Since javascript supports sparsely populated arrays, this library should as well. there are those that want to pass nothing to the common operations, like #820 . And there have been previous requests that wanted to pass 'null' in order to create shapes using complex loops.

sadly, you hit one of those edge cases. i remember testing various combinations of sparse arrays in the return of main. obviously, there's still a few bugs.

**Comment by z3dev** [comment]
> 

Yeah. This is bad. The whole application should recover, and allow the user to continue.

**Comment by z3dev** [comment]
> Seems like `null` is user error and should fail. The problem here is that the viewer handles it poorly:
> 
> * Viewer doesn't show the error to the user. It prints "processing, please wait" forever.
> * After the error, the viewer is in an unrecoverable state, even if the design is fixed.

Yeah. This is bad. The Web UI should recover and allow the user to recover. And as @hrgdavor mentioned error handling is tricky in the current framework.

**Comment by z3dev** [comment]
@samuelwang48 I took a look at the compareSolids() function. i think a simple filter would be best, i.e. reduce current to a list of objects.

**Comment by samuelwang48** [comment]
@z3dev I will have a try tomorrow.
 Something similar to this
…current.filter((s)=>{s!=null}).map(…

**Comment by samuelwang48** [comment]
here I have some updates. I've tried to filter as suggested by @z3dev 

I did something similar to this within the implementation of `compareSolids(a, b) => boolean`
```
current = current.filter((s) => { s != null })
previous = previous.filter((s) => { s != null })
```

Unfortunately the result was not ideal as it didn't fix the issue.
Moreover I also realized that this idea was to mutate one or more "Inputs" of a function inside the implementation of this function.
It was not very "functional". If we followed this idea, we should fix the caller of this function before an improper input gets passed into the function OR simply throw an exception in the callee.
If we throw an exception, it is hard to be captured and hard for users to recover.

I would stick to option 2 for now. We can hold this PR until we all agree.

**Comment by samuelwang48** [comment]
Another similar but not directly related issue.
If null is present in colorize() the UI becomes unrecoverable.

```
jscad = require('@jscad/modeling');
const Array_Utils = require('@jscad/array-utils');
const Booleans = jscad.booleans;
const CssColor = jscad.colors.cssColors;
const Colors = jscad.colors;
const Primitive = jscad.primitives;

function main() {
  return [Colors.colorize(CssColor.silver, [Booleans.union(Primitive.cube({
    center: [0, 0, 0],
    size: 1
  })), null]), null];
}

module.exports = { main }
```

**Comment by samuelwang48** [comment]
```
jscad = require('@jscad/modeling');
const CssColor = jscad.colors.cssColors;
const Colors = jscad.colors;
const Primitive = jscad.primitives;

function main() {
  return [Colors.colorize(CssColor.silver, [Booleans.union(Primitive.cube({
    center: [0, 0, 0],
    size: 1
  })), null]), null];
}

module.exports = { main }
```
Found more cases that will break the web and cause the web to be unrecoverable especially with the dist'ed package.
Looks like once an error is detected in a user script some state will not immediately be restored or reverted.
I am struggling to figure out how to solve it in a more elegant way but I lack the redux expertise.
My workaround is to flush the state by feeding the codemirror an empty payload to execute immediately after user script failure. This kind of "flush" workaround seems to restore those clogged state.

The workaround will be triggered in `setErrors()` from `ui/flow/errors.js`. It's not an elegant way of dealing with reverting/recovering state so I keep it local.

**Comment by hrgdavor** [comment]
Personally I am not against this fix. It is useful, and if sbdy will want to tackle it elegantly, that is fine as well. I just think app is better with it than without.

**Comment by z3dev** [comment]
I found the old issue #665 which also reported the same issue.

Here's my test case for it...

```
const { path2, geom2, geom3 } = require('@jscad/modeling').geometries
const { square } = require('@jscad/modeling').primitives

const main = () => {
  let a = path2.create()
  let b = geom2.create()
  let c = geom3.create()
  let d = 'hello'
  let e = square()

  return [undefined, a, null, b, null, c, null, d, null, e, undefined]
}

module.exports = { main }
```

**Comment by z3dev** [comment]
@samuelwang48 the latest release contains YOUR fix for this error. if satisfied then please close this issue.

**Comment by samuelwang48** [comment]
Verified the changes in the merged branch. Ok to close now. Closing.
